export const computerData = [
  {
    id: 4101,
    title:
      "14 Things You Can Do in macOS 10.14 Mojave That You Couldn't Do Before",
    type: "Computer",
    time: "Sep 24, 2018",
    author: "Same Emmanuel",
    img: "https://img.netnaija.com/hsi/aHR0cHM6Ly9pLmtpbmphLWltZy5jb20vZ2F3a2VyLW1lZGlhL2ltYWdlL3VwbG9hZC9zLS1aWi1TcVRwNC0tL2Nfc2NhbGUsZl9hdXRvLGZsX3Byb2dyZXNzaXZlLHFfODAsd184MDAvc3E2d3NudmhpazV2eGhpbThqeDQuanBn/images/sq6wsnvhik5vxhim8jx4.jpg",
    body: "The new and improved macOS 10.14 Mojave is rolling out to compatible Macs everywhere today. Here's all the cool new stuff you can get busy with once you've installed the upgradeon your laptop or desktop. 1. Clean up your desktop- Stacks is a new desktop feature that groups files on the desktop by type or date, cleaning up the clutter in an instant. With the desktop in focus, choose View and then Use Stacks from the Finder menu-if you then go to choose View and Group Stacks By you can decide how they're organized. Click on any Stack on your desktop to reveal the files contained therein. 2. Turn on Dark Mode - Dark modes are certainly fashionable at the moment, and now macOS has one to call its own with the arrival of Mojave. You can switch it on by clicking General and then Dark in System Preferences-you'll notice there are some extra accent colors to play around with too, so you can customize the look of the OS just that little bit more than you could before. 3. Apply a dynamic desktop wallpaper Speaking of the desktop, Mojave supports dynamic wallpapers. They're 'dynamic' in the sense that they change as the day goes on. From the Desktop &amp; Screen Saver screen in System Preferences, open the Desktop tab and choose one of the options under Dynamic desktop, making sure that Dynamic is picked from the drop-down menu above as well. 4. Avoid duplicating passwords - Just like iOS 12, macOS Mojave can warn you if you're using the same password across multiple sites and services. To audit yourself on this aspect of your digital security, open Safari and then pick Preferences from the Safari menu-go to the Passwords tab and you'll see yellow exclamation marks next to all the saved entries that have duplicate passwords.5. Trim down audio and video easily - Quick Look has some new tricks in Mojave, including the ability to trim down video and audio. With a compatible file selected in Finder, hit Space, and in the Quick Look window that appears you'll see a Trim button up at the top-click on this and then adjust the handles at each end of the timeline to make your cuts. Click Done to confirm the edits. 6. Make quick edits to screenshots - Following the lead set by iOS, macOS Mojave shows thumbnails of newly taken screenshots in the corner of the screen as you snap them-click this thumbnail to make edits to the image before saving it. If you don't like this new behavior, hit Shift+Cmd+5 to bring up the screenshot panel, then click Options, then untick the Show Floating Thumbnail entry.",
    comments: [],
  },
  {
    id: 4102,
    title: "Video Games Myths You Should Stop Believing",
    type: "Computer",
    time: "Aug 11, 2017",
    author: "Tayo",
    img: "https://img.netnaija.com/hsi/aHR0cHM6Ly93d3cuMzYwbm9icy5jb20vd3AtY29udGVudC91cGxvYWRzLzIwMTcvMDgvaW1hZ2VzLTE3LmpwZw==/images/images-17.jpg",
    body: "With the advent of video games, there has been countless opinions regarding it's suitability and how it affects us in real life. The truth however is that a lot of opinions regarding them are not right. If you're wondering how to separate the facts from the myths regarding video games, here are all the biggest misconceptions you should know. 1.Video Games Are Addictive. One common myth is that video games are as addictive as drugs most especially since they are designed to get gamers spending lots of their time and money in them. Addiction experts however see things differently as they say video games can't be an addiction.Experts are of the opinion that video game addiction cannot be classified as a disease, much like alcoholism. They believe more research was needed to back up the claim that 10% of video game players are video game addicts.So far, research hasn't shown much that would make games more of an addictive thing so - at least for now, you can indulge in your games.Men Play Video Games More In truth, chances are when you think about a video game competition or store, chances are all you see in your mind is a place filled with men simply because everyone feels girls don't play nerdy video games. The fact however is that gamers are not predominantly boys. Adult women make up a larger percentage of video game players than even teenage boys. To be fair however, men are still the largest demographic, but it just goes to show you that more and more, women are playing video games. Video Games Are Cheap To Make. It is easy to see our favourite past time as nothing more than exciting features made from binary codes , especially if you have an idea of software development. That however is not the case as video games are not things you can simply make in your room with a couple of friends. Video Games are actually very large and complex things that require the expertise of designers, artists, voice artists, more designers, programmers and Quality Assurance testers. A lot of work goes into their actual creation, talk more of their marketing as we would certainly talk about the bad commercials of them that we see. It is important to keep in mind that there are some exceptions to the rule of expense as there would be occasional cheap ones that will be good. But any game worth its onions will require a lot of money, with some costing hundreds of millions of dollars, just to produce! You Don't Need A Degree To Make Them. A common myth around is that almost anyone has the capacity to build video games and no schooling or help is required to make them. To be a professional video game designer, you will need to go to school for it. A lot of tertiary institutions offer them as a course and while a degree is not a compulsory requirement, it can help to set you apart. With the business of making games pretty much a multi-billion dollar business, and games becoming more and more complex to make, getting a degree is pretty much a necessity.",
    comments: [],
  },
  {
    id: 4103,
    title: "Time for a new notebook computer: buy on Jiji.ng",
    type: "Computer",
    time: "Apr 26, 2016",
    author: "Same Emmanuel",
    img: "http://img.netnaija.com/yPkHHK.jpg",
    body: "If a perfect shopping spot exists, its name is Jiji.ng. It allows buying things of good quality at considerably low prices and without any difficulties. It is the biggest Nigerian classifieds, which can impress anyone with the amount of offers available. Also, it is easy and convenient in using. No wonder that this website keeps attracting more and more people. Jiji to the great extent reminds a market, where people can send various things. There are more than ten categories, divided into smaller sections. Due to this, you can be sure that your item can always find a place among other offers and can be found easily. In addition to convenience, Jiji provides the opportunity to post ads for free, unlike a real market, where you should surely pay at least for a counter. Though Jiji is shopping spot No.1 in Nigeria, it doesn't sell anything. It only helps others to sell. Jiji is not a web store. It is an online marketplace. It means that this service provides territory and conditions for convenient shopping of its users. As a result, they can easily communicate directly with each other and make all the deals with ease.",
    comments: [],
  },
  {
    id: 4104,
    title: "How To Get Android Notifications On Windows 10",
    type: "Computer",
    time: "Aug 21, 2016",
    author: "Tayo",
    img: "https://img.netnaija.com/hsi/aHR0cDovL3RlY2h2aXJhbC5jb20vd3AtY29udGVudC91cGxvYWRzLzIwMTYvMDgvR2V0LUFuZHJvaWQtTm90aWZpY2F0aW9uLU9uLVdpbmRvd3MtMTAtNjk2eDQ2My5qcGc=/images/Get-Android-Notification-On-Windows-10-696x463.jpg",
    body: "Till now you must have read lots of guides that makes your task easier in your Windows PC and in your android phone and what about getting android notification right on your windows pc, yes its possible this can be done easily by using the common app and its services in your windows 10 PC and your android phone. So here cortana will be helpful, you might not have used Cortana till now but you will love to use it after reading out this guide. As Cortana will now help you to receive your android notification on your Windows 10 PC. With this, you will not need to operate your android again and again to react to every notification as they will be right on your PC. So have a look on complete guide discussed below to proceed. The method is quite simple and easy and you just need to do synchronization of Microsoft account between android Cortana app and your Windows 10 PC to get the notifications on PC. So follow up the below steps to proceed. Steps To Get Android Notification On Windows 10: First of all in your android phone, you need to download and install the Cortana in your android phone. After downloading the app you need to launch it and then proceed with the initial guides. Now you need to sign in the app with your Microsoft account that you had used on your Windows 10 PC.",
    comments: [],
  },
  {
    id: 4105,
    title: "How to Add Subtitles in Windows Media Player On Pc",
    type: "Computer",
    time: "Nov 05, 2016",
    author: "Tayo",
    img: "https://img.netnaija.com/hsi/aHR0cDovL2JlZWJvbS5yZWRrYXBtZWRpYS5uZXRkbmEtY2RuLmNvbS93cC1jb250ZW50L3VwbG9hZHMvMjAxNi8wOS9Ib3ctdG8tYWRkLXN1YnRpdGxlcy1pbi1XaW5kb3dzLU1lZGlhLVBsYXllci1zYW1lLWZpbGUtbmFtZS5qcGc=/images/How-to-add-subtitles-in-Windows-Media-Player-same-file-name.jpg",
    body: "While Microsoft has introduced a new media player app dubbed Movies & TV with Windows 10, it still includes the age old Windows Media Player. It's a wise move, considering there are a number of people who still use the Windows Media Player for its simplicity. While Windows Media Player is great when it comes to handling simple media playing tasks, chances are, you are here because you haven't been able to add external subtitles to videos in the application. If you explore the web, you will find various ways that claim to fix subtitle addition in Windows Media Player, however, in our experience, most of those ways don't really work. Well, the good news is, we tried different options and we did manage to add subtitles in Windows Media Player. So, without further ado, here's how to add subtitles in Windows Media Player: 1. The first step is to make sure that the video file and its subtitle file feature the exact same name. Windows Media Player does not let you add subtitles manually and it only detects the subtitles when they have the same name as the video. 2. Once done, open Windows Media Player and in the Library Mode, go to Play -> Lyrics, captions, and subtitlesand click on 'On if available'. You can also find this option in the Now Playing Mode by right clicking on the top. 3.Then, download the DirectVobSub (VSFilter) codec and install it on your PC. It's available for both 32-bit and 64-bit machines. You only need to install the codec and there's no need to configure anything. Make sure to download the codec from the official website, as people have reported of it packing malware when downloaded from other sources.",
    comments: [],
  },
  {
    id: 4106,
    title: "How To Remove All Viruses From Your Computer Using Rescue USB Disk",
    type: "Computer",
    time: "Jul 25, 2016",
    author: "Tayo",
    img: "https://img.netnaija.com/hsi/aHR0cDovL3d3dy5tZWxvZ2lzdC5jb20ubmcvd3AtY29udGVudC91cGxvYWRzLzIwMTYvMDcvY29tcHV0ZXItdmlydXMuanBn/images/computer-virus.jpg",
    body: "Couple of hours ago, we published a post which was tagged 'Top 10 Most-Destructive Computer Viruses Ever.' Today, we are glad to inform all windows users that we have found out a method to remove all viruses from the computer using Rescue USB Disk. The spread of viruses, malwares, key-loggers and Trojans etc, are now very rampants these days. There is even a recent malware called HummingBad affecting over 2 million devices. These worms enters into windows PC either from an unsecured internet or from data sharing with infected computers. Though Antivirus can help you remove all the viruses, but what if you find it difficult to access your windows due to infected viruses?. At that time, you can use the rescue disk to clean up your computer from viruses. So better read up the complete method discussed below. In this method, you must have a bootable USB of antivirus that will run on your boot screen, scan all the viruses and remove them. And this will definitely fix out a lot of errors your windows has been experiencing. So below are the discussed steps on howbyoy can eventually wipe off stubborn viruses from your windows PC. Steps To Create A Rescue USB To Free Up System From Viruses",
    comments: [],
  },
  {
    id: 4107,
    title: "Top 10 Most-Destructive Computer Viruses Ever",
    type: "Computer",
    time: "Jul 25, 2016",
    author: "Tayo",
    img: "https://img.netnaija.com/hsi/aHR0cDovL3RlY2h2aXJhbC5jb20vd3AtY29udGVudC91cGxvYWRzLzIwMTYvMDcvTW9zdC1EZXN0cnVjdGl2ZS1Db21wdXRlci1WaXJ1c2VzLUV2ZXItNjk2eDM5Mi5wbmc=/images/Most-Destructive-Computer-Viruses-Ever-696x392.png",
    body: "The word 'Computer Virus' really scares all computer users. As we all know, Viruses can cause a lot of damage to the computer. It can damage victims privacy, can access private files and can even corrupt the very precious data which includes photos, videos, saved passwords etc. Computer viruses have already caused many financial losses for many companies. Sometimes it is good to look at the past and take a look at the viruses that caused widespread destruction that can make you conscious of computer viruses. Following are the 10 most destructive computer viruses of all time. ILOVEYOU- It is the computer worm that attacked more than ten millions of windows personal computers. The virus started to spread as an email message which includes a subject line 'ILOVEYOU' and has the attachment of 'LOVE-LETTER-FOR-YOU.txt.vbs'. Once clicked it had the capabilities of forwarding itself to everybody in the victim's address book and proceed to overwrite files with itself which makes the computer unbootable. This virus was created by two Filipino Programers, Reonel Ramones and Onel de Guzman.",
    comments: [],
  },
  {
    id: 4108,
    title: "Nigerian Communications Commision (NCC) To Review Data Price",
    type: "Computer",
    time: "Jul 22, 2017",
    author: "Same Emmanuel",
    img: "https://img.netnaija.com/hsi/aHR0cHM6Ly93d3cuZ2lzdHJlZWwuY29tL3dwLWNvbnRlbnQvdXBsb2Fkcy8yMDE3LzA3L3ZsbGt5dDZ1djZkaThpZ2U2LmNjYzE2YmU3LmpwZw==/images/vllkyt6uv6di8ige6.ccc16be7.jpg",
    body: "The Nigeria Communications Commission (NCC) has revealed that the price of data will be changed as soon as the ongoing cost-based research is done with. Umar Garba Dambatta whi happens to be the Executive Vice Chairman of the NCC made this known while speaking a set of Journalist present. He further stated that the planned review is in response to the growing usage of data plans by Nigerian consumers. Dambatta 'We have noticed that the level of data usage is growing. This attests to the earlier assertion by the NCC that data is going to be the next frontier.' He reminded the journalists that the previous data price floor met a strong resistance from the consumers and that it will be to harmonize the data market. The NCC Boss indicated as soon as the outcome of this consultancy that is on-going over data price is discussed,stake holders will meeting to decide the most adequate price for The Vice-Chairman also in attendance mentioned that the intention of the commission is to also create room for competition from the smaller operators. Let us hope the outcome of the research favours the consumers.",
    comments: [],
  },
];
