export const generalFBTData = [
  {
    id: 4001,
    title: "'Pokemon Go' Reaches 800 Million Downloads",
    type: "General/FBT",
    time: "May 30, 2018",
    author: "Tayo",
    img: "https://img.netnaija.com/hsi/aHR0cHM6Ly9wbWN2YXJpZXR5LmZpbGVzLndvcmRwcmVzcy5jb20vMjAxOC8wNS9pbWFnZS11cGxvYWRlZC1mcm9tLWlvcy0xMy5qcGc=/images/image-uploaded-from-ios-13.jpg",
    body: "Pokemon Company's president Tsunekazu Ishihara announced Tuesday at a Tokyo press conference that their hit mobile game 'Pokemon Go' has been downloaded 800 million times. The free-to-play game has been a runaway hit since its release in summer of 2016. The 800 million figure hints that the game shows no sign of slowing down any time soon, as it's a rapid increase from the 650 million downloads announced at the Game Developers Conference in March. 'Pokemon Go' has made the Pokemon Company an impressive amount of money through micro-transactions. According to Newzoo, the mobile game earned $470 million USD in the first 80 days after launch. The title is free to download and play on iOS and Android, but players have the option to buy in-game currency to purchase accessories, like Pokeballs and Lures, with their real-world dollars. The news comes just after the reveal of two new 'Pokemon Let's Go' titles coming to Switch. 'Pokemon: Let's Go, Pikachu!' and 'Pokemon: Let's Go, Eevee!' are coming in November. The games are based on the popular 90s Gameboy title 'Pokemon Yellow: Special Pikachu Edition.' A free-to-start Pokemon game, 'Pokemon Quest,' hit the Switch last night as well.Earlier in May, 'Pokemon Go' developer Niantic Labs announced they intend to create an augmented reality map of public spaces using the help of players and startup Escher Reality. Niantic Labs is also currently working on a new AR title based on the world of Harry Potter called 'Harry Potter: Wizards Unite.'",
    comments: [],
  },
  {
    id: 4002,
    title: "Nigeria Air is undergoing security clearance - NCAA",
    type: "General/FBT",
    time: "Apr 13",
    author: "LuvlyGist",
    img: "https://static.netnaija.com/i/mjyK6J30KwD.jpg",
    body: "The Nigeria Civil Aviation Authority (NCAA) has said that the process of issuing an Air Operator's Certificate (AOC) for the proposed national carrier, Nigeria Air, is ongoing. This was disclosed by Director-General of the agency, Capt. Musa Nuhu. Nuhu who said he can't disclose when the license will be issued, told newsmen in Lagos that some issues are not completely under the purview of NCAA like seeking security clearance for the applicant. He said:- 'The only thing I can tell you is that the promoters of that airline have applied and their AOC is ongoing. I don't have any assurance of when the licenses would be. 'You see, when you apply for AOC or any certification, some issues are not completely under the purview of NCAA like seeking security clearance for the applicant, security agents do that. 'I don't have control over security agencies to give such clearances. They have applied and it is ongoing, we are waiting for security clearance.'",
    comments: [],
  },
  {
    id: 4003,
    title: "Airtel Scrap Hourly Unlimited Night Plan, Introduced 1.5GB For N50",
    type: "General/FBT",
    time: "Jul 14, 2016",
    author: "Olaniran Sodiq Adeniyi",
    img: "https://img.netnaija.com/hsi/aHR0cHM6Ly8xLmJwLmJsb2dzcG90LmNvbS8tRmpieHZFN0ZmeEkvVjRjc1lnb0l2Q0kvQUFBQUFBQUFKajAvNXFWZHoxdEZINVFob0VUNWpManpkbUVfWVhTN3BZTGRRQ0xjQi9zMTYwMC9BaXJ0ZWwlMkJzbWFydHRyeWJlLnBuZw==/images/Airtel%2Bsmarttrybe.png",
    body: "Airtel Night plan introduced few months ago has been one of the best data plan for unlimited download and it has been saving heavy downloaders since 1900BC. You'll all bear me witness that you have enjoyed unlimited 1hour uninterrupted download with N100 and 2hours unlimited download with N200 but it seems the big boys Airtel are not too comfortable with that, hence deem it fit to scrap the unlimited. And replace it with 500MB for N25 and 1.5GB for N50 valid for one single night at the Hour of 12:00AM - 5AM. The new Airtel Night plan which offers you 500MB for N25 and 1.5GB for N50' looks some similar to that MTN Night plan which offers you 500MB for N25. No matter how cheap it is, you can't compare it with Unlimited Nigh Plan. Airtel also introduced 1GB for N500 which is valid for 1week and N200 for 200MB + 30Min Airtel calls weekend offer and free 15mb for 7days when you recharge with N200. How Can I Get This Offer? You must Migrate to Airtel SmartTrybe by dialing *312# then reply with 1 How To Subscribe For Airtel 1.5GB for N50, 500MB for N25 and 1GB for N500. 1. Kindly Dial *312# 2. Reply with 2 for N500 For 1GB (7 days) 3. Reply with 3 for 500MB for N25 and 1.5GB for N50 (Night Plan 12am - 5am) 4. Reply with 4 for N200 for 200mb + 30Min call (Weekend: Sat and Sun) Note: that call tariff on SmartTrybe feature 11k/s calls charges for all national networks (N6.60K/min). Now heavy downloaders, do you think this new tariff is favorable to you? I love data, but I cherish it more when it is unlimited.",
    comments: [],
  },
  {
    id: 4004,
    title: "How to Avoid Plagiarism using a Paraphrasing Tool",
    type: "General/FBT",
    time: "Oct 04, 2019",
    author: "Same Emmanuel",
    img: "https://img.netnaija.com/hsi/aHR0cHM6Ly93d3cueW91bml2ZXJzaXR5dHYuY29tL3dwLWNvbnRlbnQvdXBsb2Fkcy8yMDE4LzEwL3JlcGhyYXNpbmctdG9vbC5qcGc=/images/rephrasing-tool.jpg",
    body: "When you look up a topic on the internet, a lot of material for that topic comes up. But if you observe closely, no two materials written by different people on that topic or idea are alike because; two people can never have the same representation of the same idea. As writers, whether for academia, poetry, articles, speeches, or any form of writing, originality is as important as the content of your work. I dare say, more important! Some writers, especially in the early stages of their writing career lack originality. This may be as a result of improper research on the idea they are writing on or due to ignorance and laziness on their own part. Writers that lack originality always find themselves unwilling victims of plagiarism. It is important for every writer to avoid plagiarism because it can damage your reputation and bring your career as a writer, to an end. I'm sure you wouldn't want that. Every writer ought to know what plagiarism is and how serious of an offense it is. But for the sake of clarity and to serve as a reminder, I will explain to you what plagiarism is and the forms of plagiarisms that exist before going ahead to tell you how it can be avoided. -Plagiarism- Plagiarism is the act of lifting someone's idea with or without the person's consent, and presenting it without any form of acknowledgement. It can also be referred to as an act of literary theft and fraud. Plagiarism is considered a breach of journalistic ethics and academic dishonesty. It is a punishable offense which attracts; penalties, including suspension that may lead to expulsion from school or work, fines from courts, and in very serious cases, imprisonment. It is important to know that unless an idea is common knowledge, you cannot include it in your writing without acknowledging or citing the source. -Forms of plagiarism.- There are a good number of plagiarisms that exist, simple forms which are easily detected such as; copying a literary work word for word, and complex forms, which may not be easily detected or considered as not being plagiarism by 'amateurs'. Both simple and complex forms of plagiarism attract consequences. The forms of plagiarism are; Direct plagiarism: This is the most common form of plagiarism. It is an act of copying someone's work word for word, without acknowledgement. If you have to use the exact words from someone's work, you need to put it in quotation mark and cite the source. It is also direct plagiarism to lift and include a paragraph from someone's work, pay someone to write an essay, article or journal, thereafter submitting it as your own work without any reference or acknowledgement. Citation plagiarism: It is when your citations are missing, or when your sources are cited incorrectly. The most common example of this form of plagiarism is when you do not acknowledge a source because you think that particular idea is common knowledge; a lot of writers are guilty of this. One major cause of citation plagiarism is disorganized or improper research processes. Paraphrased plagiarism: This form of plagiarism happens when you make few changes; involving sentence structure or arrangement, to someone's work and pass it off as your own. Mosaic plagiarism: This is a combination of direct and paraphrased plagiarism. This happens when your work has word for word and paraphrased phrases, sentences or paragraphs without the use of quotation marks. Copying and pasting texts or paragraphs from different sources and piecing it together to form your work is also mosaic plagiarism. Image plagiarism: This involves including an image that was not captured by you in your work without permission and proper citation. For example, using the book cover of a novel in your literary work without citation. Self plagiarism: Always very unintentional, is an act of lifting an idea from your previous work into your new work without citation. Non-existence citation or source: It is very improper for you to give a 'made-up' citation to an idea or statement because you could not find the actual citations. This is very misleading to your readers, as they would assume your statement is supported by a source. You should avoid doing this.",
    comments: [],
  },
  {
    id: 4005,
    title:
      "See The Countries That Use The Most Gigabyte In The World (Guess Who Topped The List)",
    type: "General/FBT",
    time: "Oct 15, 2017",
    author: "Tayo",
    img: "https://img.netnaija.com/hsi/aHR0cDovL3d3dy5uYWlqYWxvYWRlZC5jb20ubmcvd3AtY29udGVudC91cGxvYWRzLzIwMTcvMTAvZ2lnLTcwMHg0OTkuanBn/images/gig-700x499.jpg",
    body: "From new and updated researches, mobile broadband penetration in OECD countries has reached 99.3 percent, meaning there is nearly one high-speed mobile broadband subscription for every inhabitant. As the smartphone became mainstream and mobile internet started to become more common, pricing in mobile markets shifted from telephony to data usage. That trend is particularly evident when it comes to 4G services that are designed for IP-based traffic, rather than being optimized for voice. The rapid expansion of 4G, coupled with providers in many countries introducing unlimited data packages, has seen levels of data usage rise considerably in recent years. The above info-graphic shows mobile data usage per mobile broadband subscription in selected OECD countries last year, with Finland first by a wide margin. In 2016, Finnish smartphone users consumed an average of 10.95GB of mobile data per month, considerably more than Austria's 6.28GB. In Finland, users can select the speed for all services without having their usage capped. For example Elisa offers tiered speeds for 4G at 50 Mbps, 100 Mbps and 300Mbps including unlimited data usage. Sweden and South Korea recorded mobile data usage of 4.38 and 3.83GB per month respectively while U.S. smartphone owners used 2.67GB. While some U.S. operators like Sprint and T-Mobile do offer unlimited usage plans and charge by speed, others are still rooted back in the 3G-era.",
    comments: [],
  },
  {
    id: 4006,
    title: "WhatsApp: 9 Things You Probably Do Not Know You Can Do On WhatsApp",
    type: "General/FBT",
    time: "Jun 08, 2016",
    author: "Olaniran Sodiq Adeniyi",
    img: "https://img.netnaija.com/hsi/aHR0cDovL3d3dy5uYWlqYW1vdXRoZWQuY29tL2ltYWdlcy9mZWF0dXJlZC8yMDE2LzA2L3doYXRzYXBwLTktdGhpbmdzLXlvdS1wcm9iYWJseS1kby1ub3Qta25vdy15b3UtY2FuLWRvLW9uLXdoYXRzYXBwLmpwZw==/images/whatsapp-9-things-you-probably-do-not-know-you-can-do-on-whatsapp.jpg",
    body: "WhatsApp is fast becoming the go-to app when instant messaging apps are concerned. It is used by quite a lot of people and has become the best ways people connect all over the world. Unlike the way it is with text messaging, WhatsApp uses a data connection, which means sending a message is essentially free, especially for those with unlimited data plans. While the app is reasonably simple, there are features many users haven's discovered yet! These are 9 things you probably do not know you can do on WhatsApp. 1. See how many messages you and your friends have sent to each other. To find out whom you communicate with most on WhatsApp, go to Settings > Account > Network Usage. A number appears next to each contact that represents the total number of messages sent back and forth. Selecting a person reveals more information, including how many messages have been sent by whom. 2. Mute group chats. If group chats are very disturbing and take your attention, you can mute the group chats and go back to them when you are less busy. To do this, go to the group chat in question, click on its name and select 'mute,' where you will be presented with three options: eight hours, a week, and a year. 3. Hide your 'last seen' time. Hiding your 'last seen' time is a useful feature if you don't want people to know when you last checked into WhatsApp. To switch it off, head to settings > Account > Privacy > Last seen. From here, you can select who gets to view your 'last seen' time. If you activate this feature however, you cannot see other's last seen.",
    comments: [],
  },
  {
    id: 4007,
    title: "How to Convert Video to GIF Image on Whatsapp and Send to Someone",
    type: "General/FBT",
    time: "Jul 31, 2017",
    author: "Tayo",
    img: "https://img.netnaija.com/hsi/aHR0cHM6Ly9pLnl0aW1nLmNvbS92aS9rWklnbERwSjVrNC9tYXhyZXNkZWZhdWx0LmpwZw==/images/maxresdefault.jpg",
    body: "In this post, I will be going straight to the point showing you how to convert a video to GIF using the inbuilt converter in whatsapp and how to send the converted GIF file to someone on whastapp as well. NOTE: You will need to update your Whatsapp to the latest version from your device app store, and then proceed as follo. How to Convert Video to GIF Image on Whatsapp and Send to Your Someone. To convert a video to GIF on Whatsapp, you will need to make sure that the video is not longer than 6 seconds. If the video is longer than that, the inbuilt video-to-GIF converter in whatsapp will lets you set and cut the 6-second time frame, in a way that you can set where you want the GIF's loop to start and end. Tap on the contact (your friend) you wanted to send the GIF to. Tap on the attachment icon. Tap on the Gallery icon, and find the video you want to convert to GIF. Tap on the GIF option, to convert the video to GIF. Add a few text (optional) in the box for Add a caption, and tap on the send icon, to send the converted GIF file to your friend. You are done. I hope you now know how to convert video to GIF using whatsapp application on your smartphone. Share this post and drop comment below.",
    comments: [],
  },
  {
    id: 4008,
    title: "Nigerian Communications Commision (NCC) To Review Data Price",
    type: "General/FBT",
    time: "Jul 22, 2017",
    author: "Tayo",
    img: "https://img.netnaija.com/hsi/aHR0cHM6Ly93d3cuZ2lzdHJlZWwuY29tL3dwLWNvbnRlbnQvdXBsb2Fkcy8yMDE3LzA3L3ZsbGt5dDZ1djZkaThpZ2U2LmNjYzE2YmU3LmpwZw==/images/vllkyt6uv6di8ige6.ccc16be7.jpg",
    body: "The Nigeria Communications Commission (NCC) has revealed that the price of data will be changed as soon as the ongoing cost-based research is done with. Umar Garba Dambatta whi happens to be the Executive Vice Chairman of the NCC made this known while speaking a set of Journalist present. He further stated that the planned review is in response to the growing usage of data plans by Nigerian consumers. Dambatta 'We have noticed that the level of data usage is growing. This attests to the earlier assertion by the NCC that data is going to be the next frontier.' He reminded the journalists that the previous data price floor met a strong resistance from the consumers and that it will be to harmonize the data market. The NCC Boss indicated as soon as the outcome of this consultancy that is on-going over data price is discussed,stake holders will meeting to decide the most adequate price for The Vice-Chairman also in attendance mentioned that the intention of the commission is to also create room for competition from the smaller operators. Let us hope the outcome of the research favours the consumers.",
    comments: [],
  },
  {
    id: 4009,
    title: "Etisalat Confirms Name Change, Check Out Their New Logo",
    type: "General/FBT",
    time: "Jul 19, 2017",
    author: "Tayo",
    img: "https://img.netnaija.com/hsi/aHR0cHM6Ly93d3cuMzZuZy5uZy93cC1jb250ZW50L3VwbG9hZHMvMjAxNy8wNy9sLTQuanBn/images/l-4.jpg",
    body: "Etisalat Nigeria has confirmed it has indeed change its name to 9Mobile. The company has changed all their social media profiles to @9mobileng and in fact deleted previous uploads of Etisalat. In the coming weeks, Etisalat signal will begin to change to 9mobile on mobile devices.",
    comments: [],
  },
  {
    id: 4010,
    title: "Glo Introduces Free Data to Subscribers....See Current Procedure",
    type: "General/FBT",
    time: "Jul 11, 2017",
    author: "Olaniran Sodiq Adeniyi",
    img: "https://img.netnaija.com/hsi/aHR0cDovL3d3dy50b3JpLm5nL3VzZXJmaWxlcy9pbWFnZS8yMDE3L2p1bC8xMS9nbG8xLkpQRw==/images/glo1.JPG",
    body: "Globacom has introduced a new data offer, which guarantees its data subscribers a free access to the Internet for a whole day. The telecommunications company said that the new offer, 'Free Data Day', had been programmed to give subscribers on the network that met the threshold of voice or data usage, 200 megabytes, usable throughout the day for all data-related activities. 'The offer is open to all Glo subscribers,' a statement from the telecoms company said. The Globacom's Zonal Business Coordinator, Lagos, Adebola Omoboya, said that the offer would allow subscribers on the Glo network to browse the Internet free of charge for a whole day. According to him, subscribers who want to enjoy the Free Data Day are expected to spend a certain amount or more on calls in the preceding seven days to a free data day or spend at least N150 on voice calls. 'They are also expected to use a minimum of 100MB of data in the preceding seven days to the free data day from any or a combination of methods such as 'Pay as you use', purchase of data plan' and usage from existing data plan,' Omoboya said.",
    comments: [],
  },
  {
    id: 4011,
    title: "Etisalat Pulls Out Of Nigeria, Issues Ultimatum For Name Change",
    type: "General/FBT",
    time: "Jul 10, 2017",
    author: "Tayo",
    img: "https://img.netnaija.com/hsi/aHR0cDovL3d3dy5uYWlyYWxhbmQuY29tL2F0dGFjaG1lbnRzLzU2Mjc4NjBfdW5uYW1lZDEwX2pwZWc2ZDJkZGVkM2JjY2QyOTRmMGEyNGQ4MmVlYzIyMWY5Nw==/images/5627860_unnamed10_jpeg6d2dded3bccd294f0a24d82eec221f97",
    body: "Nigerian regulators intervened last week to save Etisalat Nigeria from collapse after talks with its lenders to renegotiate a $1.2 billion loan failed. Abu Dhabi's Etisalat has terminated its management agreement with its Nigerian arm and given the business time to phase out the brand in Nigeria, the chief executive of Etisalat International told Reuters on Monday. Nigerian regulators intervened last week to save Etisalat Nigeria from collapse after talks with its lenders to renegotiate a $1.2 billion loan failed. All UAE shareholders of Etisalat Nigeria have exited the company and have left the board and management, Hatem Dowidar said in an interview. Dowidar said discussions were ongoing with Etisalat Nigeria to provide technical support, adding that it can use the brand for another three weeks before phasing it out.",
    comments: [],
  },
  {
    id: 4012,
    title: "MTN Introduces 7GB + 2GB For N2000 Data Plan On Dealzone",
    type: "General/FBT",
    time: "Jul 23, 2016",
    author: "Tayo",
    img: "https://img.netnaija.com/hsi/aHR0cDovL2kyLndwLmNvbS9uYWlqYWtub3dob3cuY29tL3dwLWNvbnRlbnQvdXBsb2Fkcy8yMDE2LzA3LzdnYi1mb3ItbjIwMDAtb24tTVROLURlYWx6b25lLmpwZw==/images/7gb-for-n2000-on-MTN-Dealzone.jpg",
    body: "I know you all must have seen Tech+ ads scattered all over websites, blogs and social media platforms; an event claimed to be the biggest tech event in Nigeria. Anyway, am not here to yarn about TechPlus, but to make known to you about MTN 7GB for N2000 Ads boldly unfurled on the handbill shared at the event. MTN in collaboration with Techplus newly launched a new data plan, and was displayed on the leaflet shared yesterday. Right in front of this leaflet, displayed MTN 7GB for N2000 on Dealzone; this is an opportunity for MTN users to get double of what they should have gotten when they subscribe with N2000, initially you will get 3.5GB, but with this plan... you'd get 100% data bonus upon subscribing for this new plan.",
    comments: [],
  },
];
