export const mobileData = [
  {
    id: 4201,
    title: "How to Manage App Permissions on Android Marshmallow",
    type: "Mobile",
    time: "Jul 25, 2016",
    author: "Tayo",
    img: "https://img.netnaija.com/hsi/aHR0cDovL3RlY2h2aXJhbC5jb20vd3AtY29udGVudC91cGxvYWRzLzIwMTYvMDcvSG93LXRvLU1hbmFnZS1BcHAtUGVybWlzc2lvbnMtb24tQW5kcm9pZC1NYXJzaG1hbGxvdy02OTZ4NDQ3LmpwZw==/images/How-to-Manage-App-Permissions-on-Android-Marshmallow-696x447.jpg",
    body: "After gaining lots of success in the Smartphone arena, android developers started to improve their software and started to launch the newer and much improved versions of the Android OS. Marshmallow is the name given to the latest version of the android i.e Android 6.0. This version is totally different in case of its UI and performance etc from the other versions launched before it. The main function of the android that differs it from other operating systems is that while using android you can personally manage every app to behave at certain conditions in way that you want or you have set about before. Managing the app permissions in Android Marshmallow is some what different than other versions of android. Here in this article you will know about how you can manage the app permissions easily on Android Marshmallow. Just go though the article given below to know how you can do that. How to Manage App Permissions on Android Marshmallow. You can although easily manage app permissions while using android as the apps will prompt to ask you for your permissions that you can either grant or deny. But for further handling your app permissions for multiple apps in all you have to follow the below method. -Steps To Manage App Permissions on Android Marshmallow:- 1. First of all you have to go to the Settings menu of your device on Android Marshmallow and then from there you have to select the'Apps' option. You will now reach to the screen where you will see all the apps that either running, downloaded or are on your device.",
    comments: [],
  },
  {
    id: 4202,
    title: "WhatsApp Update Finally Adds Support For Stickers",
    type: "Mobile",
    time: "Oct 26, 2018",
    author: "Same Emmanuel",
    img: "https://img.netnaija.com/hsi/aHR0cHM6Ly9jZG5zc2wudWJlcmdpem1vLmNvbS93cC1jb250ZW50L3VwbG9hZHMvMjAxOC8xMC93aGF0c2FwcC1zdGlja2Vycy5qcGc=/images/whatsapp-stickers.jpg",
    body: "One of the features that apps such as LINE and KakaoTalk have that is an advantage over WhatsApp is support for stickers. For the most part stickers act like emojis, but because they are bigger and can also be animated, they do make for more 'fun' and interesting and dynamic conversations that emojis might not otherwise be able to provide. However WhatsApp is expected to level that playing field soon as the company has finally announced the support for stickers. They will be similar in terms of functionality like the ones we've seen in other message apps, and WhatsApp has also announced that they'll be supporting third-party sticker packs which means that if the default ones aren't to your liking, you should be able to find alternatives and variety from third-party creators. This strategy has actually worked out rather well for Naver's LINE messaging app, where we have seen companies such as Disney launch various themed stickers for the app. We've also seen collaborations with various popular musicians and bands and also anime. It is unclear if WhatsApp will eventually allow creators to start selling their own stickers but based on the FAQ, there is no mention of selling stickers for now. Support for stickers will be rolling out for both iOS and Android devices over the course of the next few weeks, so keep an eye out for them.",
    comments: [],
  },
  {
    id: 4203,
    title:
      "Xiaomi Announces Xiaomi Fan Festival 2022 With Exclusive Gifts and Unique Experiences",
    type: "Mobile",
    time: "Apr 07",
    author: "Same Emmanuel",
    img: "https://static.netnaija.com/i/wnRaMp8j7dq.jpg",
    body: "Xiaomi today announced the launch of the 12th annual Xiaomi Fan Festival, with the theme 'All for Xiaomi Fans.' The packed schedule features an exciting array of online and offline activities across more than 30 markets to connect with Xiaomi Fans around the globe. And there's a stylish present for Xiaomi Fans this year, with the chance to win one of 300 Redmi Note 11 XFF Special Edition gift packages, adding to the fun. Redmi Note 11 XFF Special Edition - For Xiaomi Fan Festival 2022, Xiaomi is launching a special edition smartphone: Redmi Note 11 XFF Special Edition. This is an exclusive variation of one of Xiaomi's most popular smartphones launched this year. Redmi Note 11 XFF Special Edition comes in fashion-forward gift packaging, complete with a creative and stylish design, and delivered within a transparent tote bag. The packaging alone stands out as an iconic fashion statement.",
    comments: [],
  },
  {
    id: 4204,
    title: "Xiaomi Debuts Latest 5G Additions to Redmi Note and Redmi Lineup",
    type: "Mobile",
    time: "Apr 01",
    author: "Same Emmanuel",
    img: "https://static.netnaija.com/i/zOJabmA07G2.jpg",
    body: "5G at accessible prices with Redmi Note 11 Pro+ 5G Redmi Note 11 Pro+ 5G is available from March 29th in Nigeria market.Xiaomi announced the debut of Redmi Note 11 Pro+ 5G complementing its popular Redmi Note 11 Series with more 5G power and making next-gen connectivity accessible to more consumers. Redmi Note 11 Pro+ 5G is available from March 29th in Nigeria market..With the launch of Redmi Note 11 Pro+ 5G, Xiaomi is pushing the legacy of Redmi Note Series one step further by delivering a performance that exceeds expectations. Featuring 120W Xiaomi HyperCharge and an ultra-clear 108MP camera, Redmi Note 11 Pro+ 5G sets a new standard in the segment. As the first-ever Redmi smartphone equipped with 120W wired charging, Redmi Note 11 Pro+ 5G charges its 4,500mAh battery to 100% in merely 15 mins.1 Built with industry-leading dual charge pumps to deliver the blazingly fast charging speed, the device also ensures charging safety and stability with more than 40 safety features, as well as attaining TÜV Rheinland's Safe Fast-Charge System certification.",
    comments: [],
  },
  {
    id: 4205,
    title: "Xiaomi 12 Series Redefines Flagship Category",
    type: "Mobile",
    time: "Mar 15",
    author: "Same Emmanuel",
    img: "https://static.netnaija.com/i/1xYNevjxKLJ.jpg",
    body: "Cutting-edge AI algorithms and Snapdragon® mobile platforms deliver cinematic experiences. Xiaomi today announced the launch of the all-new flagship Xiaomi 12 Series for Nigeria markets. Designed to empower users around the world with a cutting-edge videography studio and entertainment powerhouse, Xiaomi 12 Series delivers impressive advancements in Xiaomi's AI algorithm, flagship processing power, and an all-round elevated experience. Capture cinematic shots at any time Xiaomi 12 Pro enables users to record studio-quality shots no matter the scenario, be it challenging lighting conditions or moving objects. It boasts a pro-grade triple camera array for versatile shooting, starring a massive 50MP main wide angle camera, with 8K recording capabilities. Xiaomi 12 Pro stands out with its state-of-the-art triple 50MP array, which features a cutting-edge Sony IMX707 ultra-large main sensor. This sensor is capable of catching large amounts of light and empowers advanced imaging capabilities with faster focus speeds and increased color accuracy.",
    comments: [],
  },
  {
    id: 4206,
    title:
      "John Wick's Director Shot This Epic Snowball Action Sequence Using Only The iPhone 11 Pro",
    type: "Mobile",
    time: "Dec 03, 2019",
    author: "Same Emmanuel",
    img: "https://img.netnaija.com/hsi/aHR0cHM6Ly9pLnl0aW1nLmNvbS92aS9jTThEY0NvWnVsdy9tYXhyZXNkZWZhdWx0LmpwZw==/images/maxresdefault.jpg",
    body: "The best camera that you could possibly own is the one that's with you. If you don't take the shot, then it's as good as not having a camera at all. Granted, there are certain pieces of gear that can probably get the job done a lot faster and a lot better, but this doesn't mean that you can't still create something amazing. To prove that, director David Leitch filmed an iPhone commercial for Apple where with the iPhone 11 Pro, he managed to shoot a very epic and impressive snowball fight sequence that you can check out in the video above titled 'Snowbrawl'. For those unfamiliar, Leitch is a director that is probably best known for movies such as the original John Wick and also Deadpool 2, so suffice to say that he knows a thing or two about shooting fight sequences. It also goes to show how well the iPhone handles itself when it comes to shooting videos, where if you did not know any better, you might have assumed that it was shot using fancy high-end equipment. While we're not saying that you should go out and replace your DSLRs and video cameras anytime soon, it is comforting to know that our smartphones these days can shoot in quality high enough. Apple has also done a pretty good job with its latest iPhone, where it seems that it can hold its own when it goes up against a $20,000 Leica camera.",
    comments: [],
  },
  {
    id: 4207,
    title: "Apple announces iPhone 12 with 5G speeds (Video)",
    type: "Mobile",
    time: "Oct 13, 2020",
    author: "Moses O",
    img: "https://img.netnaija.com/hsi/aHR0cHM6Ly93d3cuZ2lzdHJlZWwuY29tL3dwLWNvbnRlbnQvdXBsb2Fkcy8yMDIwLzEwLzk2MHgwLmpwZw==/images/960x0.jpg",
    body: "It might be happening a bit later than usual, but APPLE has just announced the iPhone 12. Featuring the same 6.1-inch display size as the iPhone 11 and iPhone XR before it, the latest 'main' iPhone - and likely the model most people will gravitate toward - is making the transition from an LCD screen to OLED. And as rumored, the phone has flat sides for an overall look that more closely matches the iPad Pro and iPad Air (plus the iPhone 4 from years ago). The iPhone 12 will come in black, white, blue, red, and green. Aside from the flat sides, it still largely resembles the iPhone 11. There's still a notch at the top that houses Apple's Face ID technology, though the bezels around the screen have been reduced - another perk of the OLED switch. Around back, the iPhone 12 has two cameras housed in a matte glass squircle, which makes for a nice contrast with the rest of the glossy back panel.",
    comments: [],
  },
  {
    id: 4208,
    title: "iPhone XR, XS, XS Max: Meet Apple's three new iPhones",
    type: "Mobile",
    time: "Sep 12, 2018",
    author: "Tayo",
    img: "https://img.netnaija.com/hsi/aHR0cHM6Ly93d3cuZ2lzdHJlZWwuY29tL3dwLWNvbnRlbnQvdXBsb2Fkcy8yMDE4LzA5L0RtNlV2Y2xXc0FNWHdlZS5qcGc=/images/Dm6UvclWsAMXwee.jpg",
    body: "Finally, we meet the new iPhones- The iPhone XS, iPhone XS Max and iPhone XR, Apple's new iPhones for 2018, are officially here. While the iPhone XS and iPhone XS Max have virtually the same guts, just in two different sizes, the iPhone XR introduces a profound shift in Apple's strategy by folding its 'bargain' phone into the premium iPhone mix. The next edition of the iPhone is here. Dubbed the iPhone XS (pronounced Ten-S), the new phone has major changes inside, including a faster processor and more storage. Apple is also launching the iPhone XS Max, which features a huge 6.5-inch screen.Both phones have dazzling displays and improved stereo sound thanks to beefed up speakers. CEO Tim Cook said the phones are 'by far the most advanced' phones ever created. The also have a better battery. Apple says the iPhone XS battery will last 30 minutes longer than the X. The battery for the XS Max will last up to an hour and a half longer. Apple's surprise announcement: New iPhone XR. It's 6.1-inches with a bright LCD screen and comes in a variety of colors including, white, black, blue, coral and red. It's missing a home button, and instead will be activated by swiping.",
    comments: [],
  },
  {
    id: 4209,
    title: "WhatsApp Will Soon Let You Lock It With Your Fingerprint",
    type: "Mobile",
    time: "Jan 11, 2019",
    author: "Same Emmanuel",
    img: "https://img.netnaija.com/hsi/aHR0cHM6Ly9zdGF0aWMud2hhdHNhcHAubmV0L3JzcmMucGhwL3YzL3lPL3IvRnNXVXFSb09zUHUucG5n/images/FsWUqRoOsPu.png",
    body: "Earlier reports have suggested that WhatsApp has been developing biometric authentication features for its iOS app. This would allow iOS users to keep their favorite cross-platform messaging app locked using Face ID or Touch ID. WhatsApp's latest beta for Android shows that a similar biometric authentication feature is also being developed for the Android app. WhatsApp itself doesn't offer any protection at the app level. Your conversations can easily be accessed by anyone if you don't secure your phone. Even if you do secure it, anyone who gets their hands on your phone when it's unlocked can steal a glance at your messages. This authentication feature will reportedly let you lock the app using your fingerprint on Android so the feature won't be limited to specific chats. It will provide another layer of security and will be a great option for those who often have to hand over their unlocked phones either to friends or family members for whatever reason. Screenshots from the beta show that this feature will be present in the Privacy section of the app. It will even be possible to use the device credentials to lock the device if you don't want to use the fingerprint sensor. No word as yet on when this feature will be rolled out but it's reassuring to see that the Facebook-owned company is working on it.",
    comments: [],
  },
  {
    id: 4210,
    title:
      "Microsoft Confirms Sticky Notes Will Soon Be Coming To iOS & Android",
    type: "Mobile",
    time: "Oct 11, 2018",
    author: "Same Emmanuel",
    img: "https://img.netnaija.com/hsi/aHR0cHM6Ly9jZG5zc2wudWJlcmdpem1vLmNvbS93cC1jb250ZW50L3VwbG9hZHMvMjAxOC8wOC93aW5kb3dzLXN0aWNreS5qcGc=/images/windows-sticky.jpg",
    body: "A couple of months ago, a report suggested that one of Windows 10's features, Sticky Notes, could eventually find its way to mobile. For those who are unfamiliar with the app, it's basically Microsoft's version of Notes on macOS and iOS, but the difference is that it acts like virtual sticky notes where you can paste it over your desktop for little reminders and memos. The idea of it coming to mobile isn't that much of a stretch and actually makes a lot of sense, which is why it doesn't come as a surprise to learn that the previous report turned out to be true. Sticky Notes for mobile has since been confirmed for iOS and Android by Reza Jooyandeh who is the Engineering Manager for Microsoft Sticky Notes. Jooyandeh had been teasing the availability of the app on mobile, but his latest tweet comes right out and confirms it. There is no word on when the app will be released, but it could be worth looking out for. With many iOS users out there using Windows computers, it would actually be very beneficial to be able to sync notes on their phones to their computers. Those who use Macs probably find it so useful. In any case we'll keep our eyes peeled for when the app is released, so check back with us in the near future for more updates on Sticky Notes' availability on mobile devices.",
    comments: [],
  },
  {
    id: 4211,
    title: "Best Flagship Phones To Expect Before The End Of 2018 (Photos)",
    type: "Mobile",
    time: "Aug 20, 2018",
    author: "Same Emmanuel",
    img: "https://img.netnaija.com/hsi/aHR0cHM6Ly90ZWNoY2Fwb24uY29tL3dwLWNvbnRlbnQvdXBsb2Fkcy8yMDE4LzA4L21heHJlc2RlZmF1bHQtMS03Njh4NDMyLmpwZw==/images/maxresdefault-1-768x432.jpg",
    body: "1. LG V40 ThinQ (October 5TH)-This phone from LG is coming to challenge the Samsung Galaxy S9/S9 Plus. Following rumors it consist of 20MP primary, 16MP wide-angle and will support a 3D facial recognition system, Qualcomm's Snapdragon 845 processor which is a beast in terms of performance and the best chipset right now, 4K OLED display and and a dedicated Google Assistant button. 2. OnePlus 6T (October)- For phone savvy guys who are looking for alternatives for the super expensive phones like the Samsung Note 9, Galaxy S9, and so on, the OnePlus 6T is your best option. It is a mixture of high-end specs and affordable price. The price of the OnePlus 6T is tentatively set at $550",
    comments: [],
  },
  {
    id: 4212,
    title:
      "See Why You Should Stop Installing Android Games And Apps Outside Google Playstore",
    type: "Mobile",
    time: "Aug 07, 2018",
    author: "Tayo",
    img: "https://img.netnaija.com/hsi/aHR0cHM6Ly90ZWNoY2Fwb24uY29tL3dwLWNvbnRlbnQvdXBsb2Fkcy8yMDE4LzA4L2ZvcnRuaXRlLmpwZw==/images/fortnite.jpg",
    body: "I have received multiple questions on how to install apps from third party developers (UNTRUSTED SOURCES) outside the Google playstore but I want to warn that installing apps outside the playstore or Apple app store is a PRETTY BAD IDEA. I know that sometimes, big game developers such as EPIC GAMES refuse to sell their games via the playstore because they don't want to pay the 30% commission that Google demands for selling games via the playstore. They want you to download directly from their websites for example the newly released FORTNITE games. They call it 'sideloading'. A lot of people download games and apps outside the Google Playstore without considering the risks involved. Android is open source so they only warn you but won't stop you from installing the games and this is why people think iPhone is more secure that Android. Apple forbids it's users from installing free apps outside the app store and they make it extremely difficult to do so. They have good reasons and that's why I want to show you the dangers of installing outside the playstore.",
    comments: [],
  },
];
