export const businessData = [
  {
    id: 4901,
    title: "Elon Musk finally takes over Twitter, fires top executives",
    type: "Business",
    time: "Yesterday 10:50am",
    author: "Moses O",
    img: "https://static.netnaija.com/i/3g8NBgXvKDR.webp",
    body: "The world's richest man, Elon Musk assumed full control of Twitter late Thursday. In an apparent confirmation on Friday, the co-founder of Tesla and SpaceX tweeted 'the bird is freed'. The $44billion purchase of the influential social media platform was first announced in late April. But the following months witnessed disagreements which threatened the sale and take over. The then-Twitter management filed a lawsuit accusing Musk of trying to go back on the terms of agreement. Now in charge, Musk has fired Twitter CEO Parag Agrawal, CFO Ned Segal and top legal executive Vijaya Gadde. Co-founder Biz Stone thanked the trio for their 'collective contribution' to the business. Agrawal and Segal were escorted out of Twitter's San Francisco headquarters after the deal closed, according to Reuters.",
    comments: [],
  },
  {
    id: 4902,
    title: "Elon Musk pulls out of Twitter deal; gives reason",
    type: "Business",
    time: "Jul 09",
    author: "Moses O",
    img: "https://static.netnaija.com/i/BQJNjYQyarL.webp",
    body: "SpaceX founder and Tesla CEO, Elon Musk has pulled out of his $44 billion deal to buy Twitter, a microblogging platform. The billionaire investor accused the company of 'misleading' statements about the number of fake accounts on the social media platform. In a fresh SEC filing on Friday July 8, Twitter shared a letter it received from Elon Musk's legal team frowning at the level of 'spam and fake accounts' on its service. The letter from Musk's lawyers to Twitter's Chief Legal Officer Vijaya Gadde partly reads: 'Mr. Musk is terminating the Merger Agreement because Twitter is in material breach of multiple provisions of that Agreement, appears to have made false and misleading representations upon which Mr. Musk relied when entering into the Merger Agreement, and is likely to suffer a Company Material Adverse Effect.'",
    comments: [],
  },
  {
    id: 4903,
    title:
      "Elon Musk announces his starlink network is coming to Nigeria; lists benefits",
    type: "Business",
    time: "May 28",
    author: "Moses O",
    img: "https://static.netnaija.com/i/Gem7Qw9DNYx.webp",
    body: "On Friday, World's richest man, Elon Musk received approval from the federal government to launch his Starlink network in Nigeria. The SpaceX founder will now be competing with the likes of MTN, Airtel, and several others for Nigeria's massive telecommunication market. The billionaire's annoucement revealed that after months of negotiation, his company received approval to operate in Nigeria by the Federal government.Musk's Starlink is a satellite internet constellation operated by SpaceX, providing satellite Internet access coverage to 32 countries where its use has been licensed. It can be argued that Nigerians will not only enjoy a high-speed network, but one with a low-latency broadband which has been optimized to process a very high volume ofbdata with minimal delay. Speaking, the Nigerian Communications Commission (NCC) confirmed to Nairametrics that it has licensed Starlink, a satellite internet constellation operated by SpaceX. This licensing followed a visit to Nigeria by the company's team in May last year. According to NCC, the International Gateway license has a 10-year tenure while the ISP license is to last for five years. Both licenses take effect from May 2022 and may be renewed after the expiration.",
    comments: [],
  },
  {
    id: 4904,
    title: "Union Bank CEO, others resign as Titan Trust completes acquisition",
    type: "Business",
    time: "Jun 03",
    author: "Moses O",
    img: "https://static.netnaija.com/i/gVpagRxg7wO.webp",
    body: "Union Bank Plc has announced the completion of core investors' sale of a majority shareholding to Titan Trust Bank. In a statement on Thursday, the bank also notified the Nigerian Exchange Group of the resignation and subsequent retirement of directors from the board of the Union Bank. The directors included: the Chair/Non-Executive Director, Mrs Beatrice Bassey, and the Chief Executive Officer, Mr Emeka Okonkwo. It stated that, 'Following the bank's notification in December 2021 of the execution of a share sale and purchase agreement between Union Bank of Nigeria majority shareholders - Union Global Partners Limited, Atlas Mara Limited, et al. - and Titan Trust Bank Limited, and the subsequent receipt of all necessary regulatory approvals, Union Bank hereby notifies the Nigerian Exchange Limited, Securities & Exchange Commission and members of the public of the completion of the transaction under the SSPA, which effectively transfers 93.41 per cent of Union Bank's issued share capital to TTB.' Consequently, it added, in compliance with the NGX rule book and the amendments to the listing rules, Union Bank notified the NGX, its stakeholders and the investing public of the new developments. Union Bank notified the NGX that with the completion of the transaction, TGI Group, parent of TTB, had become the majority shareholder and core investor in Union Bank. It stated, 'Union Bank hereby notifies the NGX of the completion of the divestment of the bank's entire shareholding interest (direct and indirect) in its subsidiary, Union Bank (UK) Plc ('UBUK'), to all the shareholders on the company's records as of 4th March 2022, pro rata to their existing shareholding interests in the company. 'Consequently, UBUK is not included in the transaction with Titan Trust Bank.'Other directors that resigned were Independent Non-Executive Director, Mrs Obafunke Alade-Adeyefa; Non-Executive Director, Mr Richard Burrett; Non-Executive Director, Mr Ian Clyne; Non-Executive Director, Mr. Kenroy Dowers;  Non-Executive Director, Mr Paul Kokoricha; Non-Executive Director, Mr Taimoor Labib; Non-Executive Director, Mr Mark Patterson; Non-Executive Director, and Mr Emeka Ogbechie.",
    comments: [],
  },
  {
    id: 4905,
    title:
      "Bank customers to provide indemnity for online transfers above N1m - CBN",
    type: "Business",
    time: "Jun 03",
    author: "Same Emmanuel",
    img: "https://static.netnaija.com/i/8yZaJw3dNJ0.jpg",
    body: "The Central Bank of Nigeria has ordered banks and Payment Service Providers to accept indemnity from customers for highly secured online funds transfers. It stated this in a circular signed by the Director, Payments System Management Department, Musa Jimoh, with the reference number: PSM/DIR/PUB/CIR/01/006, titled 'Circular on the review of operations of the NIBSS Instant Payments System and other electronic payment options with similar features', which was released on Thursday. The circular stated that... 'Further to the circular on the above reference BSP/DIR/GEN/CIR/01/011 and dated August 13, 2014, banks are hereby required to comply with the following: 'Accept indemnity from customers for highly secured online funds transfer above N1m for individual and N10m for corporate, subject to a maximum of N25m (individual) and N250m (corporate). 'Provide customers with the option of electronic or paper indemnity based on the customer's preference. 'Implement electronic indemnity with stricter controls requiring biometric verification of identify. 'Adhere to multiple factor authentication for highly secured online funds transfer. 'Inform and educate customers on the use of indemnity to increase transaction limits where possible.' The CBN also released another guideline titled 'Guidelines for the registration & operation of Bank Neutral Cash Hubs (BNCH) in Nigeria'. It stated in the guidelines that BNCHs were cash collection centers to be established by registered (licensed) processing companies or Deposit Money Banks based on business needs.",
    comments: [],
  },
  {
    id: 4906,
    title: "BREAKING: Twitter deal temporarily on hold - Elon Musk",
    type: "Business",
    time: "May 13",
    author: "Moses O",
    img: "https://static.netnaija.com/i/eDxawM8rKPZ.webp",
    body: "Billionaire, Elon Musk, on Friday said his $44 billion deal for micro-blogging and social media platform, Twitter, is temporarily on hold. Musk disclosed this in a tweet via his Twitter handle, citing pending details on spam and fake accounts. 'Twitter deal temporarily on hold pending details supporting calculation that spam/fake accounts do indeed represent less than 5% of users,' Musk tweeted. Musk, the world's richest man, had said that one of his priorities would be to remove 'spam bots' from Twitter. He recently bought Twitter for $44 billion and is expected to serve as a temporary CEO for a few months. The 50-year old has been giving insight into what the social media platform under him will be like.",
    comments: [],
  },
  {
    id: 4907,
    title:
      "Elon Musk sends clear message to critics after buying Twitter for $44bn",
    type: "Business",
    time: "Apr 26",
    author: "Moses O",
    img: "https://static.netnaija.com/i/3g8NBgXvKDR.webp",
    body: "Billionaire, Elon Musk has sent a clear message to critics after buying Micro-blogging and social media platform, Twitter, on Monday. Musk had reached an agreement to buy Twitter for approximately $44 billion, the company confirmed on Monday night. The 50-year-old acquired the company at $54.20 a share, the same price named in his initial offer on April 14. However, in a tweet last night, Musk urged his critics to remain on Twitter because that is what free speech means. He tweeted: 'I hope that even my worst critics remain on Twitter, because that is what free speech means. 'And be my love in the rain,' he added. Recall that Musk has offered to buy Twitter for $43 billion earlier this month. Musk, the world's richest person according to Forbes, announced the offer in a filing with the U.S. Securities and Exchange Commission.",
    comments: [],
  },
  {
    id: 4908,
    title: "Nigeria to effect higher taxes on",
    type: "Business",
    time: "Apr 16",
    author: "Moses O",
    img: "https://static.netnaija.com/i/WAPK4w0DN0B.jpg",
    body: "The Federal Government of Nigeria has announced that the new tax regime for tobacco will be implemented from June 1, 2022. Director of Technical Services, Federal Ministry of Finance, Fatima Hayatu said this at a meeting with the Civil Society Legislative Advocacy Centre (CISLAC). The Programme Manager on Democratic Governance, Okeke Anya led the organisation's Tobacco Taxation Working Group. Hayatu called the tobacco industry a powerful one, assuring that the ministry is committed to checkmating illicit flow of the product into the market. She hinted that plans were underway to engage relevant stakeholders to implement a robust track and trace system. The government is set to constitute a tobacco tax working group to study what other ECOWAS countries are doing. The director said the taxation on a stick of cigarette was N2.90kobo but has now increased to N4.20kobo. This followed ECOWAS recommendation of 0.02cents per stick of cigarette which, at the current exchange rate, would give N8.40kobo. 'However, it was agreed to meet the recommendation half-way which would give N4.20kobo starting from 2022. 'Then in 2023, and additional 50kobo would be added to make N4.70kobo then in 2024, 50kobo would be added to make it N5.20kobo.",
    comments: [],
  },
  {
    id: 4909,
    title:
      "CBN slashes ATM withdrawal, inter-bank transfer charges; removes card maintenance charges",
    type: "Business",
    time: "Jan 31",
    author: "Same Emmanuel",
    img: "https://static.netnaija.com/i/deYakA0PKP3.jpg",
    body: "The Central Bank of Nigeria (CBN) has slashed charges for Automated Teller Machine (ATM) withdrawal and inter-bank transfers. CBN's review of the charges was contained in its revised guidelines to charges by banks, other financial institutions and non-bank financial institutions. ATM withdrawals that attract a service charge of N65 will now be N35 after the third withdrawal within the same month, according to the CBN. It also slashed the interbank transfers to a maximum of N50 per transaction from N300. CBN has also amended guidelines to charges by banks, other financial institutions (OFIs), and non-bank financial institutions, the CBN has downward reviewed charges for electronic banking transactions and electronic banking transactions. Chibuzor Efobi, the Director, Financial Policy and Regulation Department, in a circular, said the review was in response to 'further evolution in the financial industry in the last few years.' CBN said the reviewed guidelines include a review of other bank charges to comply with market changes. The new guideline also contains sections of accountability, responsibility, and sanction regime to directly address instances of excessive unapproved, (arbitrary) charges, CBN said.CBN notes that the Standing Order charge for intra-bank will be free instead of the N300 contained in the 2017 guideline.",
    comments: [],
  },
  {
    id: 4910,
    title:
      "'Report and we will take it up' - CBN to Nigerians over unauthorized/excessive debits",
    type: "Business",
    time: "Dec 19, 2021",
    author: "Moses O",
    img: "https://static.netnaija.com/i/rOx7xAmda0M.jpg",
    body: "The Central Bank of Nigeria (CBN) has called on Nigerians to report any case of unauthorized and excessive debit on their accounts. The apex financial institution in Nigeria issued this statement via its spokesman, Osita Nwanisobi during an interview with TheCable. Owing to the outcries from Nigerians due to excessive and incomprehensive debits on their bank accounts, Mr Nwanisobi told citizens not to hesitate to report directly to the institution in order for the case to be duly addressed. In his words: 'What you should be asking them (bank customers) is if they have reported those incidents to the CBN. We work based on the information we receive. 'We have channels, we have educated them, we have said that you have the right to complain if you get debited. We have written on our website about the cost of bank charges. If anybody is charging you more than what you see, what do you do? 'You need to report to CBN and we will take it up. Anytime we have done sensitisation, we showed them, in concrete terms, the amount we have recovered from banks and sent back to individuals. 'Customers should report to the CBN. We have channels, we have email addresses where they can reach us. That's what they should do.'He added that if banks fail to efficiently address laid down complaints within two weeks, the customer can forward the complaint to the Consumer Protection Department (CPD) of the CBN.",
    comments: [],
  },
  {
    id: 4911,
    title:
      "Crypto Ban: FCMB Begins Treating Customers Aged 18-30 as Fraud Suspects",
    type: "Business",
    time: "Nov 09, 2021",
    author: "Same Emmanuel",
    img: "https://static.netnaija.com/i/mr9KYdAGNq6.jpg",
    body: "First City Monument Bank has put out an alert on accounts held by people between the ages of 18-30, asking staff to be on the lookout for money launderers and other criminal activities. An internal email seen by Peoples Gazette titled 'Compliance Advisory on Cryptocurrency Dealing/Transactions' is in furtherance of the Central Bank of Nigeria's ban on the trading of cryptocurrency in the country. Accounts 'with high volume transactions operated by individuals between the age brackets of 18-30 years as signatories,' should be flagged for possible fraudulent activities by staff members, the memo said. Other account types with similarly discriminatory guidelines include youth savings accounts, business savings accounts, personal business accounts, amongst others. The bank did not define what constitutes a high volume of transactions, but the account types listed captured all of its available packages for Nigerian youths. The internal email urges staff to monitor the listed accounts for red flags 'in order to make the Bank safe and protected from the activities of criminals, organized gangs, money launderers and terrorist financiers.' This compliance advisory comes after the CBN ordered all Nigerian commercial banks to freeze the accounts of certain individuals for purportedly trading in cryptocurrency. The Gazette reported that two individuals, Nnamdi Francis Okereke and Nwaorgu Kingsley Chibuzor and a company TVS Hallmark Service Limited had been named in a Post-No-Debit directive issued by the banking industry regulator. But the FCMB's memo marked the latest escalation in the enforcement of the CBN's directive. Section 42 of the Nigerian Constitution prohibits discrimination against citizens under whatever guise. FCMB did not return calls and e-mails seeking comments about the leaked memo to staff members.",
    comments: [],
  },
  {
    id: 4912,
    title: "Kano School dares CBN, receives fees in cryptocurrency",
    type: "Business",
    time: "Jun 25, 2021",
    author: "Moses O",
    img: "https://static.netnaija.com/i/xM6K53jqayE.jpg",
    body: "Despite the ban on cryptocurrency, the Central Bank of Nigeria (CBN), a private secondary school in Kano, New Oxford Science Academy, Chiranchi, on Thursday announced that it is accepting cryptocurrency as payment for school fees. Proprietor of the school, Sabi'u Musa Haruna while addressing journalists in Kano, said the school management took the decision after consulting parents and guardians. 'We have decided to accept cryptocurrency as school fees because the world today is tilting towards the system. 'We believe one-day digital money will gain more acceptance than paper money.' The decision is aimed at easing the payment of school fees for the parents,' Haruna said. We recall that the apex bank had on February 5, 2021 banned all forms transactions using the cryptocurrency. The CBN announcement was contained in a circular addressed to banks and other financial institutions.",
    comments: [],
  },
];
