export const loanData = [
  {
    id: 5001,
    title: "Top 20 Online Meeting and Web Conferencing Software 2017",
    type: "Loan",
    time: "Dec 13, 2017",
    author: "Same Emmanuel",
    img: "https://img.netnaija.com/hsi/aHR0cDovL3d3dy5jc3NyZWZsZXguY29tL3dwLWNvbnRlbnQvdXBsb2Fkcy8yMDEyLzAyL3dlYi1jb25mZXJlbmNpbmctdG9vbHMuanBn/images/web-conferencing-tools.jpg",
    body: "In a world where we now communicate and collaborate mainly via the Internet, it's important to have the right tool available. Not only do you need something that is dependable and works properly, but you also want a tool that is easy for all of your collaborators to use. Having a lot of features is nice, but if the people you're trying to communicate with can't figure out how to join you, more than likely you'll end up alone! This list will get over some of the best online tools for meetings, group collaborations, and screen sharing. These kind of tools come in handy for many things like webinars, training, projects, technical support, or just to have a group chat for fun. All of these tools are easy-to-use and, for the most part, are even easier for your collaborators to join in as well. Let's take a look. 1. MeetingBurner MeetingBurner is not just a great place to hold online meetings (right in the browser - no downloads required), it's also good for hosting webinars, and sharing your screen. It includes Skype integration, conference lines, and one click recording and sharing. You'll also get analytics for your meetings so that you can see how your guests interact with your content. Due to it's fast load times and easy-to-use interface, it's one of the most popular services for online meetings; best of all, the service is free.",
    comments: [],
  },
  {
    id: 5002,
    title: "Effective PPC Management Made Easy",
    type: "Loan",
    time: "Nov 20, 2017",
    author: "Same Emmanuel",
    img: "https://img.netnaija.com/hsi/aHR0cHM6Ly92NXowejN4ZWV2djJ3bHd1MjJlb2JydHQtd3BlbmdpbmUubmV0ZG5hLXNzbC5jb20vd3AtY29udGVudC91cGxvYWRzLzIwMTQtMDUtUFBDTWFuYWdlbWVudEJMT0dfZ3JhcGhpYy1jb3B5XzFhLmpwZw==/images/2014-05-PPCManagementBLOG_graphic-copy_1a.jpg",
    body: "You can't make the most of your PPC ads and campaigns without effective PPC management. It is not enough to merely 'set it and forget it' - you have to be willing to spend time actually managing your account. Fortunately, PPC management doesn't need to be a time-consuming process, but it is important to know which areas of your account need work and which will yield the greatest returns.Let's discuss the tools and processes you can use to make PPC management easier and more effective for your business. Improve Your Paid Search Workflow While it is important to pay attention to the granular details of PPC management, paid search best practices can be broken down into four main categories: Keyword research, Keyword grouping, Ad text, Landing pages. In addition to ensuring that these four areas of your paid search campaigns align with PPC management best practices, you'll find that creating systematic workflow priorities will help you identify which areas of your account to focus on and when.. For example, if you manage several PPC accounts, which one needs the most immediate attention? Which tasks are more important? How will you determine what your priorities are? The answers to these questions can help you prioritize your pay-per-click marketing efforts and identify areas in which your campaigns can improve.",
    comments: [],
  },
  {
    id: 5003,
    title: "Liberty Settlement Funding Review - Structured Settlement Company",
    type: "Loan",
    time: "Oct 30, 2017",
    author: "Same Emmanuel",
    img: "https://img.netnaija.com/hsi/aHR0cHM6Ly9pLnl0aW1nLmNvbS92aS9mWFpzcG9TUjc4Zy9tYXhyZXNkZWZhdWx0LmpwZw==/images/maxresdefault.jpg",
    body: "Liberty Settlement Funding Fort Lauderdale The secondary settlement and factoring industry is very large in south Florida. Companies such as Structured Asset Funding, Woodbridge, Imperial, and Peachtree all have offices located in the region and so does Liberty Funding in the heart of Broward county Florida. Their office is located at: 33 NE 2nd Street, Suite 100, Fort Lauderdale, FL 33301 and their office phone number is 1-855-577-2274. Liberty Settlement Reviews The better business bureau aka the BBB typically has a lot of complaints about companies in the factoring industry but Liberty has a standout A- rating with only 1 advertising sales issue submitted over the last year where other companies tend to have 10+ issues. Again the BBB is not a credible source but that is still impressive in comparison to the other competitors in the industry. The current principle of the company is Marc Hermes and is run by Jim McCabe. They specialize in purchasing fixed annuities, lottery payments, and future insurance payments that are received as a result of a lawsuit.",
    comments: [],
  },
  {
    id: 5004,
    title: "Top 9 Best Structured Settlement to Cash Companies in the USA",
    type: "Loan",
    time: "Oct 28, 2017",
    author: "Same Emmanuel",
    img: "https://img.netnaija.com/hsi/aHR0cHM6Ly9pMC53cC5jb20vd3d3LmhlYWx0aGNhcmVwZXJrLmNvbS93cC1jb250ZW50L3VwbG9hZHMvMjAxNy8xMC9hbm51aXQyLmdpZg==/images/annuit2.gif",
    body: "Structured settlements are legal settlements where a defendent pays a specified settlement amount to a plaintiff in installments over time. For instance, if you win a $50,000 settlement, you may receive $1,000 a month for 50 months or $1,000 a year for 50 years, depending on the terms of your structured settlement. Structured settlement payments can also result from other annuities of various types. Instead of receiving a settlement over the course of many months or years, many people prefer one lump sum which can then be spent or invested immediately. Sometimes, a recipient of a structured settlement will seek out a buyer to purchase all or a portion of their payments. A structured settlement company, sometimes called a factoring company, then pays the consumer a discounted lump sum in exchange. This system can benefit the consumer by allowing access to money up front, and can also benefit the company that purchases the settlement at a discount. Because some predatory companies take advantage of less knowledgeable consumers, it is important to know what to look for when choosing a settlement company.",
    comments: [],
  },
  {
    id: 5005,
    title: "How To Sell My Annuity for Cash in the USA",
    type: "Loan",
    time: "Oct 28, 2017",
    author: "Same Emmanuel",
    img: "https://img.netnaija.com/hsi/aHR0cHM6Ly9pMC53cC5jb20vd3d3Lm1lZGlhaG9hcmRlcnMubmcvd3AtY29udGVudC91cGxvYWRzLzIwMTYvMTEvbWVkaWFob2FyZGVyc19jb21fbmctaG93LXRvLXNlbGwtbXktYW5udWl0eS1mb3ItY2FzaC1pbi10aGUtdXNhLTAxLmpwZw==/images/mediahoarders_com_ng-how-to-sell-my-annuity-for-cash-in-the-usa-01.jpg",
    body: "With the biggest payouts in North America we wanted to extend a special thank you to all of our Annuitants for making us the largest buyer. Thanks to great customer service and maximizing our payouts to annuitants just like yourself we continue to excel in the market. Have an annuity payment that you want to trade in for cash now? Well today you can cash in your annuity with 'CIYA' the leader in fast payouts for annuitants. Are program designated to purchase your annuity payments are facilitated and limited to residents of the United Statesso if you are in Canada, Mexico, or Central America then we are not easily able to facilitate a deal for yourself. Our process of selling annuity payment streams are fast and simple. Our expert advisory staff work with you based on your wants and needs and can get you the funding needed in as little as 24 hours.",
    comments: [],
  },
  {
    id: 5006,
    title:
      "10 Big Things That Happened in the Auto Insurance & Car Industries in 2016",
    type: "Loan",
    time: "Oct 26, 2017",
    author: "Same Emmanuel",
    img: "https://img.netnaija.com/hsi/aHR0cHM6Ly93d3cubWVkaWFob2FyZGVycy5uZy93cC1jb250ZW50L3VwbG9hZHMvMjAxNy8wMS9tZWRpYWhvYXJkZXJzX2NvbV9uZy0xMC1iaWctdGhpbmdzLXRoYXQtaGFwcGVuZWQtaW4tdGhlLWF1dG8taW5zdXJhbmNlLWNhci1pbmR1c3RyaWVzLWluLTIwMTYtMDEuanBn/images/mediahoarders_com_ng-10-big-things-that-happened-in-the-auto-insurance-car-industries-in-2016-01.jpg",
    body: "2016 was a very eventful year for the auto insurance and car industries. From the advancement of self-driving vehicles to an insurtech boom and a new transportation secretary-a lot happened in the past 12 months. Here is a recap of the 10 biggest events that occurred in 2016. 1. The first 'self-driving car' death occurred. In May, a driver traveling in a Tesla Model S on autopilot mode-a SAE Level 2 automated vehicle-died when the car crashed into a tractor-trailer in Florida. Neither the autopilot or the driver distinguished a white tractor-trailer against the bright sky and the car collided with the vehicle, killing the driver Joshua Brown. This event was widely reported as the first self-driving car death. Of course, the Tesla Model S is not a fully autonomous self-driving car-those will not be available for years-and the drivers are still required to be prepared to take over the Tesla when necessary. There were also reports that an earlier January crash occurred in China. A Tesla Model S on autopilot mode collided with a street sweeper on the highway, instantly killing the driver. The May event was the first U.S. autonomous-related car death and both collisions raised concerns worldwide about self-driving vehicle safety and the need for increased regulation and public education.",
    comments: [],
  },
  {
    id: 5007,
    title: "Best Criminal Defense Lawyers in Arizona",
    type: "Loan",
    time: "Oct 26, 2017",
    author: "Same Emmanuel",
    img: "https://img.netnaija.com/hsi/aHR0cHM6Ly93d3cubWVkaWFob2FyZGVycy5uZy93cC1jb250ZW50L3VwbG9hZHMvMjAxNy8wMS9tZWRpYWhvYXJkZXJzX2NvbV9uZy1iZXN0LWNyaW1pbmFsLWRlZmVuc2UtbGF3eWVycy1pbi1hcml6b25hLTAxLTY0MHg0MjcuanBn/images/mediahoarders_com_ng-best-criminal-defense-lawyers-in-arizona-01-640x427.jpg",
    body: "Best Criminal Defense Lawyers in Phoenix, AZ. Handpicked Top 3 Criminal Defense Lawyers in Phoenix, AZ. We checked customer reviews, history, complaints, ratings, satisfaction, trust, cost and their general excellence. You deserve only the best in life!",
    comments: [],
  },
  {
    id: 5008,
    title: "Best Online Brokers for Stock Trading 2017",
    type: "Loan",
    time: "Oct 25, 2017",
    author: "Same Emmanuel",
    img: "https://img.netnaija.com/hsi/aHR0cHM6Ly93d3cubWVkaWFob2FyZGVycy5uZy93cC1jb250ZW50L3VwbG9hZHMvMjAxNi8xMS9tZWRpYWhvYXJkZXJzX2NvbV9uZy1iZXN0LW9ubGluZS1icm9rZXJzLWZvci1zdG9jay10cmFkaW5nLTIwMTYtMDEuanBn/images/mediahoarders_com_ng-best-online-brokers-for-stock-trading-2016-01.jpg",
    body: "Picking an online broker for your stock trading account is a big decision. The one you choose will impact the investments available to you, the amount you'll pay to trade them and the way those trades will be executed. Consider which factors matter most to you: Some investors value low commissions above all else, and others are willing to pay more for access to better research or a larger investment selection. NerdWallet has picked the best online brokers in a variety of categories, so you can quickly determine which one is right for you. The best overall: NerdWallet's top online brokers. Both OptionsHouse and TD Ameritrade offer strong customer support, advanced trading platforms with no balance or trade minimums, and an impressive amount of research. TD Ameritrade's trade commissions are on the high side, but many traders find their first-class trading platforms, Trade Architect and thinkorswim, worth that higher cost. The broker also offers a large selection of no-transaction-fee mutual funds and commission-free ETFs. Although OptionsHouse fails to offer either, it has very competitive commissions for stock, ETF and options trades. The best online brokers for beginners. If you're new to the markets and looking to dabble in a little trading, you may value handholding over fancy tools, research or even low fees. You want to be able to pick up the phone - or visit a branch - and talk to someone who can walk you through your choices. With both TD Ameritrade and Charles Schwab, you can do that (though making a trade through a broker, rather than online, will generally cost extra). They also both offer a wide selection of commission-free ETFs and no-transaction fee mutual funds, as well as educational content to help you gain your footing. Charles Schwab often waives its $1,000 account minimum for investors who agree to auto-deposits of at least $100 a month. The best online brokers for investment selection. E-Trade and OptionsXpress both offer stocks, bonds, ETFs, mutual funds, futures, and options trading, alongside powerful trading platforms that advanced traders will appreciate. Be sure to compare trading costs for the investments you plan to trade most frequently: For example, futures trading at E-Trade is slightly cheaper at $2.99 per contract (compared with $3.50 at OptionsXpress), but high-volume options traders will save money at OptionsXpress. E-Trade also offers a large selection of no-transaction-fee mutual funds, while OptionsXpress has none - but that broker scores higher marks for its extensive selection of commission-free ETFs.",
    comments: [],
  },
  {
    id: 5009,
    title: "The Benefits Of Your Car Donation In California",
    type: "Loan",
    time: "Oct 25, 2017",
    author: "Same Emmanuel",
    img: "https://img.netnaija.com/hsi/aHR0cHM6Ly93d3cubWVkaWFob2FyZGVycy5uZy93cC1jb250ZW50L3VwbG9hZHMvMjAxNy8wMS9tZWRpYWhvYXJkZXJzX2NvbV9uZy10aGUtYmVuZWZpdHMtb2YteW91ci1jYXItZG9uYXRpb24taW4tY2FsaWZvcm5pYS0wMS5qcGc=/images/mediahoarders_com_ng-the-benefits-of-your-car-donation-in-california-01.jpg",
    body: "Car donation is the better way to help & support to people who have to need without bothering himself. You are donate the car for remove the old car. It is good alternative for people who have old car by getting rid of an old useless vehicle. With this donation you are also help to other people. There are no need to a better condition car for donation. Cracked or Broken cars may also donate. You have also other choice to donate money through your old car. There are many social company are make the auction of this type of cars and make the profit. The profit is use in social works. After the car donation you can get your donation receipt. There are 20 percent of Poor families are not able to purchase the car. They are spent large budget of their income in transportation. Social companies provide them a car or money through your donation. The poor families are also happy through getting the car or money. Other benefits of your car donation in California is free towing services offered. In this offer you are not required to take the car at Center for Car Donation. The Center Authorities providing pickup facility to you. They pick up the car from your home. For the car donation you have to prepare some important documents like insurance & registration and if you do not have the title, the Center Authority provides you duplicate form of title. Donation center also give the facility for donate your car. At the time of pick up the car the donation center give you the tax form which is very important for you because this tax form is provides tax deduction from your tax. You can ask the picker about the form filling. They are introduce to you about the tax form. Donation of your car is one of the most rewarding work. When you donate the car, you do support the people who are poor & you shining other's life by helping poor peoples. There are many homeless family in California & their children are not able for go to school. By helping this type of peoples you get great blessings from the mouth of poor families. Your thinking is better than other and your work of car donation will be blessings of God for you.",
    comments: [],
  },
  {
    id: 5010,
    title: "Car Donation Charities in California",
    type: "Loan",
    time: "Oct 25, 2017",
    author: "Same Emmanuel",
    img: "https://img.netnaija.com/hsi/aHR0cHM6Ly93d3cubWVkaWFob2FyZGVycy5uZy93cC1jb250ZW50L3VwbG9hZHMvMjAxNy8wMS9tZWRpYWhvYXJkZXJzX2NvbV9uZy1jYXItZG9uYXRpb24tY2hhcml0aWVzLWluLWNhbGlmb3JuaWEtMDEtNjQweDM2NS5qcGc=/images/mediahoarders_com_ng-car-donation-charities-in-california-01-640x365.jpg",
    body: "Car Donation Charities in California The act of donating a car to charity is one of the most rewarding things you can do. When you donate your car, you do more than just support a charity. You actually help to improve someone's life. To help a needy person, please donate a car to one of these respected charities in California. Established in 1946 in Davis, California, Freedom From Hunger has been fighting chronic hunger and poverty in the world through innovative programs designed to help families achieve long term food security. Their programs are serving over 18 million people in some of the poorest countries in the world. They are both nongovernmental and nonsectarian and they have been given an A- rating from the American Institute of Philanthropy. Car Donation Charities in California Teach for America works to ensure that children in low income areas get an excellent education. Less than half of the children in California are on grade level for reading and math, and it ranks 48th in academic performance. In the Bay Area, Teach for America has been providing great education for over 10 years. In Los Angeles, they have operating since 1990. Teach for America works to recruit leaders who work to expand educational opportunities in low income areas and then teach for two years in those areas. The Guthy Jackson Charitable Foundation is dedicated to the treatment and a cure for neuromyelitis optica. NMO is a very rare disease that can affect the optic nerve and spinal cord. People with this horrible disease can develop vision loss, or weakness, numbness, and sometimes paralysis of the arms and legs along with sensory disturbances and loss bladder and bowel control. Although there are some treatments available a lot more research is needed to find better ones and a cure.",
    comments: [],
  },
  {
    id: 5011,
    title: "Charities That Accept A Vehicle Donation",
    type: "Loan",
    time: "Oct 25, 2017",
    author: "Same Emmanuel",
    img: "https://img.netnaija.com/hsi/aHR0cHM6Ly93d3cubWVkaWFob2FyZGVycy5uZy93cC1jb250ZW50L3VwbG9hZHMvMjAxNi8xMS9tZWRpYWhvYXJkZXJzX2NvbV9uZy1jaGFyaXRpZXMtdGhhdC1hY2NlcHQtYS12ZWhpY2xlLWRvbmF0aW9uLTAxLmpwZw==/images/mediahoarders_com_ng-charities-that-accept-a-vehicle-donation-01.jpg",
    body: "Vehicle Donation - Opening the Doors to Charities Nationwide Donate a Car Canada makes it easy for ANY Canadian Charity to benefit from vehicle donations nationwide. Most charities are not set up to directly receive vehicles as a form of donation. The process is too complicated, time consuming, and costly for them, thus making it a difficult or impossible form of fundraising. Our simple process makes it possible for more charities to benefit from the generosity of donors like you. We expertly handle all aspects of processing your used cars, send the net sale proceeds to the charity, and then the charity mails you the tax receipt.",
    comments: [],
  },
  {
    id: 5012,
    title: "How Much Does Travel Insurance Cost? And Loan",
    type: "Loan",
    time: "Oct 24, 2017",
    author: "Same Emmanuel",
    img: "https://img.netnaija.com/hsi/aHR0cHM6Ly93d3cubWVkaWFob2FyZGVycy5uZy93cC1jb250ZW50L3VwbG9hZHMvMjAxNi8xMS9tZWRpYWhvYXJkZXJzX2NvbV9uZy1iZXN0LWF1dG8taW5zdXJhbmNlLWNvbXBhbmllcy1hbmQtbG9hbi0wMS5qcGc=/images/mediahoarders_com_ng-best-auto-insurance-companies-and-loan-01.jpg",
    body: "Answer: Travel insurance vacation plans cost between 4-8% of the total trip cost. loan Here's an example: Loan If your cruise costs $4,000, a travel insurance plan would cost between $160-$320. Remember, this is the general range but keep in mind that basic 'budget' plans can be less than 4%, and premium plans can be loan over 12% of the trip cost (any expenses that are pre-paid and non-refundable). The cost of travel insurance is based on factors.",
    comments: [],
  },
];
