export const afroMusicData = [
  {
    id: 2401,
    type: "Nigerian/Afro-Music",
    song: "Wizkid - Money & Love",
    time: "Yesterday 9:42am",
    title: "Money & Love",
    singer: "Wizkid",
    year: "2022",
    comments: [],
    body: "Grammy award-winning Wizkid is back with a new single 'Money & Love.' The new single comes ahead of the planned release of his forthcoming album 'More Love, Less Ego' scheduled for release on November 4, 2022. 'More Love: Less Ego' Wizkid's fifth studio album follows his 2020 Grammy award-winning 'Made In Lagos.' Later that year, he released the deluxe edition of the album, which included a guest appearance from international act Justin Bieber on 'Essence.' 'Money & Love' is Wizkid's second release after 'Bad To Me', also listed on his album. Earlier this year, he worked with Chris Brown on the single 'Call Me Every Day.' Listen to 'Money & Love' below.",
    img: "https://static.netnaija.com/i/Aq2NAGAv7zJ.jpg",
  },
  {
    id: 2402,
    type: "Nigerian/Afro-Music",
    song: "Iyanya - One Side",
    time: "Yesterday 3:09pm",
    title: "One Side",
    singer: "Iyanya",
    year: "2022",
    producer: "Shugavybz",
    body: "Iyanya comes through with a brand new single titled, 'One Side',  produced by Shugavybz. It serves as a follow-up to the popular single 'Like' which features Davido and Kizz Daniel.",
    comments: [],
    img: "https://static.netnaija.com/i/x5PKDXXEKnM.jpg",
  },
  {
    id: 2403,
    type: "Nigerian/Afro-Music",
    song: "Small Doctor - See Me (feat. Mr Eazi)",
    time: "Oct 14",
    title: "See Me (feat. Mr Eazi)",
    singer: "Small Doctor",
    year: "2022",
    producer: "Krizbeatz",
    body: "After a brief hiatus from the music scene, Small Doctor returns with an amazing collaboration. He dishes out a brand new single entitled 'See Me' featuring renowned singer and businessman, Mr Eazi. 'See Me' is produced by highly gifted beatmaker, Krizbeatz and it serves as Small Doctor's first official single for the year. It is a direct follow-up to his previous singles, 'Hain' and the Davido-assisted 'Mademan.'",
    comments: [],
    img: "https://static.netnaija.com/i/1qGK1Zxw7rV.jpg",
  },
  {
    id: 2404,
    type: "Nigerian/Afro-Music",
    song: "Kizz Daniel - Cough (Odo)",
    time: "Oct 14",
    title: "Cough (Odo)",
    singer: "Kizz Daniel",
    year: "2022",
    producer: "Blaise Beatz",
    body: "Nigerian singer-songwriter and performer, Kizz Daniel, introduces a new song titled 'Cough (Odo)'. 'Cough (Odo)' follows the massive success of his previously released single 'Buga' which received high appreciation from music lovers.",
    comments: [],
    img: "https://static.netnaija.com/i/gEeK8exg7P8.jpg",
  },
  {
    id: 2405,
    type: "Nigerian/Afro-Music",
    song: "T.I Blaze - Lock Up",
    time: "Oct 13",
    title: "Lock Up",
    singer: "T.I Blaze",
    year: "2022",
    producer: "BNiphkeys",
    body: "Nigerian recording artist, T.I Blaze has released a brand new single titled, 'Lock Up'. Coming as His fourth single for the year, 'Lock Up' serves as follow-up to his recent song titled, 'My Life' released back in August.",
    comments: [],
    img: "https://static.netnaija.com/i/zxG7Z0DzNq2.jpg",
  },
  {
    id: 2406,
    type: "Nigerian/Afro-Music",
    song: "DJ Spinall - Top Mama (feat. Reekado Banks, Phyno & Ntosh Gazi)",
    time: "Oct 13",
    title: "Top Mama (feat. Reekado Banks, Phyno & Ntosh Gazi)",
    singer: "DJ Spinall",
    year: "2022",
    body: "Nigerian premium disc jockey, DJ Spinall has released a brand new single titled, 'Top Mama'. 'Top Mama' features Nigerian singer, Reekado Banks with Nigerian rapper, Phyno alongside Tanzanian singer, Ntosh Gazi. The song is an Amapiano-influenced record that has the artists switching vocals.",
    comments: [],
    img: "https://static.netnaija.com/i/3g8NBnvRNDR.jpg",
  },
  {
    id: 2407,
    type: "Nigerian/Afro-Music",
    song: "Johnny Drille - How Are You (My Friend)",
    time: "Oct 12",
    title: "How Are You (My Friend)",
    singer: "Johnny Drille",
    year: "2022",
    producer: "Don Jazzy",
    body: "Mavin Records singer/songwriter Johnny Drille has released a special single titled 'How Are You (My Friend).' Don Jazzy produced this new track, which serves as Johnny's first single for 2022 after the successful release of his first album, 'Before We Fall Asleep.' 'How Are You (My Friend)' is a hopeful and reassuring song.",
    comments: [],
    img: "https://static.netnaija.com/i/ZOoan3WONjA.jpg",
  },
  {
    id: 2408,
    type: "Nigerian/Afro-Music",
    song: "Harrysong - Chi Chon Thin (feat. Kolaboy)",
    time: "Oct 07",
    title: "Chi Chon Thin (feat. Kolaboy)",
    singer: "Harrysong",
    year: "2022",
    producer: "DalorBeatz",
    body: "Alter Plate's singer and songwriter, Harrysong has released a brand new single titled, 'Chi Chon Thin'. On the song 'Chi Chon Thin', he collaborates with Nigerian fast-rising rapper, Kolaboy who added a some good bars to the song. The song serves as follow-up to his recent track 'Meta', released back in June. This new entry would be his third offering for the year.",
    comments: [],
    img: "https://static.netnaija.com/i/3g8NBn4XNDR.jpg",
  },
  {
    id: 2409,
    type: "Nigerian/Afro-Music",
    song: "Seyi Vibez - Bullion Van",
    time: "Oct 07",
    title: "Bullion Van",
    singer: "Seyi Vibez",
    year: "2022",
    body: "Nigerian singer Seyi Vibez releases a lovely song called 'Bullion Van'. This new one is off his forthcoming project, Billion Dollar Baby scheduled to be released 21st October, 2022.",
    comments: [],
    img: "https://static.netnaija.com/i/qEQN24p876W.jpg",
  },
  {
    id: 2410,
    type: "Nigerian/Afro-Music",
    song: "Jamopyper - Balance",
    time: "Oct 07",
    title: "Balance",
    singer: "Jamopyper",
    year: "2022",
    producer: "Niphkeys",
    body: "Fast rising street hop singer, Jamopyper has released a brand new single titled 'Balance'. Produced by Niphkeys, 'Balance' is a follow up for his previously heard single 'Tease Me' which was released in June 2022.",
    comments: [],
    img: "https://static.netnaija.com/i/ZOoan39BNjA.jpg",
  },
  {
    id: 2411,
    type: "Nigerian/Afro-Music",
    song: "BlaqBonez & JAE5 - Back in Uni",
    time: "Oct 07",
    title: "Back in Uni",
    singer: "BlaqBonez & JAE5",
    year: "2022",
    producer: "JAE5",
    body: "Nigerian rapper and singer, Blaqbonez has released a brand new single titled 'Back In Uni'. The new single serves as a follow up for his previously released single 'Go Home' which was released in June. 'Back In Uni' was produced by JAE5.",
    comments: [],
    img: "https://static.netnaija.com/i/Wz27W3w375R.jpg",
  },
  {
    id: 2412,
    type: "Nigerian/Afro-Music",
    song: "Dandizzy - Bad Boy Szn",
    time: "Oct 07",
    title: "Bad Boy Szn",
    singer: "Dandizzy",
    year: "2022",
    body: "Highly gifted Nigerian rapper, Dandizzy has returned with a brand new single which he titled, Bad Boy Szn. 'Don't judge me, I'm in my own phase,' Dandizzy gifts one to all the playboys and bad boys out there. Bad Boy Szn serves as the Port Harcourt-born rapper's first official single for 2022. Although it came in quite later, it is definitely worth the wait. It comes after the release of his 2021 single 'Shalaye' featuring Suss.",
    comments: [],
    img: "https://static.netnaija.com/i/mr9KYnYm7q6.png",
  },
  {
    id: 2413,
    type: "Nigerian/Afro-Music",
    song: "Joeboy - Likkle Riddim",
    time: "Oct 07",
    title: "Likkle Riddim",
    singer: "Joeboy",
    year: "2022",
    producer: "P. Priime",
    body: "Amid the controversy with veteran singer, Asa as regards alleged copyright infringement, Joeboy still has something to offer his fans. The gifted singer delivers a brand new single entitled, Likkle Riddim. Likkle Riddim is produced by the serial hitmaker, P. Priime and it serves as Joeboy's 4th offering for the year. It is a follow-up to the previously released Countour - produced by Tempoe.",
    comments: [],
    img: "https://static.netnaija.com/i/g3M73rbLK9y.jpg",
  },
  {
    id: 2414,
    type: "Nigerian/Afro-Music",
    song: "Joeboy - Likkle Riddim",
    time: "Oct 07",
    title: "Likkle Riddim",
    singer: "Joeboy",
    year: "2022",
    producer: "P. Priime",
    body: "Amid the controversy with veteran singer, Asa as regards alleged copyright infringement, Joeboy still has something to offer his fans. The gifted singer delivers a brand new single entitled, Likkle Riddim. Likkle Riddim is produced by the serial hitmaker, P. Priime and it serves as Joeboy's 4th offering for the year. It is a follow-up to the previously released Countour - produced by Tempoe.",
    comments: [],
    img: "https://static.netnaija.com/i/g3M73rbLK9y.jpg",
  },
  {
    id: 2415,
    type: "Nigerian/Afro-Music",
    song: "Naira Marley - Ayewada",
    time: "Oct 06",
    title: "Ayewada",
    singer: "Naira Marley",
    year: "2022",
    producer: "Rexxie",
    body: "From Naira Marley's God's Timing's The Best album, here is Ayewada. Produced by Rexxie.",
    comments: [],
    img: "https://static.netnaija.com/i/1xYNeMWANLJ.jpg",
  },
  {
    id: 2416,
    type: "Nigerian/Afro-Music",
    song: "Rexxie - Abracadabra (feat. Naira Marley & Skiibii)",
    time: "Oct 06",
    title: "Abracadabra (feat. Naira Marley & Skiibii)",
    singer: "Rexxie",
    year: "2022",
    producer: "Rexxie",
    body: "Nigerian talented producer, Rexxie, comes through with a new self-produced song which is titled 'Abracadabra'. 'Abracadabra' features Marlian Music boss, Naira Marley and talented Afrobeats singer, Skiibii.",
    comments: [],
    img: "https://static.netnaija.com/i/PrO7OeW9Nyp.jpg",
  },
];
