export const carouselData = [
  {
    id: 1201,
    title: "ASUU suspends eight-month-old strike",
    type: "Education News",
    time: "Yesterday 7:41am",
    author: "Moses O",
    img: "https://media.premiumtimesng.com/wp-content/files/2022/03/20220301_151826-scaled-e1646379650750.jpg",
    body: "The Academic Staff Union of Universities, ASUU, has suspended its eight-month-old industrial action.A member of the union's National Executive Committee, NEC, confirmed this early Friday.ASUU decided to suspend the strike during a meeting of its leadership that started on Thursday night and lasted into the early hours of Friday.The state branches of the union met over the Court of Appeal ruling last week, following which members voted to conditionally suspend the strike.The Court of Appeal had issued an order to ASUU to suspend the strike before its appeal of the ruling ordering lecturers to resume work could be heard.The National Executive Committee meeting was attended by chairmen of the state chapters and national executive members at the ASUU National Secretariat in Abuja.ASUU had been on strike since February 14 this year.",
    comments: [],
  },
  {
    id: 1202,
    title: "Six benefits of going braless",
    type: "Health",
    time: "Yesterday 9:46am",
    author: "Same Emmanuel",
    img: "https://static.netnaija.com/i/WAPK4vvYa0B.jpg",
    body: "Bras and women have a troubled connection. A great bra might provide fantastic support and shape but on other days, bras can stab you and cause discomfort. Numerous studies over the years have found that wearing a bra may not be physiologically, anatomically, or psychologically necessary and may not significantly benefit your health (keep your breasts young and healthy). They might not be the most comfortable though, depending on the sort of cloth used to make them. To raise awareness of breast cancer, ladies are asked to forego wearing bras on October 13 of each year. The first No Bra Day was celebrated on July 9, 2011. However, after three years, it was relocated to October, on the thirteenth day of National Breast Cancer Awareness Month. Here are six benefits of going braless at least for a day: (1)Improved breast skin condition - Regularly pressing dirt and perspiration against the skin of the breasts while wearing a bra can clog pores and irritate the skin, especially beneath the breasts. If you have ever worn your sports bra a little too long after a workout, you may have felt this irritation, even though it is more typical in women with larger breasts. Going bra-free allows the skin to breathe more easily, stay clear, and be free of any potential irritants that could cause pores to clog.  (2)Increased blood flow - Long periods spent wearing a bra can feel restrictive, smothering, and plain uncomfortable. (If you concur, raise your hand.) Bras can reduce blood flow to the muscles in the back and chest, which can lead to pain and discomfort. One of the main benefits of forgoing the bra is that you can improve the blood flow to your upper body. Those aching muscles from wearing a bra are history! (3) Enhanced breast form and muscular tone - Fear of their breasts sagging without the added support provided by wearing a bra is one of the main reasons why many women are discouraged from giving up their bras. I am here to tell you that this is wholly untrue. (4) Gradual comfort improvement - Many women are so used to wearing a bra that they feel utterly exposed when they go braless for the first time. Take it from the girl who has not worn a real bra since 2017 (apart from special occasions and holidays): after you get used to it, you entirely lose the discomfort and feel more at ease and liberated overall. You will not ever want to wear actual bras again since it is so unpleasant. (5)Not wearing a bra can strengthen your breasts - Rouillon discovered that not wearing a bra strengthened women's breasts in the same study. Long-term consequences of not wearing a bra revealed that additional muscle tissue developed to act as a natural support system. According to Dr. Seshandri, the breast tissue must be raised against gravity by the body's pectoral muscles. Therefore, don't use the weight equipment at the gym; instead, discard your bra. (6) It may also make them perkier - Your breasts appear 'perkier' when you're without wearing a bra because of all the additional muscle. According to Rouillon's research, women who didn't wear bras often had their nipples elevated 7mm higher than those who did. But according to Dr. Seshadri, it all depends on the size of your breasts. Wearing a bra, she notes, 'may slow down the process of sagging if your breast size is higher.'",
    comments: [],
  },
  {
    id: 1203,
    title: "Court discharges, acquits Nnamdi Kanu of terrorism charges",
    type: "Governance",
    time: "Oct 13",
    author: "Moses O",
    img: "https://static.netnaija.com/i/gVpagPbeNwO.webp",
    body: "The Appeal Court in Abuja has discharged and acquited Nnamdi Kanu, leader of the Indigenous People of Biafra, IPOB, of terrorism charges. Kanu approached the Appeal Court seeking to quash terrorism charges brought against him by the Federal Government. Kanu had faulted the order of Justice Binta Nyako of a Federal High Court, Abuja, which ordered him to answer seven out of the 15-count terrorism charge against him. He had prayed the appellate court to quash the entire charges and set him free on various grounds. The IPOB leader had said the purported offences were not committed in Nigeria. However, the Justice Hanatu Sankey-led 3-man panel of Justices, discharged Kanu. Yje ruling was disclosed by Kanu's lead counsel, Ifeanyi Ejiofor. In a tweet, Ejiofor wrote: 'Appeal allowed, MNk discharged and acquitted. 'Appeal allowed , Onyendu Mazi Nnamdi KANU, discharged and acquitted. We have won! Victory victory victory victory.'",
    comments: [],
  },
  {
    id: 1204,
    title: "Deal sealed, ASUU strike over in matter of days - Gbajabiamila",
    type: "Governance",
    time: "Oct 11",
    author: "Same Emmanuel",
    img: "https://static.netnaija.com/i/pJdN9PmRa4P.webp",
    body: "Speaker of the House of Representatives Femi Gbajabiamila last night said that in a matter of days the Academic Staff Union of Universities, ASUU will call of the 7 months old strike that had kept the citadel of learning under lock and keys. Rising from a meeting with the ASUU leadership led by its President, Professor Emmanuel Osodeke called at the instance of the lawmakers, the speaker said that the deal had been sealed. It will be recalled that the leadership of the House led by Gbajabiamila hd in that last 4 weeks held 4 different meetings with the academic body to resolve the lingering, knotty issues with the government. Last week, the Speaker led a delegation of the lawmakers to the Presidential Villa where he met with President Muhammadu Buhari to submit the report of the meeting with ASUU. Gbajabiamila said President Muhammadu Buhari would make a declaration on the 'No Work No Pay' issue, which is a significant area of contention, on Tuesday October 11. He said that both the government and ASUU had agreed to shift grounds on their respective positions in over all interests of the students and the country at large. The meeting witnessed a closed door session. He said, 'This is a recap to seal the deal on what has been a long fought, long hard road for everybody both for ASUU, the students and the government. As you would recall, some weeks ago the House got involved in this crisis and we had long, tough, intense meetings with ASUU. We had meetings with those on the government side and we are happy to report that as the result of the consultation and intervention of the House, very significant progress has been made and we are more or less at the of the road. Save for dotting some 'I's and crossing some 'T's. 'We agreed with ASUU and the government on certain things which we took to Mr President. I have visited the president twice. First time we made our recommendations with the government shifting some and ASUU shifting some. We spoke with Mr President. There was one sticking issue which was the issue of no work no pay. And the President did ask that he would suggest the recommendations and would have one more meeting which we did on Friday after the budget'.'The issue of UTAS which was another important issue both ASUU and the office of the Accountant General and government have agreed that they will work together and the peculiarities of UTAS that is required for the payment platform IPPIS, they would sit down together and the chairman Committee on Tertiary Education would also be part of that tripartite sit down arrangement to include all those things that are required by ASUU in the IPPIS platform. 'I believe we have covered ground, covered most of the thorny issues and it is basically, what we have agreed with ASUU is basically to put everything on paper and sign off and I believe if we had met yesterday and the papers had been drawn up, ASUU, I am sure would have called of the strike today. But we only just met behind closed doors now and so we have to draw up the agreement as I have stated to you, and hopefully in the next couple of days, of course ASUU has to get back to its bases as well, once that is agreed, I am very hopeful and very excited about the possibility or probability the strike would be called of in a manner of days.",
    comments: [],
  },
  {
    id: 1205,
    title: "The Perfect Gift Ideas For Your Anniversary",
    type: "Romance",
    time: "Oct 09",
    author: "Same Emmanuel",
    img: "https://static.netnaija.com/i/8yZaJr2kaJ0.jpg",
    body: "Special people deserve special treatment every day, but more so on special days, like an anniversary. It doesn't matter if you are celebrating a few months or 10 years together; a thoughtful gift can melt your partner's heart and make their day. The best gift you can give the one you love is one that screams, 'Nobody knows you as I do', and I'm grateful to be with you. So before you go through this list, think of something you know that nobody else does. This list contains some of the best gift ideas for your anniversary. -PHOTO ALBUMS - A photo album will hit the spot, especially if their love language is quality time. Fill your photo album with candids and bloopers for a more personal touch. If your person doesn't take many pictures, try doing a video compilation of random happy moments. -STICKY NOTES IN A JAR - This option is excellent for people that love acts of service and words of affirmation. Nonetheless, you can tailor this to their love language. You may fill these notes with reasons why you love them, short messages to energize them if they're having a bad day, or even a few dares, just for fun. This option requires a lot of creativity, so buckle down.-A BLISSFUL STAYCATION - Long distance partners can enjoy their anniversary together when they plan a staycation. Before the staycation, clear up your schedules for at least two whole days. There should be no calls from work during this period. Fill up those hours with items like a spa date, dinner on the beach, or a resort trip.-A HOTEL DATE WITH A NICE VIEW - Say you don't have two whole days for a staycation; you could do it all in one night. Start with a light lunch, then a fun physical activity like mountain climbing, a hearty dinner, and then a party into the night. If you've got some extra cash, book a fancy vacation away from the hustle and bustle of town, just the two of you basking in your love and affection for each other. Our recommendation, find a hotel with a beachfront or mountain top view. Nature is really the best romance.-JEWELRY - Everyone loves a good piece of jewellery. From wristwatches to rings, necklaces and earrings, jewellery convey a lot of emotions and are a great way to let your partner know just how much you care about them. As an added tip, go on to engrave the jewellery to make them even more special. Engrave an affectionate pet name at the back of wristwatches, and add a great picture of the both of you in a locket. There's so much more you can do with jewellery. -FLOWERS - Every lady loves a beautiful bouquet of flowers. Not only do they communicate feelings of love and affection, but they are also pleasant to the eyes and smell even better. Sending your partner a bouquet of flowers on your anniversary reminds them just how much you care about them and how much you love them. -CAKE - Tasty and delicious, every celebration deserves a cake and anniversaries are not left out. Get them their favourite cake flavour; chocolate, vanilla etc, with an adorable inscription that celebrates your special day. Whichever choice you make, one thing to know for sure is your partner would love and accept the gifts you pick out for your anniversary. Let's know which of these you choose, we'd be happy to know we helped.",
    comments: [],
  },
  {
    id: 1206,
    title: "Appeal Court Orders ASUU To Call Off Strike",
    type: "Governance",
    time: "Oct 07",
    author: "Same Emmanuel",
    img: "https://static.netnaija.com/i/yMX7y9By783.jpg",
    body: "The court of appeal sitting in Abuja has ordered the Academic Staff Union of Universities (ASUU) to call off its strike.At the court session on Friday, the appellate court said ASUU should obey the order of an industrial court which directed the suspension of the strike before seeking to appeal the judgment.ASUU has been on strike since February 14 to press home the demand for improved funding for universities, and a review of salaries for lecturers, among other issues.After several meetings to resolve the strike ended inconclusively, the federal government proceeded to the national industrial court to challenge the action.The industrial court, in a ruling delivered on September 21, granted the federal government's application for an interlocutory injunction to restrain ASUU from continuing with the strike pending the determination of the substantive suit.Not satisfied with the ruling, ASUU approached the court ofappeal seeking leave to challenge the lower court's decision.The court of appeal on Wednesday had asked the parties to explore the option of an out-of-court settlement.However, at the court session on Thursday, both parties agreed to proceed with the hearing after failing to reach a settlement.Delivering a ruling at the resumed court session on Friday, a three-member panel of the appellate court granted the union 'conditional leave' to appeal the industrial court's decision.The panel led by Hamman Barka said for ASUU to file its notice of appeal within seven days, it must show evidence that its members have resumed work immediately.The panel held that failure to adhere to the order will make the appeal incompetent before the court of appeal.",
    comments: [],
  },
  {
    id: 1207,
    title: "Young man builds tricycle from scratch in Kano (Photos)",
    type: "Social Media",
    time: "Oct 07",
    author: "Moses O",
    img: "https://static.netnaija.com/i/m9z7oY8YN2r.webp",
    body: "Young talented man who goes by the name, Faisal builds an amazing tricycle (Keke Napep) from scratch in Kano State. The news was shared on the micro blogging platform, Twitter, by @Ovienews who uploaded pictures showing various stages of its creation. One of the photos shared captured the young man drawing out plans for the tricycle and another showing him welding the various parts together. Faisal, after creating the amazing ride, hit the streets with it, drawing awestruck looks from passers-by. Social media users have commended the young man on his wonderful creation as some called on the FG to support the brilliant Faisal. Nigerian man from Kano, Faisal, fabricates this tricycle from scratch . Please retweet to find him more support and sponsor .",
    comments: [],
  },
  {
    id: 1208,
    title:
      "Moment BBNaija level-up winner, Phyna received her 50 million naira cheque, brand new SUV, others (Photos/Videos)",
    type: "BBNaija 2022",
    time: "Oct 05",
    author: "Same Emmanuel",
    img: "https://static.netnaija.com/i/8yZaJomZNJ0.jpg",
    body: "The winner of the Big Brother Naija level-up season, Ijeoma Josephina Otabor, popularly known as Phyna, has received her 50 million naira cheque and a brand new car. The 25-year-old, who was announced the winner of the 7th season of the reality show on Sunday, October 2, received her 50 million naira cheque and the keys to a brand new SUV car from Innoson Motors during the live prize presentation on Tuesday, October 4. As the winner of the ultimate winner of the 100 million naira grand prize, 25-year-old Phyna gets a N50 million cash prize, a new SUV from Innosons Motors, a Dubai trip for two, a year's supply of Pepsi, new tecno Camon 19, supply of Unik soap and supply of home appliances from Nexus among other mouth-watering prizes. Phyna beat the first runner-up, Bryann, to clinch the grand prize with a total of 40.74% of the votes and became the second female winner of the reality show after 'pepperdem' winner, Mercy Eke.",
    comments: [],
  },
  {
    id: 1209,
    title: "Ogun state government gifts Tobi Amusan N5m and a house",
    type: "Happenings",
    time: "Oct 05",
    author: "Same Emmanuel",
    img: "https://static.netnaija.com/i/rOx7xdX170M.jpg",
    body: "Athletics World champion, Tobi Amusan has been rewarded by the Ogun state government for her success in the recently held 2022 Commonwealth Games.The Ogun State governor, Dapo Abiodun presented her with a house and N5 million as gifts, barely months after breaking the world record.Amusan received the award at the Ogun State Government House, Abeokuta on Tuesday, October 4. While receiving Amusan, Abiodun commended her doggedness, resilience, and determination to excel. 'We are going to be presenting you with one of those homes in Ijebu-Ode. We are rest assured that you will come back home and live in Ijebu Ode,' the governor said. 'We will be giving you a small token. Now you are a big girl, we are only a state government. No matter who you are, you can't be bigger than your state. It's not the quantum of what we are giving you but the thoughts that come with it. We are donating to you the sum of N5 million today.'",
    comments: [],
  },
  {
    id: 1210,
    title: 'Marvel Unveils "Black Panther 2" Trailer (Watch!)',
    type: "Videos & Movies",
    time: "Oct 03",
    author: "Same Emmanuel",
    img: "https://static.netnaija.com/i/bvoKd3PrNrx.jpg",
    body: "Marvel Studios has released the official trailer for its long awaited sequel 'Black Panther: #WakandaForever.' A sequel to its 2020 blockbuster 'Black Panther' the new film tells the story of the Wakanda People in a world following the death of their beloved king T'Challa (Chadwick Boseman). As revealed previously, Boseman's character was not recast, rather the new film is considered to be a tribute to his legacy In the first teaser for the film, the words 'The King lives and the Panther... forever in us...' are painted in Wakandan on a mural of T'Challa in Wakanda. This picture looks to be part of a segment from the teaser that also includes Wakandans dancing and performing music while wearing white ceremonial clothing. The new trailer alsoh includes fighting scenes as a new Black Panther is unveiled.",
    comments: [],
  },
  {
    id: 1211,
    title: "Bobrisky shares a sex tape on his Snapchat",
    type: "Celebrity Gist",
    time: "Yesterday 9:03am",
    author: "Same Emmanuel",
    img: "https://static.netnaija.com/i/xM6K5gxqayE.jpg",
    body: "Bobrisky has joined the 'sex tape leak gang' just after his fellow crossdresser, James Brown, made headlines following the leak of his sex tape with a woman. In the now-deleted Snap Bobrisky shared, a yet-to-be couple were spotted having sex. Also commenting on sex tape leaks, Bobrisky stated that while he tries to act classy, he's actually naughty with his man.He added that his sex tape will show how crazy he is during sex.",
    comments: [],
  },
  {
    id: 1212,
    title:
      "'I never knew it'd be like this' - Lady laments after attempt to get pink lips (Video)",
    type: "Social Media",
    time: "5 hours ago",
    author: "Moses O",
    img: "https://static.netnaija.com/i/yMX7y9kJ783.webp",
    body: "Young lady laments the condition of her lips after the application of an ointment meant to make it pink and attractive. A video making rounds on social media captured the swollen condition of the lips of a lady who got something different other than her desire. Taking to social media to share before and after photos of the pink lips ointment, the lady bemoans the pain from it. She, however, pleaded against backlash from other social media users who slammed her for her desperation.",
    comments: [],
  },
  {
    id: 1213,
    title:
      "'Will be 30 next year, no marriage, no child; I always go to bed in tears' - Lady (Video)",
    type: "Social Media",
    time: "5 hours ago",
    author: "Moses O",
    img: "https://static.netnaija.com/i/mr9KYnq17q6.webp",
    body: "29-year-old lady pours out her heart as she bemoans her relationship status as she approaches the milestone of age 30. A video making rounds on social media captured a lady in tears who prayed for healing over her unmarried and childless state. The lady affirmed that she is particularly worried because she is approaching age 30, hence, feeling helpless as she goes to bed weeping. 'Will be 30 next year, no marriage, no child; I always go to bed in tears. Heal my heart Lord,' she wrote.",
    comments: [],
  },
  {
    id: 1214,
    title: "ASUU Strike: UNIPORT Announces Resumption, Marathon Exams",
    type: "Education News",
    time: "4 hours ago",
    author: "Same Emmanuel",
    img: "https://static.netnaija.com/i/8yZaJrEYaJ0.webp",
    body: "Following the suspension of the eight month old strike by Academic Staff Union of Universities (ASUU), the University of Port Harcourt (UNIPORT) has announced resumption of academic activities.This was contained in a circular exclusively obtained by CAMPUS GIST, Friday, entitled 'Approved Revised Academic Calendar for 2020/2021 session and 2021/2022 session full time.' In the circular seen by CAMPUS GIST, all year one 'B' students for the 2021/2022 session were asked to resume 16th October, while first semester exams commences 24th to 29th October, 2022.But that will be after just a one week revision expected to last from 17th to 21st October, 2022. Senate will meet 30th November to consider the semester results.For the 2020/2021 session, second semester, all old students are to arrive October 30, 2022 while lectures commences 31st October to 22nd December, 2022 (eight weeks).The institution will observe the Christmas break from 23rd December to 2nd January only to reopen 3rd January, 2023 for one week revision before the commencement of the semester exams.",
    comments: [],
  },
  {
    id: 1215,
    title: "PSG: People getting tired of you - Samir Nasri tells Mbappe",
    type: "Sports",
    time: "5 hours ago",
    author: "Moses O",
    img: "https://static.netnaija.com/i/bvWaqXm7rky.webp",
    body: "Former Arsenal attacking midfielder, Samir Nasri, has urged Paris Saint-Germain forward Kylian Mbappe to focus on football and leave the off-pitch stories behind. Nasri believes people are getting tired of Mbappe because the France international has always been on the news so far this season. Mbappe has stirred up controversy once again this season, with multiple reports of his discontent in the PSG squad. Things have reportedly gone over the boil, and Mbappe, 23, now wants to leave PSG. Speaking to Canal Plus, as relayed by PSG Talk, Nasri said Mbappe has all the qualities to become the best player in the world, but he must steer clear of off-field distractions and concentrate on his football to earn adulation from fans. Nasri said, 'The player is fantastic. He is, for me, in the future, the best player in the world; he has all the qualities for it. But he is in too many stories: the image rights of the French team, the penalty gate, yesterday that, before that a year to make his choice between PSG and Real Madrid, where he left all the world in suspense. 'When your name comes out too much, people start getting tired of you. He has so much talent. As soon as there is a rumour about him, he should deny it if it is not true and play football. And everyone will start loving him again.'",
    comments: [],
  },
  {
    id: 1216,
    title:
      "OIL THEFT: Tompolo uncovers illegal pipeline operating near military post in Delta",
    type: "Governance",
    time: "41 minutes ago",
    author: "Same Emmanuel",
    img: "https://static.netnaija.com/i/3g8NBnoyNDR.webp",
    body: "The Tantita Security Services Nigeria Limited, TSSNL, a surveillance company operated by ex-militant leader, Government Ekpemupolo, alias Tompolo, has discovered another huge illegal pipeline connected to the 48-inch Trans Forcados Export Trunk line, at the rear of a military security post in Burutu Local Government Area, Delta State. Sources said that oil companies, oil bunkers, Nigerian National Petroleum Corporation, NNPCL, and security officials jointly steal crude oil through the illicit pipeline connected to the trunk line through an abandoned pipeline by the Nigerians Agip Oil Company Limited, NAOCL, and linked to a location in the high sea, where they load crude oil into vessels and sell overseas. Meanwhile, the Oil Spill Victims Initiative, OSPIVV, has threatened to sue NNPCL and Shell Petroleum Development Company, SPDC, over the illegal pipeline connections used to siphon the country's crude oil. The Shell Petroleum Development Company, SPDC, operates the Forcados Terminal in Ogulagha, which has a nameplate capacity to export 400,000 barrels per day. It takes delivery of crude from the Forcados Oil Pipeline System and is the second largest pipeline network in the oil-producing region, after the Bonny Pipeline System in the eastern Niger Delta. Some IOCs and Nigerian independents operating in the western Niger Delta pump oil to the Forcados Oil Terminal for exports. The newest discovery is like the earlier illegal 4-km pipeline also attached to the same Trans-Forcados export trunk line, earlier discovered by Tantita operatives. An executive director of OSPIVV, Prince Harrison Jalla, told reporters in Warri, 'There are many reports of crude oil theft in the Niger Delta, but we are particularly interested in the theft of crude oil from the Forcados Terminal.' 'They have been stealing our national heritage for the past nine years and no one can say for sure where it began or where it ended. We want to start by holding the NNPCL and SPDC accountable for the oil theft and the atrocities committed against the Niger Delta people. 'We will take on the NNPCL and SPDC. We have already briefed our solicitors to sue. So many International Oil Companies have to account for this heist, but we want to start with the Shell Group because there is no way they could pipe crude oil from those terminals without the involvement of those running the terminal. 'We do not know if other areas where pipelines traverse the region are involved. We can now see there is a massive approach to stealing crude oil in the Niger Delta region. Therefore, we are going to court. The two organizations should let the court know what they know about the massive oil heists since 2003. 'If we have a court where everyone will recount what they know, it is fair and good for us. We want to take them to a proper court of competent jurisdiction to unravel what is happening in the trunk lines. 'Our interest is to unravel what has been happening in the oil sector, so whether they claim it at Forcados Terminal is not our business. Our concern is that some people have perpetrated the crime of massive oil theft and the resources pocketed by those we do not know. The international community and IOCs are involved,' he said. On the newly uncovered criminal pipeline, sources informed Sunday Vanguard that the bunkers actually ferry the crude to the sea for loading and onward movement abroad through the abandoned NAOC pipeline.",
    comments: [],
  },
  {
    id: 1217,
    title: "Nud£ photos of #BBNaija Khloe trends",
    type: "BBNaija 2022",
    time: "Feb 01, 2018",
    author: "Tayo",
    img: "https://img.netnaija.com/hsi/aHR0cHM6Ly9pMi53cC5jb20vd3d3LnlhYmFsZWZ0b25saW5lLm5nL3dwLWNvbnRlbnQvdXBsb2Fkcy8yMDE4LzAyLzEzNDY2MTcwXzEwMjA0ODg5Mjc1NzkxNDMzXzE1MzUwOTIxMDc4MjIzMzUyNzlfbi5qcGc/cmVzaXplPTY0MCUyQzgwMQ==/images/13466170_10204889275791433_1535092107822335279_n.jpg?resize=640%2C801",
    body: "The 24-year-old Fashion stylist says she's an entrepreneur, and a lover of horror movies. Khloe owns having no hidden talent and is only looking to bring drama to the house. Just incase you missed it! Award-winning Video director, Unlimited claimed he's been dating Khloe for a while, and they'd get married once she leave the house with the money.",
    comments: [],
  },
];
