export const celebrityData = [
  {
    id: 1401,
    title:
      "Berbiedoll shares her HIV test result as she denies having an affair with IVD",
    type: "Celebrity Gist",
    time: "2 hours ago",
    author: "Moses O",
    img: "https://static.netnaija.com/i/1qdNVj1mN4g.webp",
    body: "Popular socialite and influencer, Kayode Christiana popularly known as Berbiedoll has debunked claims of having an affair with businessman, Ikechukwu Ogbonna a.k.a IVD. IVD made headlines following the report of his wife, Bimbo Ogbonna's death. It was alleged that before her death, he subjected her to rounds of domestic abuse which left her scarred. Just like Big Brother Naija winner, Mercy Eke, Berbiedoll was also accused of having an affair with IVD whose brother-in-law and late wife claims to have HIV. Reacting to the claim, the socialite released her HIV test result and further stated that she decided to go public with her negative status because she has worked hard for her brand and would like to keep it that way. Berbiedoll also went on to place curses on the social media user who allegedly started the rumor of the affair.",
    comments: [],
  },
  {
    id: 1402,
    title:
      "Erica Nlewedim says she's a feminist and reveals the only reason she will submit to a man",
    type: "Celebrity Gist",
    time: "1 hours ago",
    author: "Same Emmanuel",
    img: "https://static.netnaija.com/i/no4NXY1yK9M.jpg",
    body: "Erica Nlewedim has revealed that she is a feminist. The former Big brother Nsija reality star called herself a 'feminine feminist'. She explained that only love can make her submissive. She then added that some guys demand submission simply because they are men, not because they've earned it.",
    comments: [],
  },
  {
    id: 1403,
    title:
      "Tasha Amos shares test result as she also debunks having an affair with IVD",
    type: "Celebrity Gist",
    time: "2 hours ago",
    author: "Moses O",
    img: "https://static.netnaija.com/i/3g8NBnWeNDR.webp",
    body: "Socialite and influencer, Tasha Amos has issued a disclaimer to counter claims of having an affair with businessman, Ikechukwu Ogbonna a.k.a IVD, who is at the center of a domestic violence controversy following the death of his wife, Bimbo Ogbonna. Tasha Amos also shared a photo of her HIV test result which came out negative, to further buttress her point of not having an affair with IVD, after the popular car dealer's late wife and brother-in-law alleged that he has HIV. In the disclaimer, issued hours after Big Brother Naija winner, Mercy Eke, and influencer, Berbiedoll also denied having an affair with IVD, the socialite warned people to be mindful of the information they share online as it could worsen the pain of the family. She wrote:- 'Disclaimer!!!, I will usually not talk about issues like this but for the face, it bothers around life and death. I will like to state for the records I have nothing to do with all these allegations leveled against me. Making claims & allegations without substantial evidence but only ill intended motives will only worsen the pain of the family that have lost their loved ones. Please be guided accordingly. Thank you'.",
    comments: [],
  },
  {
    id: 1404,
    title:
      "IVD stirs reactions as he updates Instagram display picture amidst backlash",
    type: "Celebrity Gist",
    time: "2 hours ago",
    author: "Moses O",
    img: "https://static.netnaija.com/i/5wPKLgQkNVB.webp",
    body: "Famous Lagos businessman, Ikechukwu Ogbonna popularly known as IVD, triggers mixed reactions with new display picture amidst backlash trailing loss of his wife. This comes following the numerous interviews granted by the late Bimbo Ogbonna's brother seeking justice for the late mother of five. In a recent development, IVD who had been quiet on the issue after taking down all the posts on his Instagram makes an appearance on the page. The business changed his former display picture to that of the photo of his wife and children. 'He no go kill himself ni! Stay away from domestic violence life moves on if you die😢,' a user wrote. Another social media user wrote in reaction, 'He is about to change his victim! Young girls, do not think he's gon change.'",
    comments: [],
  },
  {
    id: 1405,
    title: "Burna Boy launches Cannabis brand 'BrkFst' in Miami",
    type: "Celebrity Gist",
    time: "2 hours ago",
    author: "Moses O",
    img: "https://static.netnaija.com/i/Aq2NAYl6NzJ.webp",
    body: "Following the success of his hit single 'Last Last', Nigerian Afrobeats sensation and Grammy Award winner Burna Boy has launched his Cannabis brand BrkFst.Black Cannabis Magazine reported that Burna Boy's Cannabis brand BrkFst, is a partnership with Jokes Up/ Ice Kream, and it was launched in South Beach, Miami, a few days ago. The launch came a little over a year after the singer said the ban on cannabis in Nigeria is 'dumb'. The brand launch which coincided with Miami Carnival, started with a Pop Up from 12- 3, followed by brunch at a Miami Diner from 3:30-7. There was also a team representing Burna Boy at the all-white-themed Tipsy Musical Festival at Bayfront Park, which he headlined. It is speculated that the brand is inspired by Burna Boy's hit single 'Last Last', where he sings... 'I need Igbo and shayo (Shayo).' In those lines, Burna Boy talked about getting a heartbreak, moving on, and healing from the 'emotional wounds' with weed (Igbo) and alcohol (shayo). The video for the song is currently on YouTube with 94 million views and is the first single released from his latest album, 'Love, Damini,' which was released on July 8th, 2022, through Atlantic Records. The afrobeats track is produced by Chopstix, and it samples Toni Braxton's classic 2000 record 'He Wasn't Man Enough.'",
    comments: [],
  },
  {
    id: 1406,
    title:
      "Blessing Okoro clashes with late Bimbo's brother, slams him for granting 24 interviews (Video)",
    type: "Celebrity Gist",
    time: "2 hours ago",
    author: "Moses O",
    img: "https://static.netnaija.com/i/eDxaw9eQKPZ.webp",
    body: "Famous relationship adviser, Blessing Okoro, condemns the late Bimbo Ogbonna's brother for chasing clout after granting multiple interviews and revealing many information about their family. This comes following the unending exposé done by Oyindamola Martins about the passing of his sister to domestic violence at the hands of husband, IVD. In a live session, Blessing Okoro berated the late Bimbo's for accusing IVD of shooting at Cubana's club, having HIV, pushing his wife in fire after she soaked herself with fuel, and many others. According to the relationship expert, Oyindamola is meant to be grieving other than feeding the public too much information than it's needed. In response to Blessing Okoro before taking down his account, Oyindamola, wished for 'an IVD' for Blessing for coming after him publicly.",
    comments: [],
  },
  {
    id: 1407,
    title:
      "Bobrisky spills more details as he slams ailing fan, Lord Casted, for claiming that tattoo got him sick (Video)",
    type: "Celebrity Gist",
    time: "2 hours ago",
    author: "Moses O",
    img: "https://static.netnaija.com/i/G4E7z9V6Kb6.webp",
    body: "Nigerian crossdresser, Bobrisky, has slammed his ailing fan, Lord Casted, for calling him out again over his illness. Bobrisky in a post on Instagram, accused the fan of getting in bed without protection, and trying to pin the illness on the tattoo he drew. He slammed the young man, insisting that he tells the truth to everyone. Bobrisky also regretted stretching out a helping hand to Lord Casted after seeing his video on social media for the first time. In his words:- 'If there's one thing I wish or want to erase, it's helping ungrateful people. Lord Casted or whatever your name is, stop calling my name in your videos. I remember the last time I have you money, you rained insult on me and called me fake.' 'If you truly need help, stop taking drugs. Lastly stop lying to everyone that you got illness from tattoo. When you were enjoying it raw, I dey help you enjoy am?'",
    comments: [],
  },
  {
    id: 1408,
    title:
      "Reactions as Nigerian man shares video of Wizkid's alleged childhood home in Surulere",
    type: "Celebrity Gist",
    time: "3 hours ago",
    author: "Moses O",
    img: "https://static.netnaija.com/i/mr9KYn5m7q6.webp",
    body: "A Nigerian man has shared a video of a house in Surulere where he claimed popular singer, Wizkid, lived during his childhood. While sharing a video of the house, he called a security man residing at the area to attest to his claim, and the security man affirmed that Wizkid actually grew up there. Sharing the video on TikTok, the man captioned: 'This is Wizkid's childhood home in Surulere, Lagos. Wizkid is called grace. He started from nothing to something.' Reacting to the video, @da_tasie said:-'Why will I not love dis man 🥺❤️⭐️🦅 I keep believing, seb' Oluwa loni ma ribatise.' @user151622 commented: 'Everyone has a past history and if u don't u would get to understand or experience the world itself.' @sparklynnath added: 'Wizkid self nor suffer, that house na big man house oo, I been think say na mud hux he take grow.'",
    comments: [],
  },
  {
    id: 1409,
    title:
      "Ooni of Ife throws grand wedding party for first wife, Yeyeluwa Mariam Ogunwusi (Videos)",
    type: "Celebrity Gist",
    time: "3 hours ago",
    author: "Moses O",
    img: "https://static.netnaija.com/i/1xYNeM1ANLJ.webp",
    body: "Barely two days after marrying his 4th wife, Princess Ashley Adegoke, the Ooni of Ife Oba Adeyeye Ogunwusi has thrown a grand wedding party for his first wife, Yeyeluwa Mariam Ogunwusi. Recall that the Osun monarch who began marrying new wives in September, 9 months after his ex-wife Naomi Silekunola announced their split, now has 4 wives. Queen Mariam became the Osun monarch's first wife after their wedding ceremony in September, as his three previous marriages failed. Days after the wedding ceremony, Queen Elizabeth Ogunwusi was betrothed to him in Magodo, Lagos. Tobi Phillips became Ooni's third wife following their wedding ceremony on October 9, 2022. The Ooni of Ife also married Princess Ashley Adegoke as his fourth wife on Friday, October 14, 5 days after the Osun monarch married ex-beauty Queen, Tobi Phillips. On Sunday, October 16, Ife Ife buzzed with fanfare following a grand wedding party the Oonirisa held for his first wife, Yeyeluwa Mariam Ogunwusi. The Monarch is expected to marry two more wives before the end of October. Here are videos from the grand wedding party...",
    comments: [],
  },
  {
    id: 1410,
    title:
      "'God never sleeps nor slumbers' - Yul Edochie's 1st wife, emotional as she shares messages she received",
    type: "Celebrity Gist",
    time: "3 hours ago",
    author: "Moses O",
    img: "https://static.netnaija.com/i/gVpagPm5NwO.webp",
    body: "Yul Edochie's first wife, May Edochie, has penned down a heartfelt note amid her husband's marriage to second wife. The beautiful mother of 4 thanked fans for standing by her and helping her get through the emotional trauma she faced. she also revealed that she has been receiving messages from fans and well wishers expressing their love, concern and support for her. According to her, the heartfelt messages made her feel like it's her birthday again. In her words:- 'My amazing, loving and distraught fam, I'm here and I'm fine. Honestly your concern, love and support is immeasurable and I want y'all to know that I don't take any of these for granted. I am favoured to have you and should count my blessings instead. When I came online today, for a sec, I taught it was my birthday again😊.... My pix on timelines and loads and loads of messages, even my sis' inbox is full, my only option was to smile from ear to ear😊😊😊. God indeed never sleeps nor slumbers and He is forever faithful and true to His words. I want y'all to know that I love back to the moon and beyond and pray that the good Lord will bless you all abundantly for me and give you reasons to smile.'",
    comments: [],
  },
  {
    id: 1411,
    title:
      "Update: Brother to late Bimbo speaks on why his sister put fire on her matrimonial home that eventually led to her death",
    type: "Celebrity Gist",
    time: "Yesterday 9:17pm",
    author: "LuvlyGist",
    img: "https://static.netnaija.com/i/zOJabvOZaG2.jpg",
    body: "Oyindamola Martins who is the younger brother of late Bimbo Ogbonna, wife of auto dealer Ikechukwu Ogbonna aka IVD, has given details of how his sister put fire to her matrimonial home that eventually led to her death In an interview with OAP, DaddyFreeze, Oyindamola said after many years of sadness, physical and emotional trauma, the late Bimbo recently decided it was time for her to walk out of her marriage but she did not want to walk away empty-handed. He said Bimbo told him that she had 'sacrificed' her life for her husband, IVD and that she made him who he is today and cannot just walk away. Oyindamola said Bimbo asked her husband to give her the documents of their property in Lagos so she can take possession of the property but he refused. He said Bimbo then vowed to burn the house so that both of them would not have it. 'She said since this is the only house we have, let us burn it so the two of us would leave with nothing' He said Bimbo poured kerosine on herself and then threatened to burn herself but IVD who was home at the time failed to persuade her not to do so. He said Bimbo then set fire to their curtain and held on to IVD but he allegedly pushed her into the burning curtain which consumed her. She got 100-degree burns. As she was lighting up the whole house, she poured kerosine on her body and was like let everything just end.  When she did it, she stopped for a while and went round the house. He was not saying anything. He was like 'if you want to die, die'.' Oyindamola said at this point, Bimbo set fire to their curtain. 'As the curtain was burning, she now jacked him and was like you will give me this papers today..He pushed her off his body and this got her into the curtain.' Oyindamola said Bimbo suffered 100-degree burns on her body. 'She suffered from a hundred degree burns. That takes like about of a couple of minutes to get 100 degree burns. When she was on fire, her husband was right in front of her doing nothing.' He said Bimbo was the one who ran out by herself and asked for help to be taken to any hospital. He said she was rejected by 10 different hospitals before they finally found one where she was admitted. On allegations that Bimbo helped IVD carry out some ritual exercise, Oyindamola said he cannot confirm that but it is something Bimbo could have done because she loved him so much. He also said that he isn't sure if IVD has HIV or not.",
    comments: [],
  },
  {
    id: 1412,
    title: "Reality TV star, Khloe, flaunts her butt in sexy new photos",
    type: "Celebrity Gist",
    time: "Yesterday 9:11pm",
    author: "LuvlyGist",
    img: "https://static.netnaija.com/i/ZOoan3oENjA.jpg",
    body: "BBNaija star, Abiri Oluwabusayomi aka Khloe showed off her butt in sexy new photos she shared online this afternoon. Clad in a black bodysuit and pantyhose, Khloe posed for her sexy photo shoot.",
    comments: [],
  },
  {
    id: 1413,
    title:
      "We suspect they took a blood covenant because she kept running back to him - Late Bimbo Ogbonna's brother reveals their family did everything including taking her to rehab for her to leave IVD",
    type: "Celebrity Gist",
    time: " Yesterday 9:56am",
    author: "LuvlyGist",
    img: "https://static.netnaija.com/i/wnRaMDmm7dq.jpg",
    body: "The brother of late Bimbo Ogbonna, wife of auto dealer, Ikechukwu Ogbonna, has said his family members did everything possible to keep Bimbo away from IK but she kept on going back to him. While responding to comments on his Instagram page, Oyindamola said it all started when an 18-year-old Bimbo met Ikechukwu. He said she had given Ikechukwu all her school fees and eventually dropped out of school. He further stated that after several failed warnings for them to stop seeing each other, Bimbo's family took her to Abuja to live. However, IK contacted her and told her that he was going to kill himself if she did not come back.  He said Bimbo ran down to Lagos to be with him. Oyindamola added that their family even offered to pay IVD money to stay away from young Bimbo at the time, but  they continued their relationship. He said he believes Bimbo and IVD had a blood covenant because she kept going back to him even with all that was going on.",
    comments: [],
  },
  {
    id: 1414,
    title:
      "Doris Ogala sends message to naysayers as she reportedly acquires three cars and house",
    type: "Celebrity Gist",
    time: "Yesterday 7:47pm",
    author: "Moses O",
    img: "https://static.netnaija.com/i/90ZNPP6RN8e.webp",
    body: "Notable Nollywood actress, Doris Ogala, counts her blessings as she reportedly gifts her mother a car, and acquires two more for herself, and a new house. The thespian took to the image-sharing platform Instagram to speak about her progress while passing a message to those against her. Making the announcement, Doris Ogala advised those against her progress to request a refund from their native doctors. 'Pls go and tell your native doctor to refund you I'm still progressing! Just bought a house.. Bought a car for mumsy. Bought two cars for my self.. Ahhhhhh Ask for your refund Biko!' she wrote on her Instagram story.",
    comments: [],
  },
  {
    id: 1415,
    title:
      "Precious Chikwendu slams troll that wished her same fate as late Bimbo Ogbonna",
    type: "Celebrity Gist",
    time: "Yesterday 7:40pm",
    author: "Moses O",
    img: "https://static.netnaija.com/i/XV5KvQBGN9m.webp",
    body: "Femi Fani-Kayode's wife, Precious Chikwendu, slams a troll who made an insensitive comment about being the next to be 'cried over.' This comes amidst the controversy trailing the businessman, Ikechukwu Darry Ogbonna, popularly known as IVD following the death of his wife to domestic violence. It would be recalled that Precious Chikwendu fought tooth and nail to return to the life of her children following the battle for custody with her husband. A social media user, however, wished Precious the same fate as IVD's wife following her reconciliation with Femi Fani Kayode. 'You are next to be cried over since you choose to go back to the animal the whole world joined you in fighting,' the troll wrote.",
    comments: [],
  },
  {
    id: 1416,
    title:
      "Any Pastor that says there's witchcraft in Nollywood is a liar - Keppy Ekpenyong",
    type: "Celebrity Gist",
    time: "Yesterday 11:49am",
    author: "Moses O",
    img: "https://static.netnaija.com/i/yMX7y94e783.webp",
    body: "Veteran actor, Keppy Ekpenyong Bassey has pushed back at claims of witchcraft practice in Nollywood. Responding to a question by a student of the Africa Film Academy training, who asked if there is truly witchcraft in Nollywood as alleged by a popular pastor, Keppy Ekpenyong stated that any Pastor who claims there's witchcraft in Nollywood is a liar. The veteran actor who further added that people behind such claim are 'stupid', also stated that Nollywood is the second largest employer of labour in Nigeria outside the civil service. Keppy said:- 'The industry in Nollywood is the second largest employer of labour in Nigeria outside the civil service. No other industry employs labour more than Nollywood. What kind of stupid person will now say that there is witchcraft in Nollywood? Any pastor that says that is a liar. Take it from me.'",
    comments: [],
  },
];
