export const comedyVideosData = [
  {
    id: 2201,
    title:
      "Broda Shaggi - Monthly Salary (feat. Nini Singh, Michael Ejoor & Alhaji Suberu)",
    type: "Comedy Videos",
    time: "Oct 15",
    duration: "00:11:05",
    img: "https://static.netnaija.com/i/PrO7OeOyNyp.jpg",
    body: "Having the belief that he has been favored and overpaid, Broda Shaggi goes on a spending spree and spends on Nini Singh. After the circumstances behind his 'overpay' is revealed, Shaggi is shell-shocked. Also starring Michael Ejoor and Alhaji Suberu; shot by Bot Studio ",
    source: "https://www.youtube.com/watch?v=-LgXbOrZVCk",
    comments: [],
  },
  {
    id: 2202,
    title:
      "Mr Macaroni - The Prayerful Husband (feat. Small Doctor & Mo Sogunle)",
    type: "Comedy Videos",
    time: "Oct 05",
    duration: "00:09:15",
    img: "https://static.netnaija.com/i/mjyK6D4YawD.jpg",
    body: "Daddy Wa receives a new suitor for Motunde in the person of Small Doctor who is as prayerful to a fault. Shot by Edem Victor.",
    source: "https://www.youtube.com/watch?v=dxEyysf5SJc",
    comments: [],
  },
  {
    id: 2203,
    title:
      "Broda Shaggi - 30BG New Signee (feat. BrainJotter & Daniel Etim Effiong)",
    type: "Comedy Videos",
    time: "Oct 03",
    duration: "00:09:10",
    img: "https://static.netnaija.com/i/Gem7QXAmKYx.jpg",
    body: "Broda Shaggi and Brainjotter collaborates in this new comedy skit titled '30BG New Signee'. The skit sees Broda Shaggi as manager, organises for his act 'Sparkatus' - 'the next best thing to Davido' to perform at a birthday party. 30BG New Signee also stars Nollywood actor, Daniel Etim-Effiong. Shot by Bot Studioz.",
    source: "https://www.youtube.com/watch?v=G3RZxvIkIs8",
    comments: [],
  },
  {
    id: 2204,
    title:
      "Broda Shaggi - The Eve Gender (feat. Bimbo Ademoye, Efe Irele, Correct Aboki, Alhaji Suberu & Tontirin)",
    type: "Comedy Videos",
    time: "Sep 28",
    duration: "00:08:19",
    img: "https://static.netnaija.com/i/AqgKGP3x7r1.jpg",
    body: "Broda Shagg features Bimbo Ademoye, Efe Irele, Correct Aboki, Alhaji Suberu and Tontirin in his new skit titled 'The Eve Gender'. The skit sees Shaggi's girlfriends gang up to teach him a lesson. Shot by Bot Studioz.",
    source: "https://www.youtube.com/watch?v=xnKittJ6kxM",
    comments: [],
  },
  {
    id: 2205,
    title:
      "Broda Shaggi - Trouble Nene (starr. Nengi Rebecca Hampson, Ope Keshinro & Ton Tirin)",
    type: "Comedy Videos",
    time: "Sep 29",
    duration: "00:08:36",
    img: "https://static.netnaija.com/i/mjyK6PEDawD.jpg",
    body: "Broda Shaggi features Nengi of BBNaija fame in his new skit titled 'Trouble Nene'. The new skit sees Nene come to the defense of Her sister who Shaggi just broke up with. Shot by Bot Studioz.",
    source: "https://www.youtube.com/watch?v=jP9prrVGT94",
    comments: [],
  },
  {
    id: 2206,
    title: "Papa Benji",
    type: "Comedy Videos",
    time: "Dec 12, 2020",
    img: "https://static.netnaija.com/i/g3M7324vK9y.jpg",
    body: "Papa Benji is the story of the Egwuonwu family, their pepper soup joint and their son Benjamin. Papa Benji (Mr. Bajamin Engwuowu, played by comedian Senator), an industrious Igbo man who took a loan to start his pepper soup joint, which attends to many other interesting characters that come into the joint; Mrs. Obioma Engwuowu (played by Ekwutousi), a failed fashion designer who owns a shop right in front of their building and Benjamin Jr. (played by OG Tega), a first year student of University of Lagos, a perfect description of what they call a Marlian.",
    source: "https://www.youtube.com/watch?v=Iwamc8yqBQc",
    genre: "Comedy, Drama",
    stars:
      "Basketmouth, Senator, Nedu, OG Tega, Ekwutousi, Buchi, Sunshine Rosman",
    premiere: "Oct 3, 2022 (South Korea)",
    comments: [],
  },
  {
    id: 2207,
    title:
      "Mr Macaroni - Serious Wahala in the House (starr. Mide Martins & Korex)",
    type: "Comedy Videos",
    time: "Aug 03",
    duration: "00:07:28",
    img: "https://static.netnaija.com/i/rOx7x6zEN0M.jpg",
    body: "Debo (Mr Macaroni) brings his friend Otunba (Korex) to the house to meet His new wife. Their conversation was going good until Otunba harmlessly did the unacceptable and the new Mummy Wa (Mide Martins) let loose.",
    source: "https://www.youtube.com/watch?v=5iHvQxfQE7M",
    comments: [],
  },
  {
    id: 2208,
    title: "Mr Macaroni - My New Wife (starr. Mide Martins & Kemz Mama)",
    type: "Comedy Videos",
    time: "Jul 27",
    duration: "00:06:19",
    img: "https://static.netnaija.com/i/XV5Kvl6na9m.jpg",
    body: "Daddy Wa brings home, a new wife, who comes in and takes charge immediately, even sending Mummy Wa out. Starring Mr. Macaroni, Mide Martins and Kemz Mama.",
    source: "https://www.youtube.com/watch?v=9DD-4lLNPNg",
    comments: [],
  },
  {
    id: 2209,
    title: "Kiekie & Broda Shaggi - The New Pharmacist",
    type: "Comedy Videos",
    time: "Jul 13",
    duration: "00:09:14",
    img: "https://static.netnaija.com/i/PrO7OMZ6Nyp.jpg",
    body: "Nurse Kiekie is tasked with finding a new pharmacist for her pharmacy. Broda Shaggi shows up, not for the job, but it all happens he's the best person for the job by Kiekie's recommendation. Shaggi gets the job and gets to handle his first patient. Shot by Edem Victor.",
    source: "https://www.youtube.com/watch?v=Ucz3x80RzRM",
    comments: [],
  },
  {
    id: 2210,
    title: "Edem Victor - My Inheritance (starr. Motunde, Nasboi & Korexx)",
    type: "Comedy Videos",
    time: "Jul 07",
    duration: "00:06:21",
    img: "https://static.netnaija.com/i/rOx7xYPba0M.jpg",
    body: "After the previous meeting, the family has reconvened to pick someone to take up the office of Ijogo of the community which just recently became vacant..Felix explains his claims but Uncle as usual has the final say. Starring Nasboi, Korexx, Mo Sogunle and Dirty Grandma; produced and shot by Edem Victor.",
    source: "https://www.youtube.com/watch?v=0yt8z2jW_vI",
    comments: [],
  },
  {
    id: 2211,
    title:
      "Professor Hardlife - The Handout (starr. Mr. Macaroni, Korexx, Diva Gold, Timi Agbaje, Bro Bouche & Mofe)",
    type: "Comedy Videos",
    time: "Jul 07",
    duration: "00:04:02",
    img: "https://static.netnaija.com/i/3g8NByWXaDR.jpg",
    body: "Professor Hardlife reveals Mofe is yet to get the handout he had told the entire class to get. The rest of the class came to her defense and was about to make a contribution to help buy hers just before her father - a loving one at that, appears to make the payment. Starring Mr. Macaroni, Korexx, Timi Agbaje, Bro Bouche, Mofetoluwa, Victoria Okere and Divagold.",
    source: "https://www.youtube.com/watch?v=WWOw725ED60",
    comments: [],
  },
  {
    id: 2212,
    title: "Twyse Ereme - Talent Hunt (Nigeria Audition)",
    type: "Comedy Videos",
    time: "Jun 09",
    duration: "00:02:57",
    img: "https://static.netnaija.com/i/qEQN2BAdN6W.jpg",
    body: "Jerry, Sade and Taofeek take their turns to perform for the judges in the 'Show Yourself Talent Hunt'. Created and shot by Twyse Ereme.",
    source: "https://www.youtube.com/watch?v=CKliZiAWTeg",
    comments: [],
  },
  {
    id: 2213,
    title: "Nasboi & Modola - Relationship for Hire",
    type: "Comedy Videos",
    time: "Jun 09",
    duration: "00:05:43",
    img: "https://static.netnaija.com/i/yMX7ym58783.jpg",
    body: "Modola and Nasboi are having a good date and are about go their separate ways before Modola makes a proposal that didn't seem to go down well with Nasboi. All hell let loose when Nasboi puts forwards his own proposal. Created and shot by Edem Victor.",
    source: "https://www.youtube.com/watch?v=RuRq2G4mCGc",
    comments: [],
  },
  {
    id: 2214,
    title: "BrainJotter & Lasisi Elenu - World's Most Sincere Job Interview",
    type: "Comedy Videos",
    time: "Jun 06",
    duration: "00:08:15",
    img: "https://static.netnaija.com/i/1qdNVZYgN4g.jpg",
    body: "BrainJotter attends a job interview where Lasisi is the interviewer and continuously answers honestly in a way that gets the interviewer flared up. Shot by Director Sweet.",
    source: "https://www.youtube.com/watch?v=CfbLoy-0zRs",
    comments: [],
  },
  {
    id: 2215,
    title: "Broda Shaggi - Phone Seller (starr. Ton Tirin)",
    type: "Comedy Videos",
    time: "Jun 06",
    duration: "00:04:55",
    img: "https://static.netnaija.com/i/gEeK8go4NP8.jpg",
    body: "Broda Shaggi and his assistant Ton Tirin goes about selling fake phones to unsuspecting buyers until he met his waterloo. Shot by Bot Studioz.",
    source: "https://www.youtube.com/watch?v=5xsK8CB1bLg",
    comments: [],
  },
  {
    id: 2216,
    title:
      "Skibii Mayana The Baddest Boy (starr. Skiibii, Mr Macaroni, Motunde & Mummy Wa)",
    type: "Comedy Videos",
    time: "Jun 03",
    duration: "00:04:43",
    img: "https://static.netnaija.com/i/m9z7oP9ya2r.jpg",
    body: "With Daddy Wa's female interests of the day all turning out to be romantically engaged with Skiibii and Mayana (who are one and the same person), he (Daddy Wa) reluctantly agrees to meet Motunde's new suitor despite the bad day he is having. Shot by Edem Victor.",
    source: "https://www.youtube.com/watch?v=6zEardqAB5k",
    comments: [],
  },
];
