export const governanceData = [
  {
    id: 1901,
    title: "China opens police station in Nigeria",
    type: "Governance",
    time: "1 hour ago",
    author: "Moses O",
    img: "https://static.netnaija.com/i/rOx7x9oba0M.webp",
    body: "The Chinese government has opened police stations in Nigeria and in over 20 countries in Europe, the Americas, Asia, and Africa. The move could be viewed as a campaign to tackle the rising criminal activities, such as fraud and telecommunication crimes by Chinese nationals living abroad. The new development was stated in an investigative statement titled, 110 Overseas Chinese Transnational Policing Gone Wild. The Chinese Police Station known as 'Service Station' is located in Benin City in Nigeria and in two other countries in Africa including Maseru in Lesotho, and Dar es Salaam in Tanzania. Further reports also have it that the police stations are created to bring 'down on all kinds of illegal and criminal activities involving overseas Chinese'.",
    comments: [],
  },
  {
    id: 1902,
    title: "Deal sealed, ASUU strike over in matter of days - Gbajabiamila",
    type: "Governance",
    time: "Oct 11",
    author: "Same Emmanuel",
    img: "https://static.netnaija.com/i/pJdN9PmRa4P.webp",
    body: "Speaker of the House of Representatives Femi Gbajabiamila last night said that in a matter of days the Academic Staff Union of Universities, ASUU will call of the 7 months old strike that had kept the citadel of learning under lock and keys. Rising from a meeting with the ASUU leadership led by its President, Professor Emmanuel Osodeke called at the instance of the lawmakers, the speaker said that the deal had been sealed. It will be recalled that the leadership of the House led by Gbajabiamila hd in that last 4 weeks held 4 different meetings with the academic body to resolve the lingering, knotty issues with the government. Last week, the Speaker led a delegation of the lawmakers to the Presidential Villa where he met with President Muhammadu Buhari to submit the report of the meeting with ASUU. Gbajabiamila said President Muhammadu Buhari would make a declaration on the 'No Work No Pay' issue, which is a significant area of contention, on Tuesday October 11. He said that both the government and ASUU had agreed to shift grounds on their respective positions in over all interests of the students and the country at large. The meeting witnessed a closed door session. He said, 'This is a recap to seal the deal on what has been a long fought, long hard road for everybody both for ASUU, the students and the government. As you would recall, some weeks ago the House got involved in this crisis and we had long, tough, intense meetings with ASUU. We had meetings with those on the government side and we are happy to report that as the result of the consultation and intervention of the House, very significant progress has been made and we are more or less at the of the road. Save for dotting some 'I's and crossing some 'T's. 'We agreed with ASUU and the government on certain things which we took to Mr President. I have visited the president twice. First time we made our recommendations with the government shifting some and ASUU shifting some. We spoke with Mr President. There was one sticking issue which was the issue of no work no pay. And the President did ask that he would suggest the recommendations and would have one more meeting which we did on Friday after the budget.",
    comments: [],
  },
  {
    id: 1903,
    title:
      "Federal Government warns Nigerian citizens to be wary of fake study and job opportunities in Cyprus",
    type: "Governance",
    time: "4 hours ago",
    author: "Same Emmanuel",
    img: "https://static.netnaija.com/i/LqXNEJkDKlE.webp",
    body: "The Federal government has warned Nigerians to be wary of fake admissions and unverifiable job opportunities in Cyprus. The Ministry of Foreign Affairs spokesperson, Francisca Omayuli, titled 'Travel Advisory For Nigerians Seeking Admission Or Job Opportunities In The Turkish Republic Of Northern Cyprus (TRNC)' gave the word of caution in a statement released today October 18. The ministry explained that many young Nigerians have become stranded in the country after falling prey to agents advertising unverifiable opportunities in the territory. The statement reads - 'The attention of the Federal Government of Nigeria has been drawn to the clandestine activities of unscrupulous elements parading themselves as agents and deceiving unsuspecting young Nigerians into believing that Turkish Republic of Northern Cyprus, provides easy access to 'greener pastures' for studies and jobs opportunities. This has led to an alarming influx of Nigerians into the territory in recent times. The resultant effect, being an unprecedented increase in consular cases of stranded young Nigerians in TRNC. The general public is advised to be on the alert in order to guard against these so-called agents in Nigeria or elsewhere peddling admissions and the existence of unverifiable job opportunities in the TRNC.' It is advisable that students and their parents/guardians carry out due diligence checks on any so-called university or tertiary institution before application for admission is made. It is also instructive to be forewarned against deceptive advertising of job opportunities in the Turkish Republic of Northern Cyprus' the statement read",
    comments: [],
  },
  {
    id: 1904,
    title:
      "Countries granting visa to Nigerian youths are wicked - Ex-governor, Amosun",
    type: "Governance",
    time: "Oct 15",
    author: "Moses O",
    img: "https://static.netnaija.com/i/g3M73rXzK9y.webp",
    body: "Ex-Governor of Ogun State, Ibikunle Amosun, condemns the massive immigration of Nigerian Youths abroad as he blames western nations for receiving them. The UN's Department of Economic and Social Affairs revealed that the number of international migrants from Nigeria in 2020 is 1.7 million, up from 990,000 a decade earlier. In a recent interview on BBC Yoruba, the chieftain of the ruling All Progressives Congress, Amosun, revealed that the countries accepting Nigerian youths are doing Nigeria more harm than good. 'I have heard about it and the reports are scary. All our youths and young talents are traveling out of Nigeria, seeking greener pastures, and the prospective countries are deliberately giving them visas to leave the country, without putting the origin country into consideration,' Amosun stated. 'What scares me most in all this is the proliferation of emigration. Foreigners will not fix our nation for us if all our citizens should leave the country. I am seeing the countries granting visas to our youths as wicked because they are not considering the origin nation, from which their prospective labour force is coming from. 'If you ask our people leaving the nation for greener pastures, they will tell you that they are not planning to return to Nigeria. If you look closely at the situation, you would see that all our lawyers, accountants and most especially medical practitioners make up the largest chunk of the people leaving the country. We cannot blame them however; insecurity is one of the major problems pushing our people out of the country.'",
    comments: [],
  },
  {
    id: 1905,
    title: "FG reacts to attack on Nigerian students in India (Video)",
    type: "Governance",
    time: "Yesterday 10:34am",
    author: "Moses O",
    img: "https://static.netnaija.com/i/gVpagP9RNwO.webp",
    body: "The federal government has reacted to the trending footage of an attack on Nigerian students in India. The Chairman, Nigerians In Diaspora Commission (NiDCOM), Abike Dabiri-Erewa gave an update on Monday. The official commented on a video posted by Ashok Swain, a Professor of Peace and Conflict Research. 'Nigerian students are being attacked in a University Campus near Delhi. '30,000 Nigerian students come to study in India paying money, 50,000 Indians live in Nigeria to make money,' Swain tweeted. Dabiri-Erewa said the incident occurred last Saturday after a disagreement during a football match between African and Indian students. The chairman confirmed that the Nigerian mission took custody of 86 citizens and invited the representatives of the Indian government. Abike Dabiri-Erewa said diplomats got an assurance of safety of the students who then returned to school on Sunday. 'Calm has returned to the campus. A few injuries were recorded and further investigations are ongoing. 'The Nigerian mission had made it clear that the Indian authorities would be held responsible if anything happens to any of the students,' she said. Abike Dabiri-Erewa disclosed that there's a written commitment by the Indian authorities to guarantee protection. The NiDCOM chief urged students feeling threatened to report to the Nigerian mission in Delhi immediately.",
    comments: [],
  },
  {
    id: 1906,
    title: "Recent killings of Nigerians in South Africa callous - FG",
    type: "Governance",
    time: "Oct 17",
    author: "Moses O",
    img: "https://static.netnaija.com/i/zOJabvg0aG2.webp",
    body: "The federal government has described the recent killings of Nigerians in South Africa as callous. The Consulate General of Nigeria in South Africa in a statement issued Monday said the killings, which happened In the last three weeks, were unnecessary. It said: 'The Consulate General of Nigeria, Johannesburg, has received with grave concern reports of recent violent killings of Nigerians in Durban, KwaZulu-Natal Province. 'The killings, which happened In the last three weeks, are unnecessary, condemnable, and utterly callous. The Consulate General is saddened by these developments and hereby extends its heartfelt condolences to the families and friends of the victims.' The Mission said while it was confident that the South African Police Service (SAPS) would conduct full and investigations into the murders, it urged all Nigerians residing in KwaZulu-Natal Province to remain calm, security conscious and law-abiding. It added: 'To this end, it advised that Nigerians should endeavour to avoid potential flashpoints and immediately report any threat to life and property to the Police. 'Meanwhile, families directly impacted by the latest gruesome killings may wish to contact the Consulate General for consular assistance.'",
    comments: [],
  },
  {
    id: 1907,
    title:
      "I'm sorry for the next president who comes in and says he wants to remove fuel subsidy after day one - Sanusi",
    type: "Governance",
    time: "Oct 16",
    author: "LuvlyGist",
    img: "https://static.netnaija.com/i/5VrNpnEP79O.jpg",
    body: "Deposed Emir of Kano and vice chairman, Kaduna Investment Promotion Agency, Lamido Sanusi has said that the next President who takes over from President Muhammadu Buhari has a lot of work to do due to the bad state of the economy. Speaking at a Kaduna Investment programme titled, 'Building a resilient economy', Sanusi, who is also the current Khalifah, Tijaniyat Movement of Nigeria, averred that the nation's economy has been tied to the oil and gas sector and subsidy removal is fast mitigating the economy's growth. He said; 'Nigeria has continued to be a rentier state. It does not exist for development but as a sight of rent, and extraction to make those who control the state rich turning them into billionaires overnight. 'In 2023, if we have an election, we cannot continue to have the trend. Because any continuation will lead to insecurity and might get us to Mali, Burkina Faso's situation. 'We can't keep towards pushing the brink; we have to come back.' The 14th Emir who also cited data from the Federation Account Allocation Committee which revealed that only 50% of states in the country generated enough revenue to cover their wages, overheads and debt services, added that he is sorry for the next president who comes in and says he wants to remove fuel subsidy after day one. He also stated that every money the federal government currently earns goes to service debt and it is not also enough. Sanusi added; 'In other words, debt service is now 108 per cent of revenue. Every naira the Federal Government earns goes to service debt and it is not enough, (as the FG) has to borrow to service the debt. And then begin to borrow to build roads, pay salaries and overheads. 'We are leaving a mountain of debt for our children. They (children) might curse us because we are taking all the money borrowed to subsidise petrol and enjoy it cheaply. 'We see the problem and we are going to continue. I'm sorry for the next president who comes in June and says I'm removing fuel subsidy after day one.'",
    comments: [],
  },
  {
    id: 1908,
    title:
      "OIL THEFT: Tompolo uncovers illegal pipeline operating near military post in Delta",
    type: "Governance",
    time: "Oct 15",
    author: "Same Emmanuel",
    img: "https://static.netnaija.com/i/3g8NBnoyNDR.webp",
    body: "The Tantita Security Services Nigeria Limited, TSSNL, a surveillance company operated by ex-militant leader, Government Ekpemupolo, alias Tompolo, has discovered another huge illegal pipeline connected to the 48-inch Trans Forcados Export Trunk line, at the rear of a military security post in Burutu Local Government Area, Delta State. Sources said that oil companies, oil bunkers, Nigerian National Petroleum Corporation, NNPCL, and security officials jointly steal crude oil through the illicit pipeline connected to the trunk line through an abandoned pipeline by the Nigerians Agip Oil Company Limited, NAOCL, and linked to a location in the high sea, where they load crude oil into vessels and sell overseas. Meanwhile, the Oil Spill Victims Initiative, OSPIVV, has threatened to sue NNPCL and Shell Petroleum Development Company, SPDC, over the illegal pipeline connections used to siphon the country's crude oil. The Shell Petroleum Development Company, SPDC, operates the Forcados Terminal in Ogulagha, which has a nameplate capacity to export 400,000 barrels per day. It takes delivery of crude from the Forcados Oil Pipeline System and is the second largest pipeline network in the oil-producing region, after the Bonny Pipeline System in the eastern Niger Delta. Some IOCs and Nigerian independents operating in the western Niger Delta pump oil to the Forcados Oil Terminal for exports. The newest discovery is like the earlier illegal 4-km pipeline also attached to the same Trans-Forcados export trunk line, earlier discovered by Tantita operatives. An executive director of OSPIVV, Prince Harrison Jalla, told reporters in Warri, 'There are many reports of crude oil theft in the Niger Delta, but we are particularly interested in the theft of crude oil from the Forcados Terminal.' 'They have been stealing our national heritage for the past nine years and no one can say for sure where it began or where it ended. We want to start by holding the NNPCL and SPDC accountable for the oil theft and the atrocities committed against the Niger Delta people. 'We will take on the NNPCL and SPDC. We have already briefed our solicitors to sue. So many International Oil Companies have to account for this heist, but we want to start with the Shell Group because there is no way they could pipe crude oil from those terminals without the involvement of those running the terminal. 'We do not know if other areas where pipelines traverse the region are involved. We can now see there is a massive approach to stealing crude oil in the Niger Delta region. Therefore, we are going to court. The two organizations should let the court know what they know about the massive oil heists since 2003. 'If we have a court where everyone will recount what they know, it is fair and good for us. We want to take them to a proper court of competent jurisdiction to unravel what is happening in the trunk lines. 'Our interest is to unravel what has been happening in the oil sector, so whether they claim it at Forcados Terminal is not our business. Our concern is that some people have perpetrated the crime of massive oil theft and the resources pocketed by those we do not know. The international community and IOCs are involved,' he said. On the newly uncovered criminal pipeline, sources informed Sunday Vanguard that the bunkers actually ferry the crude to the sea for loading and onward movement abroad through the abandoned NAOC pipeline.",
    comments: [],
  },
  {
    id: 1909,
    title:
      "Former Defense Spokesperson, Major General John Eneche explains why he said shooting during #EndSARS protest at Lekki tollgate was photoshop",
    type: "Governance",
    time: "Oct 15",
    author: "Moses O",
    img: "https://static.netnaija.com/i/1xYNeMbPNLJ.webp",
    body: "Former Defence Spokesperson, Major General John Enenche (retd.) has explained why he said the shooting during the #EndSARS protest at Lekki tollgate was a photoshop. Eneche offered the explanation following the outcry that trailed his inclusion in a Presidential Campaign Council list released by the Labour Party ahead of the 2023 election. The outcry pushed the party into releasing a statement, promising to review and publish a new list before the inauguration of the council. In tweets he shared on his official handle, @EnenchejohnEne1, the retired General said at the time he made the comment, he was working with the overriding interest of Nigerians at heart based on the oath of allegiance he swore on commission into the military service. He also said that everyone that anyone that commented in any way was right based on the information at their disposal and individual analysis. Eneche tweeted-:'Dear country men and women, following my appointment on the campaign council of Labour Party, there were reactions on the social media about my pronouncement concerning a video shot at the scene of #EndSARS incident at Lekki toll-gate on October 20, 2020. Everyone that commented in anyway was right based on the information at their disposal and individual analysis. 'Personally and professionally, I worked with the overriding interest of Nigerians at heart based on the oath of allegiance I swore on commission into the military service, which is sacrosanct. 'I sincerely shared in the pains of that breaking news through the social media as it were. On that note, I want to assure all that more efforts will be put in, so that all assertions can be cleared convincingly from appropriate sources. God bless our cause for the recovery of our dear country Nigeria.'",
    comments: [],
  },
  {
    id: 1910,
    title:
      "Nnamdi Kanu: Case not over, we'll exploit appropriate legal options - Malami",
    type: "Governance",
    time: "Oct 14",
    author: "Same Emmanuel",
    img: "https://static.netnaija.com/i/5VrNpnlW79O.webp",
    body: "The Federal Government, on Thursday, gave an indication that it will approach the Supreme Court to challenge the Court of Appeal judgement that quashed the terrorism charge it preferred against the detained leader of the Indigenous People of Biafra, IPOB, Nnamdi Kanu. Reacting to the judgement, FG, through the Attorney-General of the Federation and Minister of Justice, Mr. Abubakar Malami, SAN, contended that Kanu was merely discharged by the appellate court and not acquitted. Malami, SAN, while insisting that issues that predated Kanu's rendition from Kenya, are yet to be determined by the court, said the government would exploit the appropriate legal options and also communicate same to the public. A statement the AGF made available to newsmen through his media aide, Dr. Umar Gwandu, read: 'The Office of the Attorney General of the Federation and Minister of Justice has received the news of the decision of the Court of Appeal concerning the trial of Nnamdi Kanu. 'For the avoidance of doubt and by the verdict of the Court, Kanu was only discharged and not acquitted. 'Consequently, the appropriate legal options before the authorities will be exploited and communicated accordingly to the public. 'The decision handed down by the court of appeal was on a single issue that borders on rendition. 'Let it be made clear to the general public that other issues that predates rendition on the basis of which Kanu jumped bail remain valid issues for judicial determination. 'The Federal Government will consider all available options open to us on the judgment on rendition while pursuing determination of pre-rendition issues'.",
    comments: [],
  },
  {
    id: 1911,
    title: "Wike to support Rivers flood victims with N1bn",
    type: "Governance",
    time: "Oct 12",
    author: "Same Emmanuel",
    img: "https://static.netnaija.com/i/1xYNeMpxNLJ.jpg",
    body: "Gov.Nyesom Wike of Rivers, on Wednesday, approved the sum of N1 billion for emergency relief for flood victims in the state. Wike announced this in a statement issued by his Special Assistant on Media, Mr Kelvin Ebiri, in Port Harcourt. He said that the amount was to enable the vulnerable families to cope with the devastating flood that had affected their homes and farmlands, thus forcing them to relocate to safer places. The governor, who empathised with the flood victims, also set up a task force to coordinate the distribution of relief materials to the affected communities. The News Agency of Nigeria (NAN) reports that the six-man task force was headed by the Permanent Secretary of, Special Services Bureau (SSB), Dr George Nwaeke. Other members included: Mrs Inime Aguma (Secretary), Mr Hope Ikiriko, Chairman of Ahoada West LGA, Mr Vincent Job, Chairman of Ogba/Egbema/Ndoni LGA and Mr Chukwuemeka Onowu, Director of Administration, Ministry of Special Duties. NAN also reports that all members of the task force had been directed to meet with the governor on Oct. 13. Wike, who also appointed 28,000 Special Assistants for all the political units in the state, said that the appointments took immediate effect. NAN recalls that the governor had, on Oct. 11, appointed 319 Ward Liaison Officers and 40 Local Government Area Liaison Officers.",
    comments: [],
  },
  {
    id: 1912,
    title: "Former South Africa president, Jacob Zuma released from prison",
    type: "Governance",
    time: "Oct 08",
    author: "Moses O",
    img: "https://static.netnaija.com/i/bvWaq0bX7rk.webp",
    body: "South African government has announced the released of its former president, Jacob Zuma from prison following the completion of his jail sentence. The government, in a statement on Friday, noted that he had been released from their system having served only part of his term behind bars. Reacting to his freedom, Zuma said its a day of mixed emotions, as he compared his release with that of 1973, when he walked out of Robben Island prison, after been jailed as an apartheid-era political prisoner with Nelson Mandela. While thanking his supporters for speaking out against what he termed an 'unjust and cruel incarceration', the 80 year old said, 'I am relieved to be free again, to walk around and do whatever I want to do without restrictions.' Zuma was jailed for 15 months in July last year for his refusal to appear before the Judicial Commission of Inquiry into allegations of State Capture while he was president from 2009-2018. He was granted medical parole for an undisclosed illness two months later, in September 2021. In December 2021, the High Court in Pretoria ordered Zuma's return to prison, ruling that he was unlawfully granted medical parole after opposition parties questioned his release.",
    comments: [],
  },
  {
    id: 1913,
    title: "MC Oluomo leads 'five million-man' rally for Tinubu in Lagos",
    type: "Governance",
    time: "Oct 09",
    author: "Same Emmanuel",
    img: "https://static.netnaija.com/i/1xYNeMjqNLJ.jpg",
    body: "Chairman of the Lagos state parks and garages management committee, Musiliu Akinsanya popularly known as MC Oluomo, has led a 'five million-man' rally for presidential candidate of the All Progressives Congress, Bola Tinubu, in Lagos. MC Oluomo had announced a massive rally for Tinubu after supporters of Labour Party presidential candidate, Peter Obi marched on various streets of Lagos last week. The rally which took off from Teslim Balogun Stadium, Surulere, has led to traffic gridlock in some parts of Lagos. Prior to the rally, the Lagos State Traffic Management Authority (LASTMA) announced a traffic diversion for the rally. The Lagos state agency advised motorists from Eko Bridge inwards Surulere to pass through the stadium bridge to Funsho Williams avenue and connect to their destination through Ojuelegbe to Lawanson-Itire road. During the march across streets in Lagos, shouts of 'Awa Lokan', 'Se Jagaban', 'Tinubu for President' rend the air.",
    comments: [],
  },
];
