export const hollywoodData = [
  {
    id: 2501,
    title: "The Stranger (2022)",
    type: "Movies",
    time: "Yesterday 10:58am",
    duration: "01:57:42",
    img: "https://static.netnaija.com/i/yMX7y9pX783.jpg",
    body: "The closer you get...Two men who meet on a bus and strike up a conversation that turns into friendship. For Henry Teague, worn down by a lifetime of physical labour and crime, this is a dream come true.",
    genre: "Crime, Drama, Thriller",
    stars: "Joel Edgerton, Sean Harris, Jada Alberts",
    imdb: "https://www.imdb.com/title/tt11897478/",
    premiere: "Oct 19, 2022 (Australia)",
    comments: [],
  },
  {
    id: 2502,
    title: "The School for Good and Evil (2022)",
    type: "Movies",
    time: "Oct 19",
    duration: "02:28:54",
    img: "https://static.netnaija.com/i/XV5KvQ0BN9m.jpg",
    body: "There are two sides to every story. Best friends Sophie and Agatha navigate an enchanted school for young heroes and villains - and find themselves on opposing sides of the battle between good and evil.",
    genre: "Action, Drama, Fantasy",
    stars: "Sophia Anne Caruso, Sofia Wylie, Laurence Fishburne, Michelle Yeoh",
    imdb: "https://www.imdb.com/title/tt2935622/",
    premiere: "Oct 19, 2022 (United States)",
    comments: [],
  },
  {
    id: 2503,
    title: "Bros (2022)",
    type: "Movies",
    time: "Oct 18",
    duration: "01:55:27",
    img: "https://static.netnaija.com/i/deYakpQyNP3.jpg",
    body: "A romantic comedy that gives you all the feels. Two men with commitment problems attempt a relationship.",
    genre: "Comedy, Romance",
    stars:
      "Billy Eichner, Luke Macfarlane, Guy Branum, Miss Lawrence, Ts Madison",
    imdb: "https://www.imdb.com/title/tt9731598/",
    premiere: "Sep 30, 2022 (United States)",
    comments: [],
  },
  {
    id: 2504,
    title: "Mid-Love Crisis (2022)",
    type: "Movies",
    time: "Oct 18",
    duration: "01:24:09",
    img: "https://static.netnaija.com/i/XV5KvQPXN9m.jpg",
    body: "Life is a game of exes and ohs. The week of her 50th birthday, Mindy, a divorced teacher, is going through a bonafide mid-life crisis as she prepares to host a long weekend at the lake with former boyfriend Sam, ex-husband Marc, and daughter Rita and her girlfriend Emily. In the process, Mindy begins to discover what it is she truly wants as she gets ready to start the next chapter.",
    genre: "Drama, Romance",
    stars: "Teri Hatcher, James Tupper, Brian Markinson, June Laporte",
    imdb: "https://www.imdb.com/title/tt21932636/",
    premiere: "Oct 9, 2022 (Canada)",
    comments: [],
  },
  {
    id: 2505,
    title: "The Curse of Bridge Hollow (2022)",
    type: "Movies",
    time: "Oct 14",
    duration: "01:31:46",
    img: "https://static.netnaija.com/i/zxG7Z00zNq2.jpg",
    body: "Halloween comes to life. A Halloween-hating dad reluctantly teams up with his teenage daughter when an evil spirit wreaks havoc by making their town's decorations come to life.",
    genre: "Adventure, Comedy, Family, Horror",
    stars: "Marlon Wayans, Priah Ferguson, Lauren Lapkus, Dave Sheridan",
    imdb: "https://www.imdb.com/title/tt15289240/",
    premiere: "Oct 14, 2022 (United States)",
    comments: [],
  },
  {
    id: 2506,
    title: "Summit Fever (2022)",
    type: "Movies",
    time: "Oct 14",
    duration: "01:55:26",
    img: "https://static.netnaija.com/i/Aq2NAYrONzJ.jpg",
    body: "All that matters is your next move. A daring dream to scale the world's most challenging trio of mountains soon turns into a terrifying nightmare for a group of friends when a deadly storm traps the climbers near the summit and cuts off all hope of rescue. With the odds stacked against them, the friends are forced to trust each other to save themselves by any means necessary.",
    genre: "Drama, Thriller",
    stars: "Ryan Phillippe, Freddie Thorp, Michel Biel, Mathilde Warnier",
    imdb: "https://www.imdb.com/title/tt8514848/",
    premiere: "Oct 17, 2022 (United Kingdom)",
    comments: [],
  },
  {
    id: 2507,
    title: "Stars at Noon (2022)",
    type: "Movies",
    time: "Oct 14",
    duration: "02:17:56",
    img: "https://static.netnaija.com/i/bvWaq0Wg7rk.jpg",
    body: "A sumptuous tale of romance and espionage. In present-day Nicaragua, a headstrong American journalist and a mysterious English businessman strike up a romance as they become embroiled in a dangerous labyrinth of lies and conspiracies and are forced to try and escape the country.",
    genre: "Drama, Romance, Thriller",
    stars: "Margaret Qualley, Joe Alwyn, Benny Safdie",
    imdb: "https://www.imdb.com/title/tt10354106/",
    premiere: "Oct 14, 2022 (United States)",
    comments: [],
  },
  {
    id: 2508,
    title: "The Accursed (2022)",
    type: "Movies",
    time: "Oct 14",
    duration: "01:36:56",
    img: "https://static.netnaija.com/i/zOJabvRBaG2.jpg",
    body: "Are you ready to gaze into hell?...Hell Lives Here. Elly is asked by a family friend to spend a few days looking after an elderly woman living in a remote cabin. She readily agrees thinking a short trip to the woods will be a nice escape. The cabin turns out to be anything but relaxing as Elly begins hallucinating in ways that blur reality with her dreams. As the visions take over, Elly realizes that she was lured there by a demonic presence hiding inside of the woman just waiting to break free.",
    genre: "Horror",
    stars: "Sarah Grey, Meg Foster, Sarah Dumont, Alexis Knapp",
    imdb: "https://www.imdb.com/title/tt14617254/",
    premiere: "Oct 14, 2022 (United States)",
    comments: [],
  },
  {
    id: 2509,
    title: "Old Man (2022)",
    type: "Movies",
    time: "Oct 14",
    duration: "01:37:35",
    img: "https://static.netnaija.com/i/eDxaw9wgKPZ.jpg",
    body: "Beware the enemy within. Deep in the woods, a lost hiker stumbles upon the cabin of an erratic and reclusive old man. What starts off as cordial conversation soon turns dangerous as it becomes clear that one or both of them might be hiding a terrifying secret.",
    genre: "Thriller",
    stars: "Stephen Lang, Marc Senter, Patch Darragh, Liana Wright-Mark",
    imdb: "https://www.imdb.com/title/tt13456976/",
    premiere: "Oct 14, 2022 (United States)",
    comments: [],
  },
  {
    id: 2510,
    title: "Game of Love (2022)",
    type: "Movies",
    time: "Oct 14",
    duration: "01:30:47",
    img: "https://static.netnaija.com/i/LqXNEJM6KlE.jpg",
    body: "Follows Vivien and Roy as their love story continues and leads them to Roy's childhood home in Sicily to prepare for the sale of the family estate. During the visit, a mysterious woman arrives and befriends Vivien, much to Roy's displeasure. Tensions build and lines are crossed as secrets from Roy's past force the couple to face aspects of their relationship they did not know existed.",
    genre: "Drama, Romance",
    stars:
      "Bella Thorne, Benjamin Mascolo, Alma Noce, Simone Coppo, Michael E. Rodgers",
    imdb: "https://www.imdb.com/title/tt15397918/",
    premiere: "Oct 14, 2022 (Italy)",
    comments: [],
  },
  {
    id: 2511,
    title: "Accident Man: Hitman's Holiday (2022)",
    type: "Movies",
    time: "Oct 14",
    duration: "01:37:05",
    img: "https://static.netnaija.com/i/m9z7oYzwN2r.jpg",
    body: "A vacation to die for. The Accident Man is back, and this time he must best the top assassins in the world to protect the ungrateful son of a mafia boss, save the life of his only friend and rekindle his relationship with his maniacal father figure.",
    genre: "Action, Comedy, Crime",
    stars: "Scott Adkins, Ray Stevenson, Perry Benson, Sarah Chang",
    imdb: "https://www.imdb.com/title/tt9669176/",
    premiere: "Oct 14, 2022 (United Kingdom)",
    comments: [],
  },
  {
    id: 2512,
    title: "Rosaline (2022)",
    type: "Movies",
    time: "Oct 14",
    duration: "01:36:03",
    img: "https://static.netnaija.com/i/1qdNVj4RN4g.jpg",
    body: "The love story you know, the ex you don't. Left heartbroken after Romeo begins to pursue her cousin Juliet, Rosaline schemes to foil the famous romance and win back her guy in this comedic twist of Shakespeare's Romeo and Juliet.",
    genre: "Comedy, Romance",
    stars: "Kaitlyn Dever, Isabela Merced, Kyle Allen, Sean Teale",
    imdb: "https://www.imdb.com/title/tt1777606/",
    premiere: "Oct 14, 2022 (United States)",
    comments: [],
  },
  {
    id: 2513,
    title: "Halloween Ends (2022)",
    type: "Movies",
    time: "Oct 14",
    duration: "01:50:53",
    img: "https://static.netnaija.com/i/wnRaMDjp7dq.jpg",
    body: "Four years after the events of Halloween in 2018, Laurie has decided to liberate herself from fear and rage and embrace life. But when a young man is accused of killing a boy he was babysitting, it ignites a cascade of violence and terror that will force Laurie to finally confront the evil she can't control, once and for all.",
    genre: "Horror, Thriller",
    stars: "Jamie Lee Curtis, Andi Matichak, Will Patton, Kyle Richards",
    imdb: "https://www.imdb.com/title/tt10665342/",
    premiere: "Oct 14, 2022 (United States)",
    comments: [],
  },
  {
    id: 2514,
    title: "Clerks III (2022)",
    type: "Movies",
    time: "Oct 13",
    duration: "01:40:01",
    img: "https://static.netnaija.com/i/8yZaJroZaJ0.jpg",
    body: "They're too old for this shift. After narrowly surviving a massive heart attack, Randal enlists his old friend Dante to help him make a movie immortalizing their youthful days at the little convenience store that started it all.",
    genre: "Comedy",
    stars: "Jeff Anderson, Brian O'Halloran, Jason Mewes",
    imdb: "https://www.imdb.com/title/tt11128440/",
    premiere: "Sep 16, 2022 (United Kingdom)",
    comments: [],
  },
  {
    id: 2515,
    title: "Medieval (2022)",
    type: "Movies",
    time: "Oct 11",
    duration: "02:00:12",
    img: "https://static.netnaija.com/i/qEQN24kX76W.jpg",
    body: "For honor. For justice. For freedom. The story of 14th century Czech icon and warlord Jan Zizka who defeated armies of the Teutonic Order and the Holy Roman Empire.",
    genre: "Action, Drama, History, War",
    stars: "Ben Foster, Sophie Lowe, Michael Caine",
    imdb: "https://www.imdb.com/title/tt8883486/",
    premiere: "Sep 9, 2022 (Czech Republic)",
    comments: [],
  },
  {
    id: 2516,
    title: "Project Legion (2022)",
    type: "Movies",
    time: "Oct 11",
    duration: "01:29:36",
    img: "https://static.netnaija.com/i/yMX7y9rZ783.jpg",
    body: "Locking your door won't keep them out. A former marine awakens to an apocalyptic sight outside of his window and barricades himself from evil creatures that surround his apartment door and terrorize the city.",
    genre: "Action, Horror, Sci-Fi, Thriller",
    stars: "Donald Cerrone, Brande Roderick, Kelly Lynn Reiter, Chris Maher",
    imdb: "https://www.imdb.com/title/tt12885770/",
    premiere: "Oct 11, 2022 (United States)",
    comments: [],
  },
];
