export const koreanSeriesData = [
  {
    id: 2101,
    title: "Cheer Up",
    type: "Korean Series",
    time: "Oct 04",
    img: "https://static.netnaija.com/i/no4NXvXb79M.jpg",
    body: "Revolves around a once-leading university cheering squad. It will showcase the story of the use of dance on our youth. Do Hae Yi is the newest member of the university's cheerleading squad. She was selected as the top 1% in appearance. Park Jung Woo is the leader of the Yeonhee University cheering squad.",
    genre: "Comedy, Drama, Mystery, Romance",
    stars: "Han Ji-hyun, Bae In-hyuk, Kim Hyun-jin, Jang Gyu-ri",
    mydramalist: "https://mydramalist.com/715821-cheer-up",
    premiere: "Oct 3, 2022 (South Korea)",
    comments: [],
  },
  {
    id: 2102,
    title: "Mental Coach Jegal",
    type: "Korean Series",
    time: "Sep 13",
    img: "https://static.netnaija.com/i/PrO7Od96ayp.jpg",
    body: "Je Gal-gil causes an unprecedented scandal after he loses a match that he almost won due to the referee's biased call and injures his leg. Even though permanently expelled from the national team as a player, he overcomes the trauma and comes back as a sports psychology counselor also called a mental healthcare coach. Together with the retired masters, Gal-gil works to help athletes who are going through a hard time as he did in the past.",
    genre: "Action, Comedy, Drama, Sports",
    stars: "Jung Woo, Lee You-mi, Kwon Yul, Park Se-young",
    mydramalist: "https://mydramalist.com/715509-mental-coach-je-gal-gil",
    premiere: "Sep 12, 2022 (South Korea)",
    comments: [],
  },
  {
    id: 2103,
    title: "The Law Cafe",
    type: "Korean Series",
    time: "Sep 05",
    img: "https://static.netnaija.com/i/xM6K5eX6KyE.jpg",
    body: "It's the romance between a former prosecutor turned landlord who opens a coffee shop/law firm hybrid with a former Miss Korea. Jung Ho, Yu Ri, Se Yeon, and Jin Ki have been friends for 17 years since Seoyeon High. Jung Ho is a landlord who used to be called the Monster Genius of the prosecution. Despite his clumsiness, he is a cool guy with a mysterious charm.",
    genre: "Comedy, Law, Romance",
    stars: "Lee Se-young, Lee Seung-gi, Kim Seul-ki, Jo Han-chul",
    imdb: "https://www.imdb.com/title/tt21827042/",
    premiere: "Sep 5, 2022 (South Korea)",
    comments: [],
  },
  {
    id: 2104,
    title: "Gaus Electronics",
    type: "Korean Series",
    time: "Oct 17",
    img: "https://static.netnaija.com/i/W4lNmjVYKRo.jpg",
    body: "The series is about the office workers of Marketing Team 3 at the home appliance headquarters of Gaus Electronics-a multinational company. It highlights the highs and lows of corporate life, and love and friendship between the employees.",
    genre: "Comedy, Drama",
    stars: "Kwak Dong-yeon, Ko Sung-hee, Bae Hyeon-seong, Kang Min-ah",
    mydramalist: "https://mydramalist.com/713645-gaus-electronics",
    premiere: "Sep 30, 2022 (South Korea)",
    comments: [],
  },
  {
    id: 2105,
    title: "The Empire",
    type: "Korean Series",
    time: "Sep 24",
    img: "https://static.netnaija.com/i/9bVNrqYqaWv.jpg",
    body: "Depicts the vulgar scandals of Korea's nobles of the robe (whose rank came from holding judicial or administrative posts) who dream of hereditary succession. Han Hye Ryul is the chief of the special division of the Seoul Central District Prosecutors' Office. Han Hye Ryul is from a family of judicial workers who has had wealth and power for three generations. She is an ambitious figure who is not satisfied with her current position and aims to become a prosecutor general or someone higher up the ladder.",
    genre: "Drama",
    stars: "Kim Sun-a, Ahn Jae-wook, Lee Mi-sook, Song Young-chang",
    mydramalist: "https://mydramalist.com/705661-castle-in-the-sky",
    premiere: "Sep 24, 2022 (South Korea)",
    comments: [],
  },
  {
    id: 2106,
    title: "Under the Queen's Umbrella",
    type: "Korean Series",
    time: "Oct 16",
    img: "https://static.netnaija.com/i/rOx7x9pJa0M.jpg",
    body: "Within the palace exist troublemaking princes who cause nothing but headaches for the royal family and are about to be turned into proper crown princes. Their mother, Im Hwa Ryeong, is the wife of a great king. But instead of having an aura of elegance and grace, she is a prickly, sensitive, and hot-tempered queen. Once more serene, she changed since people kept pushing her buttons. She is a queen who sometimes abandons her pride and is even known to swear! Every day of her life is full of trials, but she withstands them, all for the sake of her children.",
    genre: "Comedy, Drama, History",
    stars: "Kim Hye-soo, Kim Hae-sook, Choi Won-young, Kim Eui-sung",
    imdb: "https://www.imdb.com/title/tt22265394/",
    premiere: "Oct 15, 2022 (South Korea)",
    comments: [],
  },
  {
    id: 2107,
    title: "Blind",
    type: "Korean Series",
    time: "Sep 17",
    img: "https://static.netnaija.com/i/yMX7yxjeK83.jpg",
    body: "A homicide squad detective, suspected of serial murder, searches for the real culprit. Ryu Sung Joon, Ryu Sung Hoon and Jo Eun Ki become involved in a serial murder case involving jury members as the victims. These three individuals try to uncover the truth behind the deaths.",
    genre: "Drama, Mystery, Thriller",
    stars: "Ok Taec-yeon, Ha Seok-jin, Jung Eun-ji",
    imdb: "https://www.imdb.com/title/tt21631058/",
    premiere: "Sep 16, 2022 (South Korea)",
    comments: [],
  },
  {
    id: 2108,
    title: "One Dollar Lawyer",
    type: "Korean Series",
    time: "Sep 23",
    img: "https://static.netnaija.com/i/gVpagbR47wO.jpg",
    body: "Courts are not equally accessible to everyone and people lose trust in the judicial system. But here comes a lawyer with the best skills and a commission fee of just one dollar, committed to social justice and defending fundamental human rights. This extraordinary defense lawyer confronts blindfolded justice and highly paid opposing counsel for his clients' rights.",
    genre: "Drama",
    stars: "Namkoong Min, Kim Ji-eun, Choi Dae-hoon, Lee Chung-ah",
    mydramalist: "https://mydramalist.com/715969-one-thousand-dollar-lawyer",
    premiere: "Sep 23, 2022 (South Korea)",
    comments: [],
  },
  {
    id: 2109,
    title: "The Golden Spoon",
    type: "Korean Series",
    time: "Sep 23",
    img: "https://static.netnaija.com/i/no4NXvlA79M.jpg",
    body: "Would you trade your poor but loving family for a life of riches? When Seung Cheon gets his hands on a magical spoon that allows him to switch lives with his rich best friend, he thinks it's a no-brainer. But life-altering decisions are always accompanied by a sense of doubt, and with only three chances to change his mind, Seung Cheon has to decide which of his two possible futures is worth keeping.",
    genre: "Drama, Fantasy, Sci-Fi",
    stars: "Yook Sung-jae, Yeon-woo, Jung Chae-yeon, Lee Jong-won",
    mydramalist: "https://mydramalist.com/692045-golden-spoon",
    premiere: "Sep 23, 2022 (South Korea)",
    comments: [],
  },
  {
    id: 2110,
    title: "Bad Prosecutor",
    type: "Korean Series",
    time: "Oct 05",
    img: "https://static.netnaija.com/i/no4NXYz4K9M.jpg",
    body: "A story about a prosecutor named Jin Jung who is armed with bad manners and delinquency. He breaks down the sanctuaries created by wealth and power, and he even takes down the greedy people living in those sanctuaries. He uses expedient methods over conventional ones, tricks over standard procedures, and delinquency over sincerity in order to stop the corrupt authorities from undermining society.",
    genre: "Action, Adventure, Crime, Drama",
    stars: "Doh Kyung-soo, Lee Se-hee, Ha Jun, Joo Bo-young",
    imdb: "https://www.imdb.com/title/tt22353836/",
    premiere: "Oct 5, 2022 (South Korea)",
    comments: [],
  },
  {
    id: 2111,
    title: "Love in Contract",
    type: "Korean Series",
    time: "Sep 21",
    img: "https://static.netnaija.com/i/ZOoanzbVajA.jpg",
    body: "Can marriage be a business? Sang-eun is a single-life helper with 13 years of career. Her customers are those who need a wife for their public life under social pressure. Ji-ho is Sang-eun's MWF husband client who has been with her for 5 years. While short-term, abusing clients on TTS are driving Sang-eun mad, new long-term contractor Hye-jin appears and takes up the TTS husband schedule. With two different men, MWF husband and TTS husband, Sang-eun's week flows romantically crossing the borderline between public affairs and private emotions.",
    genre: "Comedy, Drama, Romance",
    stars: "Park Min-young, Go Kyung-pyo, Kim Jae-young, Jin Kyung",
    mydramalist: "https://mydramalist.com/721517-wol-soo-geum-hwa-mok-to",
    premiere: "Sep 21, 2022 (South Korea)",
    comments: [],
  },
  {
    id: 2112,
    title: "Love Is for Suckers",
    type: "Korean Series",
    time: "Oct 05",
    img: "https://static.netnaija.com/i/W4lNmj10KRo.jpg",
    body: "A romantic comedy-drama depicting the sweet and salty reality romance between 20-year-old best friends in their 30s who have no romance or flirting. Goo Yeo Reum is a television producer in the tenth year of her professional career. Although she works harder than most producers, the shows she makes all seem to flop. Then she's selected to produce a new dating-themed reality TV show called 'Kingdom of Love.' Her neighbour and best friend of twenty years is Park Jae Hoon, a plastic surgeon who has lost all his passion for work. Their relationship is close, but purely platonic. Park Jae Hoon is jaded by his experiences and has also essentially given up on love. As such, he only ever pursues casual relationships.",
    genre: "Comedy, Drama, Romance",
    stars: "Lee Da-hee, Siwon, Song Jong-ho, Cho Soo-hyang",
    mydramalist:
      "https://mydramalist.com/719759-love-that-will-freeze-to-death",
    premiere: "Oct 5, 2022 (South Korea)",
    comments: [],
  },
  {
    id: 2113,
    title: "Seasons of Blossom",
    type: "Korean Series",
    time: "Sep 21",
    img: "https://static.netnaija.com/i/mr9KYg3Qaq6.jpg",
    body: "A story of love and friendship between five high school students from Seoyeon High School. Lee Ha-Min (Seo Ji-Hoon) appears like a bright person, but there is also darkness within his mind. Han So-Mang ( So Ju-Yeon) is a warm-hearted person, but she is also quite timid. Lee Jae-Min (Kim Min-Kyu) is a popular student with a painful past. He is kind to everyone around him. Yoon Bo-Mi (Kang Hye-Won) is a sweet, model student. Choi Jin-Young (Yoon Hyun-Soo) loves playing games. He can seem unfriendly and has a delicate personality.",
    genre: "Comedy, Drama, Mystery",
    stars: "Seo Ji-hoon, So Joo-yeon, Kim Min-kyu, Kang Hye-won",
    mydramalist: "https://mydramalist.com/714577-seasons-of-blossom",
    premiere: "Sep 21, 2022 (Korea South)",
    comments: [],
  },
  {
    id: 2114,
    title: "May It Please the Court",
    type: "Korean Series",
    time: "Sep 21",
    img: "https://static.netnaija.com/i/deYakzoZ7P3.jpg",
    body: "No Chak-Hee works for a big law firm. She is willing to take any risk to win a case and has become an ace attorney at the law firm. She is set to receive a promotion to a partner position, but a problem occurs on a case she accepted. Due to this, she almost gets suspended for a year. Instead, No Chak-Hee begins to work as a public defender. She hopes to return to her position at the law firm where she worked previously. As a public defender, she shares an office with fellow public defender Jwa Shi-Baek.",
    genre: "Drama, Mystery",
    stars: "Jung Ryeo-won, Lee Kyoo-hyung, Jung Jin-young, Kim Hye-eun",
    mydramalist: "https://mydramalist.com/715941-let-s-start-the-argument",
    premiere: "Sep 21, 2022 (South Korea)",
    comments: [],
  },
  {
    id: 2115,
    title: "Little Women",
    type: "Korean Series",
    time: "Sep 06",
    img: "https://static.netnaija.com/i/x5PKDd2RKnM.jpg",
    body: "Missing ₩70 billion appears to three sisters who grew up in absolute poverty but with a close bond. Entangled in a conspiracy that involves the rich and powerful, three sisters who wanted to live like everyone else confront a life task whether to keep or to return the money.",
    genre: "Action, Drama, Mystery, Thriller",
    stars: "Kim Go-eun, Nam Ji-hyun, Park Ji-hu, Wi Ha-jun",
    imdb: "https://www.imdb.com/title/tt21828868/",
    premiere: "Sep 3, 2022 (South Korea)",
    comments: [],
  },
  {
    id: 2116,
    title: "Glitch (KR)",
    type: "Korean Series",
    time: "Oct 07",
    img: "https://static.netnaija.com/i/G4E7z9OeKb6.jpg",
    body: "My Boyfriend Vanished from Earth. A young woman joins forces with a UFO enthusiast to investigate her boyfriend's sudden disappearance and stumbles into a wild conspiracy.",
    genre: "Comedy, Mystery, Sci-Fi, Thriller",
    stars: "Jeon Yeo-been, NANA, Lee Dong-hwi, Ryu Kyung-soo",
    imdb: "https://www.imdb.com/title/tt14735382/",
    premiere: "Oct 7, 2022 (South Korea)",
    comments: [],
  },
];
