export const latestData = [
  {
    id: 1301,
    title:
      "'It was IVD that pushed my sister into fire' - Late Bimbo's brother, Oyindamola (Video)",
    type: "Celebrity Gist",
    time: "36 minutes ago",
    author: "LuvlyGist",
    img: "https://static.netnaija.com/i/WAPK4vR0a0B.jpg",
    body: "Oyindamola Martins, the younger brother of the late Bimbo has opened up on the incident that led to his elder sister's death. Bimbo died on the 15th of October after suffering a 10-degree burn. While speaking with media personality Daddy Freeze, Oyindamola opened up about many things, including the very incident that led to Bimbo's tragic death. According to him, his sister lit the fire, thinking that her husband, IVD would tell her to stop. She did it so that both of them would leave the house empty-handed. Furthermore, he maintained that Bimbo lit the curtain and got pushed into the fire by her husband, who was trying to get her off his body.",
    comments: [],
  },
  {
    id: 1302,
    title: "Why do men get so, so angry when they're cheated on?",
    type: "Romance",
    time: "2 hours ago",
    author: "LuvlyGist",
    img: "https://static.netnaija.com/i/qvg70XqB7ze.jpg",
    body: "For a gender largely believed to be unable to help themselves when it comes to cheating, men seem to hate being cheated on too much. Why?The narrative that has been spun around the issue cheating for the longest time is that men cheat more than women, but are more hurt and distraught and angry when they find out they've been cheated on. It's kinda straightforward like that in our collective consciousness. The narrative sees us believe that women somehow 'expect' to be cheated on because 'all men cheat' and 'men will always be men.' So what we have is an unfair situation, a particularly bothersome relationship dynamic which makes it feel OK for women to pardon and forge on when their men cheat; but on the other hand, validates men's indignation and righteous rage when they get cheated on. An excellent option to protect yourself from cheating is to use mSpy software. You will see who calls your partner and what messages she gets on Messenger, Whatsapp, and Snapchat. mSpy can provide peace of mind to you. So let's talk about reasons why this is so. Why does it bother men so much when a woman cheats on them, and why do more men find cheating absolutely unforgivable compared to women? When women cheat, it is for emotional reasons. Women do not cheat for physical reasons, and for the most part it's not for sexual gratification. It has been said that the need to bridge an emotional gap, to plug some emotional vacuum is what leads women into affairs. So, for men, knowing that the woman has detached herself emotionally and that their time is likely over makes cheating an extra-uneasy pill to swallow for them. Whereas women become [inexplicably] ashamed and embarrassed when their partner cheats on them, men see cheating as an affront on their ego. They probably feel that being cheated on is the highest form of disrespect ever, and this makes it even more difficult to stomach it. Because, you know, men think they deserve respect as a birthright.",
    comments: [],
  },
  {
    id: 1303,
    title:
      "Ex-Aviation Minister mourns his brother-in-law who recently suffered cardiac arrest and died due to what he termed ''cultural failure'' at Federal Medical Centre Jabi",
    type: "Social Media",
    time: "3 hours ago",
    author: "LuvlyGist",
    img: "https://static.netnaija.com/i/zxG7Z0JQNq2.jpg",
    body: "Former Minister of Aviation, Osita Chidoka, is bereaved as he lost his brother-in-law on Saturday, October 15. In a post shared on social media, Chidoka revealed that his brother-in-law had visited the Federal Medical Center in Jabi on Friday, October 14, to complain of chest pain, but was allegedly asked to return on Saturday, October 1 as the lab technicians who were to carry out a test on him had closed for the day. Sadly, he suffered a cardiac arrest the next day and was rushed to the same hospital where he was pronounced dead on arrival. 'Yesterday, I wrote about the inevitability of death as we approach the fifth decade conscious of the fact that the life expectancy of a Nigerian is 54 years. Today death visited. My brother-in-law Apost Paul Egbon husband of my only sister Ada Chidoka Egbon died at age 56. Yesterday, he was at the Federal Medical Centre Jabi with a complaint of chest pain. The Doctor who saw him prescribed painkillers and recommended ECG and other tests. At the Lab, they said it was late in the day and asked them to come back today Saturday. He walked to the car and they drove home. Allowing him to go home was a questionable decision. I couldn't help but recall, when as a grad student, I walked into Arlington, VA General Hospital with a chest pain complaint. They brought a stretcher immediately and took me to emergency. They ran all the tests and held me fastened to the bed until all the results came and they concluded it was a chest muscle pain. Early hours of this morning about 5 am he suffered, what we suspect, to be a cardiac arrest. My sister rushed him to the same federal Medical Centre Jabi. A doctor came out saw him in the car and pronounced him dead. They gave her a form and told her to take him to the mortuary. Yes, you read right. They told a grieving woman, who was told without any preparation, to take her dead husband to the morgue. They did not remove the corpse from the car. Apparently, there is no protocol to receive a patient brought in dead. She was in the car with her dead husband when my Uncle, a medical doctor, arrived. I arrived shortly after. She was in the car crying holding her husband in the car park of the hospital. A hospital they have used for years. We struggled to get her out of the car before we moved the corpse to the morgue. The hospital did not receive the body formally. No attempt at separating a wife from a corpse. No official record of the review that pronounced him dead. They did not counsel her or even empathise with her. It was not a medical failure; wrong diagnosis or lack of treatment. It was a process and cultural failure. Something has gone wrong with our humanity and sense of empathy as a people. I advise, go for regular medical checkups. Have a primary health physician who knows you personally and has your history. Your primary physician is likely to be the difference between life and death. Our institutions are weak and our public servants are neither public-minded nor interested in service. Together with the departed, we pray for God's mercy and love upon us all. Amen. Osita Chidoka'",
    comments: [],
  },
  {
    id: 1304,
    title:
      "'The only achievement in marriage are children. Nothing special' - Actress Nkechi Blessing Sunday reacts to death of IVD's wife, Bimbo",
    type: "Celebrity Gist",
    time: "3 hours ago",
    author: "LuvlyGist",
    img: "https://static.netnaija.com/i/8yZaJr69aJ0.jpg",
    body: "Nollywood actress, Nkechi Blessing Sunday has said that the only achievement in marriage is children.The actress stated this on Saturday, October 15, while reacting to the death of Bimbo, wife of popular car dealer, Ikechukwu Ogbonna.'They say marriage is the greatest achievement but many don't get out alive. Hmmm. Loss for words,' she wrote.Responding to a follower, she added; 'The only achievement there is children, nothing special if you ask me. If marriage no work again carry your marital award (children) and leave to LIVE'",
    comments: [],
  },
  {
    id: 1305,
    title:
      "Deontay Wilder knocks out Robert Helenius in first round of comeback fight (videos)",
    type: "Sports",
    time: "3 hours ago",
    author: "LuvlyGist",
    img: "https://static.netnaija.com/i/W4lNmjYYKRo.jpg",
    body: "Forner heavyweight boxing champion, Deontay Wilder celebrated his return to the ring with a stunning signature stoppage of Robert Helenius on Sunday morning, October 16. Wilder was fighting for the first time since his second successive - and concussive defeat by Tyson Fury more than 12 months ago as he began a comeback journey with hopes of becoming heavyweight world champion again. Wilder easily dispatched former sparring partner Helenius, landing a short right hand - just Wilder's third of the fight - while backed up in the corner, leaving the Finn prone on the canvas and in need of medical attention. Wilder took his time in the opening stages as he looked to shed any ring rust, before exploding with a right hand which was high, wide and not particularly handsome. It took just a right hand to dump Helenius on the canvas with just seconds of the round remaining as the fight was immediately waved off. 'It's amazing to be back in Brooklyn. This arena is like a second home to me,' said Wilder. 'It feels so good to be back; when I came off the plane and set my foot on the ground I felt a great energy. I felt the love and I felt the support and that's all I needed. I knew it was going to be a great night for me and it was 'I was trying to keep my distance because Robert has a heart of a champion and I knew what he was capable of. I didn't take him for granted and I looked him in the eyes and he really wanted it. When they fight Deontay Wilder they come with their A++ game. 'I set him up, I allowed him to reach and when he reached, I tagged him. It was a great fight and who's next? I've been hearing rumours about [Oleksandr] Usyk but I see he's not here. Most of the times guys say they want me and they come to shows of mine, they knockouts out like that they turn. the corner. 'I'm ready for whoever, whether it's Andy Ruiz or Usyk, bring it on. Deontay Wilder is back, the excitement in the division is back. There is no heavyweight division without Deontay Wilder, that's fact!'",
    comments: [],
  },
  {
    id: 1306,
    title:
      "Mere words of mouth do not constitute any offense - CSP Adejobi replies Twitter user who asked if it is okay for police officers to threaten an unharmed individual",
    type: "Social Media",
    time: "4 hours ago",
    author: "LuvlyGist",
    img: "https://static.netnaija.com/i/wk37lR3zNPd.jpg",
    body: "The spokesperson of the Nigeria Police Force, CSP Olumuyiwa Adejobi, has said that threatening with mere words do not constitute any offense.  Adejobi stated this while responding to a Twitter user said  who said a police officer he and his wife had an encounter with, threatened to shoot them dead. See their Twitter exchange below",
    comments: [],
  },
  {
    id: 1307,
    title: "For men: Here are 4 types of s*x women enjoy",
    type: "Sexuality",
    time: "4 hours ago",
    author: "LuvlyGist",
    img: "https://static.netnaija.com/i/5wPKLg6LNVB.jpg",
    body: "The right approach is essential to learning any skill, and the same applies to sex. Women are very perceptive of what makes them feel desired and pleasured in bed. And that includes exciting sex positions. Women have forever wished to be pleasured during sex and there are some particular sex moves that completely arouse her, paving the way for an extremely erotic orgasm. If you want to spice up things with your partner under the sheets, try these tips. -Sensual sex - This is one type of sex most women desire to have. Start by clearing both your schedules, set a sexy environment, and let her know you've got all night to focus on her pleasure. Shut off your cell phones, turn off the TV, and anything else that will distract you from reaching new levels of intimacy with your lady. Remember that foreplay is the bread and butter when engaging in a night of sensual sex. So take your time, go slowly, and explore all of the erogenous zones on her body that so often go neglected in the bedroom. Be passionate and engaged, and don't be afraid to tease her a little. -Spontaneous sex- Women love to feel sexually wanted and desired by their partners - and nothing says desire like spur-of-the-moment sex on the living room stairs. Unplanned, spontaneous love-making increases the lust factor by showing your partner that your attraction for her trumps everything else. -Rough sex- Most women, every now and then, want to be sexually dominated by their partners. Engaging in a little power play can be a fun and exhilarating way to explore kink in the bedroom. First and foremost, make sure she wants to play rough, and outline boundaries to ensure that you both feel safe. Then, pull a little hair, do a little spanking, and even bust out the blindfold and handcuffs if you're feeling adventurous. Revel in the pure lust this type of sex is driven by, indulge in animalistic passion, and go ahead. Don't forget to get a little too. -Oral sex- Oral sex is super satisfying when it's right. Research has shown that men are not going down on their partners as much as women would like. Even if you are one of those wonderful guys that go down on a regular basis, how do you know you're doing it right? Pick a position that's comfortable for both of you and set up camp, rushing this process is one of the biggest mistakes that men make in bed. Take your time to give attention to all of her sensitive areas. Experiment with different pressure and patterns, and don't be afraid to use your hands to amplify her experience. Oral sex is all about investing time and effort into just one thing: your partner's pleasure. Show her you appreciate her and care about her orgasm just as much as your own.",
    comments: [],
  },
  {
    id: 1308,
    title:
      "Bimbo and IVD's old neighbor in South Africa recount how they always fought and made up before relocating back to Nigeria",
    type: "Celebrity Gist",
    time: "4 hours ago",
    author: "Moses O",
    img: "https://static.netnaija.com/i/Aq2NAY6vNzJ.webp",
    body: "Following the demise of Bimbo Ogbonna after years of alleged domestic violence at the hands of her husband and popular car dealer, Ikechukwu Ogbonna popularly known as IVD, the couple's old neighbor has taken to Facebook to share her experience from living with them in South Africa. Facebook user, Francess Olisa Ogbonnaya described Bimbo's story as a 'very complicated and near foolish one'. According to Francess, Bimbo and IVD got married around 2009 when she (Bimbo) was 18/19, while IVD was in his early twenties.She claimed that their marriage was more of a 'Bonny and Clyde thing', as they loved themselves so intensely and also fought fiercely. Francess recalled that most of them who lived in the South African neighborhood relocated to different countries in 2014, including IVD and Bimbo. The couple's relocation however came after IVD became rich. The Facebook user revealed that she was told that the money didn't reduce their fighting and crisis, but rather it worsened it. She also recounted how Bimbo would always accuse IVD of engaging in fraud and fetish practices during their fights, and also remind him that she gave up everything for him.",
    comments: [],
  },
  {
    id: 1309,
    title: "Deontay Wilder knocks out opponent in first round (Videos)",
    type: "Sports",
    time: "5 hours ago",
    author: "Moses O",
    img: "https://static.netnaija.com/i/Wz27W36n75R.webp",
    body: "Former world heavyweight champion Deontay Wilder has returned to boxing after a year-long lay-off, by knocking out his Finnish opponent, Robert Helenius in the first round. Saturday's match marked Wilder's return since being KO'd by Tyson Fury 12 months ago. The American stopped Helenius after 2min 57sec with a powerful right-hand punch to the face, improving his record to 43-2 with one drawn and 42 KOs. Wilder reportedly knew the fight was over even before it was stopped by posing against the ropes after throwing the punch. Doctors rushed to the 38-year-old prone Finnish fighter, who slowly rose to his knees. Helenius, a former Wilder sparring partner whose record fell to 31-4, eventually departed the ring under his power. Wilder who also got emotional during the post-match conference, discussed the dangers of boxing and also cited Prichard Colon, as an example. Colon is an American boxer, honourary WBC World Champion, and gold medal winner who suffers a life-altering brain injury due to the profession. 36-year-old Wilder was left considering his career following consecutive stoppage losses to Fury, 34, in their trilogy series. He is now lined up for a final eliminator against Andy Ruiz Jr, 33, with the winner becoming mandatory for Fury's title. But Wilder didn't rule out trying to fight Ukraine's unbeaten Oleksandr Usyk, who owns all the heavyweight division's other major titles.",
    comments: [],
  },
  {
    id: 1310,
    title:
      "Any Pastor that says there's witchcraft in Nollywood is a liar - Keppy Ekpenyong",
    type: "Celebrity Gist",
    time: "5 hours ago",
    author: "Moses O",
    img: "https://static.netnaija.com/i/yMX7y94e783.webp",
    body: "Veteran actor, Keppy Ekpenyong Bassey has pushed back at claims of witchcraft practice in Nollywood. Responding to a question by a student of the Africa Film Academy training, who asked if there is truly witchcraft in Nollywood as alleged by a popular pastor, Keppy Ekpenyong stated that any Pastor who claims there's witchcraft in Nollywood is a liar. The veteran actor who further added that people behind such claim are 'stupid', also stated that Nollywood is the second largest employer of labour in Nigeria outside the civil service. Keppy said: 'The industry in Nollywood is the second largest employer of labour in Nigeria outside the civil service. No other industry employs labour more than Nollywood. What kind of stupid person will now say that there is witchcraft in Nollywood? Any pastor that says that is a liar. Take it from me.'",
    comments: [],
  },
  {
    id: 1311,
    title: "LaLiga: I don't want to leave Barcelona - Midfielder begs Xavi",
    type: "Sports",
    time: "5 hours ago",
    author: "Moses O",
    img: "https://static.netnaija.com/i/x5PKDwgoNnM.webp",
    body: "Barcelona midfielder, Frankie de Jong has told manager Xavi Hernandez that he does not want to leave the club. The midfielder is not comfortable with how many games he has started for the Catalan side this season, begging Xavi for more time. Manchester United had hoped to sign the Dutch midfielder from Barcelona last summer but he insisted on staying at Camp Nou. Reports late last week suggest that the former Ajax midfielder is no longer at peace at Barcelona and wants to make the Old Trafford move. The 25-year-old thought he was going to be an integral part of Barcelona's star-studded team under Xavi. He made over 30 starts in La Liga last season, but things have not gone according to plan for him so far this campaign as he has only made three starts. Spanish publication, Sport reports that De Jong is annoyed with the situation and his frustration will only increase if he doesn't get back into the starting XI. Speaking ahead of the El Clasico, the Dutchman told reporters how he feels, 'We don't talk much with Xavi, but we only talk about football. I knew I would play fewer minutes at the beginning of the season. 'I want to be a starter again. Against Bayern, I wasn't a starter and I hope to be against Real Madrid. Maybe he already decided, but usually we don't know until the day of the game. 'I was calm. I decided in May, that I wanted to stay. 'My opinion has never changed during all this period. I remained calm. But then you know that the pressure would start coming from the newspapers, from the president, from everywhere in fact. But I wanted to stay at Barca, so it never bothered me.'",
    comments: [],
  },
  {
    id: 1312,
    title: "2023: 'Tinubu knows my party' - Sanusi",
    type: "Politics",
    time: "5 hours ago",
    author: "Moses O",
    img: "https://static.netnaija.com/i/G4E7z9rMKb6.webp",
    body: "With the 2023 general elections fast approaching, former Emir of Kano, Sanusi Lamido Sanusi, has disclosed the only party he belongs to. Sanusi said the All Progressives Congress, APC, presidential candidate, Bola Tinubu is aware that he belongs to the party called Nigeria. He disclosed this while noting that he's not a member of any political party. Sanusi spoke while addressing Tinubu and other guests in Kaduna during the seventh edition of KadInvest, an annual event organised by the Kaduna State Investment Promotion Agency yesterday. The former Governor of the Central Bank of Nigeria, CBN, also lamented oil theft, Nigeria's rising debt profile, unbalanced subsidy payment and soaring foreign exchange, amongst other monetary and economic challenges facing Nigeria at the moment. He called for transparency and credibility in the management of the nation's resources and demanded the unbundling of the Nigerian National Petroleum Company (NNPC) Limited, saying the company is not a cash cow but should be run as an independent enterprise with high-level accountability. Sanusi further urged States to free themselves from excessive reliance on the Federal Government. 'I keep repeating, hope you remember that I lost my job at the Central Bank for this same problem. 'It is not about a particular party. I have no party. My party is Nigeria. This is the problem we had in 2014. Asiwaju (Tinubu) knows my party is Nigeria,' he said.",
    comments: [],
  },
  {
    id: 1313,
    title: "How to have s*x: 5 bedroom rules couples should follow",
    type: "Sexuality",
    time: "6 hours ago",
    author: "LuvlyGist",
    img: "https://static.netnaija.com/i/LqXNEY6JNlE.jpg",
    body: "Following some bedroom rules will get closer to your partner and discover how great it is to spend time with your spouse in ways more than one.The sex habits you form with your partner over time have a huge impact on the well-being of your relationship. When you stay with a person in a relationship for so long, things are bound to get monotonous, especially during sex. With everyday hectic schedules and timelines, married couples can no longer feel physically or sexually drawn to one another. To make sure the sex life doesn't drown completely, here are some rules every married couple ought to follow in the bedroom: -Have sex at least once a week- Have sex at least once a week so that you and your partner don't enter a dry spell. Not engaging in sex can make a couple feel sexually frustrated and angry. To avoid any such complications, focus on having sex with your partner. -Set new expectations during sex- Your partner may not tell you but they may get bored repeating the same positions every time. Every now and then, it is important to try out some new positions that will excite you and your partner. Just don't keep it boring. -Make foreplay a rule- Foreplay is pretty important during sex because it includes the play of emotions as well. Some women take a long time to climax because there is no foreplay involved. Foreplay increases the chances of reaching an orgasm. -Engage in oral sex- Don't just kiss your partner on the lips. Let your imagination go wild and then kiss your partner in their most sensitive and sensual areas such as the neck, behind the knees, waist etc. This will impress your partner and keep the intimacy between you two sexy as ever. -Communicate about your sex fantasies- Everyone has different sexual fantasies and one shouldn't feel guilty about them at all. Make it a rule to communicate with your partner about your fantasies. Let your partner tend to your wild, sexual fantasies,",
    comments: [],
  },
  {
    id: 1314,
    title:
      "Phyna replies troll that said she doesn't know how to hold cutlery (Video)",
    type: "Celebrity Gist",
    time: "6 hours ago",
    author: "LuvlyGist",
    img: "https://static.netnaija.com/i/qvg70O8vKze.jpg",
    body: "BBNaija Level-up winner, Ijeoma Josephina Otabor, widely called Phyna claps back at a fan, who shaded her for not being able to hold cutlery. Following the show, housemates have been attending events organized by the show sponsors incessantly. On the 15th of October, an event was held in honor of the housemates courtesy of Oraimo. Housemates were gathered in their usual manner, partying, chit-chatting, and generally having fun. Phyna went live while eating and got bashed by a troll for not holding her cutlery properly. In a comeback, Phyna said although she may not know how to hold cutlery, she is now more famous than the so-called troll who knows how to perfectly hold cutlery.",
    comments: [],
  },
  {
    id: 1315,
    title:
      "'Sotey I dey carry sacrifice for you; stupid me' - Chats of late IVD's wife, Bimbo surfaces",
    type: "Celebrity Gist",
    time: "6 hours ago",
    author: "LuvlyGist",
    img: "https://static.netnaija.com/i/DpraRVm2aAo.jpg",
    body: "Following the passing of Bimbo Ogbonna, chats with her husband surface where she confirmed involvement in metaphysical activities on behalf of IVD. A friend to the mother of five had earlier claimed that she was aware of the late Bimbo's involvement in rituals and other diabolical activities she got herself into at the call of her husband. In the latest development, chats between the couple amidst the heat of their domestic violence surfaced. In the chat, Bimbo fumed at her husband about the effort invested in their marriage while stating that she went as far as carrying 'ebo' for IVD; a Yoruba word for 'sacrifice'.",
    comments: [],
  },
  {
    id: 1316,
    title:
      "I'm sorry for the next president who comes in and says he wants to remove fuel subsidy after day one - Sanusi",
    type: "Governance",
    time: "7 hours ago",
    author: "LuvlyGist",
    img: "https://static.netnaija.com/i/5VrNpnEP79O.jpg",
    body: "Deposed Emir of Kano and vice chairman, Kaduna Investment Promotion Agency, Lamido Sanusi has said that the next President who takes over from President Muhammadu Buhari has a lot of work to do due to the bad state of the economy. Speaking at a Kaduna Investment programme titled, 'Building a resilient economy', Sanusi, who is also the current Khalifah, Tijaniyat Movement of Nigeria, averred that the nation's economy has been tied to the oil and gas sector and subsidy removal is fast mitigating the economy's growth. He said:- 'Nigeria has continued to be a rentier state. It does not exist for development but as a sight of rent, and extraction to make those who control the state rich turning them into billionaires overnight. 'In 2023, if we have an election, we cannot continue to have the trend. Because any continuation will lead to insecurity and might get us to Mali, Burkina Faso's situation. 'We can't keep towards pushing the brink; we have to come back.' The 14th Emir who also cited data from the Federation Account Allocation Committee which revealed that only 50% of states in the country generated enough revenue to cover their wages, overheads and debt services, added that he is sorry for the next president who comes in and says he wants to remove fuel subsidy after day one. He also stated that every money the federal government currently earns goes to service debt and it is not also enough. Sanusi added:- 'In other words, debt service is now 108 per cent of revenue. Every naira the Federal Government earns goes to service debt and it is not enough, (as the FG) has to borrow to service the debt. And then begin to borrow to build roads, pay salaries and overheads. 'We are leaving a mountain of debt for our children. They (children) might curse us because we are taking all the money borrowed to subsidise petrol and enjoy it cheaply. 'We see the problem and we are going to continue. I'm sorry for the next president who comes in June and says I'm removing fuel subsidy after day one.'",
    comments: [],
  },
  {
    id: 1317,
    title:
      "'Sotey I dey carry sacrifice for you; stupid me' - Chats of late IVD's wife, Bimbo surfaces",
    type: "Celebrity Gist",
    time: "6 hours ago",
    author: "LuvlyGist",
    img: "https://static.netnaija.com/i/DpraRVm2aAo.jpg",
    body: "Following the passing of Bimbo Ogbonna, chats with her husband surface where she confirmed involvement in metaphysical activities on behalf of IVD. A friend to the mother of five had earlier claimed that she was aware of the late Bimbo's involvement in rituals and other diabolical activities she got herself into at the call of her husband. In the latest development, chats between the couple amidst the heat of their domestic violence surfaced. In the chat, Bimbo fumed at her husband about the effort invested in their marriage while stating that she went as far as carrying 'ebo' for IVD; a Yoruba word for 'sacrifice'.",
    comments: [],
  },
  {
    id: 1318,
    title:
      "ABU releases dress code for students, bans certain outfits including coloured sunglasses",
    type: "Happenings",
    time: "7 hours ago",
    author: "LuvlyGist",
    img: "https://static.netnaija.com/i/1qdNVjgAN4g.jpg",
    body: "The management of Ahmadu Bello University, Zaria, has released its 2022 dress code for students of the institution.The institution banned certain haircuts, crazy jeans, coloured sunglasses among other outfits.ABU students, staff and visitors were asked to abide by the rule.",
    comments: [],
  },
  {
    id: 1319,
    title:
      "Sorrow will be your portion - BBNaija star, Mercy Eke, weeps as she lays curses on people accusing her of being IVD's girlfriend (video)",
    type: "Celebrity Gist",
    time: "7 hours ago",
    author: "LuvlyGist",
    img: "https://static.netnaija.com/i/1xYNeME2NLJ.jpg",
    body: "Reality TV star, Mercy Eke, has said that she has nothing other than a business transaction with businessman, Ikechukwu Ogbonna popularly known as IVD, who has been accused of battering his wife, Bimbo, to death. In a post shared on her Instagram page, Mercy stated that she only visited the auto shop run by IVD to purchase her 2018 Range Rover Velar that she gifted herself on her 27th birthday in 2020. She also shared videos she made where she returned the car after she found out the car was an accident one that was refurbished and sold to her for N37 million after which she added an extra N2 million to get a better one. 'My name has been tarnished for the longest time, this is the first and last time I'm going to address this. The reason I'm addressing this blatant lie is because of the late wife Mrs Bimbo. These are evidences and receipts showing that I have nothing other than business transactions with IVD!!!' She then shared a video where she was complaining about the faulty key of the Range Rover. A distraught Mercy went on her IG live to also lay curses on anyone alleging that she had an amorous relationship with IVD.",
    comments: [],
  },
  {
    id: 1320,
    title:
      "EFCC arrested 12 bankers in Enugu for allegedly stealing funds from some dormant accounts",
    type: "Happenings",
    time: "7 hours ago",
    author: "LuvlyGist",
    img: "https://static.netnaija.com/i/3g8NBnVrNDR.webp",
    body: "The Enugu Zonal Command of the Economic and Financial Crimes Commission, EFCC, on Friday, October 14, 2022 arrested twelve (12) bankers for suspected insider fraud. A statement released by the EFCC gave the names of the suspects as Odeniyi Anthony, Deki Kingsley Onyekachi, Oguchukwu Ene, Elendu Chizaram, Anyakora Uchenna, Onah Kingsley, Akwe Elizabeth and Chinenye Grace Acibe. Others are Victoria Ezedie, Chidi-Ukah Obinna, Etoh Lawrence Uzochukwu and Udeze Harrison. According to the EFCC, preliminary investigations showed that the suspects allegedly stole funds from some dormant accounts in a branch of an old-generation bank in Enugu. 'The stolen funds were transferred from the dormant accounts to various beneficiaries, with the principal beneficiary already identified by the EFCC.'- the statement read. The antigraft agency says the suspects will be charged to court as soon as investigations are concluded.",
    comments: [],
  },
];
