export const movieSeriesData = [
  {
    id: 2001,
    title: "The Patient",
    type: "Series",
    time: "Aug 30",
    img: "https://static.netnaija.com/i/zOJab8JxKG2.jpg",
    body: "No one said therapy was easy. A psychotherapist finds himself held prisoner by a serial killer with an unusual request: curb his homicidal urges.",
    genre: "Crime, Drama, Mystery, Thriller",
    stars: "Steve Carell, Domhnall Gleeson, Linda Emond, Laura Niemi",
    imdb: "https://www.imdb.com/title/tt15574312/",
    premiere: "Aug 30, 2022 (United States)",
    comments: [],
  },
  {
    id: 2002,
    title: "Notre-Dame",
    type: "Series",
    time: "6 hours ago",
    img: "https://static.netnaija.com/i/qvg70Oj6Kze.jpg",
    body: "As the Paris firefighters try to stop the flames from spreading in the Cathedral, the show also follows characters being put through the wringer - they will have to fight each other, love each other, come across each other, hate each other, smile at or help each other - so that, in the end, they may have a chance to start all over again.",
    genre: "Drama",
    stars: "Roschdy Zem, Caroline Proust, Simon Abkarian, Alice Isaaz",
    imdb: "https://www.imdb.com/title/tt15046742/",
    premiere: "Oct 19, 2022 (France)",
    comments: [],
  },
  {
    id: 2003,
    title: "The Mighty Ducks: Game Changers",
    type: "Series",
    time: "May 27, 2021",
    img: "https://static.netnaija.com/i/Aq2NArG6KzJ.jpg",
    body: "It may be the off season, but it's on. In present-day Minnesota, the Mighty Ducks have evolved from scrappy underdogs to an ultra-competitive, powerhouse youth hockey team. After 12-year-old Evan is unceremoniously cut from the Ducks, he and his mom Alex set out to build their own ragtag team of misfits to challenge the cutthroat, win-at-all-costs culture of competitive youth sports. S02: An intense hockey camp run by Colin Cole, a charming yet hardcore former NHL player. As our team tries to survive, they're faced with the question: Can you win summer?",
    genre: "Comedy, Drama. Family, Sport",
    stars: "Lauren Graham, Brady Noon, Maxwell Simkins",
    imdb: "https://www.imdb.com/title/tt7939768/",
    premiere: "Mar 26, 2021 (United States)",
    comments: [],
  },
  {
    id: 2004,
    title: "Star Wars: Andor",
    type: "Series",
    time: "Sep 21",
    img: "https://static.netnaija.com/i/WAPK4x1kK0B.jpg",
    body: "The Rebellion begins. The tale of the burgeoning rebellion against the Empire and how people and planets became involved. In an era filled with danger, deception and intrigue, Cassian Andor embarks on the path that is destined to turn him into a rebel hero.",
    genre: "Action, Adventure, Drama, Sci-Fi, Thriller",
    stars: "Diego Luna, Kyle Soller, Adria Arjona, Joplin Sibtain",
    imdb: "https://www.imdb.com/title/tt9253284/",
    premiere: "Sep 21, 2022 (United States)",
    comments: [],
  },
  {
    id: 2005,
    title: "The Winchesters",
    type: "Series",
    time: "Oct 12",
    img: "https://static.netnaija.com/i/PrO7OeM6Nyp.jpg",
    body: "A supernatural love story. Before Sam and Dean, there was John and Mary. Told from the perspective of narrator Dean Winchester, this is the epic, untold love story of how John met Mary, and how they put it all on the line to not only save their love, but the entire world.",
    genre: "Action, Adventure, Sci-Fi, Fantasy",
    stars: "Meg Donnelly, Drake Rodger, Nida Khurshid, Jojo Fleites",
    imdb: "https://www.imdb.com/title/tt14923244/",
    premiere: "Oct 11, 2022 (United States)",
    comments: [],
  },
  {
    id: 2006,
    title: "The Resident",
    type: "Series",
    time: "Sep 26, 2018",
    img: "https://static.netnaija.com/i/wnRaMjX0Ndq.jpg",
    body: "They don't care for rules. They care for patients. A tough, brilliant senior resident guides an idealistic young doctor through his first day, pulling back the curtain on what really happens, both good and bad, in modern-day medicine.",
    genre: "Drama, Thriller, Medical",
    stars: "Matt Czuchry, Emily VanCamp, Manish Dayal",
    imdb: "https://www.imdb.com/title/tt6483832/",
    premiere: "Jan 21, 2018 (United States)",
    comments: [],
  },
  {
    id: 2007,
    title: "La Brea",
    type: "Series",
    time: "Sep 29, 2021",
    img: "https://static.netnaija.com/i/BQJNjzm3NrL.jpg",
    body: "One family torn between two worlds... When a massive sinkhole mysteriously opens in Los Angeles, it tears a family in half, separating mother and son from father and daughter. When part of the family finds themselves in an unexplainable primeval world, alongside a disparate group of strangers, they must work to survive and uncover the mystery of where they are and if there is a way back home.",
    genre: "Action, Adventure, Fantasy, Drama, Sci-Fi",
    stars: "Natalie Zea, Chiké Okonkwo, Karina Logue",
    imdb: "https://www.imdb.com/title/tt11640018/",
    premiere: "Sep 28, 2021 (United States)",
    comments: [],
  },
  {
    id: 2008,
    title: "FBI: Most Wanted",
    type: "Series",
    time: "Jan 08, 2020",
    img: "https://static.netnaija.com/i/3g8NBvL8NDR.jpg",
    body: "No ordinary criminal makes the list. No ordinary agent takes them off. The Fugitive Task Force relentlessly tracks and captures the notorious criminals on the Bureau's Most Wanted list. Seasoned agent Jess LaCroix oversees the highly skilled team that functions as a mobile undercover unit that is always out in the field, pursuing those who are most desperate to elude justice.",
    genre: "Action, Crime, Drama, Mystery, Thriller",
    stars: "YaYa Gosselin, Lorne Cardinal, Alex Anagnostidis",
    imdb: "https://www.imdb.com/title/tt9742936/",
    premiere: "Jan 7, 2020 (United States)",
    comments: [],
  },
  {
    id: 2009,
    title: "New Amsterdam",
    type: "Series",
    time: "Mar 03, 2021",
    img: "https://static.netnaija.com/i/x5PKDDbqKnM.jpg",
    body: "Take care. Always. The new medical director breaks the rules to heal the system at America's oldest public hospital. Max Goodwin sets out to tear up the bureaucracy and provide exceptional care, but the doctors and staff are not so sure he can succeed. They've heard this before. Not taking 'no' for an answer, Dr. Goodwin's instinctive response to problems large and small is four simple words: 'How can I help?' He has to disrupt the status quo and prove he'll stop at nothing to breathe new life into this underfunded and underappreciated hospital, returning it to the glory that put it on the map.",
    genre: "Drama",
    stars: "Ryan Eggold, Jocko Sims, Tyler Labine",
    imdb: "https://www.imdb.com/title/tt7817340/",
    premiere: "Sep 25, 2018 (United States)",
    comments: [],
  },
  {
    id: 2010,
    title: "The Rookie: Feds",
    type: "Series",
    time: "Sep 28",
    img: "https://static.netnaija.com/i/wnRaMjJgNdq.jpg",
    body: "The FBI has a new secret weapon. Special Agent Simone Clark, the oldest rookie in the FBI Academy, is assigned to support the LA field office.",
    genre: "Action, Crime, Drama",
    stars:
      "Niecy Nash, Frankie Faison, Felix Solis, Britt Robertson, Kevin Zegers",
    imdb: "https://www.imdb.com/title/tt18076310/",
    premiere: "Sep 27, 2022 (United States)",
    comments: [],
  },
  {
    id: 2011,
    title: "FBI",
    type: "Series",
    time: "Oct 03, 2018",
    img: "https://static.netnaija.com/i/5wPKLxGZKVB.jpg",
    body: "FBI is a scripted drama that follows the inner workings of the New York office of the FBI, bringing to bear all the Bureau's skills, intellect and mind-blowing technology to keep New York and the country safe.",
    genre: "Crime, Drama, Mystery",
    stars: "Missy Peregrym, Zeeko Zaki, Ebonee Noel",
    imdb: "https://www.imdb.com/title/tt7491982/",
    premiere: "Sep 25, 2018 (United States)",
    comments: [],
  },
  {
    id: 2012,
    title: "FBI",
    type: "Series",
    time: "Oct 03, 2018",
    img: "https://static.netnaija.com/i/5wPKLxGZKVB.jpg",
    body: "FBI is a scripted drama that follows the inner workings of the New York office of the FBI, bringing to bear all the Bureau's skills, intellect and mind-blowing technology to keep New York and the country safe.",
    genre: "Crime, Drama, Mystery",
    stars: "Missy Peregrym, Zeeko Zaki, Ebonee Noel",
    imdb: "https://www.imdb.com/title/tt7491982/",
    premiere: "Sep 25, 2018 (United States)",
    comments: [],
  },
  {
    id: 2013,
    title: "Queen Sugar",
    type: "Series",
    time: "Jun 13, 2019",
    img: "https://static.netnaija.com/i/zxG7ZryL7q2.jpg",
    body: "'Queen Sugar' tells the story of the estranged Bordelon siblings in Louisiana. At the center of the family are Nova, a journalist and activist; Charley, the wife and manager of an NBA player; and formerly incarcerated father Ralph Angel, who is searching for redemption. Following a tragedy in the family, the siblings must put their complicated lives aside so that they can come together to run the clan's struggling sugar cane farm. Also involved in the farm are Aunt Violet and family friend Remy Newell.",
    genre: "Drama",
    stars: "Rutina Wesley, Dawn-Lyen Gardner, Kofi Siriboe",
    imdb: "https://www.imdb.com/title/tt4419214/",
    premiere: "Sep 6, 2016 (United States)",
    comments: [],
  },
  {
    id: 2014,
    title: "Tell Me Lies",
    type: "Series",
    time: "Sep 13",
    img: "https://static.netnaija.com/i/Gem7QmQm7Yx.jpg",
    body: "You never forget your worst. When Lucy Albright arrives on the campus of her small college, away from her mother whom she's never forgiven for an act of betrayal in her early teen years, Lucy embraces college life and all it has to offer. But everything changes when she meets Stephen DeMarco, who has a mysterious past of his own. Their addicting entanglement will have consequences they never could have imagined.",
    genre: "Drama",
    stars: "Grace Van Patten, Jackson White, Catherine Missal, Spencer House",
    imdb: "https://www.imdb.com/title/tt13018148/",
    premiere: "Sep 7, 2022 (United States)",
    comments: [],
  },
  {
    id: 2015,
    title: "FBI: International",
    type: "Series",
    time: "Sep 22, 2021",
    img: "https://static.netnaija.com/i/1xYNeYyqNLJ.jpg",
    body: "Follow the elite agents of the FBI's International Fly Team as they travel the world with the mission of protecting Americans wherever they may be.",
    genre: "Crime, Drama",
    stars: "Jordan Belfi, Alex Brock, Samantha Blaire Cutler",
    imdb: "https://www.imdb.com/title/tt14449470/",
    premiere: "Sep 21, 2021 (United States)",
    comments: [],
  },
  {
    id: 2016,
    title: "The Good Doctor",
    type: "Series",
    time: "Sep 28, 2021",
    img: "https://static.netnaija.com/i/wnRaMj9zNdq.jpg",
    body: "His mind is a mystery, his methods are a miracle. A young surgeon with Savant syndrome is recruited into the surgical unit of a prestigious hospital. The question will arise: can a person who doesn't have the ability to relate to people actually save their lives",
    genre: "Drama",
    stars: "Freddie Highmore, Hill Harper, Richard Schiff",
    imdb: "https://www.imdb.com/title/tt6470478/",
    premiere: "Sep 25, 2017 (United States)",
    comments: [],
  },
];
