export const politicsData = [
  {
    id: 1801,
    title:
      "El-Rufai reacts as video 'vindicates' Peter Obi of alleged Anambra house arrest",
    type: "Politics",
    time: "6 hours ago",
    author: "Moses O",
    img: "https://static.netnaija.com/i/pJdN9PM1a4P.webp",
    body: "Following an outburst by the Kaduna State Governor, Nasir El-Rufai alleging that the Labour Party presidential candidate, Mr Peter Obi ordered his arrest in 2013, more facts have emerged. We recall that El-Rufai had on Monday while addressing the Arewa Joint Committee organised for presidential candidates, said he would have arrested Peter Obi in Kaduna State as allegedly done to him in Anambra State. He said, 'I want to say that I went to Anambra state for my party to monitor election, Peter Obi who was a Governor put me under house arrest for 48 hours. 'Today, I am the Governor of Kaduna state and he's coming to Kaduna to campaign and apart from other security agencies, I have the First Mechanized Division of the Army in Kaduna but I will not arrest him because we Northerners are civilized people.' We report that the governor had gone to Anambra State in 2013 to lend support for Chris Ngige, the current Minister of Labour, who ran against Peter Obi on the platform of the All Progressives Congress, APC, during governorship election. A tweep, Adetutu Balogun, however, tweeted an old video which captured El-Rufai blaming authorities from Abuja for being responsible for his alleged house arrest. In the video, El-Rufai was heard saying 'I left my hotel room to go and get my breakfast and I was blocked by three SSS officers with AK-47, threatening me that they have directive from Abuja to restrict me to my room'. Reacting to Balogun's tweet, El-Rufai took to his verified handle to claim that he has video evidence of Obi claiming responsibility for the alleged unlawful detention. He wrote, 'Yes but your little god Peter Obi later revealed on national TV - we have the video clip - that he got the unlawful detention effected, and said I had no right to be in Anambra State since it was not Katsina State. 'The clown didn't even know that I am from Kaduna State.'",
    comments: [],
  },
  {
    id: 1802,
    title:
      "Presidency: Peter Obi opens up on receiving private jets donation from eminent Nigerians",
    type: "Politics",
    time: "Yesterday 12:08am",
    author: "Moses O",
    img: "https://static.netnaija.com/i/AqgKGOZ3Kr1.jpg",
    body: "The Labour Party, LP, presidential candidate, Peter Obi, on Sunday debunked reports of him receiving personal jets to boost his campaign. Reports claimed that some eminent Nigerians donated personal jets to Obi's presidential campaign. Condemning such reports, Obi described such viral claims as false. In a series of tweets, Obi wrote: 'Recently, several social media reports have alluded that some eminent Nigerians have donated their personal jets for my use during my campaign. 'In as much as I appreciate the expression of such hopes, I have never received any of such offer.' The former Anambra State governor also prayed that God would bless those 'eminent Nigerians'. He further wished that they are not distracted by such remarks. 'I pray that those eminent Nigerians mentioned, are not unduly distracted by such social media utterances. 'May God Almighty bless those eminent Nigerians always,' he added.",
    comments: [],
  },
  {
    id: 1803,
    title:
      "Peter Obi is campaigning in Lagos because we developed and stabilized it. He should go back to his state and campaign - Lagos Deputy Governor, Babafemi Hamzat (video)",
    type: "Politics",
    time: "Oct 04",
    author: "Same Emmanuel",
    img: "https://static.netnaija.com/i/5VrNpldWN9O.webp",
    body: "Lagos State Deputy Governor, Babafemi Hamzat has been caught on video launching a verbal attack at Labour Party presidential candidate, Peter Obi. In the video, Hamzat was heard saying that Peter Obi is campaigning in Lagos after 'they developed and stabilized' the South-West state. The Lagos state Deputy Governor who also claimed that Peter Obi can't campaign in Lagos, asked the former Anambra state governor to go back to his state.",
    comments: [],
  },
  {
    id: 1804,
    title: "2023: 'Tinubu knows my party' - Sanusi",
    type: "Politics",
    time: "Oct 16",
    author: "Moses O",
    img: "https://static.netnaija.com/i/G4E7z9rMKb6.webp",
    body: "With the 2023 general elections fast approaching, former Emir of Kano, Sanusi Lamido Sanusi, has disclosed the only party he belongs to. Sanusi said the All Progressives Congress, APC, presidential candidate, Bola Tinubu is aware that he belongs to the party called Nigeria. He disclosed this while noting that he's not a member of any political party. Sanusi spoke while addressing Tinubu and other guests in Kaduna during the seventh edition of KadInvest, an annual event organised by the Kaduna State Investment Promotion Agency yesterday. The former Governor of the Central Bank of Nigeria, CBN, also lamented oil theft, Nigeria's rising debt profile, unbalanced subsidy payment and soaring foreign exchange, amongst other monetary and economic challenges facing Nigeria at the moment. He called for transparency and credibility in the management of the nation's resources and demanded the unbundling of the Nigerian National Petroleum Company (NNPC) Limited, saying the company is not a cash cow but should be run as an independent enterprise with high-level accountability. Sanusi further urged States to free themselves from excessive reliance on the Federal Government. 'I keep repeating, hope you remember that I lost my job at the Central Bank for this same problem. 'It is not about a particular party. I have no party. My party is Nigeria. This is the problem we had in 2014. Asiwaju (Tinubu) knows my party is Nigeria,' he said.",
    comments: [],
  },
  {
    id: 1805,
    title: "Obasanjo hands over seat to Peter Obi (Video)",
    type: "Politics",
    time: "Oct 14",
    author: "Moses O",
    img: "https://static.netnaija.com/i/x5PKDXGEKnM.webp",
    body: "Former President Olusegun Obasanjo gave his seat to the Labour Party (LP) presidential candidate, Peter Obi at a function in Abuja this week. Social media users are ascribing political annotations to a video of the scene now trending. Obasanjo, Obi and other dignitaries were at the Transcorp Hilton in Abuja for a gathering organized by Fidelity Bank. The event celebrated the national honour given to Professor Benedict Oramah by President Muhammadu Buhari. Oramah is the President and Chairman of the Board of Directors of the African Export-Import Bank (Afreximbank). In a Twitter post, @OluwaseunP, the master of ceremonies, narrated how Obi walked in while Obasanjo was making his speech. The 2023 LP flagbearer took a seat at the back of the hall after refusing to take one of those reserved for VIPs. 'OBJ noticed & told them, 'leave him alone o'. He then went himself to bring Obi to the front & gave him his own seat. Then said, 'my job is done', the tweet added. The video has gone viral on Twitter and Facebook, with some describing Obasanjo's action as 'symbolic' and 'an endorsement'. We gathered that some former Nigerian leaders were tactically supporting the former Anambra governor. Obasanjo, in particular, is believed to be rallying other former Heads of State, influential retired Generals and powerful Northerners, including monarchs, for Obi. There are speculations that the jet Obi has been using in recent times was offered by shipping and oil magnate, T. Y. Danjuma. The 83-year-old former Chief of Army Staff served as the first Minister of Defence under the Obasanjo administration. Akin Osuntokun, a former political adviser to Obasanjo, recently disclosed that his ex-principal may be supporting Obi to become President in 2023.",
    comments: [],
  },
  {
    id: 1806,
    title:
      "Labour Party to review presidential campaign council after outcry over inclusion of General who claimed #EndSARS massacre was photoshop and others",
    type: "Politics",
    time: "Oct 14",
    author: "Moses O",
    img: "https://static.netnaija.com/i/1qGK1ZZw7rV.webp",
    body: "The Labour Party (LP) has announced plan to review its list of members for its presidential campaign council. This came after an outcry following the inclusion of Nigeria Labour Congress and the Trade Union Congress Presidents, and retired major general of the Nigerian Army and ex-defence spokesperson, John Enenche, on the list. General Eneche had during the 2020#EndSARS protest, said that videos of the Lekki tollgate shooting were 'photoshopped.' He said at the time; 'These videos were cropped and photoshopped. If not that I am not permitted I would have forwarded it to you. Up till this morning, I got an analyst to analyze the video and they said it was cropped and put together.'Following the outcry that trailed the list, LP national chairman Julius Abure who read a communique at the end of the party's expanded national working committee (NWC) meeting, held in Abuja on Thursday, October 13, said it was an error for presidents of the Nigeria Labour Congress (NLC) and Trade Union Congress (TUC) to be on the campaign council. Abure said the list will be corrected and a supplementary list will be released before the inauguration of the council.",
    comments: [],
  },
  {
    id: 1807,
    title: "PDP sends four South-South govs to beg Wike",
    type: "Politics",
    time: "Oct 14",
    author: "Same Emmanuel",
    img: "https://static.netnaija.com/i/1xYNeMYkNLJ.jpg",
    body: "Four South-South governors of the Peoples Democratic Party have been assigned to beg the Rivers State Governor, Nyesom Wike, to support the party's presidential candidate, Atiku Abubakar, in next year's presidential election. The governors saddled with the responsibility are Udom Emmanuel (Akwa Ibom), Douye Diri (Bayelsa), Ifeanyi Okowa (Delta) and Godwin Obaseki (Edo). This was contained in a communique issued at the end of South-South PDP Governors' Forum meeting which was hosted in Uyo, Akwa Ibom State, by Governor Udom Emmanuel. Apart from the four governors of the region who attended the meeting, Governor of Sokoto, Aminu Tambuwal, who is also the Director-General, Atiku/Okowa Campaign Council and Chairman of Nigeria Governors' Forum, was in attendance. Others were the immediate past governors of Cross River State, Liyel Imoke; Lucky Igbinedion of Edo; Celestine Omehia; the immediate past National Chairman of the PDP, Prince Uche Secondus; serving and past members of the National Assembly, serving and past Members of State Assemblies. The communique was signed by the PDP vice presidential candidate and governor of Delta State, Ifeanyi Okowa, and made available to journalists in Uyo. 'The meeting strongly urged the four PDP Governors within the South-South Zone that took part in the meeting to do everything necessary within their powers to persuade their brother governors, especially Governor Nyesom Wike, to review their position and join hands with the party to rescue, rebuild and reunite the country in the interest of the suffering Nigerians. 'The meeting formally congratulated HE Atiku Abubakar for his emergence as the party Presidential Candidate and thanked the party leadership for the nomination of one of the great sons of the Zone, Ifeanyi Okowa, Governor of Delta State, as the Presidential running mate. 'The meeting underscored the need for unity and urged all members of the party within the South-South Zone to make all necessary sacrifices both individually and collectively to ensure the victory of the party in all of the elections in 2023, especially to save the country from the precipice and brinks of total collapse culminating from the clueless, incompetent and ineptitude APC's administration in the country. 'The meeting reviewed recent events in our party, the PDP, and in the country, especially the dwindling fortunes of the country in the areas of insecurity, economy, unemployment, poverty, inflation, corruption, currency devaluation,' the communique read in pa",
    comments: [],
  },
  {
    id: 1808,
    title:
      "I joined politics to change the system not to defend PDP history - Singer Banky W",
    type: "Politics",
    time: "Oct 12",
    author: "Moses O",
    img: "https://static.netnaija.com/i/Aq2NAYXYNzJ.jpg",
    body: "Famous Nigerian singer and actor turned politician, Olubankole Wellington, popularly known as Banky W, has disclosed that he joined politics to make changes and not to defend the People's Democratic Party (PDP) history. Banky W made this known during an interview on Arise TV's 'The Morning Show' on Wednesday. While narrating his passion for a better Nigeria, the Peoples Democratic Party House of Representatives candidate for Eti-Osa Federal Constituency, said, 'I have participated in peaceful protests just like anybody that I know among my peers. 'But the goal of activism and advocacy is improvement and if you haven't seen the impact you seek, then that activism is not enough. 'So, for me, the message started changing from just raising awareness via activism and advocacy to saying we have to start moving from protests to politics. 'We have to start taking these energies and channeling them toward getting like-minds into the government and using that consensus of like-minds to get a change and that is where my mindset started changing and in 2018 I started feeling like the problem in Nigeria is top-down and the solution is from the bottom up. 'And I started thinking that if with my education, success, background, audience, following, and voice and I can't stick my neck out that I can be a part of this system and can bring a solution to the table, who am I waiting for to get involved in the system? 'So, in 2018, I prayed about it and I informed my wife and what she told me was that 'you know politics in Nigeria is dirty and I know your heart and I know the system is what it is and I don't want anything that will soil your hands' and I told her that the truth of the matter is politics will always be dirty and dangerous until good people start to be intentional about putting like-minds in the system.'",
    comments: [],
  },
  {
    id: 1809,
    title:
      "CSOs allege plots to stop INEC from using electronic transmission of results",
    type: "Politics",
    time: "Oct 12",
    author: "Moses O",
    img: "https://static.netnaija.com/i/mjyK6GoG7wD.webp",
    body: "A coalition of Civil Society Organizations (CSOs) has alleged that there is a grand plot to force the Independent National Electoral Commission (INEC) to stop the electronic transmission of the 2023 general elections.The allegation which is emanating from the opposition and other concerned Nigerians also revealed that plans were being hatched to pressure the electoral Commission to deactivate Bi-modal Voter Accreditation System (BIVAS) from the server including stirring a possible change in leadership of INEC.Spokesman of CUPP, Ugo Ikenga Ugochinyere, while addressing a press conference on Wednesday in Abuja, alleged that 'there was immense pressure on the leadership of INEC to deactivate the BIVAS from the server, which pressure has been resisted by INEC hence the plot by the ruling party's agents led by some governors to commence the plot to cause a leadership change in the electoral management body.The plan is also being orchestrated in such a way that it will consume top officials including the Chairman and the few National Commissioners, who are still insisting on the use of the BIVAS.' The CSOs opposed to the plans have resolved to petition the United Kingdom High Commission and the United States Embassy and alert them of the alleged new conspiracy, which they said threatens the Nigerian electoral process and regional stability.According to the groups, the International community will be urged to keep vigilant eyes on the process as development partners and ensure there is adequate vigilance and support insisting that the right things are done in compliance with extant laws.One of the Groups, the CUPP said it intends to immediately approach the Court to seek judicial redress to ensure the electoral process is not derailed, adding, 'the suit, when filed, will restrain the Federal Government, DSS, Nigeria Police, National Assembly, ICPC, CCB, EFCC, CCT, and Attorney General of the Federation, from stopping the use of BIVAS, deactivating BIVAS from the INEC Server, removing of the INEC Chairman, arresting or using an exparte injunction to suspend him, suspending him from office under any guise or any form of detention with the intention to remove him from acting as INEC Chairman.It would be recalled that the CUPP had a few weeks ago also uncovered an alleged compromise of the voters' registration exercise in some All Progressives Congress (APC) controlled states in a secret illegal operation code-named Omuma magic, which the opposition insisted that those behind the mafia operation should be arrested and prosecuted.'The BIVAS is an electronic machine that will be used to electronically accredit all voters for the 2023 general election and also be used to transmit election results from the Polling Units direct to the INEC central server.'The BVAS had been deployed in the last three cycle governorship elections in Anambra, Ekiti, and Osun states and has been observed to have generally improved the credibility of the elections as the perennial problems associated with snatching of result sheets and changing of results at collation centres has been solved,' the CUPP Spokesman explained.",
    comments: [],
  },
  {
    id: 1810,
    title:
      "Shagari explains why he rejected to become Peter Obi's running mate",
    type: "Politics",
    time: "Oct 12",
    author: "Moses O",
    img: "https://static.netnaija.com/i/xM6K5gQWayE.webp",
    body: "Alhaji Mukhtar Shagari, a former Deputy Governor of Sokoto State, has revealed that he was approached to become the running mate of the Labour Party (LP) Presidential candidate, Peter Obi. Shagari said he rejected the offer to become Peter Obi's running mate because he strongly believes that the Labour Party cannot defeat the Peoples Democratic Party in any election. The former Deputy Governor who also claimed that Labour Party has no presence in Sokoto where he hails from in an interview on Channels Television added that Nigerians are not looking for lofty ideas, but solutions to the problems and maladies in the area of the economy. He said; 'I was contacted to be the running mate of Peter Obi. I told them I will not be able to leave my Party because I believe in the philosophy of my Party, I believe in what my Party stands for Nigeria and I also believe that the Labour Party will not be able to beat my party at any election. 'What is happening? So many young people as you said, who are those young people? I asked the Labour Party members that contacted me, 'Tell me who really is the Chairman of Labour Party in Sokoto State? Who are the candidates of Labour Party in Sokoto State? Who is contesting for Senate? Who is contesting for governorship and so on and so forth, I did not get any successful answer. 'The issue is at any point in time, Nigerians are not looking for lofty ideas, Nigerians are looking for solutions to the problems and maladies of this country in the area of economy, in the area of security, in the area of infrastructure, in the area of poverty alleviation.'",
    comments: [],
  },
  {
    id: 1811,
    title:
      "Frank Edoho queries Omojuwa over Twitter poll he conducted which three major candidates he put up lost even after he left out Peter Obi",
    type: "Politics",
    time: "Oct 11",
    author: "Same Emmanuel",
    img: "https://static.netnaija.com/i/m9z7oYW0N2r.webp",
    body: "Media personality, Frank Edoho has queried his colleague in the media industry, Japheth Omojuwa over a recent Twitter poll he conducted ahead of the 2023 presidential election. Omojuwa had in the Twitter poll listed Bola Tinubu, Atiku Abubakar, Rabiu Kwankwaso as the main contenders. Omoyele Sowore, Kola Abiola, and 'others' were all joined together on the final row of the poll. Omoyele Sowore, Kola Abiola, and 'others' however got 58% of 98,035 votes which was cast for the poll.  Tinubu got 27.6%, Atiku got 9.8% and Kwankwaso got 4.6%. Edoho who reacted to the poll, mocked Omojuwa by saying Peter Obi is so big that he (Omojuwa) had to put him in the 'OTHERS' category that polled the majority of the votes. The media personality who thanked Omojuwa for being 'Obedient', added that he must be a Davido fan because he rises by lifting 'OTHERS'.",
    comments: [],
  },
  {
    id: 1812,
    title:
      "Katsina lawmaker elected to fill up position of late lawmaker, dies in Saudi Arabia",
    type: "Politics",
    time: "Oct 10",
    author: "Moses O",
    img: "https://static.netnaija.com/i/9bVNr90YaWv.webp",
    body: "Dr. Ibrahim Aminu Kurami, the lawmaker representing Bakori Local Government Area in Katsina State House of Assembly, is dead. The lawmaker who died today around 2 am Nigerian time, was elected to Katsina State House of Assembly in a by-election conducted on October 31, 2020, following the death of his predecessor, Hon. Abdurrazak Ismail Tsiga. Kurami's family told Daily Trust that he died after a brief illness in Madinah, Saudi Arabia. He reportedly traveled to the Middle-East country to perform Umrah. Ibrahim Aminu Kurami left behind two wives, 11 children, and three grandchildren. A crowd of sympathizers was spotted at his house on Monday morning when visited by some journalists.",
    comments: [],
  },
  {
    id: 1813,
    title: "MC Oluomo leads 'five million-man' rally for Tinubu in Lagos",
    type: "Politics",
    time: "Oct 09",
    author: "Same Emmanuel",
    img: "https://static.netnaija.com/i/1xYNeMjqNLJ.jpg",
    body: "Chairman of the Lagos state parks and garages management committee, Musiliu Akinsanya popularly known as MC Oluomo, has led a 'five million-man' rally for presidential candidate of the All Progressives Congress, Bola Tinubu, in Lagos. MC Oluomo had announced a massive rally for Tinubu after supporters of Labour Party presidential candidate, Peter Obi marched on various streets of Lagos last week. The rally which took off from Teslim Balogun Stadium, Surulere, has led to traffic gridlock in some parts of Lagos. Prior to the rally, the Lagos State Traffic Management Authority (LASTMA) announced a traffic diversion for the rally. The Lagos state agency advised motorists from Eko Bridge inwards Surulere to pass through the stadium bridge to Funsho Williams avenue and connect to their destination through Ojuelegbe to Lawanson-Itire road. During the march across streets in Lagos, shouts of 'Awa Lokan', 'Se Jagaban', 'Tinubu for President' rend the air.",
    comments: [],
  },
  {
    id: 1814,
    title:
      "Former PDP secretary Olisa Metuh asks the party to issue a disclaimer against Reno Omokri's posts",
    type: "Politics",
    time: "Oct 10",
    author: "Same Emmanuel",
    img: "https://static.netnaija.com/i/no4NXY03K9M.webp",
    body: "Former secretary of the PDP, Reno Omokri has asked the Peoples Democratic Party to issue a disclaimer against former presidential aide, Reno Omokri's posts. Metuh made the call while quoting Reno Omokri's post targeted against supporters of Labour Party presidential candidate, Peter Obi. Omokri had written; You rage against Tinubu. You insult his ethnicity (who are the most accommodating people in Nigeria and perhaps Africa). You accuse him of using MC Oluomo. You say Obi is far better than Tinubu. You say Obi will turn Nigeria into paradise. Yet, you remain in Lagos and refuse to leave Lagos for the paradise that Obi created in Anambra! The only reason I am against Tinubu is because as a drug lord, he can be blackmailed by foreign intelligence services. Otherwise, he performed as Lagos Governor. If you maintain that Obi did better than Tinubu, prove it by packing your kaya and relocate to Anambra!",
    comments: [],
  },
  {
    id: 1815,
    title:
      "I don't know Tinubu's whereabouts, he is not in the country - Keyamo",
    type: "Politics",
    time: "Oct 06",
    author: "LuvlyGist",
    img: "https://static.netnaija.com/i/9bVNr9wDaWv.jpg",
    body: "Minister of State for Labour and Employment of Nigeria and Spokesperson of the All Progressives Congress campaign council, ]Festus Keyamo, admits not knowing the whereabouts of ]Bola Ahmed Tinubu. During a chat on Channels Television on Wednesday, October 5, Keyamo addressed the backlash trailing a fitness video of the APC's presidential candidate. According to Festus Keyamo, Tinubu is out of the country and he is clueless about his return or exact location. Keyamo said; 'Our candidate is not in the country currently and I don't have any information on where he is. I know he will be back in a couple of days but I don't know the particular day. 'He is also not on a medical trip; I don't have such information. It is not true that we have not started campaigns because the candidate is sick and is not around.' Addressing the mixed reactions generated by ]Tinubu's fitness video, he said 'As far as I am concerned it was done in real-time and posted on his Twitter handle. It is not to prove that he is alive, we are not trying to prove anything to anybody. Our candidate is not struggling to prove himself to anybody. People who are close to him know that he is an avid cyclist, he does that all the time, and it is his regular routine. 'I think what we want to prove this period is to correct mischievous enquires by mischief makers. We want to prove that the tail doesn't wag the dog, it is the dog that wags its tail. 'It is not every time you ask mischievous questions, we would be struggling to prove ourselves. We are not dancing to the tune of the opposition. We have our tune and music and we would do with it whatsoever we like. We are not going to be reacting all the time to what the opposition is doing with mischief. 'We are all aware that the Presidential candidate of the PDP, Atiku Abubakar, travels to Dubai all the time, I don't see any media intensity on what he is doing in Dubai. Whenever he travels, nobody remembers him until he comes back a week or two later. They know he is the candidate to beat and so the searchlight is on him and we are proud of that.'",
    comments: [],
  },
  {
    id: 1816,
    title: "I Inherited a country with bombs going off in cities - Buhari",
    type: "Politics",
    time: "Oct 06",
    author: "Moses O",
    img: "https://static.netnaija.com/i/XV5KvQrgN9m.jpg",
    body: "President Muhammadu Buhari has claimed he inherited a country at crossroads with bombs detonating in cities of Nigeria. Buhari disclosed this during the passing-out parade and commissioning ceremony of cadets of regular Course 69 of the Nigerian Defence Academy, NDA, in Kaduna on Thursday. He, however, said his administration has been able to manage Nigeria's security crisis since assuming office in 2015. 'When this government came in 2015, we inherited a country at crossroads with bombs going off with frightening frequency even in our cities, and we came in to manage the crisis,' he said. Buhari called on the cadets to replicate the spirit of social cohesion they learned at the NDA and be incorruptible models to society. He stressed that the cadets emerged in the era of expanding global security threats. A total of 239 cadets, including those from sister African countries such as Liberia, Sierra Leone, Niger Republic, Chad, and Uganda are passing out from the Academy as junior military officers. Among the dignitaries present are service chiefs and the Inspector General of Police, Usman Alkali; Senate President Ahmed Lawan; the governors of Niger and Kaduna States, as well as National Assembly members.",
    comments: [],
  },
];
