export const romanceData = [
  {
    id: 1501,
    title:
      "If he cheats with you, he will cheat on you - Clergyman Kingsley Okonkwo tells ladies",
    type: "Romance",
    time: "Oct 06",
    author: "Same Emmanuel",
    img: "https://static.netnaija.com/i/8yZaJrX9aJ0.jpg",
    body: "Clergyman, Kingsley Okonkwo, has asked women to be wary of cheating men. In a post shared on Twitter, the Lagos-based pastor stated that if a man cheats with a woman, there is every tendency he will cheat on her too, if they get married. He pointed out that exchanging marital vows with a cheating man doesn't change his character. His tweet reads:- 'If he cheats with you, he will cheat on you, saying 'I do' doesn't change your character'",
    comments: [],
  },
  {
    id: 1502,
    title: "Why do men get so, so angry when they're cheated on?",
    type: "Romance",
    time: "Yesterday 1:00pm",
    author: " LuvlyGist",
    img: "https://static.netnaija.com/i/qvg70XqB7ze.jpg",
    body: "For a gender largely believed to be unable to help themselves when it comes to cheating, men seem to hate being cheated on too much. Why? The narrative that has been spun around the issue cheating for the longest time is that men cheat more than women, but are more hurt and distraught and angry when they find out they've been cheated on. It's kinda straightforward like that in our collective consciousness. The narrative sees us believe that women somehow 'expect' to be cheated on because 'all men cheat' and 'men will always be men.' So what we have is an unfair situation, a particularly bothersome relationship dynamic which makes it feel OK for women to pardon and forge on when their men cheat; but on the other hand, validates men's indignation and righteous rage when they get cheated on. An excellent option to protect yourself from cheating is to use mSpy software. You will see who calls your partner and what messages she gets on Messenger, Whatsapp, and Snapchat. mSpy can provide peace of mind to you. So let's talk about reasons why this is so. Why does it bother men so much when a woman cheats on them, and why do more men find cheating absolutely unforgivable compared to women? 1. They know that cheating, for women, is solely for emotional purposes. When women cheat, it is for emotional reasons. Women do not cheat for physical reasons, and for the most part it's not for sexual gratification. It has been said that the need to bridge an emotional gap, to plug some emotional vacuum is what leads women into affairs. So, for men, knowing that the woman has detached herself emotionally and that their time is likely over makes cheating an extra-uneasy pill to swallow for them. 2. Ego takes a hit. Whereas women become [inexplicably] ashamed and embarrassed when their partner cheats on them, men see cheating as an affront on their ego. They probably feel that being cheated on is the highest form of disrespect ever, and this makes it even more difficult to stomach it. Because, you know, men think they deserve respect as a birthright. 3. They never see it coming. The average man, no matter how unkempt, emotionally unavailable, difficult and problematic he is, still feels like he deserves loyalty and may never, for the life of him, imagine that his babe has it in her to either dump him or cheat with another man. And while this is not entirely a wrong thing to expect, [I mean, if you're still with someone, it's only OK for them to expect loyalty from you] it's still kinda deluded and naïve to think that women, especially the ones with unmet and unsatisfied emotional needs cannot or will not seek to get it from someone else. 4. They feel like cheating is for men. Crazy, right? But, yeah, it's true. Some men are conditioned to think that only women get cheated on. They think it's a man's game to do that. Cheating is something men do. A woman cheating is... just wrong. But when it's a man, it could be pardonable, explainable, there could be some way to justify it, it could be explained away, put in some perspective that makes it less of an issue. But a woman cheating... and God safe us... a married woman?! Nah. That's too scandalous. The greatest sin of all time. 5. They've been faithful all along. Like we pointed out above, cheating is painted to look like a man's game. So when a man chooses to stay faithful to his wife or partner, they think they deserve some medal. Some extra cool points for being the guy who does not cheat, not to be rewarded with cheating. Conclusion: The point of this is not to justify women cheating or saying it's cool for men to get cheated on. Hopefully everyone sees cheating as something that bothers everyone equally. Women get just as hurt as men when they're played. And anyone can cheat. Anyone can actually get cheated on, and ultimately, everyone owes their partner the duty to be faithful and honest.",
    comments: [],
  },
  {
    id: 1503,
    title:
      "OMG!!! See What Happened To Lagos Big Boy After Sleeping With A Calabar Sales Girl",
    type: "Romance",
    time: "Feb 28, 2017",
    author: "Same Emmanuel",
    img: "https://img.netnaija.com/hsi/aHR0cDovL25haWphbG9hZGVkLTE0ZmNreXpmdHdoeHJkNWN0YmF1LnN0YWNrcGF0aGRucy5jb20vd3AtY29udGVudC91cGxvYWRzLzIwMTcvMDIvTm5la2Etc3VnYXItbXVtbXkuanBn/images/Nneka-sugar-mummy.jpg",
    body: "A privileged man staying at the highbrow area of Lagos State seems to have fallen in love with a common sales girl from Calabar after a s*xual encounter with her.A young man based in the upscale Ikoyi area of Lagos State has expressed his desire to marry a 'low-level' Calabar girl after sleeping with her and tasting her food. He wrote to a relationship blogger, Joro Olumofin to seek advice about his current obsession with the lady who doesn't fit his social class.",
    comments: [],
  },
  {
    id: 1504,
    title:
      "Miami Female Teacher Had Sex, MouthAction With Student, 17, In Class, Car (Pics)",
    type: "Romance",
    time: "Jan 15, 2018",
    author: "Same Emmanuel",
    img: "https://img.netnaija.com/hsi/aHR0cHM6Ly9hbGV4aXMubGluZGFpa2VqaXNibG9nLmNvbS9waG90b3Mvc2hhcmVzLzVhNWJlY2UzYzVkZmUuanBn/images/5a5bece3c5dfe.jpg",
    body: "A pretty Maimi teacher has been arrested after she was accused of performing a sex act with an underage student in her classroom, car and his home during a two-year secret tryst' Valeria Costadoni, head of the language arts department at Miami Arts Charter School is alleged to have had a two-year relationship with a 17-year-old student. Local news channel WPLG reported that Valeria was nabbed after the student told Police he had sex with his teacher. According to a police report, the 30-year-old had sex with the student at school and four times at her home. The student said his relationship with Costadoni involved her performing MouthAction on him on 'many different occasions' inside a school classroom. It was also reported that the two had sex in Costadoni's car and at the student's home. Costadoni is now facing charges of Lewd and Lascivious battery on a child between 12 and 16 years old and lewd and lascivious battery with sexual activity. She was booked at the Turner Guilford Knight Correctional Center and posted $15,000 bond.",
    comments: [],
  },
  {
    id: 1505,
    title: "The Perfect Gift Ideas For Your Anniversary",
    type: "Romance",
    time: "Oct 09",
    author: "Same Emmanuel",
    img: "https://static.netnaija.com/i/8yZaJr2kaJ0.jpg",
    body: "Special people deserve special treatment every day, but more so on special days, like an anniversary. It doesn't matter if you are celebrating a few months or 10 years together; a thoughtful gift can melt your partner's heart and make their day. The best gift you can give the one you love is one that screams, 'Nobody knows you as I do', and I'm grateful to be with you. So before you go through this list, think of something you know that nobody else does. This list contains some of the best gift ideas for your anniversary. PHOTO ALBUMS - A photo album will hit the spot, especially if their love language is quality time. Fill your photo album with candids and bloopers for a more personal touch. If your person doesn't take many pictures, try doing a video compilation of random happy moments. STICKY NOTES IN A JAR - This option is excellent for people that love acts of service and words of affirmation. Nonetheless, you can tailor this to their love language. You may fill these notes with reasons why you love them, short messages to energize them if they're having a bad day, or even a few dares, just for fun. This option requires a lot of creativity, so buckle down. A BLISSFUL STAYCATION - Long-distance partners can enjoy their anniversary together when they plan a staycation. Before the staycation, clear up your schedules for at least two whole days. There should be no calls from work during this period. Fill up those hours with items like a spa date, dinner on the beach, or a resort trip. A HOTEL DATE WITH A NICE VIEW - Say you don't have two whole days for a staycation; you could do it all in one night. Start with a light lunch, then a fun physical activity like mountain climbing, a hearty dinner, and then a party into the night. If you've got some extra cash, book a fancy vacation away from the hustle and bustle of town, just the two of you basking in your love and affection for each other. Our recommendation, find a hotel with a beachfront or mountain top view. Nature is really the best romance. JEWELRY - Everyone loves a good piece of jewellery. From wristwatches to rings, necklaces and earrings, jewellery convey a lot of emotions and are a great way to let your partner know just how much you care about them. As an added tip, go on to engrave the jewellery to make them even more special. Engrave an affectionate pet name at the back of wristwatches, and add a great picture of the both of you in a locket. There's so much more you can do with jewellery. FLOWERS - Every lady loves a beautiful bouquet of flowers. Not only do they communicate feelings of love and affection, but they are also pleasant to the eyes and smell even better. Sending your partner a bouquet of flowers on your anniversary reminds them just how much you care about them and how much you love them. CAKE - Tasty and delicious, every celebration deserves a cake and anniversaries are not left out. Get them their favourite cake flavour; chocolate, vanilla etc, with an adorable inscription that celebrates your special day. Whichever choice you make, one thing to know for sure is your partner would love and accept the gifts you pick out for your anniversary. Let's know which of these you choose, we'd be happy to know we helped.",
    comments: [],
  },
  {
    id: 1506,
    title: "Is it right to put your girlfriend on a monthly allowance?",
    type: "Romance",
    time: "Oct 06",
    author: "LuvlyGist",
    img: "https://static.netnaija.com/i/eDxaw93RKPZ.jpg",
    body: "As great as bae allowances are, no one should ever feel under any pressure to give them. These are the days of no money, no love Let's talk about boyfriends, girlfriends and the appropriateness of giving monthly allowances to someone you are in a relationship with. Unsurprisingly, one of the most discussed, often controversial aspects of relationships is ]money and its application in those. Issues about cab fares after visits, who pays during dates, how much one needs to earn before considering a relationship, etc have been debated on social media in the recent past. One other aspect of this money discussion is the practice of giving a girlfriend money at the end of every month for her up keep. This money is actually known as Bae Allowance - money a guy gives his girlfriend at the end of each month for her random needs. Bae allowance is cool... There is nothing stopping anyone from giving money to a girlfriend. Heck, there's even no rule about how frequent it should be or how much it should be. It is not illogical for a man to want to spoil his woman in all manners he deems fit. If a monthly allowance is one of the ways he chooses to appreciate his woman's presence in her life, then, no one should give such guy grief for that. For the guys who feel comfortable doing so, it is admirable and nice. And you should never feel discouraged by people to stop if you see no problem with it. Bae allowance is not a relationship standard Bae allowance may not be wrong but it should never be a relationship benchmark for anyone. If you date someone who gave you a monthly, weekly or daily allowance, it is important to understand that such person did it as a largesse and not a compulsory or widely-expected relationship standard. Bae allowance is not on the same pedestal of relationship expectations as communication, honesty, ]gift-giving and others. This is why every money [whether monthly or less frequently] between partners need to be appreciated for the gifts they are, and not demanded as if they contractual obligations. As we already said in another post here, your boyfriend does not owe you the ]duty of gifting you money, just as you do not owe him the duty of cooking his meals or tidying up his apartment in your visits. People should do these things because they are capable and want to do so. No one should be compelled to do them. There are relationship things you can demand because you are entitled to them; a monthly allowance, as nice as it is, isn't one of them.",
    comments: [],
  },
  {
    id: 1507,
    title:
      "How to be in a private relationship without getting secretive about it",
    type: "Romance",
    time: "Oct 06",
    author: "LuvlyGist",
    img: "https://static.netnaija.com/i/qEQN24DZ76W.jpg",
    body: "Keeping your relationship private is good. Keeping it a secret is bad. Coded Couple [iStock] For many, the most notable sign of being in love or getting into a new relationship is how ceaselessly they talk about their new partner. You could be talking about something totally unrelated and they'll look for a way to bring their new girlfriend or boyfriend into it. On the flipside, it is also quite common to hear people say they don't like putting their relationships out there. Just as you have people that share everything about their relationships, you also have people who won't breathe a word about it, even if you press them repeatedly. It is perfectly OK if a private relationship or marriage is what you want. But just be sure that you are keeping a private relationship and not a secret relationship because there's actually a difference. In fact, some people who keep their relationships secret think they are just being private about it. If no one knows that you are in a relationship, despite having been asked severally, or having been presented with the opportunity to indicate your relationship status, then you are keeping it secret. Being asked if you are in a relationship and not stating your answer clearly - YES or NO - is wrong. It could be rightly interpreted as you lying. And lying about your relationship status almost always means one thing - you are considering the possibility of cheating, or hoping to 'sexually defraud' someone by making them believe you are single when you are not. That's just sneaky and deceptive. Some may also say this is a sigh that you are ashamed of your partner - and they won't entirely be wrong. Being private about your relationship means that although you are not excessively loud and or annoying with it all the time, you are still unequivocally truthful about being in one. However, that's all you let people know. You don't go on social media to show every gift your boo bought, you don't do everything for the gram, you don't tell your friends every time you have sex with your girl, your girls don't get the complete gist of every moment spent with bae. Private relationships are defined by how limited of the details that The minimal the information you share with close friends, family member and social media, the better. Just look at ]Beyonce and Jay Z's marriage as an example, as well as ]Simi and Adekunle Gold's. Despite being such public, popular figures, they keep such a tight lid on what gets out and what does not. You know they are a couple but that's pretty much it. You only know what they want you to - and they feed the public crumbs every now and then. That's how to be private in relationships.",
    comments: [],
  },
  {
    id: 1508,
    title: "Why ghosting is clear communication, and frequently the right move",
    type: "Romance",
    time: "Oct 06",
    author: "LuvlyGist",
    img: "https://static.netnaija.com/i/1qdNVjWAN4g.jpg",
    body: "It's okay to ghost people. One common part of relationships and friendships these days is ghosting. Ghosting is a modern way to describe being ignored. Acts of ghosting include not picking up calls, reading messages and not replying or responding coolly. Some people ghost by blocking phone numbers or social media accounts. The term ghosting is apt because the person soon becomes a ghost in your life. While many articles have been written against ghosting, it is sometimes necessary to ghost and even more necessary to accept being ghosted. Sometimes, there are simply no words Oftentimes, we tend to over-communicate. We have the same conversations and arguments over and over again, no one listens to the other person and nobody changes. Instead of going through this rigorous and toxic cycle, just ghost. Ghosting is clear communication. Most people who are against ghosting are always talking about how it traumatizes them, the fact is it is not the ghosting that hurts but the rejection. Feeling bad about being ghosted is often an attempt to get them to tell us what we did wrong or said - hmm that sounds like closure and we all know closure is a scam. Why don't you simply accept that they don't want you anymore? You might invalidate their feelings. So, imagine they tell you what you did to you or how they feel and you invalidate their feelings by defending yourself, giving them reasons why they should not think that way or even begging them to stay with you, they would rather just go away gently without drama. Yes, ghosting hurts and can leave many unsaid questions in your mind but take their actions for what it is, a rejection and move on. You don't need to know why, just know they don't want you. Also, if you don't want to be manipulated and gaslighted to stay in a relationship you are tired of, by all means, ghost them for your peace of mind.",
    comments: [],
  },
  {
    id: 1509,
    title: "5 tips for a steamy sexting session with your lover",
    type: "Romance",
    time: "Oct 06",
    author: "LuvlyGist",
    img: "https://static.netnaija.com/i/90ZNPPrRN8e.jpg",
    body: "Sexting is a skill, and not everyone is very good at it. That's why we are here to give some pointers. A guide to sexting [Good divas] Many reasons can make you and your partner sext each other. Long distance or good old fun can cause couples to resort to sexting. Sexting also spices up a relationship because it is adventurous. Sexting is sending sexual messages to your partner that are sometimes accompanied by pictures. Although, if you are not married to the person, sexting is always a risk because you might see details of your conversation online. Anyways, here are some tips; 1. Be graphic - You don't want to start texting like a novelist saying things like, 'the room was dark, the AC was blowing cold air.' No, get into the nitty gritty of it immediately. 2. Say what you want to do - An easy way to get around sexting is to think of what you want to do and type it out. No matter how wild and crazy it might seem. Of course, be respectful. 3. Incorporate your fantasies - This is the time to be wild because you are not really doing and you may not even have to. What have you always wanted to try? Sex in a room full of mirrors, an elevator or on the beach, paint the scenario and sext away. 4. Use words that trigger emotions - Some trigger words will spark interest immediately. Words like 'fuck', 'fucking', 'sucking' and so on are trigger words. 5. Give compliments - You can never run out of ideas if you are generous with compliments. Reminisce on past sexual encounters. 'I loved it when you...' 'I love how you...' The time you did so and so really blew my mind. Humans respond well to praise and it will set the ball rolling.",
    comments: [],
  },
  {
    id: 1510,
    title:
      "Why ladies prefer dating married men - Relationship expert, Joro Olumofin",
    type: "Romance",
    time: "Oct 04",
    author: "Same Emmanuel",
    img: "https://static.netnaija.com/i/PrO7OYXANyp.webp",
    body: "Nigerian relationship expert, Joro Olumofin has revealed why ladies prefer being a side chick to married men. Joro Olumofin made the reasons known on his Instagram story, saying that married men are more committed and generous compared to bachelors. According to him, married men are more mature, and willing to sponsor their side chick's business. He added that they are more likely to engage them in prolific conversations and even promise them a long-time commitment, unlike most bachelors whose intention only is to bankrupt their girlfriends, at the same time ask her for sex all the time. Olumofin urged single men to step up their game 'because lots of single ladies would rather be a side chick to a married man, then the main girlfriend to a Bachelor.' He wrote, 'Quite funny, but married men promise commitment and marriage more than single guys, and a married man is more generous, caring, and mature'. 'Married men will always support their girlfriend's business and also engage their girlfriends in prolific conversation' 'Married men sponsor vacation that doesn't require a lady to spend her money' He added, 'Meanwhile, most single guys are only interested in 24 hours of sex, clubbing, and asking their girlfriends for occasional loans.'",
    comments: [],
  },
  {
    id: 1511,
    title: "How To Stop Fighting With Your Partner",
    type: "Romance",
    time: "Sep 09",
    author: "Same Emmanuel",
    img: "https://static.netnaija.com/i/XV5KvxQZa9m.jpg",
    body: "Are you tired of complaining about the same things I've rand over again? Tired of ruining your family dinners and parties because your significant other decided to be an ass? Maybe you should try these tactics to help you stop getting into arguments. Start with your faults. Recurring arguments form a pattern. It's easy to dwell on your partner's faults and not recognize how distant you've become. Before you start pointing fingers, ask yourself if you've been fair and just all the time. More often that not, you'lol find that you have some adjusting to do. These faults will help you understand your partner's perspective better. Create boundaries for arguments. The difference between arguments that end a relationship and those that make it better are safe, healthy boundaries. No matter how angry you are, there are some things that you shouldn't do. For example, you shouldn't hit your partner or bring up particularly sensitive topics. Talk to your partner about creating boundaries within arguments, like keeping your family out of it, banging doors, breaking plates etc. Don't be on the defensive While you hash it out with your partner, allow room for vulnerability. Don't be afraid to admit that you were wrong about a notion you had before the argument. Always staying on the defensive and projecting yourself as never entirely wrong won't help your relationship grow. Check if you're transferring aggression Before walking up to your partner, review your day and fish for any triggers that may have made you angry. Many times, you're not actually angry at them, you just had a rough day at work. Be careful with your phrasing and tone. Maybe it's not what you're saying, but how you're saying it. If you still value your partner, try to correct them in a constructive tone, not a condescending one.",
    comments: [],
  },
  {
    id: 1512,
    title: "How to Break The Ice After An Argument",
    type: "Romance",
    time: "Sep 13",
    author: "Same Emmanuel",
    img: "https://static.netnaija.com/i/mr9KY4kLNq6.jpg",
    body: "Arguments happen, and they don't always end well. Sometimes, you still don't feel good after talking and letting out all that anger. That's where the ice comes in. healthy silences can help you reassess your feelings and replay the last few days' events. During this period of reflection, you may decide that despite your former disposition, your partner was right. You want to get back with them, but they're still in the cold shoulder phase. How do you break the ice after an argument? A cute epistle Honesty always wins. If you don't know what to say, just tell them everything. Write a cute epistle about how much you miss them, want them back, and can't stop thinking about them. Remember to add that you're ready to do better than just good enough. Try somewhere you're familiar with Maybe what you both need isn't time apart, but time together in a different environment. However, because new environments can cause some tension, try a fairly familiar place. For example, try a new hike location if you've been on a hike before, try a new hike location. Make them their favorite breakfast There's no underestimating how an argument can ruin a day, in extreme cases, even weeks. You can make up for that by making them breakfast. This is a sign that you're ready to extend the olive branch and bridge the gap. You may start a conversation over breakfast, but don't force it. Send their favorite snack to them at work Sending a package across has its appeal. It puts in a good word for you when you're nowhere near, and will have your special person thinking of you all day. Don't forget to add a cute note that expresses just how you feel at that moment.",
    comments: [],
  },
  {
    id: 1513,
    title:
      "I Love Him But This Embarrassing Thing Happens Whenever We Have S*x - Nigerian Lady",
    type: "Romance",
    time: "Mar 13, 2017",
    author: "Olaniran Sodiq Adeniyi",
    img: "https://img.netnaija.com/hsi/aHR0cDovL3d3dy50b3JpLm5nL3VzZXJmaWxlcy9pbWFnZS8yMDE3L21hci8xMy9jdW0lMjBzZXguSlBH/images/cum%20sex.JPG",
    body: "A lady whose boyfriend has refused to c*m during several s*x romps has cried out to a relationship adviser and blogger, Joro Olumofin. The confused lady has adopted several tactics in the other room but all to no avail. She is currently feeling like a failure amid suggestions that her lover must have taken some conk s*xual herbs like some men do.",
    comments: [],
  },
  {
    id: 1514,
    title:
      "Nurse screams in joy as her soldier lover shows up unannounced at her workplace, gifts her flowers (Video)",
    type: "Romance",
    time: "Sep 29",
    author: "Moses O",
    img: "https://static.netnaija.com/i/yMX7y62Xa83.webp",
    body: "A heartwarming video making rounds online shows the moment a soldier surprised his lover at her workplace. The soldier showed up at his wife's workplace unannounced alongside another soldier who accompanied him. They both stood by the door as nurses proceeded to call out the soldier's lover. As soon as she stepped into the place and saw her soldier lover, she screamed and hugged him tightly. The soldier has won the hearts of many people with his romantic gesture as he presented her beautiful flowers and kissed her.",
    comments: [],
  },
  {
    id: 1515,
    title: "How To Spot Quiet Quitting In Relationships",
    type: "Romance",
    time: "Sep 07",
    author: "Same Emmanuel",
    img: "https://static.netnaija.com/i/Aq2NAdE6azJ.jpg",
    body: "Having someone to do life with definitely slaps, but is your partner only physically present while their heart and mind is long gone? Is your partner just waiting for a valid reason to break up with you? Here's your one-stop guide to spotting quiet quitting in relationships early. WHAT IS QUIET QUITTING? Quiet quitting is the new buzz word for Emotional or Romantic Disengagement. It started out as a typical workplace behavior: do what's necessary, nothing less, nothing more. In a romantic relationship, this pans out as always giving the barest minimum. Quiet quitting sometimes looks like complacency;you think your partner feels safe and somewhat stable, and your relationship hardly has any ups or downs. Meanwhile they're mentally done with the relationship, but can't bring themselves to tell you. HOW DO I SPOT IT? How do you differentiate quiet quitting from a plateau in your relationship? These tips will tell you when to call for a red table talk. They hardly ask questions, and they don't give answers either. Basically, they're not interested in sharing any details of their day. They may go ahead and answer because they think you have a right to know, but left to them, it's none of your business. No physical touch. Every relationship has its downtimes and communication may not be as good as before, but if you can't remember your partner's touch, it's time to pound the alarm. They're spending less and less time around you. These days you have to go the extra mile to see them, and they don't seem to mind when something steals your 'us-time'. They seem far away even when they're near. There are a number of reasons why your partner seems inattentive. You can go ahead and ask if they have a lot on their mind, and if they want to share with you. As we've established, quiet quitters don't like to divulge information. If you feel your partner slipping away, you can try to talk to them. Sometimes, there's an underlying reason for quiet quitting.",
    comments: [],
  },
  {
    id: 1516,
    title: "Couple ties the knot in Lagos hospital despite health setbacks",
    type: "Romance",
    time: "Sep 23",
    author: "Moses O",
    img: "https://static.netnaija.com/i/PrO7OYnZNyp.webp",
    body: "An adorable couple has earned a spot on the Nigerian trends table after getting married in a Lagos hospital. The couple got married at Evercare Hospital in Lekki, Lagos state, and photos from their wedding ceremony were shared on the hospital's Twitter account. The hospital congratulated the newlywed couple and wished them eternal love and marital bliss. The medical facility also revealed that it is the first wedding to ever take place in the hospital. Photos shared online showed the groom who is down with an undisclosed ailment, lying on the hospital bed with his bride by his side, and also participating in the wedding with his bride while sitting in a wheelchair. The hospital tweeted; 'We had our very FIRST Evercare wedding'.'Congrats to the newlywed couple on this milestone event and we wish them eternal love and marital bliss'.",
    comments: [],
  },
];
