export const sportsData = [
  {
    id: 1701,
    title:
      "Ballon d'Or 2022: It wasn't easy - Benzema breaks silence after winning award",
    type: "Sports",
    time: "5 hours ago",
    author: "Moses O",
    img: "https://static.netnaija.com/i/1xYNeM9wNLJ.jpg",
    body: "Real Madrid's, Karim Benzema was on Monday night announced as the winner of this year's Ballon d'Or award. The Frenchman admitted his career hasn't always been easy after winning the prize for the first time. Benzema also became the oldest player ever at 34 to win the Ballon d'Or. 'I always had this dream in my mind that everything's possible. 'There was a difficult period where I wasn't in the French team but I worked hard and never gave up, kept my head down and enjoyed playing football. 'People play until their later years now and I still have this burning desire. 'It is this drive that has kept me going and never allowed me to let up. I just want to make the most of it,' Benzema said. Benzema netted 44 times in 46 appearances as Los Blancos lifted both the LaLiga title and Champions League trophy.",
    comments: [],
  },
  {
    id: 1702,
    title:
      "Ballon d'Or 2022: Mourinho reveals why it took long before Benzema finally won award",
    type: "Sports",
    time: "5 hours ago",
    author: "Moses O",
    img: "https://static.netnaija.com/i/wnRaMDQg7dq.jpg",
    body: "Roma manager, Jose Mourinho has claimed Karim Benzema did not win the Ballon d'Or award all these years, because he is 'obsessed with his team'. The Real Madrid captain was announced the winner of this year's prize at 34 years. Benzema led Los Blancos to LaLiga and the Champions League glory. Mourinho managed Benzema during his three years at the Santiago Bernabeu, when Cristiano Ronaldo was the team's main man. It was only after Ronaldo left that Benzema assumed the mantle of being Madrid's leading light. 'Karim is a great character, great personality, and a team guy. 'He is not obsessed with himself, he is not obsessed with the Ballon d'Or, he is not a guy obsessed with scoring more goals than A, B or C. 'He is just a team guy who does a lot in a way that the Ballon d'Or becomes a natural consequence. I think he is a guy obsessed with his team,' Mourinho said in a recorded tribute.",
    comments: [],
  },
  {
    id: 1703,
    title:
      "EPL: You're disrespecting Ronaldo, I don't agree with your management - Saha slams Ten Hag",
    type: "Sports",
    time: "5 hours ago",
    author: "Moses O",
    img: "https://static.netnaija.com/i/eDxawxLgNPZ.jpg",
    body: "Manchester United's former striker, Louis Saha has told manager, Erik ten Hag he is 'disrespecting' Cristiano Ronaldo at the club. This was after the veteran forward was replaced during United's Sunday's game against Newcastle United. Ronaldo led the line for the Red Devils at Old Trafford and after seeing two efforts ruled out, the Portuguese was replaced by Marcus Rashford with 18 minutes left on the clock. He was muttering and shaking his head in irritation as he left the pitch and Saha questioned ten Hag's decision to pull out a known goal getter, insisting there is no one better than him when you are under pressure to score. Saha is convinced the former Real Madrid star has not declined in any way, adding there is 'no indication' he is slowing down. 'Ronaldo has been disrespected,' Saha told Boyle Sports. 'I have not fully agreed with the management of Ten Hag. 'I can understand why Ronaldo was upset after the Newcastle game because he trusts himself to score, lately, he has not been as lucky and efficient, it happens, and people need to realise he is not a robot. 'When people are tired, Ronaldo is a killer, there is no one better than him when you are under pressure to score important goals, he did it last year and there is no reason for him not to continue that this season. 'I have not seen any indication physically that shows he's slowing down.'",
    comments: [],
  },
  {
    id: 1704,
    title: "I am still here - Lewandowski warns Haaland over Golden Ball award",
    type: "Sports",
    time: "6 hours ago",
    author: "Moses O",
    img: "https://static.netnaija.com/i/x5PKDXzYKnM.jpg",
    body: "Barcelona striker, Robert Lewandowski has warned the new generation of strikers, including Manchester City's Erling Haaland, that he is 'still here'. Lewandowski stated this while collecting his Gerd Muller Trophy at the Ballon d'Or awards on Monday. The Poland international was warned by Didier Drogba of a 'kid' at Manchester City who is 'on fire' - a reference to Haaland. In response, Lewandowski said: 'The season is very long, and I know for me it's also a new chapter with Barcelona. 'Since the first days, I'm feeling very well in this club.' The 34-year-old added: 'From the first minutes, I see that with my team-mates we have big potential and I have the opportunity to score a lot of goals. 'I am sure that all together we are working on this.'",
    comments: [],
  },
  {
    id: 1705,
    title: "Ballon d'Or 2022: Six players who received zero vote revealed",
    type: "Sports",
    time: "Yesterday 10:11pm",
    author: "Moses O",
    img: "https://static.netnaija.com/i/Gem7Q8nJKYx.webp",
    body: "At least six players received no votes for this year's Ballon d'Or award. Liverpool striker, Darwin Nunez, finished in joint 25th place in the rankings confirmed on Monday by the organizers, France Football. The Uruguayan, who moved from Benfica this summer for £85million, didn't receive any votes in the final rankings, with five other players also falling into that category. Manchester City defender, Joao Cancelo, also didn't get any votes despite winning the Premier League title. Another player who finished in that position was Bayern Munich midfielder Joshua Kimmich, along with RB Leipzig's Christopher Nkunku, who has been linked with a move to Chelsea, and AC Milan goalkeeper Mike Maignan.",
    comments: [],
  },
  {
    id: 1706,
    title:
      "Ballon d'Or 2022: Benzema announced winner ahead of Mane, De Bruyne",
    type: "Sports",
    time: "Yesterday 9:48pm",
    author: "Moses O",
    img: "https://static.netnaija.com/i/90ZNPPYMN8e.jpg",
    body: "Real Madrid captain, Karim Benzema, has won this year's Ballon d'Or award. The Frenchman has won it after a spectacular season up-front for Real Madrid, spearheading their attack as they won LaLiga and the Champions League in 2022. Benzema was also crowned as the Champions League top scorer, La Liga top scorer and UEFA Player of the Year. The award was presented by former Real Madrid manager, Zinedine Zidane, at the Theatre du Chatelet in Paris, France. Bayern Munich's Sadio Mane came second behind Benzema. Manchester City's Kevin De Bruyne came third and Robert Lewandowski came fourth.",
    comments: [],
  },
  {
    id: 1707,
    title: "EPL: Mane reacts to Liverpool's 1-0 win over Man City",
    type: "Sports",
    time: "Yesterday 9:47pm",
    author: "Moses O",
    img: "https://static.netnaija.com/i/eDxawwo2aPZ.webp",
    body: "Bayern Munich forward, Sadio Mane, has reacted to Liverpool's Premier League 1-0 win over Manchester City on Sunday. Mane, who left Liverpool to join Bayern Munich during the summer transfer window, said he was happy that Jurgen Klopp's side defeated Man City at Anfield. Liverpool defeated Pep Guardiola's side following Mohamed Salah's second-half goal. Reacting, Mane told BILD, 'I'm very happy for the boys that they beat City. 'I couldn't watch because we were on the bus. 'I have a lot of faith in the boys and the coach that they will get back to the top!' Mane spent six years with Liverpool, scoring 120 goals and registering 48 assists in 269 appearances for the English club.",
    comments: [],
  },
  {
    id: 1708,
    title: "Ballon d'Or 2022: PSG forward, Kylian Mbappe booed at ceremony",
    type: "Sports",
    time: "Yesterday 9:46pm",
    author: "Moses O",
    img: "https://static.netnaija.com/i/8yZaJdpYKJ0.webp",
    body: "Paris Saint-Germain forward, Kylian Mbappe, was booed as he arrived at the Ballon d'Or ceremony on Monday. Jeers could be heard as Mbappe walked the red carpet along with his father. The ceremony was staged at the Theatre du Chatelet in Paris and it seems local fans were not too happy to see the PSG star. Mbappe's future with the Ligue 1 champions seems uncertain amid continued speculation about a possible exit. However, the France international has denied 'completely false' reports that he has asked to leave in the January transfer window. It had been previously rumoured Mbappe wanted to sever his ties with the club, despite only signing a new contract in the summer, after seeing working relationships break down.",
    comments: [],
  },
  {
    id: 1709,
    title: "Ballon d'Or: Oshoala ranked 16th best in the world",
    type: "Sports",
    time: "Yesterday 9:46pm",
    author: "Moses O",
    img: "https://static.netnaija.com/i/zxG7ZYxjKq2.webp",
    body: "Super Falcons forward, Asisat Oshoala, finished in 16th position in the 2022 women's Ballon d'Or. The award ceremony took place in Paris, France on Monday night. Oshoala was the only African rated in the Top 20. Her Barcelona teammate, Alexia Putelas won the award. It was a back-to-back win for Putelas, the main star in the Barcelona Femeni team. Oshoala has won a record five CAF Player of the Year awards. Senegal and Bayern Munich forward, Sadio Mane scooped the inaugural Socrates Humanitarian Award for his philanthropic work in his village.",
    comments: [],
  },
  {
    id: 1710,
    title:
      "LaLiga: What El Clasico 3-1 defeat to Real Madrid mean for Barcelona - Lewandowski",
    type: "Sports",
    time: "Yesterday 9:45pm",
    author: "Moses O",
    img: "https://static.netnaija.com/i/1xYNeMeANLJ.webp",
    body: "Barcelona striker, Robert Lewandowski, has said that his team's LaLiga El Clasico defeat to Real Madrid will only make the Blaugrana work harder going forward. Lewandowski was unable to save Barcelona as Real Madrid won 3-1 in Sunday's El Clasico at the Santiago Bernabeu. Karim Benzema, Federico Valverde, and Rodrygo scored the goals for Real Madrid against Xavi's side. Ferran Torres did score a goal for the visitors against Carlo Ancelotti's side. In a post via his Instagram account, Lewandowski also admitted that the latest defeat hurt Barcelona. The Polish attacker said, 'Today hurts, but it makes us work harder tomorrow. @fcbarcelona.'",
    comments: [],
  },
  {
    id: 1711,
    title: "EPL: Idiot player - Enrique slams Man City midfielder",
    type: "Sports",
    time: "Yesterday 9:44pm",
    author: "Moses O",
    img: "https://static.netnaija.com/i/wnRaMDRX7dq.webp",
    body: "Former Liverpool defender, Jose Enrique, has hit out at Manchester City midfielder Bernardo Silva for being a sore loser following his team's Premier League 1-0 defeat against the Reds at Anfield on Sunday. Liverpool defeated Man City, thanks to Mohamed Salah's second-half goal as Phil Foden's goal was disallowed by the referee during the tie. However, Silva was visibly irked about Foden's disallowed goal during his post-match interview. Speaking to Sky Sports, the Portugal international said: 'What we expect from the referees is consistency in the decisions. When you go through a path of not whistling little contacts throughout the whole game, you need to keep those decisions and keep going that way. If you want to whistle all of them, whistle all of them.' But in a tweet via his Twitter handle, Enrique labelled Silva as an idiot player, adding that he doesn't know how to lose. He tweeted, 'Bernardo Silva is one of the most idiots players in the game, seriously. He doesn't know how to lose.'",
    comments: [],
  },
  {
    id: 1712,
    title: "Ballon d'Or 2022: Ronaldo finishes in 20th position",
    type: "Sports",
    time: "Yesterday 9:44pm",
    author: "Moses O",
    img: "https://static.netnaija.com/i/x5PKDXg3KnM.webp",
    body: "Manchester United forward, Cristiano Ronaldo, has finished 20th in this year's Ballon d'Or race. This was confirmed on Monday by the organizers of the award, France Football. It is Ronaldo's worst ranking since he finished 20th in 2005 - level with Jamie Carragher. The 37-year-old, however, finishes ahead of Harry Kane, who's 21st. Ronaldo has won the Ballon d'Or five times already in his career. He is only behind arch-rival Lionel Messi who has taken home the prize seven times. The Portugal captain has endured a miserable start to the campaign with United, as he now starts most games from the bench. He has only scored twice so far, against Sheriff in the Europa League and Everton in the Premier League.",
    comments: [],
  },
  {
    id: 1713,
    title:
      "EPL: I'm really sorry - Jurgen Klopp apologises to Pep Guardiola after Man City defeat",
    type: "Sports",
    time: "Yesterday 3:23pm",
    author: "Moses O",
    img: "https://static.netnaija.com/i/PrO7Oe1bNyp.jpg",
    body: "Liverpool boss, Jurgen Klopp has issued an apology to Pep Guardiola after the Manchester City manager claimed that he had coins thrown at him by Red Devils' supporters at Anfield. Liverpool are currently investigating the incident, vowing to ban for life any fan found culpable for the offence. Told about what his counterpart claimed to have experienced at Anfield, Klopp said: 'Oh, horrible. I am sorry. I apologise for that. 'I had no idea about it. It never should happen, never,' he added. Mohamed Salah scored the only goal of the match to give the home side all three points in the highly entertaining football match. Manchester City, who fell to their first defeat of the season, remain second in the Premier League table but are now four points behind league leaders, Arsenal.",
    comments: [],
  },
  {
    id: 1714,
    title:
      "Barcelona president, Laporta sent out of referees' dressing room after Real Madrid defeat",
    type: "Sports",
    time: "Yesterday 12:54pm",
    author: "Moses O",
    img: "https://static.netnaija.com/i/PrO7OMyANyp.jpg",
    body: "Barcelona president, Joan Laporta, confronted match officials following their 3-1 defeat to Real Madrid on Sunday. Los Blancos moved three points clear of rivals Barca after the El Clasico at the Santiago Bernabeu. Rodrygo's 91st-minute penalty sealed the win for Madrid in controversial fashion, as referee Sanchez Martinez was urged to check the VAR pitch-side monitor before awarding the spot kick. Earlier on in the match, Martinez ignored a similar penalty claim from Robert Lewandowski. Laporta was unhappy with the officials and confronted them directly post-match. The referee's match report revealed that the Barca president came into their dressing room and 'repeatedly requesting explanations about some situations in the match'. Laporta was then 'invited to leave without further incident'.",
    comments: [],
  },
  {
    id: 1715,
    title:
      "Ligue 1: I'm not involved directly or indirectly - Mbappe breaks silence on 'leaving' PSG",
    type: "Sports",
    time: "Yesterday 12:50pm",
    author: "Moses O",
    img: "https://static.netnaija.com/i/mjyK6bgLKwD.jpg",
    body: "Paris Saint-Germain forward, Kylian Mbappe has denied that he wants to quit the club in January. According to the 24-year-old, he was surprised by the news. 'I never asked for my departure in January. 'The information that came out on the day of the [Champions League match against Benfica], I did not understand it. I am not involved in this information neither directly nor indirectly,' Mbappe told reporters after PSG's 1-0 win over Marseille in Ligue 1 on Sunday. It was claimed Mbappe felt 'betrayed' by PSG president Nasser Al-Khelaifi and wanted to leave the Ligue 1 champions as soon as possible. 'I was as shocked by this news as everyone else. People may think I'm involved, I'm not at all. 'I was taking a nap, my entourage was at my little brother's game. We were stunned when we found out. 'Afterwards, we had to deal with it, we had a match to play. I just wanted to say that it's completely false, I'm very happy here,' Mbappe added.",
    comments: [],
  },
  {
    id: 1716,
    title: "EPL: Why I only substituted Ronaldo for Rashford - Ten Hag",
    type: "Sports",
    time: "Yesterday 12:06am",
    author: "Moses O",
    img: "https://static.netnaija.com/i/W4lNmlRwaRo.jpg",
    body: "Erik ten Hag has explained his decision to substitute only Cristiano Ronaldo for Marcus Rashford in Sunday's goalless draw at home to Newcastle. In his words, most of his players were not available. Key players such as Christian Eriksen and Anthony Martial were missing from the matchday squad due to illness and fitness issues. Ten Hag made just one change which was taking off Ronaldo fo Rashford as United chased the winner. The former Ajax boss was asked why he opted for just one sub, and he told reporters, 'Exactly. Some players were not available, as you know, today. Christian Eriksen not available, Anthony Martial not available, Scott McTominay not available. 'So that was the feeling I had. I brought freshness with Rashy, I think he had an impact. If he scored that goal then you do everything right.' It was Manchester United's first draw of the season, having lost three Premier League matches and won six before today. The Red Devils heaviest defeat came in the hands of Brentford and Manchester City earlier in the season.",
    comments: [],
  },
];
