export const wrestlingData = [
  {
    id: 2301,
    title: "WWE Raw",
    type: "Pro Wrestling",
    time: "May 27",
    img: "https://static.netnaija.com/i/1qdNVO2RK4g.jpg",
    body: "The superstars of World Wrestling Entertainment's 'RAW' brand collide each and every week on WWE Monday Night. For more than 25 years and well over 1000 episodes, Raw has been WWE's flagship show. Its memorable moments have thrilled the WWE Universe and earned it the distinct honor of being the longest-running episodic television show in history.",
    genre: "Action, Sport",
    imdb: "https://www.imdb.com/title/tt0185103/",
    premiere: "Jan 11, 1993 (United States)",
    comments: [],
  },
  {
    id: 2302,
    title: "WWE SmackDown!",
    type: "Pro Wrestling",
    time: "May 28",
    img: "https://static.netnaija.com/i/bvWaqLEg7rk.jpg",
    body: "Superstars of World Wrestling Entertainment do battle in elaborate, long-running rivalries in a weekly two-hour showdown. For more than 20 years and with more than 1,000 episodes, SmackDown has showcased WWE's top Superstars and created countless memorable moments.",
    genre: "Action, Sports",
    imdb: " https://www.imdb.com/title/tt0227972/",
    premiere: "Apr 27, 1999 (United States)",
    comments: [],
  },
  {
    id: 2303,
    title: "WWE NXT",
    type: "Pro Wrestling",
    time: "Aug 05",
    img: "https://static.netnaija.com/i/Aq2NA5o5NzJ.jpg",
    body: "WWE NXT features the next generation of Superstars battling to make an impact.Wrestlers will portray heroes or villains as they follow a series of events that build tension and culminate in a wrestling match or series of matches.",
    genre: "Action, Sport",
    imdb: "https://www.imdb.com/title/tt1601141/",
    premiere: "Feb 23, 2010 (United States)",
    comments: [],
  },
  {
    id: 2304,
    title: "WWE Extreme Rules (2022)",
    type: "Pro Wrestling",
    time: "Oct 09",
    img: "https://static.netnaija.com/i/1xYNeMDqNLJ.jpg",
    body: "The 2022 Extreme Rules is the 14th annual Extreme Rules professional wrestling pay-per-view and live-streaming event produced by WWE. It will be held for wrestlers from the promotion's Raw and SmackDown brand divisions. This years event took place in Philadelphia, Pennsylvania.",
    genre: "Action, Sport",
    imdb: "https://www.imdb.com/title/tt21048288/",
    premiere: "Oct 8, 2022 (United Status)",
    comments: [],
  },
  {
    id: 2305,
    title: "WWE Clash at the Castle (2022)",
    type: "Pro Wrestling",
    time: "Sep 05",
    img: "https://static.netnaija.com/i/3g8NBdMy7DR.jpg",
    body: "Roman Reigns and Drew McIntyre clash for the Undisputed WWE Universal Championship at the biggest WWE event in United Kingdom history. Liv Morgan battles Shayna Baszler for the SmackDown Women's Championship. Raw Women's Champion Bianca Belair, Alexa Bliss & Asuka face Bayley, Dakota Kai & IYO SKY.",
    genre: "Action, Sport",
    imdb: "https://www.imdb.com/title/tt19870404/",
    premiere: "Sep 3, 2022 (United Kingdom)",
    comments: [],
  },
  {
    id: 2306,
    title: "WWE SummerSlam (2022)",
    type: "Pro Wrestling",
    time: "Jul 31",
    img: "https://static.netnaija.com/i/Wz27W5GnN5R.jpg",
    body: "The 2022 SummerSlam was the 35th annual SummerSlam professional wrestling event produced by WWE. It was held for wrestlers from the promotion's Raw and SmackDown brand divisions. The event aired on pay-per-view (PPV) worldwide and was available to livestream through Peacock in the United States and the WWE Network internationally. SummerSlam took place on Saturday, July 30, 2022, at Nissan Stadium in Nashville, Tennessee, and it was the first SummerSlam to not be held during the month of August. This was also the first WWE PPV event following the retirement of WWE owner Vince McMahon, who had served as Chairman and Chief Executive Officer of the company since 1982.",
    genre: "Action, Sport",
    imdb: "https://www.imdb.com/title/tt15766852/",
    premiere: "Jul 30, 2022 (United States)",
    comments: [],
  },
  {
    id: 2307,
    title: "WWE Money In The Bank (2022)",
    type: "Pro Wrestling",
    time: "Jul 03",
    img: "https://static.netnaija.com/i/wk37llDe7Pd.jpg",
    body: "The 2022 Money in the Bank is the 13th annual Money in the Bank professional wrestling live event produced by WWE. It took place on Saturday, July 2, 2022, at the MGM Grand Garden Arena in the Las Vegas suburb of Paradise, Nevada.",
    genre: "Action, Drama, Sport",
    imdb: "https://www.imdb.com/title/tt15766816/",
    premiere: "Jul 2, 2022 (United Ststes)",
    comments: [],
  },
  {
    id: 2308,
    title: "WWE Hell in a Cell (2022)",
    type: "Pro Wrestling",
    time: "Jun 06",
    img: "https://static.netnaija.com/i/3g8NBYRVaDR.jpg",
    body: "The 2022 Hell in a Cell was the 14th annual Hell in a Cell professional wrestling live event produced by WWE. It was held for wrestlers from the promotion's Raw and SmackDown brand divisions.",
    genre: "Action, Drama",
    imdb: "https://www.imdb.com/title/tt18938676/",
    premiere: "Jun 5, 2022 (United States)",
    comments: [],
  },
];
