export const fashionData = [
  {
    id: 4501,
    title: "What Colour Looks Best On Me?",
    type: "Fashion",
    time: "Aug 22",
    author: "Same Emmanuel",
    img: "https://static.netnaija.com/i/G4E7z6Wv7b6.jpg",
    body: "You may ask, what colour looks best on me? Figuring out the colour that suits your skin can be difficult as it is easy to assume your colours based on what suits the people around you or what you prefer. Since most people tend to ignore the importance of finding the colour that flatters their skin, identifying the colour that suits you is tough. Your skin colour is determined by the amount of melanin in your skin, exposure to the sun, genetics, and atmospheric conditions, although the most prominent is the pigment 'melanin'. The people around you might have more or less melanin than you do, hence, producing multiple skin tones. The fact that a colour suits your sibling's skin do not ensure that it will suit yours. This is why you should discover that colour, the colour that makes you feel like it is made for you. Like finding the best hairstyle that suits your face, finding the perfect colour that flatters your skin is tricky. To determine the colour that best suits your skin, you should be aware of these factors: first, your skin tone, and second, your skin shade.",
    comments: [],
  },
  {
    id: 4502,
    title: "Fifty Shades Of Grey: How To Make A Grey Statement",
    type: "Fashion",
    time: "Aug 08",
    author: "Same Emmanuel",
    img: "https://static.netnaija.com/i/bvoKdmw67rx.jpg",
    body: "So let's rail off Christian Grey for a second. There are over 500 shades of grey identifiable by the human eye and they can make for a fashion statement when done right. When you think grey, you would almost always think of office suits and sweat pants. A seemingly unattractive and conservative colour with a bland taste. If world history had a colour, it would probably be grey. Industrialisation and war, the palette of Picasso's Guernica and Whistler's grim landscapes. It has also been the colour associated with worker bees in every economic phase. Whether it was the grisettes, factory girls dressed in grey in 19th century Paris; the quintessential 'man in a grey flannel suit' from 1950s America, slogging every day to get his family and the country out of the Great Depression; or one of the multitudes of software fellas in grey t-shirts and tracks somewhere in the world - the colour grey has belonged to the worker that drives the economic engine of the moment. The colour was made popular, the Nobel Westerner in the 18th century both for men and women. It was also a popular colour, almost Monks and Nuns. However, Grey, which is a common neutral colour, provides a softer alternative to black and is actually easier to wear.Ever heard of the 'groutfit'? That's a grey outfit, the sheer volume of cloudy, skate-coloured, head-to-toe looks. Fashion designers and street styles have elevated the concrete tones out of its thought boring realm. Ariana Grande in a grey Giambattista Vaill ball dress for the 2020 Grammy award show was a glam take on the thought flat colour. It's all about texture and tones.",
    comments: [],
  },
  {
    id: 4503,
    title: "7 Expert Tips To Care For Your Bags",
    type: "Fashion",
    time: "Aug 08",
    author: "Same Emmanuel",
    img: "https://static.netnaija.com/i/eDxawd0pNPZ.jpg",
    body: "Accessories pull every outfit together, and they need extra level of care especially your jewlery, bags and shoes. Your bags deserve some tender loving care away from the scratches, wrinkles and stains that begins to destroy them. Leaving these wrinkles and stain on your bags would cause them to slowly decline until they eventually become bad. Granted, everyone forgets to take care of their bags once in a while, and the pain that comes with seeing your favourite bag become a ghost of itself hurts even worse. So how do you keep your bag in prime condition for long? By following expert tips on how to care for, and store your bags. Stop hanging them As tempting as hanging your bag over a doorknob or hook sounds, it's one of the worst ways to store your bags. This is because handing your b ags by the handle could strain them and also distort the bag's material. Instead stand it upright on a shelf. Keep away from light Letting your handbag sit under sunlight could cause damage, and discolouration. Instead keep away from direct sunlight and low humidity to prevent mold. Dust bags are goated. Every baddie needs dust bags to keep their bags in proper prime condition everytime. They're also pretty affordable, so you save some coins on a new bag by only spending a few on dustbags.",
    comments: [],
  },
  {
    id: 4504,
    title: "Styling Blazers Made Easy For Ladies",
    type: "Fashion",
    time: "Jun 06",
    author: "Same Emmanuel",
    img: "https://static.netnaija.com/i/eDxawW6paPZ.jpg",
    body: "A lady's wardrobe would be incomplete without a blazer. When it comes to highlighting a clothing staple of the fashion industry, the blazer is without a doubt the winner, owing to its versatility and ability to have a 'Chic' effect on its wearer. Be it casual or formal, blazers can be worn for a variety of occasions and are often a good way to elevate the styling of an entire outfit. In honor of one of fashion's greatest inventions, here are some ways to wear a blazer. Blazer, t-shirt and jeans. Even though it appears to be a simple combination, many ladies get it wrong. Sometimes styling a blazer can be tricky because you want to look good without going overboard. This is why it's best for you to opt for a fitted blazer. A fitted blazer doesn't just accentuate your body figure but provides a great opportunity to explore different combos. So you could wear a black fitted blazer, blue jeans, and a white tee shirt. And if you think this is too cliche, a pinstripe blazer over an off-white tee and black jeans will give you that regal but mysterious look that will have heads turning.",
    comments: [],
  },
  {
    id: 4505,
    title: "5 Creative Ways To Style A Graphic T-Shirt",
    type: "Fashion",
    time: "May 04",
    author: "Same Emmanuel",
    img: "https://static.netnaija.com/i/G4E7zZj37b6.jpg",
    body: "If there's one piece of clothing that will never fail you, it's a graphic tee. Are you going to see a movie? Hang out with friends? A graphic tee's got you.Better still, just switch up the graphic, and you've made a statement! You could have a graphic t-shirt with your favourite anime character, or you could have one boldly printed with your pronouns. Yes, graphic tees are awesome for representation.However, the best thing about a graphic tee is that it is as dynamic as a plain canvas. Yes, you can wear a plain tee to a fancy event. Here's how: 1. With a blazer and shorts: if you're trying to wear your fav graphic tee to an outdoor event while nailing the cool, laidback look, combine your tee with a high-waisted, preferably loose pair of shorts. Then top it off with an oversized blazer, and you've got yourself a look! The rules say your t-shirt should also be one size bigger than your perfect fit. You get extra points if your blazer and shorts are a matching set. So here you have it; a t-shirt snatched at the waist by high waisted shorts, lots of legs, and an oversized blazer.",
    comments: [],
  },
  {
    id: 4506,
    title: "5 Questions To Ask Before Wearing An Outfit",
    type: "Fashion",
    time: "Mar 18",
    author: "Same Emmanuel",
    img: "https://static.netnaija.com/i/W4lNmBMYKRo.jpg",
    body: "Hold up! Before you wear that shirt, blouse, or dress you have picked out, you need to read this article. When it comes to selecting the perfect outfit, it is inadvisable to make a decision solely based on taste, because there are other important factors to consider. In the spirit of preparing you for the awesome, fun-filled weekend, we listed five questions that would help guide you through the proper selection of what to wear. Does it fit? Fit is everything. And by everything, we mean everything. A blouse or dress looks good on you if it fits your body frame perfectly. So, if you notice a dress fails to flatter your body shape, kindly move to the next choice. Am I comfortable? When you wear a dress, try to measure the amount of comfort you are experiencing. In a situation where discomfort arises, maybe the top is too tight, don't try to 'cope' or adhere to the mantra, 'fashion is pain.' Is it right for the occasion? Like the saying, there is a time for everything, there is also a dress for every occasion. It would be embarrassing for you to attend a wedding party dressed in an outfit that screams, 'Look at me, I'm a certified workaholic.'Do my accessories match the outfit? A mistake you don't want to make is having your outfit symbolize chic, and your accessories embody the definition of cheap. Accessorizing can make or mar an outfit, so pay a great deal of attention to getting them right.",
    comments: [],
  },
  {
    id: 4507,
    title: "5 Ways to Style A Basic Black Dress",
    type: "Fashion",
    time: "Mar 14",
    author: "Same Emmanuel",
    img: "https://static.netnaija.com/i/xM6K5n6W7yE.png",
    body: "A woman's wardrobe is incomplete without a little black dress (or two) sitting pretty in her closet. A great thing about having black dresses is how versatile they are. The LBD can work in different occasions like a Sunday service, red carpet, or a dinner night. Ahead, we rounded up 5 black dress styling ideas that will help you look timeless, fashionable and sophisticated. LBD and a statement accessory Looking for a way to transition your outfit from basic to elevated? Statement accessories are the way to go. Try a statement neckpiece and/or earrings, chic gloves, colourful shoes and bags and your entire outfit will be elevated.",
    comments: [],
  },
  {
    id: 4508,
    title: "4 Tips To Styling Purple",
    type: "Fashion",
    time: "Mar 09",
    author: "Same Emmanuel",
    img: "https://static.netnaija.com/i/PrO7O8zeayp.jpg",
    body: "A new month means a new you, and a new you means taking multiple fashion risks that the old you wouldn't dare to try. One of those fashion risks would be to dump all those cliché colours like black, red, white, and blue, and lean towards a brighter and more beautiful colour like purple. Now, before you quickly dismiss this idea, hear us out. Nothing screams regal, fabulous, and sophistication like purple. Wearing a purple blouse or dress not only improves your appearance but makes you the lady everyone wants to strike a pose with for the camera. Contrary to popular belief, styling purple clothes isn't complex. All you need is the right information, and you are good to walk down the streets proudly while wearing a gorgeous purple outfit. In the spirit of being the amazing fashion mentor we are, we listed four ways for you to style the colour purple. Formal purple Commanding attention in a room becomes a piece of cake when wearing either a purple suit or blazers. It also boosts your confidence when next you pitch an idea to a client or strike a pose for the cover of a magazine.",
    comments: [],
  },
  {
    id: 4509,
    title: "The Best Men's Dress Shirt Colours To Own",
    type: "Fashion",
    time: "Feb 28",
    author: "Same Emmanuel",
    img: "https://static.netnaija.com/i/Gem7QL4EKYx.jpg",
    body: "Whether you work 9-5, freelance you're a tech bro, one wardrobe staple you all have in common is the men's dress shirt. And as easy as these fits look to pull off, choosing the right colour can be tricky. Now while you don't have to be a fashion designer or stylist to pull off a proper dress shirt fit, you should have a little more help with the right colours. So let's figure out some essential yet stylish men's dress shirt colours, why each colour works for you and what to pair them with.White Shirts - An essential clothing staple, white remains the classic go-to colour for men's dress shirts mostly because of its versatility.Also accounting for its popularity is that it matches everything. Regardless of whatever colour of pants, sweaters or shoes you have on, you'll always look sharp with a white shirt. You can pair a white shirt with a blue suit, black suit, white shirt, in fact, whatever colour and combination you can think of.",
    comments: [],
  },
  {
    id: 4510,
    title: "5 Interesting Prints You Should Wear",
    type: "Fashion",
    time: "Feb 26",
    author: "Same Emmanuel",
    img: "https://static.netnaija.com/i/wnRaM8P07dq.jpg",
    body: "Armed with an aura of confidence and clad in a stunning plain blue dress paired with stiletto boots, you walk into a party being thrown by your friends. Upon sighting them, you get ready for compliments. After several hugs and greetings, no one says a word about your outfit. In your mind, you start to wonder what you did wrong. Our best guess would be that your outfit screamed 'Look at me, I'm basic.' And no one finds a basic outfit worth complimenting. Basic doesn't necessarily refer to the style of the dress you are wearing, but the colour. The truth is plain-coloured dresses are becoming cliché and boring, lacking the dramatic flair your appearance desperately needs. So, the best way to receive those compliments and attention is to opt for a dress that has a dramatic and loud element in it... something made from a printed fabric. Print clothes are a staple in every lady's wardrobe. From the popular leopard prints to the stripes, prints are a fashion trend to jump on if you still find yourself playing it safe with plain colours. In this article, we suggest five prints for you to consider.",
    comments: [],
  },
  {
    id: 4511,
    title: "Do You Know What Glass Frames Suit Your Face?",
    type: "Fashion",
    time: "Feb 23",
    author: "Same Emmanuel",
    img: "https://static.netnaija.com/i/LqXNE8p5alE.jpg",
    body: "It's a sunny day, but while you are about to step out, you take one last look at how stunning you appear. Suddenly, you feel your appearance is awkward and you can't seem to figure out why. Viola! Like a light bulb, it's your sunshades that don't suit your oval, round, square, diamond, heart, pear, or oblong face. There are up to seven face shapes, many sunshades and glasses' frames that flatter different face types, accompanied by makeup and hairstyles. Do you know your face shape? If you do, thumbs up to you because it will make shopping for the right shades a lot easier to pick. If you don't know your face shape, this can get confusing because you are in for a hassle while getting a fitting glass shade for you. This article is here to guide you to having a free hassle when shopping for the right glass shades. Beginning with some practical tips while standing in front of a mirror, push your hair to the back to get a clear outline of your face. After this is done, using lipstick or a marker, draw the outline of your face in the mirror. Now you have a blueprint that shows you the shape of your face. Another way to figure out your face shape is by measuring. This method will need you to take notes. With a measuring tape, measure your forehead width, then the width of the cheekbone and the jawlines and primarily the length of the face. Now, pay keen attention to your facial qualities. What is the widest part of your face? Again, with the acquired data, you then compare it with the other types of faces to know what category of face shapes you belong to.",
    comments: [],
  },
];
