export const healthData = [
  {
    id: 4301,
    title: "Fruit Smoothies That Are Good For Weight Loss",
    type: "Health",
    time: "Sep 27",
    author: "Same Emmanuel",
    img: "https://static.netnaija.com/i/wnRaMjGXNdq.jpg",
    body: "Every one of us has attempted to lose weight at some point in our lives, and we are all aware that it is not as simple as social media would have us believe. To ensure that our bodies receive the nutrition they require, one must be mindful of the meals that they consume. Fruits are definitely one of the greatest foods to include in your diet because they are low in calories and packed with nutrients. - You can have twice as many fruits as cooked items without having to worry about putting on weight. Because of this, we have uncovered recipes for fruit smoothies that you can consume while on a diet. - Banana Berries Smoothie Fresh berries, bananas, and orange tang all contribute to the goodness of this fruit smoothie. Enjoy this nutritious smoothie as a quick breakfast. It is rich in vitamins and minerals. - Apple Chai Smoothie. In only five minutes, you can enjoy a creamy and decadent smoothie that is packed with the health benefits of apple and chia seeds. This smoothie only needs three ingredients. - Watermelon and Strawberry Smoothie. This smoothie is a fresh fruit blend of watermelon, strawberry, low-fat yoghurt, and garnished with chia seeds. Powerful nutritious elements are packed into this smoothie.",
    comments: [],
  },
  {
    id: 4302,
    title: "Uganda confirms six more cases of Ebola including one death",
    type: "Health",
    time: "Sep 23",
    author: "LuvlyGist",
    img: "https://static.netnaija.com/i/LqXNEMpeNlE.jpg",
    body: "The World Health Organization has announced that six new cases of Ebola have been found in Uganda, just after the country reported its first fatality from the highly contagious virus since 2019. The cases confirmed on Thursday September 22, include a 24-year-old man who died this week after he developed a high fever, diarrhoea and abdominal pain, in addition to vomiting blood. After initially being treated for malaria, he was diagnosed as having contracted the Sudan strain of the Ebola virus. Seven other deaths are being investigated as suspected cases of a strain for which the authorities do not yet have a vaccine, officials said. Abdou Salam Gueye, regional emergency director with the WHO Regional Office for Africa said in a statement; 'So far, seven cases, including one death, have been confirmed to have contracted the Sudan ebolavirus. 'Forty-three contacts have been identified and 10 people suspected to have caught the virus are receiving treatment at the regional referral hospital in Mubende. 'Our experts are already on the ground working with Uganda's experienced Ebola control teams to reinforce surveillance, diagnosis, treatment, and preventive measures.' Ugandan authorities have not yet found the source of the outbreak, or 'patient zero' - the key first case. But they were able to pinpoint the epicentre of the outbreak, which is the central Ugandan district of Mubende, whose main town lies along a highway into the capital, Kampala. That travel link and several crowded artisanal gold mines there are concerning, Bbosa told the World Health Organization. Ebola, which is spread by contact with the bodily fluids of an infected person or contaminated materials, manifests as a deadly haemorrhagic fever. Symptoms include fever, vomiting, diarrhoea, muscle pain and at times internal and external bleeding. Uganda last reported an outbreak of the Ebola Sudan strain in 2012.",
    comments: [],
  },
  {
    id: 4303,
    title: "5 Reasons Why You Should Drink Red Wine",
    type: "Health",
    time: "Sep 09",
    author: "Same Emmanuel",
    img: "https://static.netnaija.com/i/90ZNPdbxN8e.jpg",
    body: "Red wines are in a class of their own. A glass of red wine can significantly improve your mood and add some flair and elegance to an otherwise bland meal. -Drinking red wine in moderation may also save you from going to the hospital too often. These are some reasons why you should drink red wine. -Lowers unhealthy cholesterol levels. There are two kinds of cholesterols your body produced; the healthy high-density lipoprotein and the unhealthy low-density lipoprotein. Red wine supports the formation of the former over the latter. LDL increases your risk of heart diseases like atherosclerosis and stroke. -Regulates blood sugar levels- Red wine contains generous amounts of resveratrol, a compound found in grape skin. Resveratrol is said to enhance glucose conversion in people with type 2 diabetes. -Red wine also contains ethanol which drives essential metabolic processes. -Prevents depression and dementia - A study involving Resveratrol and mice showed that the compound inhibits pro-depression and anxiety enzymes. Generally, adults that consume red wine moderately and regularly are less prone to depression and anxiety than those who don't. Red wine may also act as a memory booster in the long run. Resveratrol inhibits beta-amyloid proteins, a compound linked to many Alzheimer's cases. -Promotes a healthy gut -Red wine contains polyphenols, which may act as both antibiotics and prebiotics. Ingesting polyphenols makes the stomach environment more suitable for the growth of healthy gut bacteria, simultaneously weeding out the harmful ones like Helicobacter pylori, responsible for stomach ulcers.",
    comments: [],
  },
  {
    id: 4304,
    title: "5 Fruits To Give Your Skin That Spotless Ageless Glow",
    type: "Health",
    time: "Sep 19",
    author: "Same Emmanuel",
    img: "https://static.netnaija.com/i/g3M73xMoa9y.jpg",
    body: "Health is wealth, but do you not think that it begins with healthy glowing skin? When we mention nutritious cuisine, it does not need to be fancy or expensive. Or, what response do you get when you enquire of that friend or famous person about the trick to her flawless skin? plentiful fresh fruit? We have heard enough about the advantages of fruits for our health and skin since the beginning of time. In order to attain the greatest version of your skin, here are 5 healthy fruits to give your skin that spotless and ageless glow anytime any day. The experts say that antioxidants, which stop oxidative damage, are abundant in fruits. Also, vitamin A-rich foods can aid in the reduction of acne picking cucumbers and pineapple are excellent choices for treating acne. According to a study, your skin may appear more wrinkled or dry if your body is deficient in vitamin C. That's because vitamin C is essential for the process of making collagen, keeping your skin firm and minimising the appearance of ageing signs. In actuality, without the antioxidant, your body cannot efficiently create collagen. Furthermore, strong scientific evidence suggests that consuming vitamin C can promote general skin health. A study that appeared in The American Journal of Clinical Nutrition found a link between increased vitamin C intake and less wrinkled skin. For glowing skin, vitamin C intake must be daily. Oranges contain natural oils that keep your skin nourished and give it a plump appearance. Primarily, vitamin C and antioxidants, aid the body in battling free radicals and reducing DNA damage. As a result, premature ageing is slowed. Vitamin C content in raw citrus fruits is very high. One grapefruit has roughly 56 milligrammes of vitamin C, compared to one medium orange's 70 mg. Even more, vitamin C is present in citrus fruit juices; for example, a 225 mg glass of orange juice contains about 125 mg of vitamin C.",
    comments: [],
  },
  {
    id: 4305,
    title: "5 Things Your Yawns Might Be Telling You",
    type: "Health",
    time: "Aug 23",
    author: "Same Emmanuel",
    img: "https://static.netnaija.com/i/XV5Kv6wLK9m.webp",
    body: "Yawning has been viewed as a sign of exhaustion and, in some cases, boredom. Yawning or oscitation is an involuntary act of opening the mouth and taking a deep breath of air which is then exhaled. While it is considered a sign of fatigue, it is also viewed as a sign of disrespect in social gatherings. However, this simple bodily function may also be a sign of underlying health concerns. Here are five things your consistent yawns might be trying to tell you: 1.You need to slow down: More specifically, your brain needs rest. Yawning moves hot blood from the brain and replaces it with cooler air from the lungs, which is why yawns are sometimes referred to as the body's natural radiator system. 2.You're tired: Getting only a little sleep causes the brain temperature to increase, which causes you to yawn in an attempt to cool it down. Unfortunately, while yawning may help you focus for some time, it is not a total cure to the tiredness you feel. 3.It's contagious: Sometimes, you might be yawning because you saw someone else do so. Watching anyone yawn triggers a yawn in you. 4. A side effect of your medications: Yawning can also be a side effect of taking medications such as selective serotonin reuptake inhibitors, or SSRIs, medications commonly used to treat anxiety or depression. 5.An underlying issue: Excessive yawning is also associated with heart disease, epilepsy, multiple sclerosis, liver failure or hypothyroidism.",
    comments: [],
  },
  {
    id: 4306,
    title: "Eating Healthy: Why Eating Grapes Would Increase Lifespan",
    type: "Health",
    time: "Aug 30",
    author: "Same Emmanuel",
    img: "https://static.netnaija.com/i/5wPKLeEX7VB.jpg",
    body: "Doctor John Pezzuto and his Western New England University team have published research that demonstrates the amazing effects of grape consumption as well as its longevity effects on lifespans. The journal Foods published one paper and it showed that adding grapes to a high-fat diet, which is generally eaten, in an equivalent amount to slightly under two cups per day, resulted in a decrease in fatty liver and an increase in lifespan. According to Pezzuto and his team, these investigations give the proverb affirmation to what is said about being what you eat, elevating the phrase with a new meaning. He claimed that the research with grapes demonstrated real alterations in genetic expression. He has produced approximately 600 scholarly articles. Grapes boosted overall antioxidant genes and postponed natural death in conjunction with a high-fat diet. Pezzuto recognised that extrapolating a mouse's lifespan to a human being's is not an exact science. The shift seen in the study, according to his best guess, would add an additional 4-5 years to a person's lifespan, he said. In the journal Antioxidants, Dr. Pezzuto and his group of researchers published yet another study. It stated that eating grapes improved behaviour and cognition, which were negatively impacted by a high-fat diet and altered gene expression in the brain. In a third study, a group under the direction of Dr. Jeffrey Idle showed that grapes alter not only the expression of genes but also the metabolism.",
    comments: [],
  },
  {
    id: 4307,
    title: "4 ways to find out if it's true love or just nooky",
    type: "Health",
    time: "Aug 29",
    author: "LuvlyGist",
    img: "https://static.netnaija.com/i/1xYNepl9aLJ.jpg",
    body: "Have you ever been in a situation where you thought you were in a relationship but it turns out you mistook intimacy, kindness, and care for love? If you were brought up with emotionally unavailable caregivers or raised in chaotic homes then it's easier to misinterpret relationship situations. So how do you know you are in a healthy loving relationship or a friends-with-benefits relationship? Conversations don't go beyond pillow talk When someone is genuinely interested in you, they'll invest their time and energy in the relationship. You'll see them make an effort to make things work. But if they are never interested in any other area of your life such as your friends, family, career, or your mental health, then clearly, they don't like you enough. If they don't involve you in their plans, take you on dates, or introduce you to friends or family, then that's a sexual relationship. Or if they are the type to leave immediately after sex, then you have your answer. They aren't ready for commitment When you are getting good vibes from someone and you like them, it's easy to assume the feeling is mutual. It's easy to presume they want you as much as you want them. However, before you jump to conclusions, it's good to ask important questions. Do they like or want you? Are they looking forward to having a relationship with you? Is your relationship exclusive or are they seeing other people? Have they made it clear they want you as their partner? These are uncomfortable conversations but very necessary. You wouldn't want to be in a relationship where someday the other person will say they didn't ask you to be their partner. Relationships can be complicated, but when someone wants to be with you, you shouldn't have to question your place in their life, there'll be clarity. But if it's absent, it's time to go back to the drawing board.",
    comments: [],
  },
  {
    id: 4308,
    title: "Five side effects of energy drink",
    type: "Health",
    time: "Aug 10",
    author: "Same Emmanuel",
    img: "https://static.netnaija.com/i/8yZaJDLZKJ0.jpg",
    body: "Energy drinks belong to a class of products in liquid form that typically contain caffeine, with or without other added dietary supplements. Energy drinks are designed to give an 'energy boost' to the drinker by a combination of stimulants and energy boosters. The major constituent in most energy drinks is caffeine. while energy drinks might benefit performance and possible detrimental health problems. Here are five side effects of excessive intake of energy drinks: 1.Irregular heartbeat -Irregular heartbeat is a common concern for regular energy drink consumers and general caffeine consumers alike. So if you are choosing an energy drink with excessive amounts of this stimulant, you may notice your heart beating in a way that you are not used to. 2.Difficulty falling asleep- Those who drink energy drinks may have difficulty falling asleep. And not sleeping well can cause a person to feel sluggish the next day, leading them to seek a solution for their lack of energy. Enter an energy drink, which can cause sleeplessness-wash, rinse, and repeat. 3.Frequent anxiety- Consuming energy drinks is linked to increased nervousness. If you are generally a more anxious person, regularly drinking these beverages may not be the best match for you. 4.Tendency to partake unhealthy behaviour- It is becoming more commonplace for people to combine energy drinks with other less-healthful substances, whether it is alcohol, cannabis, or tobacco. Some may even call it a 'gateway drink'. So, if you are regularly drinking energy drinks, it appears that the chances of partaking in other unhealthy behaviors are increased as well. 5.Increases blood pressure- Drinking energy drinks can increase systolic blood pressure within a brief period of time after drinking. If you are trying to manage your blood pressure in a healthy way, energy drinks are not the best beverage to include in your diet for this reason.",
    comments: [],
  },
  {
    id: 4309,
    title: "Three Steps To Self-Exam The Breast",
    type: "Health",
    time: "Aug 14",
    author: "Same Emmanuel",
    img: "https://static.netnaija.com/i/bvoKdornNrx.jpg",
    body: "Most women discover breast lumps by themselves, but you don't need to wait for a lump to develop before you learn how to self-examine your breast at home. Most lumps are benign, and detecting them early would help you better manage them. Self-examination of the breast enables you to monitor your breast health and detect any changes that could prove costly. It is recommended for women above 18 years, and should be done every month, preferably anytime after menses, but not a few days before menses when the breasts might be tender. If you are a postmenopausal woman who has stopped menses, the ideal step is to pick a date of the month for breast self-examination. It is paramount for you to be regular with your examination because you are at a greater risk of developing breast diseases than women who are still menstruating. As a pregnant woman, you are expected to see changes in your breasts such as having full, heavy, and tender breasts as the pregnancy matures. It's okay to see some discharge in the latter part of your pregnancy too; this might be colostrum. But these changes should not exclude you from breast self-examination. If anything, a self-examination offers you a chance to detect any changes that could interfere with your breastfeeding and discuss such findings with your caregivers during antenatal sessions. Women who are breastfeeding can pair their self-examination sessions with breastfeeding. For instance, after emptying your breasts, you can examine them one after the other. Examining yourself after breastfeeding will reduce the possibility of feeling milk pockets and getting anxious that it could be an abnormal lump. Whatever category you belong to, a routine examination of your breast will help you track every change as they appear.",
    comments: [],
  },
  {
    id: 4310,
    title: "Five side effects of skin bleaching",
    type: "Health",
    time: "May 25",
    author: "Same Emmanuel",
    img: "https://static.netnaija.com/i/no4NX4bLN9M.jpg",
    body: "Skin-bleaching techniques, such as the use of skin lotions and soaps to attain a lighter skin tone, are widespread around the world, and generally motivated by cosmetic motivations or low self esteem for one to embrace its skin type. Here are five side effects of skin bleaching: 1. Nephrotic syndrome is a kidney illness caused by damage to the blood vessels that filter waste and excess water in your kidneys. It makes your body expel an excessive amount of protein in your urine. Mercury-containing skin whitening cosmetics have been linked to nephrotic syndrome. Swollen feet and ankles, frothy urine, loss of appetite, and exhaustion are some of the symptoms 2. Steroid acne can be caused by skin bleaching products that contain corticosteroids. With long-term usage of corticosteroids, steroid acne typically affects the chest, although it can also appear on the back, arms, and other regions of the body. Whiteheads and blackheads, little red pimples, huge, painful red lumps, and acne scars are all possible symptoms. 3. Exogenous ochronosis (EO) is a skin condition that results in blue-black pigmentation. It commonly happens as a side effect of using hydroquinone-based skin bleaching treatments for a long time. People who use it on a wide scale or on their entire body are more prone to acquire EO. 4. Contact dermatitis has been connected to the use of skin bleaching products in case studies and reports. This is a type of skin inflammation brought on by interaction with certain chemicals. Skin redness, blisters, skin ulcers, hives, dry, scaly skin, swelling, itching, burning, and tenderness are all symptoms that can range from mild to severe. 5. Kidney Disorder This is often caused by damage to the blood vessels in the kidneys responsible for filtering waste and excess water. It causes the body to excrete too much protein in your urine. Skin lightening creams containing mercury have been associated with nephrotic syndrome. Symptoms of this include; foamy urine, loss of appetite, swollen feet and ankles, and fatigue.",
    comments: [],
  },
  {
    id: 4311,
    title: "Why, how sitting may kill you!",
    type: "Health",
    time: "Aug 14",
    author: "Same Emmanuel",
    img: "https://static.netnaija.com/i/x5PKDOEYNnM.webp",
    body: "Most of us sit for hours every day-in traffic, at work, or while we watch our favourite TV shows at night. The shocking reality is that all this sitting for hours on end may be killing us. Sitting may seem like a really harmless activity, but medical experts say that doing so for long periods of time every day is associated with serious health problems like Type 2 diabetes, joint pain, blood clotting, and cardiovascular disease. You may have heard the phrase, 'sitting is the new smoking', which is credited to Dr. James Levine, Professor of Medicine at the Mayo Clinic. He has spent years studying the science of sitting, and the unintentional danger we put ourselves in each day by leading sedentary lives. Human bodies were not designed to sit as much as we do, says Dr. Levine. Our ancestors spent most of their lives upright as they hunted for, and grew food - only occasionally sitting down for breaks. In his book Get Up! Why Your Chair Is Killing You, he states that we've gone from an ancient world of movers to a modern world of chair sloths. If sitting is so relaxing, why is it bad for you? The problem lies in how much of it, and for how long, we sit each day. When our bodies are in a static position for a lengthy period of time, all kinds of bad things happen, such as blood circulation - which is crucial for good health - slows down, affecting every system of the body. Poor blood circulation allows fatty acids to build up in the blood vessels, leading to heart disease. And, according to World Thrombosis Day, another risk is that when your legs remain still for hours, your calf muscles don't contract, which normally helps blood circulate.",
    comments: [],
  },
  {
    id: 4312,
    title: "August Break: Keep your windows closed",
    type: "Health",
    time: "Aug 14",
    author: "Same Emmanuel",
    img: "https://static.netnaija.com/i/9bVNr5v4aWv.jpg",
    body: "While it is important to regularly open your interior space windows for fresh air, as breathing in stale air could lead to health issues, it is advisable that during the August break when there is neither sun nor rain, you ration that routine especially at night. This is because the August break comes with its peculiar weather condition such that if you expose your home and family to it especially at night when it is usually extremely cold, there is a possibility of cold related illness such as cough, running nose, lung and heart problems, increased blood pressure, pneumonia and poor mental health, among others. Aside from the health issues that come with the August break, your interior would be exposed to excessive dust which also contributes to health issues, condensation that creates mildews and molds, dampen insulation, deteriorate wood frames and wardrobe and encourage infestation. August break daily air routine To ration the air during this August break, it is advisable to open your windows for about five minutes in the morning so as to exchange stale air for fresh air. Repeat the procedure in the evening before going to bed and keep the windows shut all night.",
    comments: [],
  },
];
