export const sexualityData = [
  {
    id: 4601,
    title: "For men: Here're 4 ways to tell if your partner is faking orgasm",
    type: "Sexuality",
    time: "Jul 03",
    author: "LuvlyGist",
    img: "https://static.netnaija.com/i/zxG7ZGWEaq2.jpg",
    body: "When it comes to sex, many, if not most, people would love to orgasm. Couple in bed It often happens that women fake their orgasm so as not to upset or jeopardize their relationship or sex life. They fake their facial expressions, pretending to be blown away by the man's sexual prowess. However, it is your duty to see through it and make sure that she feels it for real. Try different things, positions, sex accessories, and hand movements to see what genuinely works. So look out for these 4 ways which tell you if your partner is faking an orgasm. You both 'come' at the same time Sometimes it is possible that you both arrive at the same time but if this is happening frequently, then she is faking it. It is very difficult for women to come so orgasming together every time, is a facade for sure. No contractions When a woman is about to come, there are contractions. The pelvic muscles begin clenching and if you are inside, it is impossible to miss it unless you are too lost in your own world. If you do not feel it and she is making loud noises as if she is, she is lying. No recovery time If she has climaxed and it was glorious then she has to feel all spent out. So, in case she is casually checking her phone or is doing some other work, she is definitely faking it. Reactions like porn Are the reactions and actions similar to what you must have seen in some adult movies? Then it is very much possible that she is faking it to please you. The moaning and lip biting can sometimes be a lie. If you are unable to make out the truth, simply ask her to guide you and help you so that you both enjoy the intimate time. Sex is for both partners, not just one.",
    comments: [],
  },
  {
    id: 4602,
    title: "For men: Here are 4 types of s*x women enjoy",
    type: "Sexuality",
    time: "Oct 16",
    author: "LuvlyGist",
    img: "https://static.netnaija.com/i/5wPKLg6LNVB.jpg",
    body: "The right approach is essential to learning any skill, and the same applies to sex. Women are very perceptive of what makes them feel desired and pleasured in bed. And that includes exciting sex positions. Women have forever wished to be pleasured during sex and there are some particular sex moves that completely arouse her, paving the way for an extremely erotic orgasm. If you want to spice up things with your partner under the sheets, try these tips. Sensual sex This is one type of sex most women desire to have. Start by clearing both your schedules, set a sexy environment, and let her know you've got all night to focus on her pleasure. Shut off your cell phones, turn off the TV, and anything else that will distract you from reaching new levels of intimacy with your lady. Remember that foreplay is the bread and butter when engaging in a night of sensual sex. So take your time, go slowly, and explore all of the erogenous zones on her body that so often go neglected in the bedroom. Be passionate and engaged, and don't be afraid to tease her a little. Spontaneous sex Women love to feel sexually wanted and desired by their partners - and nothing says desire like spur-of-the-moment sex on the living room stairs. Unplanned, spontaneous love-making increases the lust factor by showing your partner that your attraction for her trumps everything else. Rough sex Most women, every now and then, want to be sexually dominated by their partners. Engaging in a little power play can be a fun and exhilarating way to explore kink in the bedroom. First and foremost, make sure she wants to play rough, and outline boundaries to ensure that you both feel safe. Then, pull a little hair, do a little spanking, and even bust out the blindfold and handcuffs if you're feeling adventurous. Revel in the pure lust this type of sex is driven by, indulge in animalistic passion, and go ahead. Don't forget to get a little too.",
    comments: [],
  },
  {
    id: 4603,
    title: "Sex schedule: Here's why this may not be a bad idea at all",
    type: "Sexuality",
    time: "Oct 06",
    author: "LuvlyGist",
    img: "https://static.netnaija.com/i/1xYNeMo2NLJ.jpg",
    body: "People think scheduling takes all the fun out of sex. But that may not be the case at all. Scheduling sex can feel like a chore or a checklist item if couples show up at a predetermined time, whether they're in the mood for sex or not. But if your life has gotten busy and the initial passion has rubbed off, it will help you to be more intentional about physical intimacy. Here are some best ways to go about sex scheduling: Schedule the opportunity for sex Start with it this way, instead of scheduling your sex, why not schedule the opportunity for sex? Rather than say no, just because you're not in the mood right now, try something that will put you both in the mood. Try messing around a little. You may find yourself getting more interested in sexual activity. Some percentage of the time, you'll likely end up wanting sex when you would not have had that desire if you hadn't gotten started. Enjoy the journey without focusing on the destination So many people are focused on sex and orgasm that they have forgotten how to enjoy the pleasure and connection they can have in all their physical interactions. If you have approached sexual intimacy with an expectation about sex or reaching climax, you may be bypassing the wonder of all the other parts of the process. Scheduling demonstrates commitment When life has taken over, when you're busy with kids or careers, when you've progressed past the early sexual rush in your relationship, and especially when at least one of you has reactive sexual desire, it's important to prioritize your sex life by dedicating time to it.",
    comments: [],
  },
  {
    id: 4604,
    title: "The legal status of same-sex relationships in African countries",
    type: "Sexuality",
    time: "Oct 06",
    author: "LuvlyGist",
    img: "https://static.netnaija.com/i/gEeK8e5j7P8.jpg",
    body: "While some African countries are silent on the penalties for homosexuality, some other countries have completely outlawed it. According to Global Citizen, out of the 54 African countries, 22 countries have legalized sexuality. In the other countries, homosexuality is a crime. In Mauritania, South Sudan, Somalia and Nigeria, it is a crime punishable by death. Nigeria is especially interesting because in the South, homosexuality is punishable by 14 years of imprisonment, but in the North, it is punishable by imprisonment for up to a year but if he is married, stoning to death (Section 131 Penal Code). Women are not punished similarly. Lesbians are simply flogged. In 2019, The High Court of Kenya upheld the law criminalizing consensual same-sex sexual activity. The court held that it is 'an effective method to contain the country's HIV epidemic' In Kenya, LGBTQ folks can spend up to 21 years in jail. In Tanzania, Uganda and Zambia, life imprisonment is the maximum punishment. In African countries where it is not expressly criminalized, gay people face discrimination. In the Ivory Coast, the laws against indecency have been used to jail some homosexuals even though it is not expressly a crime. In Egypt, gay men are charged with blasphemy, debauchery and immorality. In Tanzania, condoms and lubricants are banned from LGBTQ health clinics.",
    comments: [],
  },
  {
    id: 4605,
    title: "How to have s*x: 5 bedroom rules couples should follow",
    type: "Sexuality",
    time: "Oct 16",
    author: "LuvlyGist",
    img: "https://static.netnaija.com/i/LqXNEY6JNlE.jpg",
    body: "Following some bedroom rules will get closer to your partner and discover how great it is to spend time with your spouse in ways more than one. The sex habits you form with your partner over time have a huge impact on the well-being of your relationship. When you stay with a person in a relationship for so long, things are bound to get monotonous, especially during sex. With everyday hectic schedules and timelines, married couples can no longer feel physically or sexually drawn to one another. To make sure the sex life doesn't drown completely, here are some rules every married couple ought to follow in the bedroom: Have sex at least once a week Have sex at least once a week so that you and your partner don't enter a dry spell. Not engaging in sex can make a couple feel sexually frustrated and angry. To avoid any such complications, focus on having sex with your partner. Set new expectations during sex Your partner may not tell you but they may get bored repeating the same positions every time. Every now and then, it is important to try out some new positions that will excite you and your partner. Just don't keep it boring. Make foreplay a rule Foreplay is pretty important during sex because it includes the play of emotions as well. Some women take a long time to climax because there is no foreplay involved. Foreplay increases the chances of reaching an orgasm. Engage in oral sex Don't just kiss your partner on the lips. Let your imagination go wild and then kiss your partner in their most sensitive and sensual areas such as the neck, behind the knees, waist etc. This will impress your partner and keep the intimacy between you two sexy as ever.",
    comments: [],
  },
  {
    id: 4606,
    title: "For men: 5 places you shouldn't touch a woman during s*x",
    type: "Sexuality",
    time: "Oct 06",
    author: "LuvlyGist",
    img: "https://static.netnaija.com/i/zxG7ZGWEaq2.jpg",
    body: "While the heat is on, you may think there is no boundary as to what to say or touch, but be careful, you may kill the fun while touching these places. Couple in bed Sex is always a moment of pleasure that intimate partners often take informally. Lovers usually have no boundaries to their pleasurable activity while the moment is on. However, the lovemaking process is very sensitive and couples should curtail the habit of placing their hands on some sensitive parts of the genitals which are listed below. Her cervix If you reach her cervix during sex, recognize that something is wrong. Remember, this is the narrow canal that connects the vagina to the womb. That isn't a place you want to go to, so don't try to touch her there. For starters, it's painful for her to have something rammed against her cervix, and it could be a sign that you need to shift for a position with shallower penetration. Head of the clitoris We know the clitoris is a super-sensitive zone and has a lot of nerve endings, but stimulating the head of the clitoris vigorously can turn out to be an intense and painful experience for her. Imagine gulping a cup of piping hot coffee immediately followed by an ice-cold beverage. The feeling is not pleasant, right? Instead, try rubbing around in circles or simply at the shaft of the clitoris. Feet Don't touch her feet if she's wearing socks! Wondering why? According to a study from Johns Hopkins University, wearing socks in the sack can increase the chances of having an orgasm. This logic applies to men as well. Another reason is that women need to be completely relaxed to climax, and cold feet can be an uncomfortable distraction.",
    comments: [],
  },
  {
    id: 4607,
    title: "5 s*x positions guaranteed to make a woman orgasm",
    type: "Sexuality",
    time: "Oct 06",
    author: "LuvlyGist",
    img: "https://static.netnaija.com/i/qvg70OkvKze.png",
    body: "We are all here because of sex, so one cannot deny the central role sex plays in our existence. Also, most of us enjoy sex, a lot. This is why it is important to discover the best styles and positions in the bedroom that heighten one's sexual experiences. Here are five style for the ladies which are guaranteed to make sure every lady enjoys sex to orgasmic levels: Cowgirl This position has the woman on top. This style is about the woman riding a man like a horse. The best thing about this style is that the woman sets the pace. As she sits on a man's crotch, she enjoys deep penetration, which, depending on how she likes to orgasm, can be make a lady feel like she is on top of the world. Doggy Style-The doggy style basically allows a lady to lead from behind. Sure, it can get rough, if that is what she is into. Indeed, it gives a lady a chance to enjoy sex hard and fast, like she is a co-star in the movie Fast and Furious release. It also allows for deep penetration, as well as G-spot stimulation.Yab-Yum- This sex position focuses on intimacy. Essentially, a lady sits on her lover's lap while facing them, and the two of them focus on each other and the energy between them. It makes both sexes feel emotionally vital. And every lady wants to feel that way.Butter Churner-The butter churner sex position involves the lady being penetrated while she lies on her back with their feet over her head and her hips in the air, so that the man penetrates from above. Because the lady is upside down, the blood will rush to her head, which is a sure-fire way to enjoy an orgasm.",
    comments: [],
  },
  {
    id: 4608,
    title:
      "Learn about fraysexuality: A sexual orientation where a person enjoys s*x with people with whom they have no feelings",
    type: "Sexuality",
    time: "Oct 06",
    author: "LuvlyGist",
    img: "https://static.netnaija.com/i/wnRaMDzW7dq.jpg",
    body: "There are people who want to have sex just for fun. It is not only a celebration of free sexual expression, but it is a sexual orientation and it is called fraysexuality. People who prefer casual sex and one-night stands over a stable partner and relationship have been slut shamed for years - especially in Nigeria where Yoruba men are the regular culprits. Meanwhile, they are expressing their sexual orientation just like straight people, homosexuals and lesbians. 1. Fraysexuals are attracted to people they don't know. A person is referred to as 'fraysexual' if they feel a sexual attraction to someone they don't know or don't know very well. Fraysexual people experience stronger sexual attraction to strangers or people they just met than those they've known for a while. 2. Emotions make sexual attraction die Once an emotional connection has been made, sexual attraction fades away. They are the opposite of demisexuals who only have sex with people with whom they have an emotional connection. 3. Fraysexuals can experience love It doesn't mean that they are completely emotionless and cannot experience attachment and bonds. It just means that when the connection between them and someone else deepens, emotions of sexual attraction fade. 4. Any gender or sexual orientation can be fraysexual Fraysexuality is not bound by gender or sexual orientation, anyone can be fraysexual. Homosexuals, lesbians, bisexual people etc can be fraysexuals. 5. Fraysexuals separate love from sex Fraysexuals try to strike a balance by saying even though sexual feelings aren't there, romantic feelings exist. We are sure all those people who cheat are happy to hear that. It simply means that they have lost sexual interest in you and not romantic interest. So, they might love you but not be sexually attracted to you.",
    comments: [],
  },
  {
    id: 4609,
    title:
      "Retirement Benefits: 5 reasons people still have sex with their exes",
    type: "Sexuality",
    time: "Oct 06",
    author: "LuvlyGist",
    img: "https://static.netnaija.com/i/x5PKDX0yKnM.jpg",
    body: "Why do we go back to an ex for sex even after a breakup? Should you have sex with an ex? [stocksy] Break-ups are difficult! You've spent so much time with this person, you talk all day and night, you send each other memes and funny videos, and suddenly they are gone from your life. It can feel incredibly lonely especially when they were your source of constant sex. So, why do we slip up and still have sex with them even when the relationship is over? 1. Lonelines -Even though we know they are not good for us, we still go back to them to fill in the boredom. Jared said, 'We had such a huge fight that led to the breakup, but we are egotistical and don't wanna change or apologize, but we are horny so we just come together and have sex. The next morning, we are still upset and she would say things like 'Why don't you always act before thinking?' Nothing has changed, but we just needed to get off.' 2. Familiarit -They know the things you like and want, and they have adequate knowledge of your body. Such familiarity is hard to come by. Doyin said, 'We broke up but we were still having sex for a year, he would come over and we would have sex and he would go back to his house.' 3. Residual feeling -Residual feelings can be sparked in an instant. Maybe you met at a party or they came over to pick up their things and before you know it you are back at it. Saheed went to a house party with friends where he didn't think he would see his ex but he did. They had rented out an air BnB with a couple of friends, they found themselves paired in the same room and the sex came easily. 4. The breakup was a mistak -If the breakup wasn't mutual, one person might use sex to hold on to the relationship. Sammie said, 'My ex-girlfriend new boyfriend used to beat her, and she would come to me to cry and then we would have sex while I consoled her.' 5. Simplify the relationship -Some people don't want the tag of a relationship but want to do everything a couple does with no strings attached. So, they break up and just become fuck buddies.",
    comments: [],
  },
  {
    id: 4610,
    title: "From pleasure to grave: Why people die during sex",
    type: "Sexuality",
    time: "Aug 11",
    author: "LuvlyGist",
    img: "https://static.netnaija.com/i/wnRaMPXm7dq.webp",
    body: "The other day, a student of the Polytechnic Ibadan reportedly died during sexual encounter with a female partner in Ibadan, the Oyo State capital. The student, Daniel died, while his unconscious partner, identified as Aramide, was rushed to University College Hospital (UCH), Ibadan for treatment. It was learnt that the deceased, a National Diploma II student, Civil Engineering department and his partner, Aramide, who is also a National Diploma II, Department of Business Administration allegedly took sexual enhancing drugs before engaging in the act. Few days earlier, two lovers were found dead and naked in a Toyota Highlander (SUV), parked along Oja road, off Isheri Bus stop, Jakande Estate, Ejigbo, Lagos. The lovers were believed to have died while making love in the vehicle with registration number: EPE 666 GE, as the man was fully naked while the female had her trousers stripped down to the knee level. A resident who was a witness, Maduka Augustine, said the residents didn't know the time the vehicle was parked, but that they became suspicious the way it was not properly parked and decided to check inside the vehicle.'What we saw baffled us and too bizarre. The vehicles windows were all wind up, but we saw two people inside it and we raised the alarm which attracted people. We started knocking on the SUV, but the two occupants were motionless. Operatives from Ejigbo Police Station later took them away.' On March 1, there was also another incident of death of suspected lovers inside a vehicle along the Lagos-Ibadan Expressway in Mowe-Ibafo area of Ogun State. According to eyewitnesses, the lovers died while having sex inside a Toyota Sienna vehicle around the NASFAT area of Mowe-Ibafo axis of the expressway. The bodies of the lovers caused panic on the expressway. It was gathered that people became suspicious after the vehicle remained on the same spot for two days. On February 4, a 50-year-old estate agent, Diran Elijah, reportedly died while having sex with his ex-wife inside a hotel room in the Agbado area of Ogun State.The ex-couple reignited their love affair lately when Elijah contacted her on the phone and they agreed to meet at the hotel. He was reportedly taking some rest after a pleasant time in bed with Idowu when he suddenly started gasping for breath. And the man died.",
    comments: [],
  },
  {
    id: 4611,
    title: "The fu*k buddy manual: An ultimate guide to casual relationships",
    type: "Sexuality",
    time: "Sep 11",
    author: "LuvlyGist",
    img: "https://static.netnaija.com/i/mjyK6PlmawD.jpg",
    body: "Not looking for love but just sex? Here is a guide to never catching feelings.A fuck buddy or casual relationship is all about sex. Both parties know that they are in it for solely mind-blowing intercourse. If after numerous breakups, you are done with love and just looking to get down without any strings attached, then you need this guideline or else you will be catching feelings before you know it. 1. Always establish that you are ONLY interested in sex. From the very first conversation you have with them, let it begin with something mildly sexual but appropriate. Lay your cards on the table, and let them know what you are interested in just their body, not their mind or a friendship. 2. Do not spend countless hours on the phone with them.Note that a fuck buddy and friends with benefits are not the same things. A fuck buddy is not your friend.Do not attempt to get to know them as a person or fill the loneliness in your life with your fuck buddy by calling and texting constantly. Limit the texts to only times you want to hook up with them. 3. Do not sleep over at their place for more than one night in a row. According to the manual, once it is morning, go to your house or better still never sleep over. Do not spend two nights in a row at their place. Do not start some sort of cohabitation. Before you know it, she is wearing your shirt, giving you facials and you are acting like a couple. 4. Do not cuddle all through the night. If you want to never catch feelings, do not cuddle, strip the relationship to the bare essentials, coitus, sex, intercourse - cuddling is reserved for someone you crave affection from, someone you want to love or you love.5. Do not ever talk about hurt feelings. Once you hear things like, 'I don't like what you said' know that the end of your fuck buddy relationship is over. In this arrangement, feelings don't matter, only sex. Plus, the more a person's actions hurt, the more you care about them.",
    comments: [],
  },
  {
    id: 4612,
    title: "5 foods to avoid before s*x",
    type: "Sexuality",
    time: "Oct 05",
    author: "LuvlyGist",
    img: "https://static.netnaija.com/i/no4NXY34K9M.jpg",
    body: "Below are 5 foods that are good for your health but you might want to avoid them before bedroom exercise. We all think about nutrition to pique our performance in the gym, or even at work, so why not in the bedroom, too? 'There are some foods thats can make you feel tired, lethargic and bloated, and these can interfere with great sex,' says Lorraine Perretta, a nutritional therapist. We run down a few of these food faux pas that might interfere with your performance between the sheets. Sure, a romantic dinner in a nice restaurant is usually an opportunity to treat yourself to a prime slab of meat. But unfortunately, a big steak is not going to help you feel sexy later on. Large meals can focus the body's energy and blood flow to digestion rather than sex. Meat can take up to four hours to digest. Garlic Apart from giving you stinky breathe down your lovers, garlic is supposedly a prime culprit for making a man's semen taste funky, along with caffeine, red meat and onions. There are reports that the bodily fluids of vegetarians taste better than meat eaters. So ditch the meat and garlic, and load up on greens. Heavy Carbs Another to avoid if you don't want to feel lethargic and sleepy. Carbs like potatoes, bread, and pasta are likely to raise the blood sugar levels for the short term but a couple of hours later the sugar levels crash and so does energy.",
    comments: [],
  },
];
