export const bbNaijaData = [
  {
    id: 3501,
    title:
      "Chichi sparks outrage as she reveals she charges N20 million for 1 year influencing",
    type: "BBNaija 2022",
    time: "Oct 25",
    author: "Moses O",
    img: "https://static.netnaija.com/i/wnRaMGvpKdq.webp",
    body: "Big Brother Naija season 7 finalist, Chinenyenwa Desire Okoebor, widely known as Chichi is setting the standard when it comes to influencing. News has just hit socials that the reality Tv star rolled out her charges and terms for partnership with brands. As stated in the memo, Chichi reveals that she will be charging N20 million for a 1-year brand-influencing contract, while N12 million will be charged for 6 months. Her post has stirred reactions from social media users, and an Instagram influencer, Zabeth. In her words: 'Chichi of BBNaiaj is charging 20 million Naira for 1 year influencing??? God Abeg oooo'",
    comments: [],
  },
  {
    id: 3502,
    title: "Moment Sheggz almost snubbed Bella at Pepsi event (Video)",
    type: "BBNaija 2022",
    time: "Oct 23",
    author: "Moses O",
    img: "https://static.netnaija.com/i/5VrNpnDm79O.webp",
    body: "It's been almost a month since the BBNaija season 7 show ended, but Bella and Sheggz are still going strong with their ignore game. The duo was spotted at a Pepsi event last night but failed to properly exchange pleasantries. Bella was first spotted having a conversation with Chichi when Sheggz walked in. Immediately, he said 'hi' to Chichi, who in turn stood up to give him a hug. He moved passed Chichi and almost snubbed Bella when they reluctantly exchange handshakes. The moment could not have gone unnoticed, as it was as clear as day. Fans of their ship think that it has gone on for far too long.",
    comments: [],
  },
  {
    id: 3503,
    title:
      "'I have never been surprised all my life' - Phyna writes following surprise from Phynation",
    type: "BBNaija 2022",
    time: "Oct 23",
    author: "Moses O",
    img: "https://static.netnaija.com/i/1xYNeMqGNLJ.webp",
    body: "Reality Tv star and winner of BBNaija season 7, Phyna pens words of gratitude to her maker for positively turning her life around. Her post of gratitude comes after her fans Phynation surprised her with several gifts including a money cake. Phyna takes to her social media page, where she revealed that he has never been surprised in her life. In her words: 'God has made my cup overflow. I have found favor in the eyes of great men and women, effortlessly things are falling in place for me. A long time of struggling in my life God has put a stop to them. I have never been surprised all my life but yesterday, PHNATION did. In my little understanding, I say this is God.'",
    comments: [],
  },
  {
    id: 3504,
    title:
      "Bryann praised following outstanding performance at Beauty's after party (Video)",
    type: "BBNaija 2022",
    time: "Oct 22",
    author: "Moses O",
    img: "https://static.netnaija.com/i/zxG7Z0evNq2.webp",
    body: "First runner-up of the Big Brother Naija season 7 show, Bryann, turned up for his colleague, Beauty Tukura, with a heart-melting performance at her after-party. It would be recalled that the disqualified housemate of the show celebrated her 25th birthday on Friday, 22nd of October, and was later followed with an after-party. Bryann who was one of the attendees entertained the celebrant and guests with a live performance that lit up the event. Fans of the brand influencer, however, showered him with praise for his outstanding performance and support for Beauty.",
    comments: [],
  },
  {
    id: 3505,
    title: "BBNaija 2020: Davido better than Michael Jackson - Nengi",
    type: "BBNaija 2022",
    time: "Sep 24, 2020",
    author: "Moses O",
    img: "https://img.netnaija.com/hsi/aHR0cHM6Ly9kYWlseXBvc3Qubmcvd3AtY29udGVudC91cGxvYWRzLzIwMjAvMDcvbmVuZ2ktMS0xLmpwZy53ZWJw/images/nengi-1-1.jpg.webp",
    body: "Big Brother Naija, BBNaija housemate, Nengi has claimed that popular Nigerian musician, Davido was better than the late king of pop, Michael Jackson. Nengi anchored her claim on the fact that she does not listen to any of Michael Jackson's songs. The BBNaija finalist made the remark during an interaction with fellow housemates, Vee and Neo, on Wednesday night. Nengi further said she does not know any of Michael Jackson's songs. 'OBO is better than Michael Jackson. For me, I don't listen to him. As a matter of fact, I don't know any of his songs,' she said. The reality television show billed to end on Sunday, has Nengi, Laycon, Vee, Neo, and Dorathy as finalists. Any of the last five contestants could smile home on Sunday with the all-inclusive N85m grand prize.",
    comments: [],
  },
  {
    id: 3506,
    title:
      "'I need a solution' - Hermes cries out over 'sapa', says celebrity life is not easy (Video)",
    type: "BBNaija 2022",
    time: "Oct 20",
    author: "Moses O",
    img: "https://static.netnaija.com/i/qvg70O4BKze.webp",
    body: "Former Big Brother Naija housemate, Hermes, has lamented bitterly over the expensive celebrity lifestyle. In a video shared on Instagram, the BBNaija star said 'sapa' has been dealing with him since he got out of the show. He also lamented over the hike in prices of items for sale at the markets and appealed to fans to offer him a solution. Hermes said in part: 'Omo what is happening exactly? Since I got out of Big Brother Naija e no get wetin person wan buy. Things go just go up and e no dey ever come down. Bro Sapa dey. I've been trying to buy things, everything just dey expensive.'",
    comments: [],
  },
  {
    id: 3507,
    title: "Bryann opens up about relationship with Modella (Video)",
    type: "BBNaija 2022",
    time: "Oct 19",
    author: "Moses O",
    img: "https://static.netnaija.com/i/5VrNpnv379O.webp",
    body: "BBNaija Level-up 1st Runner up, Bryann reveals his relationship status to fans who have been asking about him and Modella. The musician cum reality Tv star held a live video session, where he got to interact with some of his fans. While at it, a fan asked him if he and Modella are now an item. Bryann laughs in return, before proceeding to ask why people are so interested in his personal life. However, he tells his fans that he has been focusing a lot on work and that he is single. In his words: 'I am still single...I am focusing on my music'. Recall that Bryanna was interested in Modella back in the house, but could not pursue a relationship, because the latter refused.",
    comments: [],
  },
  {
    id: 3508,
    title:
      "'I will continue to be razz; nothing can change me' - Phyna silences critics (Video)",
    type: "BBNaija 2022",
    time: "Oct 18",
    author: "Moses O",
    img: "https://static.netnaija.com/i/LqXNEJyyKlE.webp",
    body: "BBNaija season 7 winner, Phyna has addressed detractors in her most recent post, letting them understand that she will continue to be 'razz'. Following Phyna's win, she has constantly had to address internet trolls, as she claims she is not one to let things slide. This development came to light after she shared on Twitter that she is a winner with a difference - a response she gave naysayers, who constantly tell her that she 'does not know how to talk'. In a live video, Phyna disclosed that she will continue to be who she is and that nothing can change her. She informed critics of how much of a different winner she is. The Level-up queen goes on to speak about her she will never compromise her personality for fame. She adds that the only difference is her appearance and glow.",
    comments: [],
  },
  {
    id: 3509,
    title: "I never had sex with Khalid on the show - Daniella (Video)",
    type: "BBNaija 2022",
    time: "Oct 16",
    author: "Moses O",
    img: "https://static.netnaija.com/i/m9z7oY0vN2r.webp",
    body: "Popular reality star, Daniella Peters, addresses the misconception about having sex with a fellow housemate, Khalid, during the BBNaija Season 7 edition. This comes weeks following the conclusion of the show that saw Phyna as the winner of N100M grand prize. It would be recalled that the ex-housemate and Khalid had quite a number of undersheet activities which many claimed to have been copulation. According to Daniella in a recent interview, her relationship with Khalid in the house was genuine, and at no point did they make out. She pressed on to cite situations where Dotun asked her about what she shared with Khalid.",
    comments: [],
  },
  {
    id: 3510,
    title:
      "BBNaija 7: Which ships are sailing and which ones will sink in due time?",
    type: "BBNaija 2022",
    time: "Aug 11",
    author: "LuvlyGist",
    img: "https://static.netnaija.com/i/1xYNepyPaLJ.jpg",
    body: "Some ships are paper boats while others are real ships. Every year, romantic ties form in the Big Brother House, it's only expected when you gather good-looking people together in a place. This year, we've seen so many ships being formed right away and some of us are wondering if it's real or it's just a show.",
    comments: [],
  },
  {
    id: 3511,
    title: "Phyna reveals real reason she dated Groovy (Video)",
    type: "BBNaija 2022",
    time: "Oct 06",
    author: "Moses O",
    img: "https://static.netnaija.com/i/wk37lRrONPd.webp",
    body: "Phyna never seizes to shock the BBnaija audience when it comes to matters that concern her relationship with Groovy. The winner of the season 7- Level up season has opened up about her real motive behind going for Groovy. While speaking with media personality, Elozonam in an interview, Phyna revealed that she decided to date Groovy after she heard the reason she was called a hypocrite by Beauty. Further speaking, she stated that Kess, a fellow ex-housemate told her that Beauty had told him that she called Phyna a hypocrite because she had an eye for Groovy when she did not. In her words:- 'I rapped up my mind when Sir Kess told me Beauty called me a hypocrite because she felt I had eyes for Groovy...She lied and I decided to date Groovy to see what will happen'",
    comments: [],
  },
  {
    id: 3512,
    title: "Sheggz and Bella seen exchanging pleasantries at event (Video)",
    type: "BBNaija 2022",
    time: "Oct 13",
    author: "Moses O",
    img: "https://static.netnaija.com/i/zOJabvVVaG2.webp",
    body: "After days of ignoring each other, the controversial BBNaija Level-Up couple, Sheggz and Bella spotted exchanging pleasantries. The duo was spotted at a recent Lush Hair event in Lagos, saying hello to each other. This is the first time they will be seen talking to each other since the show ended over a week ago. Mr. and Mrs. Ikoyi, as they are fondly called have also politely avoided answering questions concerning their relationship. During their media rounds, the duo has maintained unison regarding their answers, as they both claim to be focused on their brands at the moment.",
    comments: [],
  },
  {
    id: 3513,
    title:
      "'I looked at the crowd but couldn't see anyone' - Chichi tears up as she recounts grand finale events",
    type: "BBNaija 2022",
    time: "Oct 11",
    author: "Moses O",
    img: "https://static.netnaija.com/i/zxG7Z0vvNq2.webp",
    body: "Season 7 finalist, Chichi has opened up about the reason she found it difficult to answer one of Ebuka's questions at the grand finale. Recall that Ebuka has asked Chichi who she was excited to see at the finale but she failed to answer and moved on to the next.",
    comments: [],
  },
  {
    id: 3514,
    title:
      "Chichi burst into tears as she speaks about impact of BBNaija show in her life (Video)",
    type: "BBNaija 2022",
    time: "Oct 10",
    author: "Moses O",
    img: "https://static.netnaija.com/i/1xYNeMkjNLJ.webp",
    body: "One of the finalists of the BBNaija Level Up show, Chichi, speaks on the impact of the platform in her life amidst claims of this year's edition as being unnecessary. Chichi who struggled with genuine intentions from other housemates during the show that lasted for 72 days revealed that the platform gave her a supportive audience for the first time ever. During an interview with Hero Daniels, the reality star spoke about how she used to feel insecure about her ability and what others thought about her. While in tears, Chichi stated that it was a serious concern regarding what the audience thought about her until she came out and was met with unending love and support.",
    comments: [],
  },
  {
    id: 3515,
    title:
      "BBNaija is devil incarnate misleading Nigerian youths - MURIC asks lawmakers to give NCAC backing in sanctioning show",
    type: "BBNaija 2022",
    time: "Oct 09",
    author: "Moses O",
    img: "https://static.netnaija.com/i/rOx7x90da0M.webp",
    body: "The Muslim Rights Concern (MURIC) has raised an alarm of Big Brother Naija allegedly forcing youths into the world of nudity. The Islamic Rights group which had before now repeatedly called for regulatory measures to be instituted against the reality show, described it as a 'devil incarnate misleading Nigerian youths' and also appealed to the national assembly to back the National Council for Arts and Culture (NCAC) in tackling nudity on the show. MURIC made the appeal in support of calls made by Segun Runsewe, the NCAC director-general, for power to sanction BBNaija and cross-dressers in the country. The statement released by MURIC read:- 'MURIC supports Runsewe's call and we see no reason why the NASS will hesitate to give him all necessary backing. BBNaija's reality TV show is the devil incarnate misleading Nigerian youth,' the group said. 'BBNaija is forcibly dragging our youths to a world of nudity, debauchery, and shamelessness. BBNaija constitutes a potent threat to every home. It is open rape of our cultures, values, and norms. BBNaija is luciferous. 'The NASS will have its name indelibly carved in letters of gold if it hearkens to the plea made by Runsewe. 'His appeal has revealed the weakness in our legal system. It has revealed that there are no extant laws powerful enough to stop romance and sex on our television channels. The time to give the law the teeth to bite is now.'",
    comments: [],
  },
  {
    id: 3516,
    title: "EGroovy makes it rain on Phyna at her victory party (Video)",
    type: "BBNaija 2022",
    time: "Oct 09",
    author: "Moses O",
    img: "https://static.netnaija.com/i/eDxaw9RZKPZ.webp",
    body: "The official baby boy of the season, Groovy was spotted having an amazing time at his baby's party last night. On the 8th of October, 2022, a victory party was held on behalf of Phyna for emerging the winner of the BBNaija level-up season. The party was well-attended by finalists, as well as Big Brother Naija alumni. One of the highlights of the party has to be Groovy lavishing money on Phyna, as she hyped him. The word went wild after Groovy was joined by his friend, Sheggz, as they both made it rain on the lady of the moment.",
    comments: [],
  },
];
