export const crimeData = [
  {
    id: 3901,
    title: "WhatsApp Scammer jailed for $100 Fraud",
    type: "Crime",
    time: "Yesterday 10:05am",
    author: "Same Emmanuel",
    img: "https://static.netnaija.com/i/g3M73YbzN9y.webp",
    body: "The Economic and Financial Crimes Commission, EFCC, Abuja Zonal Command on October 25, 2022, secured the conviction of an internet fraudster, Ekechukwu Wilson Chinaza before Justice F.A. Aliyu of the FCT High Court sitting in Apo, Abuja. A statement released by EFCC spokesperson, Wilson Uwujaren, says Chinaza was convicted after pleading guilty to a one count charge bordering on impersonation. The charge reads :'That you, Ekechukwu Wilson Chinaza sometime in 2022 at Abuja within the jurisdiction of this Honorable Court cheat by impersonation when you created a WhatsApp profile page using a white lady's picture with the name Amber and under that assumed character did obtain the sum of One Hundred United States Dollars ($100) from Brian in the pretext that you are in a romantic relationship and thereby committed an offence contrary to Section 321 of the Penal Code Act, Laws of the Federation (Abuja) 1990, and punishable under Section 324 of the same Act'. Justice Aliyu, in convicting the defendant took cognizance of the plea of the defence counsel for leniency on the grounds that the defendant has a bed-ridden mum and had forfeited the proceeds of the crime to the Federal Government. The judge sentenced the convict to a fine of N200, 000 (Two Hundred Thousand Naira Only) and community service at a location close to his place of residence.",
    comments: [],
  },
  {
    id: 3902,
    title:
      "'He saw me with another person and came to fight' - Woman says after being apprehended for stabbing man to death in Edo (Video)",
    type: "Crime",
    time: "Yesterday 9:49am",
    author: "Same Emanuel",
    img: "https://static.netnaija.com/i/gEeK8GolNP8.jpg",
    body: "A video that captured the moment a Delta woman identified simply as Gift was apprehended for allegedly stabbing a man to death in Egor Local Government Area of Edo State, has been shared online. The woman who was handcuffed and kept in the backseat of a car admitted engaging in a physical fight with the man. When interrogated by someone at the scene of the incident, the woman claimed the deceased identified as Eghosa came to fight her after seeing her with another person. Though she didn't explain the nature of their relationship, she revealed that the fight took place at the house of the person Eghosa saw her with. She said; 'As he see me with another person, he came to fight me for that person house.'",
    comments: [],
  },
  {
    id: 3903,
    title:
      "Indian gang rapists who raped and killed a female student on a moving bus are all to be hanged",
    type: "Crime",
    time: "Jan 07, 2020",
    author: "Tayo",
    img: "https://img.netnaija.com/hsi/aHR0cHM6Ly93d3cueWFiYWxlZnRvbmxpbmUubmcvd3AtY29udGVudC91cGxvYWRzLzIwMjAvMDEvSW5kaWFuLWdhbmctcmFwaXN0LmpwZw==/images/Indian-gang-rapist.jpg",
    body: "The execution date for four men who were convicted of fatally gang-raping a female student on a bus in Delhi in 2012 has been set. The men, Akshay Kumar Singh, 31, Pawan Gupta, 25, Vinay Sharma, 26, and Mukesh Singh, 32, are due to be hanged on January 22 at 7am in the city's Tihar jail, a court has ruled. The ruling comes after the country's Supreme Court rejected appeals against the initial death sentence by all four men. According to Mail Online, the men still have once more chance to appeal against the so-called 'black warrant' death sentenced, with their lawyer expected to file a mercy plea with the country's Supreme Court. Asha Devi, the mother of 23-year-old victim Jyoti Singh, said: 'This judgement will reinforce people's faith in the judiciary. My daughter will get justice.' The victim, Singh was riding on a bus with a male friend through Delhi on December 16, 2012, when they were attacked by six men including the bus driver. Her friend, Awindra Pratap Pandey said they were beaten unconscious with a metal bar, before the men then took it in turns to rape and torture Jyoti. The man reportedly used the metal bar to inflict 'catastrophic internal injuries' on the student, who was dumped naked by the side of the road. Awindra survived with injuries, but Jyoti had to be flown to Singapore for specialist treatment, where she died two weeks later (Dec.29). Five men and one juvenile were initially arrested for the attack, but one of the men, Ram Singh, died in custody in 2013 with an autopsy ruling he hanged himself. The juvenile was convicted of rape and murder and sentenced to the harshest possible punishment - imprisonment for three years in a reform institution. The remaining four men who are now to be hanged were convicted of rape and murder in September 2013 and sentenced to death.",
    comments: [],
  },
  {
    id: 3904,
    title:
      "'I killed him all by myself'- Chidnma Ojukwu speaks on murder of billionaire Usifo Ataga",
    type: "Crime",
    time: "Oct 13",
    author: "Moses O",
    img: "https://static.netnaija.com/i/5wPKLgLQNVB.webp",
    body: "Chidinma Adaora Ojukwu, a 300 Level student of Mass Communication in UNILAG has confessed to the murder of CEO of super TV, Usifo Michael Ataga. The late billionaire was unfortunately murdered on the 15th of June 2021. Chidinma Ojukwu was questioned on her relationship with the deceased and according to her, 'Micheal Ataga was a friend that we just talked to. I didn't know him that deeply and we did not talk regularly'. Before the deceased's murder, Micheal Ataga had instructed Chidinma Ojukwu to get an apartment for them to stay which she did. According to the owner of the apartment, Nkechi Mogbo, Chidinma called her on June 13th with a private number to request for the apartment and after communicating on WhatsApp, she made a payment of 125,00 naira for three days with a GTB account that had the name, Mr Michael Usifo. Chidinma confirmed to requesting for a place and also by Monday morning, that is on the 14th of June after getting the apartment on the 13th of June, she ordered food and more drugs because according to her, she and Micheal Ataga had been taking drugs and having s*x. And it went on till Tuesday, on the 15th of June. Chidinma said Micheal wasn't being himself due to the influence of the drug, and kept asking for more s*x even after she declined cause she was tired. Michael struggled with her and eventually had his way. She said she pushed him and he hit his head on a stool that had glass cup on it and then fell to the ground.",
    comments: [],
  },
  {
    id: 3905,
    title:
      "Police arrests lecturer and daughter for assaulting lady in viral video",
    type: "Crime",
    time: "Oct 22",
    author: "Same Emanuel",
    img: "https://static.netnaija.com/i/PrO7OezrNyp.jpg",
    body: "The Nasarawa State Police Command has arrested one Dr. Fred Ekpa Ayokhai, and his daughter, Emmanuela for assaulting Blessing Mathias over a boyfriend snatching issue. A couple of videos had made rounds on the internet where the victim, Blessing was brutally beaten and stripped by the lecturer, his daughter, and others. Another video also shows an initial attack on Emmanuela over claims of taking a man's number without consent. In a statement released by the State's police command, the culprits have been arrested and are to be charged in court. 'POLICE PRESS RELEASE'- 'Sequel to the viral tweet of assault on a female teenager in Lafia, Nasarawa state, the Command swiftly commenced investigation into the case. It is gratifying to state that, two suspects namely: Dr. Fred Ekpa Ayokhai, an associate professor with the Department of History and International Studies, Federal University of Lafia and one Emmanuela Ekpa Ayokhai have been arrested in connection with the case while the vehicle belonging to Dr Fred which was used in conveying the victim to a location along Kwandere road, Lafia where she was assaulted has been recovered. Preliminary investigation revealed that Emmanuela Ekpa Ayokhai and the victim had a misunderstanding over a man named IG. The victim accused Emmanuela of snatching her supposed boyfriend and assaulted her. In retaliation, Emmanuela mobilised her family, went after the victim and got her assaulted as well. The Commissioner of police, AIG Adesina Soyemi has ordered an intensive man hunt for the other fleeing suspects and further directed that, those arrested should be charged to court for prosecution upon conclusion of investigation at the State Criminal Department, Lafia DSP Ramhan Nansel Police Public Relations Officer For: Commissioner of Police Nasarawa State Command.'",
    comments: [],
  },
  {
    id: 3906,
    title:
      "EFCC arrests two suspected currency counterfeiters with fake $270,000 in Abuja",
    type: "Crime",
    time: "Oct 21",
    author: "Same Emanuel",
    img: "https://static.netnaija.com/i/eDxaw94zKPZ.webp",
    body: "The Economic and Financial Crimes Commission, EFCC, has arrested two suspected currency counterfeiters in Abuja. A statement issued by the EFCC spokesman, Wilson Uwujaren on Friday, October 21, 2022, identified the suspects as Johnson Olumoyegun and Tanko Abubakar. He said the suspects were arrested on Thursday and Friday, October 6 and 7, 2022 in Kubwa and Area 3 Axis of Abuja, with fake $270,000 (Two Hundred and Seventy Thousand United States Dollars). In addition, Olumoyegun impersonated an officer of the Commission, using a fake EFCC ID card with the name Solomon David. He also carried an ECOWAS Passport with the name, Isa Bello. The two suspects will be charged to court as soon as investigations are concluded.",
    comments: [],
  },
  {
    id: 3907,
    title: "Court remands teenagers over murder of RCCG pastor in Festac town",
    type: "Crime",
    time: "Oct 21",
    author: "Moses O",
    img: "https://static.netnaija.com/i/deYakp3ZNP3.jpg",
    body: "Justice Sherifat Sonaike of a Lagos state High Court has remanded two boys identified as Farouk Mohammed, 16, and Kasali Jamiu, 19, at the Special Correctional Centre for Boys, Oregun, and the Ikoyi Custodial Centre, for allegedly killing a pastor with the Redeemed Christian Church of God pastor, Babatunde Dada, 46. The duo was first charged before a Yaba Chief Magistrate's Court alongside two others, Mumuni Toheeb, 21, and Mubarak Soliu, 20, in January 2022 for allegedly receiving a Spark S Tecno phone valued at N60,000 that belonged to the deceased. However, when the case came up on February 14, Chief Magistrate Olatunbosun Adeola said a prima facie case had been established against Mohammed and Jamiu. She ordered that the two teenagers should face trial at the High Court following the legal advice from the DPP and also ordered that Toheeb and Soliu be discharged based on the recommendation of the DPP. When the matter came up on Thursday, October 20, at the state High court sitting in Tinubu, Lagos Island, the Director of Public Prosecutions, Dr Babajide Martins, informed the court that the matter was for arraignment. Martins told the court that the defendants conspired among themselves and allegedly killed Dada in December 2, 2021, around 12noon, in the RCCG, Road 13, 6th Avenue, FESTAC area of Lagos. He said they killed the deceased by hitting him on the head with a wooden plank and a bottle. The prosecutor also told the court that the duo robbed the deceased of his bag and a mobile phone. Following their arraignment, the defendants pleaded not guilty to the charges. In view of their pleas, Justice Sonaike ordered their remand in custody and adjourned the case till November 29 for trial. The remanded teenagers visited the RCCG Chapel of Resurrection on 13 Road, 6th Avenue, FESTAC Town last Sunday November 2021. During the altar call, they came out and pledge to give their lives to Jesus Christ. After the service, they met with late Dada and informed him they had nowhere to stay as they were stranded. The church leaders offered them the church premises to stay pending when they will be able to help them get a place. It was while they were in the church that they allegedly attacked and killed Dada.",
    comments: [],
  },
  {
    id: 3908,
    title:
      "Fake EFCC operative arrested for allegedly defrauding Belgian woman of €45,000",
    type: "Crime",
    time: "Oct 20",
    author: "Same Emanuel",
    img: "https://static.netnaija.com/i/Aq2NAYg5NzJ.webp",
    body: "Operatives of the Economic and Financial Crimes Commission, EFCC, have arrested 29-year old man, Ume Ifechukwu Clinton for impersonation, computer related fraud, obtaining by false pretence and money laundering. Clinton was arrested on October 18, 2022 at No 46 Atoke Gbadebo Street, Isheri, Lagos, by operatives of the EFCC, following a story published by an online portal: foundation for investigative journalism narrating how Clinton defrauded Axelle Mahieu, an educator working as a caregiver in Brussels, Belgium. The victim was surfing through her Facebook page in November 2021, when she saw that someone had sent her a message. The message was from Ume Ifechukwu Clinton, who introduced himself as 'a friend of a friend'. As they continued chatting in the following days, Clinton told Mahieu that he was an official of the EFCC, with a fake Identity Card and Nigerian Passport as proofs. After several months of video calls and gaining Mathieu's trust, Clinton allegedly proposed a cryptocurrency business to her, assuring her of huge profit and secured capital. After convincing the Belgian, Clinton ended up defrauding her of €45,000.",
    comments: [],
  },
  {
    id: 3909,
    title:
      "Man caught reportedly stealing bottle of wine at supermarket to celebrate his birthday",
    type: "Crime",
    time: "Oct 14",
    author: "Moses O",
    img: "https://static.netnaija.com/i/zOJabvvBaG2.webp",
    body: "A man has been apprehended after he allegedly tried stealing a bottle of wine at a supermarket in Akwa Ibom to celebrate his birthday. It was learned that the man had worked into a supermarket and had tried stealing a bottle of 'Campari' at a supermarket along Aka Etinan Road in Uyo, Akwa Ibom State. When he was asked why he had done it, he had revealed that it was for his birthday. It was gathered that the incident had occured on Thursday, October 13, 2022. A user who shared the news on Facebook wrote: 'Earlier hours of yesterday, A young man whose name has not been disclosed, yet stole a bottle of Champari at one Super Market along Aka Etinan Road in Uyo, Akwa Ibom State. When he was caught, beaten and interrogated why he stole the Champari he explained that he stole it just to celebrate his Birthday.'",
    comments: [],
  },
  {
    id: 3910,
    title:
      "Mum of 3 k!lled by husband 1 week after she called him out for assaulting her",
    type: "Crime",
    time: "Oct 07",
    author: "Moses O",
    img: "https://static.netnaija.com/i/gVpagP25NwO.webp",
    body: "A 30-year-old woman has been sadly k!lled by her husband barely one week after she called him out for assaulting her. The mother of three had shared a video of him beating her merc!lessly in Buffalo, New York. Keaira Hudson married Adam Bennefield, 45, in February this year and she took to Facebook to say it was the happiest day of her life. She also called Adam her 'lifetime friend partner' and said he loves her 'with every breath he has'. Sadly, the union took a turn for the worse as her husband got really abusive and Keaira took to Facebook on September 29 to post a video showing him abusing her. According to a friend, Adam had a bad temper long before they got married but he always apologized whenever he hit her and promised to change. 'Keaira's family did not want her to marry him. They were so scared for her and tried to reach out to Keaira, but she felt like she was fine,' the friend wrote on Facebook. On September 28, Adam threatened Keaira at their home with a knife, b£at her brutally, took her phone and refused to let her leave the house. As she bl£d on the floor after the b£ating, he took pictures of her in her battered state. Keaira shared the video on September 29 with the caption: 'This is what this man does to me but I'm always treated like I'm the abuser.' After that incident, she ran away from home with her kids. But Adam refused to let her be and threatened to k!ll her. He was arrested and a restraining order was placed on him. He was released from jail on Tuesday, Oct. 4th, and Keaira, who was hiding in her mother's house, wore a bullet-proof vest all the time as she feared Adam would k!ll her.",
    comments: [],
  },
  {
    id: 3911,
    title:
      "23-year-old man connives with friends to fake his kidnap and extort N10m from parents",
    type: "Crime",
    time: "Oct 13",
    author: "Moses O",
    img: "https://static.netnaija.com/i/bvoKdDpzKrx.webp",
    body: "A 23-year-old man named Edward Okache has been arrested alongside four others for faking his kidnap to extort N10 million from his parents for online business. The suspect was arrested alongside Asamoah Ernest, Isiah Uti, Ephraim Anyijor, and Charity Lukpata. This followed a report lodged at Mowe divisional headquarters by one Comfort Okache who reported via phone call that her younger brother who traveled from Calabar to Lagos was kidnapped around the Mowe area of Ogun state. She also revealed that the kidnappers were demanding N10 million if the relations want to see the boy alive. 'Upon the report, the DPO Mowe division, SP Folake Afeniforo mobilized the division's tactical teams and moved to the area.Upon painstaking and enduring combing of the surrounding bush at Orimerunmu area, the victim was sighted in an uncompleted building with the duo of Asamoah Ernest, a Ghanaian, and Isiah Uti, where he was tied in both hands and legs. The two suspects found with him were promptly arrested, while the victim was rescued. But on getting to the station, the two arrested suspects made a shocking revelation that the so called victim was the person who planned with them to kidnap him in order for him to extort money from his parents to invest in an online business.' They stated further that the so called victim was introduced to them by Ephraim Anyijor and Charity Lukpata who are from the same Yala local government area of crossriver as the victim, and that they all are all part of the planned kidnap of Edward Ochace. 'Their confession led to the arrest of Ephraim Anyijor and charity Lukpata. They have all confessed to the commission of the crime,' SP Abimbola Oyeyemi, spokesperson of the state police command, said.",
    comments: [],
  },
  {
    id: 3912,
    title: "Nigerian Army arrest another soldier aiding terrorists (Video)",
    type: "Crime",
    time: "Oct 12",
    author: "Moses O",
    img: "https://static.netnaija.com/i/9bVNr9YzaWv.jpg",
    body: "The Nigerian Army has arrested another member of its personnel collaborating with terrorists. The soldier has been identified as Iorliam Emmanuel, reportedly in his 30s and hails from Benue State. Emmanuel is a member of the 156 Task Force Battalion (Operation Hadin Kai) in Mainok town. Mainok, 60km from the capital Maiduguri, is the headquarters of Kaga Local Government Area of Borno State. Emmanuel was caught with ammunition, concealed in a bag and clothing tied around his waist. A trending video shows colleagues exposing the bullets the suspect stuffed inside and underneath his uniform. He is expected to face court martial for sneaking military supplies to terror gangs. The arrest was made months after a soldier was caught assisting Boko Haram/Islamic State's West Africa Province (ISWAP). The Army said Lance Corporal Jibrin, an instructor, committed suicide while being escorted to the barracks. Intelligence had exposed Jibrin's involvement in the killings at some relaxation spots in Yobe State in April. The attacks in Geidam and Gashua towns occurred within five days and claimed the lives of about 10 people.",
    comments: [],
  },
  {
    id: 3913,
    title:
      "CCTV captures man stealing cloth material from a boutique in Calabar (Video)",
    type: "Crime",
    time: "Oct 10",
    author: "Same Emmanuel",
    img: "https://static.netnaija.com/i/mr9KYnwZ7q6.jpg",
    body: "A man was caught on CCTV stealing clothes material from a boutique in Calabar, Cross River state.The mystery thief, who had visited the boutique in the company of another man, who was at the boutique to buy clothes for himself, picked a material from the shelf and hid it in his clothes unnoticed. Journalist George Odok, who shared the footage on social media on Sunday, October 9, said anyone with useful information to nab the man should reach out. 'Anyone who can identify the suspect should please reach out to the owner of the boutique located along MCC road, close to Triangle joint, Calabar. The question is this: how much is that material? The guy has just embarrassed himself publicly. It's a shame,' he captioned the video.",
    comments: [],
  },
  {
    id: 3914,
    title:
      "Lagos: Nigerians slam police for covering faces of officers who extorted 'Yahoo boy'",
    type: "Crime",
    time: "Oct 07",
    author: "Moses O",
    img: "https://static.netnaija.com/i/5wPKLgM0NVB.jpg",
    body: "The Lagos State Police Command is under fire for concealing the faces of policemen arrested for extortion. On Thursday, a youth narrated how the officers stopped him and called him a 'Yahoo boy', the Nigerian slang for internet fraudster. In a lengthy Twitter thread, the victim, Oluwagbadura, recalled how he was accosted at Soloki in Aguda, Surulere. Though the officers did not find anything on him, they seized his phone and company laptop. 'They searched my phone. They called me a criminal for chatting with my friends on WhatsApp. 'They threatened to shoot and lock me up! Next, they took me to their station, then forced me to admit to being a criminal.' After subjecting the young man to trauma, the police team then asked him to write a statement and bail himself. 'I transferred N100,000 to the POS vendor, and then paid N2,000 for charges', he told the public. One of them also threatened to deal with Oluwagbadura while he's in the cell and boasted nothing would happen. On Friday, Police Public Relations Officer in Lagos, SP Benjamin Hundeyin announced that the culprits were summoned to the headquarters. 'The complainant positively identified them all. They have been handed over to the Provost department for appropriate disciplinary measures', the spokesperson added.",
    comments: [],
  },
  {
    id: 3915,
    title:
      "Lavish wedding of Nigerian serial robber 'Blue Cloth Bandit' three months before arrest for over 60 robberies in U.S surfaces",
    type: "Crime",
    time: "Oct 06",
    author: "Moses O",
    img: "https://static.netnaija.com/i/qEQN240x76W.webp",
    body: "Photos of the lavish wedding of a Nigerian serial robber, Charles Chukwuma Onwuemelie 'Blue Cloth Bandit' surfaces following his arrest in America. Charles had been arrested as a suspect for over 60 robberies in Los Angeles in just five months with his insignia of a blue cloth used during all his operations. The suspect would disguise himself by wearing various hats, a face mask, and rubber gloves, which made many give him the name, 'Blue Cloth Bandit'. Photos of Charles Chukwuma's lavish traditional wedding on April 23, 2022, with his wife, Stephanie, surfaced where he narrated how they met at a church in 2012.",
    comments: [],
  },
  {
    id: 3916,
    title: "Woman beats maid to death, abandons body in bush (Video)",
    type: "Crime",
    time: "Oct 06",
    author: "Same Emanuel",
    img: "https://static.netnaija.com/i/m9z7oYdvN2r.jpg",
    body: "An unidentified woman has been arrested after beating her maid to death and abandoning her body in the bush. The National Agency for the Prohibition of Trafficking in Persons (NAPTIP) got the woman arrested. In the viral video, the woman is seen locating the body, where she dumped it in the bush. The unfortunate incident happened in Anambra state. According to a statement made by the woman, she beat her maid until she started to convulse. Telling her side in Igbo language, she said: 'I beat her and she started convulsing so I took her to Kings (hospital). Getting there, she died, so I threw her body here.'",
    comments: [],
  },
];
