export const educationData = [
  {
    id: 3801,
    title:
      "Strike: Again, ASUU files appeal against Industrial Court judgement",
    type: "Education News",
    time: "Oct 23",
    author: "Moses O",
    img: "https://static.netnaija.com/i/BQJNj0JB7rL.jpg",
    body: "The Academic Staff Union of Universities has again filed an appeal seeking the nullification of the judgment of the National Industrial Court of Nigeria which ruled that the lecturers must return to the classroom. The Counsel for ASUU, Femi Falana, SAN made this known while speaking with some reporters in the Federal Capital Territory, Abuja on Saturday. We recall that Justice Hamman Polycarp of the Industrial Court had on September 21, ordered the striking lecturers to go back to work. But ASUU filed an appeal before the Appeal Court in Abuja, intending to set aside the Industrial Court judgement. However, the appellate court noted that it would not hear ASUU's appeal should the union fail to obey the ruling of the lower court. The Appeal Court, therefore, on October 7, ordered the striking lecturers to resume work with immediate effect. The 8-month strike was suspended on October 14. Academic activities have fully resumed in some Public Universities while others have scheduled their resumption for the coming days. Falan said yesterday that the fresh appeal was filed the same day the suspension of the prolonged industrial action was announced. He, however, said, 'date for a hearing has not been fixed yet'.",
    comments: [],
  },
  {
    id: 3802,
    title: "We don't have transport fare to resume classes - ASUU President",
    type: "Education News",
    time: "Oct 17",
    author: "Moses O",
    img: "https://static.netnaija.com/i/XV5KvQEGN9m.webp",
    body: "The President of the Academic Staff Union of Universities (ASUU), Prof. Emmanuel Osodeke, speaks on the difficulty to resume work as a result of their pending eight months' salary. This comes days after the union conditionally suspended their eight-month strike following a court order to resume. In a recent interview with Channels TV, Prof. Emmanuel Osodeke highlighted a number of reasons making resumption difficult; one of which included transportation. In his words; 'In schools those days, every lecturer lives on campus and you can trek to your office but these days, many lecturers live 20, 30 kilometres to their offices. How will they pay for their transport to work? These are the issues we are going to have, that the branches will have to deal with. We expect the government to pay the money [eigth months salary arrers] so that these people will go back to work while we are negotiating on other issues. We suspended the strike hoping that the government will do the needful and by tomorrow, if the universities are open, hopefully, the lecturers will go back to work. We are resuming because we are obeying an industrial court judgement because the issues have not been fully resolved, no agreement signed. We are also hoping that with the intervention of the Speaker [of the House of Representatives, Femi Gbajabiamila], as promised by him, we will resolve this problem within a very short time. Our lecturers will teach but you can't expect someone who is owed eight months' salary, maybe from his bank, he has collected more than N1m as a loan and you have not paid him one kobo and you want him to go to class and teach. I pray they go there because of the children and do the best they can do. You don't expect a hungry man to go there [school] with an open mind.'",
    comments: [],
  },
  {
    id: 3803,
    title: "ASUU suspends eight-month-old strike",
    type: "Education News",
    time: "Oct 14",
    author: "Moses O",
    img: "https://static.netnaija.com/i/eDxawLjgNPZ.webp",
    body: "The Academic Staff Union of Universities, ASUU, has suspended its eight-month-old industrial action. A member of the union's National Executive Committee, NEC, confirmed this early Friday. ASUU decided to suspend the strike during a meeting of its leadership that started on Thursday night and lasted into the early hours of Friday. The state branches of the union met over the Court of Appeal ruling last week, following which members voted to conditionally suspend the strike. The Court of Appeal had issued an order to ASUU to suspend the strike before its appeal of the ruling ordering lecturers to resume work could be heard. The National Executive Committee meeting was attended by chairmen of the state chapters and national executive members at the ASUU National Secretariat in Abuja. ASUU had been on strike since February 14 this year.",
    comments: [],
  },
  {
    id: 3804,
    title: "ASUU Strike: UNIPORT Announces Resumption, Marathon Exams",
    type: "Education News",
    time: "Oct 15",
    author: "Same Emmanuel",
    img: "https://static.netnaija.com/i/8yZaJrEYaJ0.webp",
    body: "Following the suspension of the eight month old strike by Academic Staff Union of Universities (ASUU), the University of Port Harcourt (UNIPORT) has announced resumption of academic activities. This was contained in a circular exclusively obtained by CAMPUS GIST, Friday, entitled 'Approved Revised Academic Calendar for 2020/2021 session and 2021/2022 session full time.' In the circular seen by CAMPUS GIST, all year one 'B' students for the 2021/2022 session were asked to resume 16th October, while first semester exams commences 24th to 29th October, 2022. But that will be after just a one week revision expected to last from 17th to 21st October, 2022. Senate will meet 30th November to consider the semester results. For the 2020/2021 session, second semester, all old students are to arrive October 30, 2022 while lectures commences 31st October to 22nd December, 2022 (eight weeks). The institution will observe the Christmas break from 23rd December to 2nd January only to reopen 3rd January, 2023 for one week revision before the commencement of the semester exams.",
    comments: [],
  },
  {
    id: 3805,
    title: "Strike: We will sign deal in couple of days - ASUU",
    type: "Education News",
    time: "Oct 10",
    author: "Moses O",
    img: "https://static.netnaija.com/i/W4lNmjXOKRo.jpg",
    body: "The Academic Staff Union of Universities (ASUU) and the House of Representatives, on Monday, met on the lingering industrial action by the lecturers. The lecturers led by ASUU President, Emmanuel Osodeke and the leadership of the House, led by Femi Gbajabiamila, met behind a closed-door for about 30 minutes before having another one in front of the camera. It would be recalled that the House has been hosting meetings between the government and the strike lecturers in the past couple of weeks. On Friday, the Court of Appeal agreed with an early ruling by the National Industrial Court that asked the Union to resume immediately. It would be recalled that President Muhammadu Buhari had during his budget presentation stated that N470 billion has been allocated for tertiary institutions in the 2023 budget. Speaking on the outcome of the closed-door meeting, Gbajabiamila said President Muhammadu Buhari will make a major announcement regarding the strike. Also speaking, the Osodeke, said the Union will sign some documents in the next couple of days which they will take to their members for ratification. It would be recalled that the lecturers have been on strike since February 14.",
    comments: [],
  },
  {
    id: 3806,
    title: "Prof Folasade Ogunsola emerges first female UNILAG VC",
    type: "Education News",
    time: "Oct 07",
    author: "Moses O",
    img: "https://static.netnaija.com/i/xM6K5g6ZayE.webp",
    body: "Folasade Ogunsola, a Professor of Microbiology, has emerged as the 13th Vice Chancellor of University of Lagos (UNILAG). The scholar makes history, as she becomes the first female VC of the institution established in 1962. Ogunsola will succeed the outgoing and 12th VC, Prof Oluwatoyin Ogundipe, whose five-year single term ends on November 11. Her contenders were Professors Abayomi Akinyeye, Department of History, Faculty of Arts; Mathew Ilori and Adeyinka Adekunle - Department of Microbiology, and Botany, Faculty of Sciences. Timothy Nubi, Department of Estate Management, Faculty of Environmental Sciences; Imran Smith, Faculty of Law; Ayo Olowe, Department of Finance, Faculty of Management Sciences. Born in 1958, Ogunsola is a consultant clinical microbiologist and infection control for the Lagos University Teaching Hospital (LUTH). The incoming VC holds a PhD in Medical Microbiology, MSc in Medical Microbiology with Distinction, Diploma in Biomedical Techniques from the University of Wales College of Medicine, Cardiff. She is a fellow of the Royal College of Pathologists, West African College of Physicians, Nigerian Academy of Science, Nigerian Academy of Medicine, and Academy of Medicine Specialties. Ogunsola served as UNILAG acting Vice-Chancellor and former Deputy VC in charge of Development Services. The professor was the pioneer and only female Provost of the university's College of Medicine. She has been a governing council member for three terms, the only individual with such a number of years in the body. Ogunsola has received several awards from local and international organizations, has 142 publications and co-authored four books. The decorated don has so far supervised or co-supervised eight doctoral students and 61 master's students.",
    comments: [],
  },
  {
    id: 3807,
    title: "We will review Appeal Court's ruling, decide on next action - ASUU",
    type: "Education News",
    time: "Oct 07",
    author: "Moses O",
    img: "https://static.netnaija.com/i/PrO7OVYrKyp.webp",
    body: "The Academic Staff Union of Universities, ASUU has said it would review the judgement of the Appeal Court that ordered the union to end its strike, to determine its next line of action. We reported that the appeal court on Friday ordered the union to return to work as earlier ordered by the National Industrial Court with immediate effect. In reaction to the fresh court judgement, ASUU President, Professor Emmanuel Osodeke, told DAILY POST that the union is yet to officially receive the Appeal Court ruling. He said the union would after receiving the judgement, go through the document with its lawyers and decide on its next line of action. He said, 'We have not received the ruling, when we get it, we will review it with our lawyer and then we can take the next step'. We recall that the Federal Government, following its inability to reach a truce with the university lecturer, dragged ASUU to the National Industrial Court on September 11. The court on September 24, ordered the striking lecturers to return to class while negotiation with the Federal Government continues. Miffed by the ruling, the union headed to the appellate court to appeal the ruling.",
    comments: [],
  },
  {
    id: 3808,
    title: "Strike: FG reveals what will happen to ASUU",
    type: "Education News",
    time: "Oct 03",
    author: "Moses O",
    img: "https://static.netnaija.com/i/x5PKDDedKnM.jpg",
    body: "As the industrial strike embarked by the Academic Staff Union of Universities, ASUU, enters its eighth month, the Federal Government has warned the union to cease from acting in defiance of the interlocutory injunction given by the National Industrial Court (NICN), which restrained the union from further action. Senator Chris Ngige, Minister of Labour and Employment, gave the warning in a statement signed over the weekend by the ministry's Deputy Director, Press and Public Relations, Olajide Oshundun. Recall that ASUU president, Prof Emmanuel Osodeke had said its members were not bound by the Industrial Court order to resume work since the union had appealed against the ruling and was awaiting hearing on the request for stay of execution from the court. However, Ngige said that ASUU should stop taking laws into its hands by directing its members to continue with the 8-month old strike. He said a new directive by the union, exhorting its members to continue with the industrial action was lawless, and that the government frowns at it He also warned that the union risks consequences of contempt of court order. Part of the statement read: 'The union is dishonest and misleading its members and the general public that it has filed an appeal as well as a stay of execution of the order of National Industrial Court on September 21, 2022, though it has none of this. 'Rather, ASUU only filed an application for a permission to appeal the order. It also attached to the application, a proposed notice of appeal which it intends to file if the leave to appeal is granted. The application for a stay of execution as of this moment has not even been listed for hearing. Where then is ASUU coming from? 'It is, therefore, contemptuous, dishonest and misleading for the union to tell its members that it has not only appealed the interlocutory injunction by the National Industrial Court, directing it to call off strike and return to work, but that it also has a stay of execution', it said.",
    comments: [],
  },
  {
    id: 3809,
    title: "Strike: ASUU hiding something from us - NANS",
    type: "Education News",
    time: "Sep 28",
    author: "Moses O",
    img: "https://static.netnaija.com/i/1qGK1xjMNrV.webp",
    body: "The President of the National Association of Nigeria Students, NANS, Comrade Usman Barambu, has accused the Academic Staff Union of Universities, ASUU, of hiding something from the students following the union's refusal to allow them to observe proceedings of its negotiation with the federal government. The NANS President argued that the union should call-off the strike and continue negotiation afterward. According to him, it's unfair that after the court ruling asking ASUU to return to class, the union remains adamant. Recall that a recent judgment has ruled in favour of the government where ASUU was ordered to return to class while negotiation continues. ASUU has since appealed the judgment and has remained unmoved by the court's judgment. But the NANS President said: 'They have to call-off. They didn't say they are not calling off. They said they have to appeal, hence nothing stops them from going back to class when the appeal process is on. 'If they appeal and the Appeal Court upholds the industrial court order, they will go back to class. If the court grants the appeal, the federal government has the opportunity of appealing the case.' Accusing ASUU of a hidden agenda, the students union president said he had proposed to both ASUU and the federal government to be part of their negotiation and that while the government agreed, ASUU declined, fueling suspicion that they are hiding something. He said, 'But the problem is the ASUU. Why have they refused to call-off? I think they are hiding something. Why did they refuse that I should be part of the observers in their negotiation so we can clearly understand the stage they are right now?' 'The federal government under the ministry of labour approved that we are part of the negotiation, at least to observe, but ASUU declined, saying they can't sit with their children and that it's not in their tradition. Obviously, there is something they are hiding. As a leader of the Nigerian students, I said I want to observe, but the ASUU president declined. We will hold a press conference on this,' he told DAILY POST. Recall that ASUU has been on strike for the past 7 months and all efforts to end the strike have failed. The union is requesting the implementation of all its agreements with the federal government.",
    comments: [],
  },
  {
    id: 3810,
    title: "ASUU strike: Why FG reversed decision to reopen universities",
    type: "Education News",
    time: "Sep 27",
    author: "Moses O",
    img: "https://static.netnaija.com/i/Aq2NArrvKzJ.jpg",
    body: "Fresh Facts have emerged on why the Federal Government quickly reversed its order to the various university management to reopen public universities amid the ongoing strike by members of the Academic Staff Union of Universities, ASUU. Recall that the Federal Government had earlier ordered Vice-Chancellors to re-open schools. It had asked the Vice-Chancellors of universities 'to ensure that the striking members of the Academic Staff Union of Universities (ASUU) resume and commence lectures immediately.' However, it later issued another directive withdrawing its earlier circular. We gathered that the opinion leaders and other stakeholders interested in resolving the face-off between the ASUU and the government mounted pressure on government requesting that the circular, earlier sent to mandate the reopening of the universities, be withdrawn. A senior official in the Ministry of Education, who didn't want his name mentioned, disclosed that 'the circular was withdrawn to allow for more negotiation between government and the ASUU following the ongoing invention by the Speaker of the House of Representatives'.",
    comments: [],
  },
  {
    id: 3811,
    title: "ASUU strike: Obey court ruling first - FG tells lecturers",
    type: "Education News",
    time: "Sept 23",
    author: "Moses O",
    img: "https://static.netnaija.com/i/LqXNEMeeNlE.webp",
    body: "The federal government has told the Academic Staff Union of Universities (ASUU) to obey the National Industrial Court ruling and call off its seven-month strike. The Minister of Labour and Employment, Senator Chris Ngige, gave the advice while fielding questions from journalists on the margins of the 77th United Nations General Assembly, UNGA, and the Official Launch of the Nigeria Integrated National Financing Framework Report (NIFF). The industrial court on Wednesday, ordered ASUU to call off its ongoing nationwide strike, pending the determination of a suit filed by the Federal Government. The federal government had dragged the lecturers to court in a bid to end the strike. 'I'm not ASUU but the maximum in law is that when there is a court judgment or ruling or order you must first obey and then we can apply for an appeal if you so desire or apply for stay that is stay of execution. 'So the maximum in law, jurisprudence and everything about the law, is that you obey the court's ruling, judgment or order, no matter how bad. The qualifying thing is that no matter how bad and no matter how you disagree with it, you first obey. Like the military people say, obey before complain. 'So we expect them to get back to the classrooms but that doesn't foreclose negotiations, the negotiations should be on as a matter of fact, it will be on officially and non officially. 'For example, the House of Representatives had invited us to come and brief them. And together, they are stakeholders. You heard Mr President said to the committee of Pro-Chancellors when they visited him, that he would do consultation as per the two request on putting an icing on the cake on the government offer to ASUU members and the issue of resettlement fund to cushion the effect of the 'no work no pay' situation they found themselves in. 'So, President will look at it, the House of Reps are stakeholders, Ministers we are not only stakeholders, we are advisers to Mr. President by the provisions of the Constitution, Section 5 of the Constitution and 147, that appoints ministers one from each state of the Federation, and we hold regular meetings with him, so we are his chief advisers. 'So, we will interface with the House of Representatives and all of us collectively will advise Mr. President,' Ngige said.",
    comments: [],
  },
  {
    id: 3812,
    title:
      "ASUU strike: Student drags lecturers, Nigerian govt, 36 states, National Assembly to court",
    type: "Education News",
    time: "Sept 23",
    author: "Moses O",
    img: "https://static.netnaija.com/i/g3M73xApa9y.webp",
    body: "A university student, Soohemba Aker, has prayed a Federal High Court, Abuja, for an order suspending the activities of Revenue Mobilisation, Allocation and Fiscal Commission (RMAFC) until ASUU strike is resolved. The final year Law student of Benue State University, also sought same order suspending the operation of Federal Account Allocation Committee (FAAC), The respondents include the Federal Government, Academic Staff Union of Universities (ASUU), Senate President, House of Representatives Speaker, Attorney-General of Federation (AGF) and Minister of Justice. Others are Attorney Generals of the 36 states, Vice Chancellor of the University of Abuja, Abia Governor, RMAFC, FAAC, Umar Faruk (President, National Association of Nigerian Students (NANS). The student, in a fundamental rights enforcement suit marked: FHC/ABJ/CS/1684/2022 and filed by her lawyer, Chukwuma-Machukwu Ume, SAN, said she is affected by the ongoing industrial action. Aker filed the action for herself on behalf of all students of public tertiary institutions currently affected by the nationwide ASUU strike, NAN reports. The suit relies on Sections 46(1), (2) and (3) of the 1999 Constitution and Article 17(1) of the African Charter on Human and Peoples' Rights (Ratification and Enforcement) Act Chapter A9 (Charter 10 LFN 1990) No. 2 of 1983. Aker prayed the court for an order stopping the payment of salaries, allowances and other benefits of all political office holders at the Presidency and federal lawmakers. She urged the court to stop salaries and allowances of ministers, permanent secretaries, heads of parastatals and extra-ministerial bodies, VCs of striking universities, lawmakers and ASUU members. Aker's affidavit averred that the strike continues to affect her adversely as her plans of graduating this academic year 2022 and proceed to the Nigerian Law School had been thwarted. The citizen lamented that her tuition fees paid for the academic year will go in vain as the academic year is almost lost if nothing is done. Aker added that her dream of becoming a law graduate and a lawyer was at the verge of collapsing as her sponsor declared this year was the last she would be funded. The matter is yet to be assigned to a judge. ASUU embarked on strike on February 14, 2022. The impasse is yet to be resolved despite a series of meetings.",
    comments: [],
  },
  {
    id: 3813,
    title: "Court orders ASUU to call off strike",
    type: "Education News",
    time: "Sep 21",
    author: "Same Emmanuel",
    img: "https://static.netnaija.com/i/3g8NBv9PNDR.jpg",
    body: "The National Industrial Court of Nigeria has ordered the Academic Staff Union of Universities to call off its over seven-month old strike. The Academic Staff Union of Universities (ASUU) has been on strike since February 14, 2022 to press home the demands for improved funding for universities and a review of salaries for lecturers, among other issues. After several meetings between ASUU and the federal government to reach a consensus ended in a deadlock, the Federal Government referred the prolonged strike by ASUU to the National Industrial Court of Nigeria (NICN) for adjudication. A press statement signed by the Head, Press and Public Relations, Federal Ministry of Labour and Employment, Olajide Oshundun, said the suit, dated September 8, 2022, was formally addressed to the Registrar of the National Industrial Court of Nigeria (NICN) and signed by the Minister of Labour and Employment, Chris Ngige. The federal government's counsel, James Igwe, had applied for an interlocutory injunction to restrain ASUU from continuing with the strike. In his ruling in Abuja on Wednesday, Justice Polycarp Hamman granted the government's application. The judge held that the industrial action is detrimental to public university students who cannot afford to attend private tertiary institutions. The court therefore restrained 'ASUU, whether by themselves, members, agents, privies or howsoever called, from taking further steps and doing any act in continuance of the strike action pending the hearing and determination of the suit filed.'",
    comments: [],
  },
  {
    id: 3814,
    title:
      "ASUU strike: Lecturers reach agreement with Reps, await Buhari's approval",
    type: "Education News",
    time: "Sep 20",
    author: "Moses O",
    img: "https://static.netnaija.com/i/PrO7OVYrKyp.webp",
    body: "The Academic Staff Union of Universities (ASUU) has reached a new agreement with the federal government. The leadership of the House of Representatives on Tuesday brokered the new agreement after four hours of meeting at the National Assembly in Abuja. However, the agreement is subject to the approval of President Muhammadu Buhari, who is currently at the United Nations General Assembly meeting at the UN. The President of ASUU, Emmanuel Osodeke led the Union to the meeting, while the Minister of State for Education, Goodluck Opiah represented the federal government. After the closed-door session, Femi Gbajabiamila, who chaired the meeting announced that the meeting produced some agreements, however, he did not state the agreement reached. He disclosed that the lawmakers will present the agreement to president Buhari upon his arrival, while ASUU is to do the same with their members. 'There were basically seven areas where ASUU has presented what we considered to be requisition for them to go back to strike. We have looked at the seven areas, we have more or less agreed on certain things. 'Once that is done, the leadership of this house will await the return of Mr President from the ongoing General Assembly. We will meet with Mr President. We will lay the agreement reached by the legislative arm of government. I am hopeful that Mr President will buy into the agreement and with that, I believe that this matter will be speedily brought to a close,' he said. The lawmakers will on Thursday meet with National Information Technology Development Agency, the Accountant General of the Federation, the Auditor General for the Federation and National Salaries Incomes and wages Commission to discuss further. Speaking on the meeting, ASUU president said the issue will be resolved soon. 'It is a good development and we are waiting for what they will send to us to commit our members. We hope that within the immediate future, this issue will be resolved.",
    comments: [],
  },
  {
    id: 3815,
    title:
      "ASUU strike: Businesses around universities grounded, owners count losses",
    type: "Education News",
    time: "Sep 10",
    author: "Moses O",
    img: "https://static.netnaija.com/i/eDxawxjZNPZ.webp",
    body: "Mega Screen, a once bubbling area at the temporary site of the University of Abuja is currently like a ghost town, it has been like that since February. The students, who are the main lifeblood of this area, are currently at home waiting for news on when the strike will be over. Alhaji Bagudu and many other petty traders, Mai Suya, Mai Shai and others are equally waiting for news on the call-off of the strike as the businesses depend on the students. 'In February, when the strike was declared, some of the students stayed, hoping it's going to be a short strike. After a while, most left. Right now, it is pointless opening the shops. Some days, you don't even make enough to cover transport,' Mr Bagudu said. While attention has been on the plight of students, the entire university ecosystem goes beyond students and staff of the university, as several businesses depend on the university community to sustain. From transportation to housing to hospitality and other businesses, these businesses are counting the cost of the shutdown of these schools. 'We lost 1 year of rent in 2020. And we have almost lost this year,' Aliyu Isiak, a house agent in Gwagwalada said. 'Most houses will require massive renovation when students resume. Some of these houses have been taken over by rodents. In some cases, hoodlums and thieves have burgled some of the houses,' he added. Most of these businesses depend on students. Their business models envisage short and long holidays, not strike, particularly the uncertainty associated with the strike. In some instances, the entire economy depends on these schools. When students are on holiday or strike, the economy of that community relapses into a coma. While the lecturers are insisting that their salaries while on strike must be paid, businesses around these schools continue to suffer without hope of assistance from the government.",
    comments: [],
  },
  {
    id: 3816,
    title:
      "ASUU Strike: Nigerian govt announces 23.5% salary increment for lecturers",
    type: "Education News",
    time: "Sep 06",
    author: "Moses O",
    img: "https://static.netnaija.com/i/9bVNrLow7Wv.webp",
    body: "The Minister of Education, Adamu Adamu, has said the federal government can only afford a 23.5% salary increase for lecturers. However, Professors will get a 35% increment. Adamu stated this during a meeting on Tuesday with vice-chancellors and other university stakeholders. The minister noted that President Muhammadu Buhari had warned against signing agreements which the government will not be able to meet. Adamu said, 'The Federal Government can only afford a 23.5% salary increase for all categories of the workforce in Federal Universities, except for the professorial cadre which will enjoy a 35% upward review. 'Henceforth, allowances that pertain to ad-hoc duties of the academic and non-academic staff shall be paid as at when due by the Governing Councils of Universities to which such services are rendered and to the staff who perform them.' He also said, 'a sum of 150 billion Naira shall be provided for in the 2023 Budget as funds for the revitalization of Federal Universities, to be disbursed to the Institutions in the First Quarter of the year, and that a sum of 50 billion Naira shall be provided for in the 2023 Budget for the payment of outstanding areas of earned academic allowances, to be paid in the First Quarter of the year'.",
    comments: [],
  },
];
