export const technologyData = [
  {
    id: 3701,
    title: "WhatsApp Group Video And Audio Calls Going Live On Android",
    type: "Technology",
    time: "May 29, 2018",
    author: "Same Emmanuel",
    img: "https://img.netnaija.com/hsi/aHR0cDovL2NkbjIudWJlcmdpem1vLmNvbS93cC1jb250ZW50L3VwbG9hZHMvMjAxOC8wNS93aGF0c2FwcC1ncm91cC12aWRlby1jYWxsaW5nLmpwZw==/images/whatsapp-group-video-calling.jpg",
    body: "WhatsApp has long allowed users to make voice and video calls but it was confirmed only recently that the popular cross-platform messaging app will soon let users make group video and voice calls absolutely free. This feature has started rolling out in phases to iOS users and according to reports, some Android users are also seeing this feature go live in WhatsApp on their devices as well now. It didn't surprise anyone when Facebook CEO Mark Zuckerberg revealed at the annual F8 developers' conference a few weeks ago that group video and voice calls are coming to WhatsApp. This feature had actually been seen before in countless leaks and dives into the app's code. WhatsApp is now gradually making the server-side change that enables this functionality for users on both iOS and Android. Initial reports were that the feature was only available to some iOS users but now reports are coming in from Android users who are seeing the group video and voice call functionality on the latest version of WhatsApp beta 2.18.162. Starting a group video or voice call is simple enough, just tap on the add contact icon at the top right of the screen when you're already in a call with someone and then choose which contact you want to invite. The feature is said to be going live slowly for users so it might take a while before WhatsApp's billion-plus users all get it.",
    comments: [],
  },
  {
    id: 3702,
    title: "Apple confirms USB-C is coming to iPhone: 'We have no choice'",
    type: "Technology",
    time: "Yesterday 9:29am",
    author: "Same Emmanuel",
    img: "https://static.netnaija.com/i/PrO7OlDyayp.webp",
    body: "The company did not officially announce anything, but its senior vice president of worldwide marketing all but confirmed it in an interview with The Wall Streeet Journal's Joanna Stern. When asked whether Apple is moving to USB-C, Joswiak said 'obviously we'll have to comply, we have no choice.' Joswiak is referring to a new set of regulations in the European Union, as well as in Brazil, which mandate the use of USB-C on smartphones. Apple has long resisted the idea, but now that the EU will actually start enforcing the law starting in 2024, the company will have to make the change if it wants to keep selling iPhones in the EU. For users, this will simply mean most of their gadgets, whether made by Apple or some other company, will charge with the same cable. Apple isn't too happy about this. 'We think the approach would've been better environmentally, and better for our customers, for the governments to not be that prescriptive,' said Joswiak. What Joswiak wouldn't say, however, is when the switch is going to happen, exactly. 'The Europeans are dictating timing for European customers,' he said.",
    comments: [],
  },
  {
    id: 3703,
    title: "WhatsApp restored after being down for over one hour",
    type: "Technology",
    time: "Oct 25",
    author: "Moses O",
    img: "https://static.netnaija.com/i/x5PKDGmoNnM.jpg",
    body: "The instant messaging application, WhatsApp, has been restored after over an hour of being down. At around 8:20AM on Tuesday, users of WhatsApp observed that they could no longer receive or send messages, while status could not longer be updated. Our correspondent observed that the application was down world over as people from different locations took to Twitter and other social media apps to express their displeasure. However, at 9:45AM, it was observed that users started receiving messages, while sent ones showed they have been delivered. Meta, the owner of WhatsApp, Instagram and Facebook, is yet to make a statement about the development.",
    comments: [],
  },
  {
    id: 3704,
    title:
      "You Need To See The Longest Glass Bridge in the World That China Just Opened",
    type: "Technology",
    time: "Jan 06, 2018",
    author: "Same Emmanuel",
    img: "https://img.netnaija.com/hsi/aHR0cHM6Ly93d3cubGFpbGFzYmxvZy5jb20vd3AtY29udGVudC91cGxvYWRzLzIwMTgvMDEvNWE0ZjRhNGI2MWVmNi01OTd4NDEwLmpwZw==/images/5a4f4a4b61ef6-597x410.jpg",
    body: "China has officially opened the longest glass-bottomed suspension bridge in the world. The bridge is located in the Hebei Province's Hongyagu Scenic Area. The bridge, which is definitely a test of a tourist's bravery spans 488 meter (1,600 feet) over a vertical drop of 218 meters (715 feet).  Tourists were spotted trooping to the bridge to have the idea of what it feels like walking at a height with a view of the earth underneath. 'Hongyagu glass suspension bridge marks the 2.0 era for China's glass-bottomed bridge,' says Yang Minghua, the chairman of Hebei's Bailu Group, which created the span linking two peaks in the mountainous region of northeastern China.",
    comments: [],
  },
  {
    id: 3705,
    title: "It's Happening! Twitter is Testing an 'Edit Tweet' Feature",
    type: "Technology",
    time: "Sep 01",
    author: "Same Emmanuel",
    img: "https://static.netnaija.com/i/wk37lxrV7Pd.png",
    body: "In a move that will definitely divide users into at least two sides, Twitter has announced that it's testing an 'Edit Tweet' feature, to, obviously, allow users edit a tweet after it has been posted. In a blog post on Thursday, Twitter announced that the feature is being testing by its team internally, and will soon be expanded to Twitter Blue subscribers. Twitter wants users to 'think of it as a short period of time to do things like fix typos, add missed tags, and more.'Here are 3 things you need to know about the Edit Tweet feature: You'll be able to edit your tweet a few times within a 30 minutes period after publication. Edited tweets will appear with an icon, timestamp, and label to make it clear that the original tweet has been modified. Edited tweets will also show you their 'Edit History' with past versions of the tweet when you tap the label",
    comments: [],
  },
  {
    id: 3706,
    title: "MTN To Launch 5G Network In 7 States In Nigeria",
    type: "Technology",
    time: "Aug 25",
    author: "Same Emmanuel",
    img: "https://static.netnaija.com/i/WAPK4E0M70B.jpg",
    body: "MTN Nigeria Communications Plc said it has kicked off an open 5G pilot in the lead-up to its highly anticipated commercial launch in 7 states. The states that will witness the first launch, the company said, include Lagos, Abuja, Port Harcourt, Ibadan, Kano, Owerri, and Maiduguri. MTN said through its ongoing testing of the 5G infrastructure, its customers with certain enabled devices will be allowed to connect with and try out the new service where coverage is available. The advanced technology is expected to extend the reach and capacity of MTN Nigeria's data network in Nigeria and enable much faster speeds and lower latency, giving customers near-instant access to the things they care about and downloads that take seconds, instead of minutes. What the company is saying Chief Marketing Officer, MTN Nigeria, Adia Sowho, in a statement issued on Wednesday said: 'Every major technological evolution redefines what is possible - changing how we live and connect. MTN Nigeria has been at the forefront of every leap in telecommunications: from GSM to 2G, 3G, and 4G. 5G has the potential to change everything. It will allow us to connect, create, collaborate, and compete in ways we've not even begun to imagine.' 'We appreciate the unwavering support and leadership of the Honourable Minister of Communications and Digital Economy and the Nigerian Communications Commission in implementing the National Policy on 5G Networks for Nigeria's Digital Economy, which has driven the implementation of 5G in the country. We're honoured to be a part of this revolution and being the first to bring 5G to Nigeria we are truly excited about all the possibilities for the nation,' she added. What you should know The spectrum issued to MTN Nigeria as one of the two successful winners of the 5G license bid holds a promising future for technology in Nigeria, and is projected to contribute $2.2 trillion to the global economy by 2034, according to a 2020 GSMA Intelligence report -'The Mobile Economy'. The implementation of 5G will accelerate the actualization of the national targets in the Nigerian National Broadband Plan, the National Digital Economy Policy and Strategy, as well as other sectoral policies designed to enhance Nigeria's digital transformation. While MTN is still targeting Q3 to launch in line with the conditions of the licence, the second operator with 5G licence in Nigeria, Mafab Communications, has been given a 5-month extension for its rollout by the Nigerian Communications Commission.",
    comments: [],
  },
  {
    id: 3707,
    title: "The First Xiaomi Authorized Store in Nigeria opened",
    type: "Technology",
    time: "Aug 09",
    author: "Same Emmanuel",
    img: "https://static.netnaija.com/i/g3M73ERWN9y.jpg",
    body: "Offers exclusive services to Customers from 8th to 10th August 2022. Xiaomi Corporate, a global consumer electronics and smart manufacturing company announced the launch of its first authorized store today at Essence House, Computer Village, Ikeja, Lagos. Xiaomi Authorized Store is the first official Xiaomi store opened in Nigeria, an exclusive store for all Xiaomi smartphones and its AloT products for purchase and repairs. This goes a long way to emphasize how Xiaomi value the Nigeria market by giving opportunity for customers to connect more closely with the brand. With the grand opening today, Xiaomi is giving lots of exciting gifts to anyone who stops at the store to purchase either of the Redmi Note 11 Series or Redmi 10 Series smartphones between the 8th and 10th of August, 2022. Among all kinds of choices to make life much more convenient and easier, the Redmi Note 11 Series and the Redmi 10 Series were launched earlier this year to make the successful series even more competitive. These remarkable devices which come with stronger specs and features and brings powerful upgrades to their camera systems, charging speeds, displays, and etc.- making excellent smartphone performance more accessible than ever. Redmi Note 11 Series: Flagship-level technologies Redmi Note 11 Series feature 108MP primary sensors which allow people to capture and share moments of their life in high resolution and true-to-life details. Boasting a high refresh rate of up to 120Hz and a touch sampling rate of up to 360Hz, Redmi Note 11 series enhances the screen experience with smoother animations and lag-free transitions and it also registers more precise finger touches. The series is equipped with an FHD+ AMOLED DotDisplay which features a DCI-P3 wide color gamut, providing more vibrant colors and details and it also ensures the screen's clarity even in bright daylight.",
    comments: [],
  },
  {
    id: 3708,
    title: "Federal govt bans sim card importation",
    type: "Technology",
    time: "Aug 01",
    author: "Moses O",
    img: "https://static.netnaija.com/i/deYakbRV7P3.jpg",
    body: "The Federal Government of Nigeria has banned the importation of subscriber identity module (SIM) cards. Minister of Communications and Digital Economy, Isa Pantami made the announcement on Monday in Oniru, Lagos. He spoke at the Nigerian Telecommunications Indigenous Content Expo (NTICE) organized by the Nigeria Office for Developing Indigenous Telecoms Sector (NODITS) of the Nigerian Communications Commission (NCC). Pantami said Africa's biggest country should not be importing things that could be produced within. 'Let me make it clear that the federal government will no longer tolerate the importation of sim cards. We are now producing them in Nigeria. 'Our aim is to increase indigenous content in the ICT sector so that by 2025, we will be self-reliant by at least 80 percent', the minister noted. Pantami urged stakeholders and citizens to support government efforts to boost local patronage and consumption. 'If we do this, history will be kind to all of us', the professor of Cybersecurity added. In June, Pantami informed the public that the Buhari administration had established a SIM card manufacturing plant in Lagos. The facility, built with private sector support, has the capacity to produce 200 million cards annually and also export them to other African countries",
    comments: [],
  },
  {
    id: 3709,
    title:
      "The Highly Anticipated Flagship Xiaomi 12 Series Is Coming to Nigeria",
    type: "Technology",
    time: "Mar 10",
    author: "Same Emmanuel",
    img: "https://static.netnaija.com/i/pJdN9zeLK4P.jpg",
    body: "Xiaomi's 12 series boasts Snapdragon® 8 Gen 1 Mobile Platform and powerful imaging capabilities. The Xiaomi Corporation announced today that its latest set of flagship phones, the Xiaomi's 12 Series, will launch in Nigeria market on March 15th 2022. With extremely competitive features, the highly anticipated series has received global attention with markets now eagerly waiting for the premium smartphones to arrive on their shores. The Xiaomi 12 Series is powered by the most potent Snapdragon 8 Gen 1 chipset. The premium series is designed to empower the way you live. A combination of advanced technology and elegant style, the phone helps you record precious moments through exceptional pictures, entertain with excellent audio speakers, and save time for the more important things in life, with its super-fast wired and wireless charging. Xiaomi is relentless in its pursuit of perfection, constantly refining and enhancing its products to create the best user experience possible. By manufacturing top quality products with fair prices and to support customers worldwide to enjoy a better life through innovative technology, the company is able to satisfy the diverse needs of all its consumers and to make their lives simpler.",
    comments: [],
  },
  {
    id: 3710,
    title: "4 Exciting New Features To Anticipate On Whatsapp",
    type: "Technology",
    time: "Nov 03, 2019",
    author: "Same Emmanuel",
    img: "https://img.netnaija.com/hsi/aHR0cHM6Ly9ndWFyZGlhbi5uZy93cC1jb250ZW50L3VwbG9hZHMvMjAxOS8xMC9XaGF0c0FwcC5qcGc=/images/WhatsApp.jpg",
    body: "Whatsapp has become one of the most used social media platforms and as such continues to bring cheer to its Android, iOS users with its new features. However, when it comes to new features, WhatsApp initially tests them on beta versions; these features, even though unreleased include: Disappearing Messages WhatsApp is working on a new feature called 'disappearing messages', that will be available in next updates. As the name suggests, any message eligible to be 'disappeared', will be automatically deleted from the chat! How is a message eligible to be 'disappeared'? At present, when the chat is marked as 'disappeared' all messages will be automatically removed after a certain interval. The user can mark the chat as 'disappeared' enabling the option 'Disappearing messages', in Group Info (when the feature will be available for everyone), and easily disable the it in the same way. Hide Muted Status WhatsApp will soon roll out the feature that not only enables users to mute status updates but hide them after doing so. The beta version is being rolled out on Android and it could soon be seen in other versions of WhatsApp too. To access the feature the user will have to click on a new button 'hide' that will be visible on top of the muted status updates section. If the user wants to restore the visibility of hidden muted status updates, he or she can do that by clicking on 'show'. New Group Privacy In April this year, WhatsApp had rolled out a feature called Group Privacy Settings. This helps a user stay away from getting added to unwanted WhatsApp groups. Now, according to the report, the update, New group privacy, will replace 'Nobody' with 'My contacts except'. With this change, a user will be able to select a set of contacts who won't be able to add the user to any group. Dark Mode One of the much-awaited features by WhatsApp users is the Dark mode. The social messaging service platform, which is working on a dark mode for the app, hasn't confirmed by when the feature will be ready. However, for users who have updated WhatsApp with the dark theme but no dark mode, there is no cause for alarm as it is still under development.",
    comments: [],
  },
  {
    id: 3711,
    title:
      "Binance Responds to #BinanceStopScamming Trend With a Letter to Nigerians",
    type: "Technology",
    time: "Jan 29",
    author: "Same Emmanuel",
    img: "https://static.netnaija.com/i/deYakA2qKP3.png",
    body: "Dear Nigerian Binancians, The Nigerian community is one that brings me great pride. Since the inception of Binance, Nigeria and Africa at large have been very special markets to us and for crypto. On hearing the concerns raised by the community, I decided to write to re-emphasize our commitment to you. First and foremost, we are sorry for the inconvenience caused by delays in resolving your customer support requests. User security remains our top priority. We love and are devoted to our Nigerian community, but we must ensure that our users are safe. As such, protection mechanisms such as KYC, anti-money laundering measures, collaboration with law enforcement, and account restrictions are in place to ensure our community remains protected and that fraudulent activity is prevented. This is a global approach applied in every country. Some 281 Nigerian accounts have been affected by these personal account restrictions with approximately 38% of these cases restricted at the request of international law enforcement. Regardless, we owe it to you, our users, to deliver the experience you deserve. Your trust in us is important -- and here's what we're doing to rebuild that trust: Ensuring speedy resolutions of ongoing user cases tied to account restrictions: Currently, we have resolved 79 cases and continue to work through others. All non-law enforcement-related cases will be resolved within two weeks. Devoting more customer service personnel to the region: We will dedicate more CS and risk agents with a great understanding of the Nigerian market. Rest assured, we are working hard to attend to all customer service requests Thank you for your continued support and patience.",
    comments: [],
  },
  {
    id: 3712,
    title:
      "Nigeria lifts Twitter suspension after more than six-month clampdown",
    type: "Technology",
    time: "Jan 12",
    author: "Same Emmanuel",
    img: "https://static.netnaija.com/i/9bVNrp9D7Wv.jpg",
    body: "The Nigerian Government has lifted the suspension of Twitter operations in the country, months after it announced a clampdown on the social media platform. The suspension was lifted after Twitter agreed to establish 'a legal entity in Nigeria during the first quarter of 2022', the director-general of National Information Technology Development Agency Kashifu Inuwa Abdullahi said in a statement on Wednesday. Abdullahi headed the Nigerian team that negotiated with Twitter. Apart from establishing offices in Nigeria, the Nigerian government said Twitter has also agreed to pay applicable tax in the country and 'appoint a designated country representative to interface with Nigerian authorities.' 'The Federal Government of Nigeria (FGN) directs me to inform the public that President Muhammadu Buhari, GCFR, has approved the lifting of the suspension of Twitter operation in Nigeria effective from 12am tonight, 13th January 2022,' Abdullahi said. 'The approval was given following a memo written to the President by the Honourable Minister of Communications and Digital Economy, Prof Isa Ali Ibrahim. 'In the Memo, the Minister updated and requested the President's approval for the lifting based on the Technical Committee Nigeria-Twitter Engagement's recommendation.' Nigeria banned Twitter in June, days after the platform deleted a remark from Buhari's account, provoking outcry over freedom of expression in Africa's most populous country. Nigerian officials defended the ban saying Twitter was used to promote fake news and for destabilising activities, especially by separatists in the southeast. Buhari's government and Twitter have been in talks over a list of conditions for ending the suspension, including discussions on taxes, content, and registering locally in Nigeria. 'The issues are being addressed and I have directed that the suspension be lifted, but only if the conditions are met to allow our citizens to continue the use of the platform for business and positive engagements,' Buhari said in a speech marking Nigeria's independence day.",
    comments: [],
  },
  {
    id: 3713,
    title: "FG set to lift ban as Twitter meets conditions",
    type: "Technology",
    time: "Jan 04",
    author: "Same Emmanuel",
    img: "https://static.netnaija.com/i/W4lNmeDmNRo.jpg",
    body: "The ban on Twitter operation in the country may soon be lifted as the social media giant has reportedly met six conditions imposed on it by the Nigerian government. The Nation reported that the Technical Committee raised by the government to resolve the impasse between the two parties is fine-tuning the offers by the micro blogger before making a final recommendation to President Muhammadu Buhari. It was also reported that though the President has agreed in principle that Twitter's social networking operation be restored in Nigeria, he is awaiting the report of the committee to lift the ban it imposed on Twitter on June 4, last year. There are also speculation that the federal government might amend the National Broadcasting Commission (NBC) Act to include Facebook, Instagram, WhatsApp and other social media platforms. Some of the conditions Twitter agreed to include; Open an office in Nigeria Have a country representative Register with the Corporate Affairs Commission (CAC)/get National Broadcasting Commission's licence Payment of fair taxes Sensitive to national security and cohesion. It must not undermine the nation's security Train Nigerian IT personnel and strategic intelligence officers on how to report twitter abuse /infractions noticed by the government. A source told the publication; 'From the records, Twitter has finally met six conditions set by the Federal Government for the lifting of the ban on its service in Nigeria as at the close of business in 2021. 'The operation of Twitter will now be fully regulated, including opening of office and deployment of a Country Representative. We can now hold an officer responsible for any infraction. 'Twitter only requested that the Federal Government should allow it to open the office in 2022 because there was no provision for it in its last year's budget. Since we are in a new year, we are expecting that the office will take off soon. 'With payment of taxes, we are hopeful that the government will earn enhanced revenue from Twitter. This ban has helped to correct the lapses of the past. For instance, Twitter has been raking huge cash from Nigeria without legal backing and compliance with our revenue laws. 'Although it was alleged that Nigerians have lost over N6billion to the ban but the Federal Government has lost much more in revenue. 'In spite of recourse to VPN by some users in Nigeria, Twitter revenue slumped considerably because this alternative does not fetch income to it. 'Now, the era of impunity is gone. Twitter must register with CAC and operate in Nigeria as a business concern which it is in other parts of the world.'",
    comments: [],
  },
  {
    id: 3714,
    title:
      "Twitter co-founder Jack Dorsey appoints three Nigerians to lead Bitcoin trust fund",
    type: "Technology",
    time: "Dec 16, 2021",
    author: "Same Emmanuel",
    img: "https://static.netnaija.com/i/LqXNEnJyKlE.jpg",
    body: "Twitter co-founder Jack Dorsey has appointed three Nigerians to the board of the Bitcoin (BTrust) trust fund. Dorsey, who resigned as Twitter CEO in late November, formed the Bitcoin trust fund in partnership with American hip-hop star Jay Z. 'I'm so grateful for you all and so inspired,' Dorsey tweeted on Wednesday while announcing the leaders of the Bitcoin trust fund. The Nigerians appointed into the Bitcoin trust fund are Abubakar Nur Khalil, Obi Nwosu, Ojoma Ochai, and South African, Carla Kirk-Cohen. All four have worked to promote bitcoin development efforts across Africa. Dorsey said a team selected the four developers from a pool of 7,000 applicants. 'They'll now work towards defining the operating principles as they think about how to best distribute the 500 bitcoin towards development efforts,' Dorsey tweeted. Dorsey and Jay Z had previously announced their intention to give 500 BTC to set up ₿trust, an endowment to fund bitcoin development with a starting focus on teams based in Africa and India. The former Twitter CEO has been a long-time supporter of Bitcoin and added the cryptocurrency to the payment platforms of his payments firm, Block. He had consistently hinted about spearheading a global push for cryptocurrency acceptance amid stiff opposition by countries, including Nigeria where three of his BTrust leaders are from. Dorsey in June 2021 said 'the people of Nigeria will lead bitcoin' despite the Nigerian authorities clamping down on the trading of cryptocurrencies with a ban in place by the Central Bank of Nigeria (CBN). The Nigerian government's stance against cryptocurrency trading extends to fintech companies and traditional banks serving as a gateway for trading and exchange of funds. CBN in February 2021 ordered banks to identify and close down all accounts involved in the transfer or exchange of cryptocurrencies and reminded 'regulated financial institutions that dealing with cryptocurrencies or facilitating payments for cryptocurrency exchanges is prohibited.' Despite the ban, many young Nigerians are circumventing the ban to continue buying and selling cryptocurrencies as the country's currency, the naira, continues to slide against the dollar. Nigeria ranks as the third country with the highest volume of cryptocurrency trading - over 400 million - only behind the United States and Russia, according to Statista, a global market data tracker",
    comments: [],
  },
  {
    id: 3715,
    title: "CEO Jack Dorsey leaves Twitter 'effective immediately'",
    type: "Technology",
    time: "Nov 29, 2021",
    author: "Same Emmanuel",
    img: "https://static.netnaija.com/i/no4NXedeK9M.webp",
    body: "Twitter Co-Founder, Jack Dorsey, has resigned as Chief Executive Officer, CEO, of the firm after 16 years at the social media company, to be replaced by chief technology officer, CTO, Parag Agrawal. Meanwhile, Twitter's shares rose 11% after the news broke. The company said Dorsey would step down immediately, but remain on the board until Twitter's stockholder meeting in 2022. Dorsey said: 'I've decided to leave Twitter because I believe the company is ready to move on from its founders. 'My trust in Parag as Twitter's CEO is deep. His work over the past 10 years has been transformational. 'I'm deeply grateful for his skill, heart and soul. It's his time to lead,' said Dorsey. His replacement. Agrawal has been with Twitter for a decade and served as CTO since 2017. 'I want to thank the board for their confidence in my leadership and Jack for his continued mentorship, support, and partnership,' said Agrawal. In his most recent tweet on the site, posted Sunday, Dorsey wrote: 'I love Twitter.' In an email to staff on Monday Dorsey wrote that after 16 years at the company, it was time to leave. 'There's a lot of talk about the importance of a company being 'founder-led'. 'Ultimately I believe that's severely limiting and a single point of failure,' he wrote. 'I've worked hard to ensure this company can break away from its founding and founders.' Dorsey said Agrawal was his preferred choice for CEO. 'My trust in him as CEO is bone-deep,' he wrote. 'I want you all to know this was my decision and I own it.' Dorsey, 45, co-founded the microblogging site in 2006 and posted the world's first tweet: 'Just setting up my twttr.' He co-founded Square in 2009 after being pushed out of the top job at Twitter before returning as chief executive of the social media company in 2015",
    comments: [],
  },
  {
    id: 3716,
    title: "Twitter has agreed to all FG's conditions - Festus Keyamo",
    type: "Technology",
    time: "Nov 29, 2021",
    author: "Same Emmanuel",
    img: "https://static.netnaija.com/i/mr9KYd2mNq6.webp",
    body: "Festus Keyamo, Minister of State for Labour and Employment, said that Twitter, the social media platform banned by the Federal Government of Nigerian in June 2021, has agreed to conditions laid out by the government to lift the ban. Speaking during an interview with Channels Television on Sunday, Nov. 28, Keyamo said the committee set up by the Federal Government to review the operations of Twitter has made significant progress. Keyamo, who is also a member of the committee, said: 'The reason the president took that step is to recalibrate our relationship with Twitter and not to drive them away from our country. 'That recalibration, we have started it and the President graciously added me to the committee. 'We also set up a technical committee to interface with Twitter and come up with a lot of conditions for them to fulfill for us to lift the suspension. 'It was Twitter that reached out to the Federal Government to say they want to know what and what they can do to straighten up the relationship with the Federal Government and so, we have gone far but I may not, at this forum, let out a lot but we gave them a lot of conditions and they have agreed to all the conditions.'",
    comments: [],
  },
];
