export const worldData = [
  {
    id: 3601,
    title: "Rishi Sunak emerges UK's Prime Minister",
    type: "World",
    time: "Oct 24",
    author: "Moses O",
    img: "https://static.netnaija.com/i/mr9KYqoLKq6.jpg",
    body: "Rishi Sunak has emerged the new Prime Minister of the United Kingdom. Recall that Liz Truss, former Prime minister, had resigned, saying she could no longer deliver the mandate on which she was elected by the conservative Party. According to an announcement made by Sir Graham Brady, only one nomination was received by the 1922 Committee for the new leader of the party, and backed by 100 MPs. Sir Brady, therefore, declared Sunak to be the next party leader, and consequently the new Prime Minister.",
    comments: [],
  },
  {
    id: 3602,
    title: "Liz Truss Resigns As UK Prime Minister",
    type: "World",
    time: "Oct 20",
    author: "Same Emmanuel",
    img: "https://static.netnaija.com/i/x5PKDXeqKnM.png",
    body: "Liz Truss announced her resignation as the prime minister of the United Kingdom on Thursday after more and more people in her party asked her to step down. In a statement outside Downing Street, Liz Tuss said she was resigning because she could not do what she was elected to do and had informed the British monarch, King Charles, about her resignation. 'We set out a vision for a low tax, high growth economy that would take advantage of the freedoms of Brexit. I recognise though, given the situation, I cannot deliver the mandate on which I was elected by the Conservative Party. I have therefore spoken to His Majesty the King to notify him that I am resigning as leader of the Conservative Party,' she said. Liz Truss will serve as Prime Minister until a new Conservative Party leader is chosen. She said that a party leadership election will be held within a week to 'ensure that we remain on a path to deliver our fiscal plans and maintain our country's economic stability and national security.'",
    comments: [],
  },
  {
    id: 3603,
    title:
      "Ukraine tells Elon Musk to 'f-k off' after he shared peace proposal to end war with Russia",
    type: "World",
    time: "Oct 04",
    author: "Same Emmanuel",
    img: "https://static.netnaija.com/i/wk37lzdjNPd.jpg",
    body: "Billionaire, Elon Musk has shared a 'peace plan' for the Russia-Ukraine war to end. But his proposal was quickly met with backlash-including from Ukrainian President Volodymyr Zelensky. The world's richest man and Tesla founder on Monday, October 3, suggested elections in the annexed regions under United Nations supervision. 'Russia leaves if this is the will of the people,' he said. He also said Crimea, the Ukranian city annexed by Russia in 2014 originally belonged to Russia until a 'mistake' by former Soviet Union premier, Nikita Khrushchev. He called for the Crimea to formally become part of Russia. Then, he said Crimea's water supply should be assured. And lastly, he argued, Ukraine should remain neutral rather than joining NATO. Musk then shared a Twitter poll asking his followers to give their opinion on his suggestion. 'Crimea formally part of Russia, as it has been since 1783 (until Khrushchev's mistake),'  He also opined that Ukraine should remain neutral and asked followers to reply with their recommendations in 'yes and no'. 'This is highly likely to be the outcome in the end ' just a question of how many die before then,' Musk said. He added that the war could turn nuclear although it is unlikely.",
    comments: [],
  },
  {
    id: 3604,
    title:
      "Russia-Ukraine war: Multiple Russian missiles bombard Kyiv and four other Ukranian in response to Crimea bridge attack (photos/videos)",
    type: "World",
    time: "Oct 10",
    author: "Same Emmanuel",
    img: "https://static.netnaija.com/i/qEQN24wz76W.jpg",
    body: "Russia has responded to the attack on the Crimean bridge over the weekend, sending multiple missiles to five Ukranian cities including the capital Kyiv on Monday morning, October 10. Large explosions were heard in Kyiv, Lviv, Ternopil, Dnipro, Zhytomyr, and Zaporizhzhia. Posting on his telegram account, Ukraine's president, Volodymyr Zelenskyy wrote; 'On the 229th day, they are trying to destroy us and wipe us off the face of the Earth. In general, destroy our people who are sleeping at home in Zaporizhzhia. Kill people who go to work in Dnipro and Kyiv. 'The air alarm does not subside throughout Ukraine. There are missiles hitting. Unfortunately, there are dead and wounded. Please do not leave shelters. Take care of yourself and your loved ones. Let's hold on and be strong.' Kyiv's mayor Vitali Klitchko also sent a post, saying: 'The capital is under attack from Russian terrorists! 'The rockets hit objects in the city centre (in the Shevchenkiv district) and in the Solomyan district. The air alert, and therefore the threat, continues. 'I appeal to all residents of the capital: stay in shelters during the alarm. If there is no urgent need, it is better not to go to the city today.'",
    comments: [],
  },
  {
    id: 3605,
    title: "Putin says response to Ukrainian attacks will be 'severe'",
    type: "World",
    time: "Oct 10",
    author: "Same Emmanuel",
    img: "https://static.netnaija.com/i/yMX7y9PY783.jpg",
    body: "President Vladimir Putin said on Monday that Russia's response to any further Ukrainian attacks would be 'severe', after Moscow's forces carried out retaliatory missile strikes across Ukraine. 'It was not possible to leave (Ukrainian attacks) unanswered. If attempts at terrorist attacks continue, the response from Russia will be severe and correspond to the level of threat,' Putin said at the start of a televised meeting of his security council. 'Let there be no doubt about it,' Putin said. His remarks come after a huge blast on Saturday damaged a key bridge in Crimea, Putin's flagship project and a vital transport link between Russia and the peninsula Moscow annexed in 2014. In response to the attack, Putin said Russia carried out 'a massive strike with high-precision, long-range weapons ... on energy, military command and communications facilities in Ukraine'. Putin also accused Ukraine of launching three attacks on the Kursk nuclear power plant in Russia, about 85 kilometres (53 miles) from the Ukrainian border and of attempting to hit the TurkStream gas pipeline running from Russia to Turkey under the Black Sea. Ukraine's capital Kyiv was hit by multiple Russian strikes early on Monday - the first since late June, AFP journalists witnessed. Russia also launched attacks on several other cities across Ukraine, particularly targeting energy infrastructure. Electricity cuts were reported in several regions, including Ukraine's second city Kharkiv and its surrounding region, plus the northeastern Sumy region, Zhytomyr region in the north and Khmelnitskyi region in the west.",
    comments: [],
  },
  {
    id: 3606,
    title: "War: Vladimir Putin begins formal annexation of Ukraine regions",
    type: "World",
    time: "Sep 30",
    author: "Moses O",
    img: "https://static.netnaija.com/i/x5PKDDn9KnM.webp",
    body: "The Russian President, Vladimir Putin, is set to stage a ceremony in an ornate Kremlin hall to announce Russia's rule over around 15% of Ukraine, the biggest European annexation since World War II. Putin disclosed that the four Ukrainian regions would remain 'Russian forever'. The annexation is coming on the heels of referendums in Donetsk, Luhansk, Kherson and Zaporizhzhia, which the West countries have slammed as illegal. However, Volodymyr Zelenskyy, Ukraine's President, has hit out at the move, saying that Putin wanted a war more than life. UN chief Antonio Guterres also called it a dangerous escalation and a violation of the United Nations charter. It comes as Ukrainian forces partially surround a strategic city in eastern Ukraine. Meanwhile, a Russian rocket attack killed at least 25 in Zaporizhzhia, while another 50 were wounded.",
    comments: [],
  },
  {
    id: 3607,
    title: "US capitol Washington DC declares October 1 Nigerian-American Day",
    type: "World",
    time: "Sep 30",
    author: "Moses O",
    img: "https://static.netnaija.com/i/gEeK8xDzKP8.jpg",
    body: "The City of Washington D.C. in the United States has proclaimed October 1 as Nigerian-American Day. The declaration is in consonance in celebration of Nigeria's 62nd Independence Day anniversary. The proclamation was made in a statement by the Mayor of Washington DC, Muriel Bowser. Bowser noted that the District of Columbia had one of the largest Nigerian immigrant populations in America. The Mayor hailed the contributions of Nigerian-Americans some of whom are civic leaders, innovators, and entrepreneurs. Bowser said Nigerian music and art, particularly Afrobeats and Nollywood, enrich the cultural economy and strengthen cultural ties. The Nigerian Center provides a platform for heritage preservation and expands the pathways for Nigerian immigrants to become Nigerian-Americans. 'The city's Office on African Affairs works with the Nigerian Center to foster economic inclusion and advancement and to promote Nigerian culture', Bowser noted. The Nigerian Center is the first immigrant and cultural center for the Nigerian diaspora in America. The establishment offers financial inclusion and social justice opportunities for members of the Nigerian-American community in the U.S..",
    comments: [],
  },
  {
    id: 3608,
    title:
      "Russia-Ukraine war: US will never recognize Russia's annexation attempts - Joe Biden vows",
    type: "World",
    time: "Sept 30",
    author: "LuvlyGist",
    img: "https://static.netnaija.com/i/zxG7ZDXdNq2.webp",
    body: "The United States will 'never, never, never' recognize Russia's attempt to annex territory in Ukraine, President Joe Biden has vowed. Biden made the vow ahead of a speech on Friday, September 30 from Russian president, Vladimir Putin, who is due to declare that four occupied Ukrainian regions are now part of Russia. The Kremlin says Luhansk, Donetsk, Zaporizhzhia and Kherson supported annexation in five-day referendums which have been widely condemned by the West as a sham. In a speech on Thursday night, Biden said the US will impose new sanctions on Russia as a result of the annexation. 'The United States, I want to be very clear about this, will never, never, never recognise Russia's claims on Ukraine sovereign territory,' On Thursday, the Russian president signed two decrees recognising Zaporizhzhia and Kherson as independent territories - paving the way for them to be annexed. The documents, shared on Russian state media, say the independence of the two regions is being recognised in accordance with international law and 'enshrined in the Charter of the United Nations'.",
    comments: [],
  },
  {
    id: 3609,
    title:
      "Johnny Depp is dating lawyer who represented him in UK in Amber Heard defamation trial",
    type: "World",
    time: "Sept 22",
    author: "LuvlyGist",
    img: "https://static.netnaija.com/i/gEeK8xX8KP8.jpg",
    body: "Actor Johnny Depp is reportedly dating one of the lawyers who represented him in his defamation case against his ex-wife, Amber Heard. TMZ reported that Johnny is dating an attorney named Joelle Rich, who repped him in the UK trial that he lost. Rich is married but now in the process of getting divorced. She and her estranged husband share 2 kids. Us Weekly reported that though she was not part of the Virginia trial team that beat Amber Heard, but she was present in court for 'support'. Rich's bio says she 'works to defend [clients'] reputations against false and defamatory allegations in print, online, and on social media.' It goes on to say she has 'particular expertise in protecting individuals' privacy from unwarranted intrusion and media attention.'",
    comments: [],
  },
  {
    id: 3610,
    title:
      "Queen's death ​will be felt ​​​by countless people worldwide - King Charles III",
    type: "World",
    time: "Sept 09",
    author: "Moses O",
    img: "https://static.netnaija.com/i/rOx7xx9b70M.jpg",
    body: "King Charles III has said the death of Queen Elizabeth II on Thursday will be felt by people across the world. The new king, whose title has been confirmed by Prime Minister Liz Truss, paid a tribute to his late mother in a statement. Elizabeth II was Britain's longest-reigning monarch; the late Commonwealth leader served as head of State for more than 70 years. Charles described her passing as a moment of the greatest sadness for him and all the members of the family. 'I know her loss will be deeply felt throughout the country, the Realms and the Commonwealth, and by countless people around the world,' he said. Charles said he would be comforted and sustained by the knowledge of the respect and deep affection in which the Queen was widely held. His wife, the Duchess of Cornwall, is now Queen, and will be crowned at Charles's side at his eventual coronation. Formerly Prince of Wales, 73-year-old monarch, who was married to the late Lady Diana Spencer, served in the Royal Air Force.",
    comments: [],
  },
  {
    id: 3611,
    title:
      "See shocking before and after photos of Ukranian soldier recently released in prisoner swap after four months in Russian captivity",
    type: "World",
    time: "Sep 24",
    author: "LuvlyGist",
    img: "https://static.netnaija.com/i/Aq2NArEOKzJ.jpg",
    body: "The Ukranian Ministry of defence has released shocking photos showing the devastating condition of a Ukranian soldier captured by Russia. Mykhailo Dianov, a Ukrainian soldier was released on Wednesday, September 21 by the Russian government after the UAE helped broker a prisoner exchange between Ukraine and Russia. Before the capture. Before his capture, Mykhailo Dianov, helped defend the Azovstal plant in Mariupol. He trended in Ukraine after the release of a photo where he smiles despite the serious injury to his arm inside the Azovstal steelworks during the early stages of the war... After four months in Russian prison, Diano said he did not receive any adequate medical help according to the Russian ministry of defence. After release,The Ukranian ministry of defence tweeted on Friday evening:-'Ukrainian soldier Mykhailo Dianov is among the fortunate ones: in contrast with some of his fellow POWs, he survived russian captivity. This is how russia 'adheres' to the Geneva Conventions. This is how russia continues the shameful legacy of Nazism.'",
    comments: [],
  },
  {
    id: 3612,
    title: "A Real-Life 'Squid Game' Is Being Organized In Abu Dhabi",
    type: "World",
    time: "Oct 12, 2021",
    author: "Same Emmanuel",
    img: "https://static.netnaija.com/i/AqgKGqbnar1.jpg",
    body: "As the fever of the wildly popular 'Squid Game' series sweep across the world, fans may have the opportunity to experience a real-life harmless version of the game in Abu Dhabi. The Korean Cultural Center in the United Arab Emirates is organizing a reenactment of the games seen in the Netflix series for two teams of 15 participants. The event is slated to be held in two sessions on October 12 at the center's Abu Dhabi office. 'Squid Game' premiered on Netflix on September 17 and skyrocketed to the No. 1 spot in the US, Netflix's public rankings showed. The show is a Korean-language drama centers on a contest where 456 players, drawn from different walks of life but each deeply in debt, play a set of children's games with deadly penalties for losing with the chance to win a ₩45.6 billion ($38 million) prize. The center's event page said four out of the six games seen in the Netflix series would be played during the event. These include the 'Red Light, Green Light' and 'Dalgona Candy' challenges, both of which spawned trends on TikTok. Players would also get to try their hand at the 'Marbles' and 'Ddakji' (paper-flipping) games seen in the series.",
    comments: [],
  },
  {
    id: 3613,
    title:
      "'I looked at the crowd but couldn't see anyone' - Chichi tears up as she recounts grand finale events",
    type: "World",
    time: "Oct 11",
    author: "Moses O",
    img: "https://static.netnaija.com/i/zxG7Z0vvNq2.webp",
    body: "Season 7 finalist, Chichi has opened up about the reason she found it difficult to answer one of Ebuka's questions at the grand finale. Recall that Ebuka has asked Chichi who she was excited to see at the finale but she failed to answer and moved on to the next.",
    comments: [],
  },
  {
    id: 3614,
    title: "Queen Elizabeth II has died, aged 96",
    type: "World",
    time: "Sep 08",
    author: "Same Emmanuel",
    img: "https://static.netnaija.com/i/bvWaqQnyark.jpg",
    body: "Queen Elizabeth II, Britain's longest-reigning monarch and the nation's figurehead for seven decades, has died aged 96, Buckingham Palace said on Thursday. Her family gathered at her Scottish estate after concerns grew about her health earlier on Thursday. The Queen came to the throne in 1952 and witnessed enormous social change. With her death, her eldest son Charles, the former Prince of Wales, will lead the country in mourning as the new King and head of state for 14 Commonwealth realms. In a statement, Buckingham Palace said: 'The Queen died peacefully at Balmoral this afternoon. 'The King and the Queen Consort will remain at Balmoral this evening and will return to London tomorrow.' All the Queen's children travelled to Balmoral, near Aberdeen, after doctors placed the Queen under medical supervision. Her grandson, Prince William, is also there, with his brother, Prince Harry, on his way. Queen Elizabeth II's tenure as head of state spanned post-war austerity, the transition from empire to Commonwealth, the end of the Cold War and the UK's entry into - and withdrawal from - the European Union. Her reign spanned 15 prime ministers starting with Winston Churchill, born in 1874, and including Liz Truss, born 101 years later in 1975, and appointed by the Queen earlier this week. She held weekly audiences with her prime minister throughout her reign. The Queen was born Elizabeth Alexandra Mary Windsor, in Mayfair, London, on 21 April 1926.",
    comments: [],
  },
  {
    id: 3615,
    title: "Prince Charles succeeds Queen Elizabeth as king",
    type: "World",
    time: "Sep 08",
    author: "Moses O",
    img: "https://static.netnaija.com/i/Wz27WOrM75R.webp",
    body: "Following the death of Queen Elizabeth II, the longest-serving monarch in British history, her eldest son, Prince Charles has reportedly emerged as King of England. We reported that Queen Elizabeth, an icon recognisable to billions of people around the world, died on Thursday. According to an announcement made by Buckingham on Thursday, she died peacefully at the age of 96. The Guardian reports that her eldest son, Charles, 73, succeeds the Queen as king with immediate effect.",
    comments: [],
  },
  {
    id: 3616,
    title: "Liz Truss succeeds Boris Johnson as UK Prime Minister",
    type: "World",
    time: "Sep 05",
    author: "Moses O",
    img: "https://static.netnaija.com/i/AqgKGQ11ar1.jpg",
    body: "Liz Truss, 47, has been elected as the new Prime Minister of the United Kingdom. Truss defeated Rishi Sunak by 81,326 votes to 60,399 in an internal contest after Boris Johnson's resignation in July. The lawmaker will become the Conservatives' fourth head of the British government since 2015. Truss promised to 'unleash Britain's potential by going for growth and removing the obstacles holding our country back'. The new leader insisted that a growing economy is key to delivering for the British people and unlocking opportunity. Truss promised to take bold action to guide the people through what she called these tough times'. 'I am honoured to be elected Leader of the Conservative Party', the former Foreign Secretary said. 'Thank you for putting your trust in me to lead and deliver for our great country.' Truss, a former Minister for Women and Equalities, has been Member of Parliament for South West Norfolk since 2010.",
    comments: [],
  },
];
