export const bluesData = [
  {
    id: 5201,
    type: "Blues",
    song: "Spax - Kowole (feat. Dami Krane & Spellz)",
    time: "Oct 13, 2014",
    title: "Kowole (feat. Dami Krane & Spellz)",
    singer: "Spax",
    year: "2014",
    comments: [],
    body: "Kowole is the first official single from SPAX’S forthcoming EP. This feel good RnB tune features producer, singer and songwriter SPELLZ of 323 entertainment and contemporary fuji star DAMMY KRANE of Hypertek Digital.",
    img: "https://img.netnaija.com/v-KHHK.thumb.jpg",
  },
  {
    id: 5202,
    type: "Blues",
    song: "Chiny - Sunny Bobo",
    time: "Oct 01, 2014",
    title: "Sunny Bobo",
    singer: "Chiny",
    year: "2014",
    producer: "Magik",
    body: "‘Chiny’ real names Chinonso Ijeoma Izuka, an eclectic songwriter and performer who doubles as a fashion model and a building technologist with great enthusiasm for music from way back in her university days, known for her dope singles “That girl” and a feature with “Bad Mama” star Spotlyt and ??“Where u dey go”? with rapper Young Slick is back again to whet your music appetite with a certified hit “Sunny Bobo” meant to hit you hard as she debuts with a new single for the crazy lovers out there.‘Sunny Bobo’, a touching R & B Love song and story is set to blow your mind away. Produced and mixed by 6th Avenue Magik, Video has already been shot and would be released soon.",
    comments: [],
    img: "https://img.netnaija.com/VkKHHK.thumb.jpg",
  },
  {
    id: 5203,
    type: "Blues",
    song: "Jazmine Sullivan - Forever Don't Last",
    time: "Sep 04, 2014",
    title: "Forever Don't Last",
    singer: "Jazmine Sullivan",
    year: "2014",
    body: "After going “Dumb” with the currently incarcerated Meek Mill, Jazmine Sullivan returns with the song “Forever Don’t Last.” Serving as the second single from her forthcoming Reality Show LP, the powerful Philly songstress displays her emotions and moving vocals over a soft acoustic jam.A record relatable to many listeners on the subject of relationships coming to an end, click below as listen to Sullivan’s new offering.",
    comments: [],
    img: "https://img.netnaija.com/PRKHHK.thumb.jpg",
  },
  {
    id: 5204,
    type: "Blues",
    song: "Tolu - My Lover",
    time: "Aug 31, 2014",
    title: "My Lover",
    singer: "Tolu",
    year: "2014",
    producer: "Don Jazzy",
    body: "MTN Project Fame finalist Tolu Adesina who is a vocalist, producer and songwriter teams up with Mavin boss Don Jazzy on this new melodious R&B track titled “My Lover”",
    comments: [],
    img: "https://img.netnaija.com/0LKHHK.thumb.jpg",
  },
  {
    id: 5205,
    type: "Blues",
    song: "Paul Play - Fool In Love",
    time: "Aug 04, 2014",
    title: "Fool In Love",
    singer: "Paul Play",
    year: "2014",
    body: "Afro-R&B faithful Paul Play resurfaces with a high-life influenced R&B number on his he declares that he is a 'Fool In Love'. 'Fool In Love' is different from his last single 'We Are Nigerians', unlike the conscious track which featured Tunde of Styl-Plus, 'Fool In Love' is a mid-tempo groovy reminiscent of his many signature tracks.",
    comments: [],
    img: "https://img.netnaija.com/PbHHHK.thumb.jpg",
  },
  {
    id: 5206,
    type: "Blues",
    song: "Miguel - How Many Drinks (feat. Kendrick Lamar)",
    time: "Dec 24, 2013",
    title: "How Many Drinks (feat. Kendrick Lamar)",
    singer: "Miguel",
    year: "2013",
    body: "Enjoy!",
    comments: [],
    img: "https://img.netnaija.com/hsi/aHR0cDovLzQuYnAuYmxvZ3Nwb3QuY29tLy1WaXpDLUkyMzVZVS9VVzJrZWlCaU1XSS9BQUFBQUFBQUEwYy9IR3JUM0tfbFI4dy9zMTYwMC9ibG9nLmpwZw==/images/blog.jpg",
  },
  {
    id: 5207,
    type: "Blues",
    song: "Labrinth - Beneath Your Beautiful (feat. Emeli Sande)",
    time: "Mar 31, 2013",
    title: "Beneath Your Beautiful (feat. Emeli Sande)",
    singer: "Labrinth",
    year: "2013",
    body: "This song has been making waves in England and all over the world since its release in November 2012 so I decided to share to those who doesn't already have it.Don't forget to share to your social networks.",
    comments: [],
    img: "https://img.netnaija.com/hsi/aHR0cDovLzEuYnAuYmxvZ3Nwb3QuY29tLy1sTWh2eEw2UFFvRS9VQnJZekNDTVozSS9BQUFBQUFBQUExby9HSWdPUmxMQzZhMC9zMzIwL0xhYnJpbnRoK2VtZWxpK3NhbmRlK2JlbmVhdGgreW91citiZWF1dGlmdWwrbHlyaWNzLmpwZw==/images/Labrinth+emeli+sande+beneath+your+beautiful+lyrics.jpg",
  },
  {
    id: 5208,
    type: "Blues",
    song: "Mariah Carey - Hero",
    time: "Mar 19, 2013",
    title: "Hero",
    singer: "Mariah Carey ",
    year: "2013",
    body: "Download and share!",
    comments: [],
    img: "https://img.netnaija.com/hsi/aHR0cDovLzQuYnAuYmxvZ3Nwb3QuY29tL19iSTUtOFlua2tGQS9URC1yenRrSXg3SS9BQUFBQUFBQUVUYy9Mb0pSaHRyY1dxUS9zMTYwMC8wMC1tYXJpYWhfY2FyZXlfbWFyaWFoX2NhcmV5LTE5OTAtZnJvbnQuanBn/images/00-mariah_carey_mariah_carey-1990-front.jpg",
  },
  {
    id: 5209,
    type: "Blues",
    song: "Mariah Carey - I Wanna Know What Love Is",
    time: "Mar 19, 2013",
    title: "I Wanna Know What Love Is",
    singer: "Mariah Carey",
    year: "2013",
    body: "Download and share!",
    comments: [],
    img: "https://img.netnaija.com/hsi/aHR0cDovLzQuYnAuYmxvZ3Nwb3QuY29tL19iSTUtOFlua2tGQS9URC1yenRrSXg3SS9BQUFBQUFBQUVUYy9Mb0pSaHRyY1dxUS9zMTYwMC8wMC1tYXJpYWhfY2FyZXlfbWFyaWFoX2NhcmV5LTE5OTAtZnJvbnQuanBn/images/00-mariah_carey_mariah_carey-1990-front.jpg",
  },
];
