export const foreignMusicData = [
  {
    id: 5301,
    type: "Foreign Music",
    song: "Rihanna - Lift Me Up",
    time: "Yesterday 9:31am",
    title: "Lift Me Up",
    singer: "Rihanna",
    year: "2022",
    comments: [],
    body: "After a long break from music, Rihanna makes a comeback with a new single titled 'Lift Me Up.' This is the lead single for the 'Black Panther: Wakanda Forever' soundtrack. The song was written by Tems, Rihanna, Ryan Coogler, and Oscar winner Ludwig Göransson. It is a tribute to the life and legacy of the late Chadwick Boseman.",
    img: "https://static.netnaija.com/i/eDxawQqRKPZ.jpg",
  },
  {
    id: 5302,
    type: "Foreign Music",
    song: "DJ Khaled - GOD DID",
    time: "Aug 26",
    title: "GOD DID",
    singer: "DJ Khaled",
    year: "2022",
    body: "DJ Khaled is back with his latest album, God Did. The follow-up to last year's Khaled Khaled features a stacked roster of guests, including JAY-Z and Lil Wayne (on the title track alongside Rick Ross, John Legend, and Fridayy), Drake (on opener 'No Secret'), Future and SZA (on 'Beautiful'), the late Juice WRLD ('Juice WRLD Did'), and more. Khaled also remixed Kanye West's song 'Use This Gospel,' which originally appears on Jesus Is King. The updated track features a verse from Eminem. God Did also includes lead single 'Staying Alive,' featuring Drake and Lil Baby, as well as cuts with Gunna, 21 Savage, and more. The cut titled 'Party All the Time' features a sample of Eddie Murphy's 1985 song of the same name. Listen to God Did below. God Did is DJ Khaled's thirteenth studio LP. Khaled Khaled arrived last spring, with guest spots from Megan Thee Stallion, Post Malone, Justin Timberlake, JAY-Z, Lil Wayne, Lil Baby, DaBaby, Cardi B, and Puff Daddy.",
    comments: [],
    img: "https://static.netnaija.com/i/BQJNjn83NrL.jpg",
  },
  {
    id: 5303,
    type: "Foreign Music",
    song: "Nicki Minaj - Super Freaky Girl",
    time: "Aug 16",
    title: "Super Freaky Girl",
    singer: "Nicki Minaj",
    year: "2022",
    producer: "Password",
    body: "Nicki Minaj is unleashing her inner raunchy side on her new single, 'Super Freaky Girl,' released Friday. The track, which samples Rick James' 1981 hit 'Super Freak,' wastes no time living up to the title, with the opening verses playing over the ubiquitous riff from the throwback track that inspired it. 'I can lick it, I can ride it while you slippin' and slidin' / I can do all 'em little tricks, and keep the dick up inside it / You can smack it, you can grip it, you can go down and kiss it / And every time he leave me 'lone, he always tell me he miss it,' Minaj raps. Before its official release on Friday, a snippet of the song gained popularity on TikTok with an accompanying dance challenge. Minaj also teased the track with a video on social media, to which the official account for the late Rick James responded: 'Banger.' 'Super Freaky Girl' marks the rapper's first release since 'We Go Up' with Fivio Foreign in March. Earlier this year, she also dropped 'Blick Blick' with Coi Leray, and both 'Bussin' and 'Do We Have A Problem' with Lil Baby.",
    comments: [],
    img: "https://static.netnaija.com/i/zxG7Z4mdNq2.jpg",
  },
  {
    id: 5304,
    type: "Foreign Music",
    song: "Tyga, Jhené Aiko & Pop Smoke - Sunshine",
    time: "Aug 16",
    title: "Sunshine",
    singer: "Tyga, Jhené Aiko & Pop Smoke",
    year: "2022",
    body: "Tyga returns with a heavy dose of nostalgia. On Friday, the platinum-selling rapper came through with the summer-ready track 'Sunshine' featuring Jhené Aiko and the late Pop Smoke. Co-produced by Mike Crook and DJ Swish, the song pays homage to Lil Flip's 2004 hit of the same name. Flip appears in the 2000s-inspired video, which also includes a message from Pop Smoke's mother Audrey Jackson and brother Obasi Jackson. 'Pop Smoke was a legend in the making and I wish we could've collaborated together more,' said Tyga, who was featured on Pop Smoke's 'West Coast Shit' track. 'It's a been a great experience working with his mother and brother to pay homage with this song and contributing to keeping his legacy alive-the smoke will never clear.' Pop's brother said 'Sunshine' showcases a different side of the NYC rapper, and underscores the range he possessed as an artist.",
    comments: [],
    img: "https://static.netnaija.com/i/3g8NBJYbNDR.jpg",
  },
  {
    id: 5305,
    type: "Foreign Music",
    song: "Jessie Reyez - MUTUAL FRIEND",
    time: "Aug 16",
    title: "MUTUAL FRIEND",
    singer: "Jessie Reyez",
    year: "2022",
    body: "Jessie Reyez has announced the arrival of her sophomore album, Yessie. The LP will be released on Sept. 16 via FMLY/Island Records. The singer announced the news during her appearance on Jimmy Kimmel Live on Thursday, where she shared a performance of her new single 'Mutual Friend.' In the new song, Jessie Reyez confesses to a mutual friend that there is no love loss between her and her ex. In fact, she has resolutely moved into 'don't give AF' territory. 'If you die tomorrow/I don't think I'd cry, I gave ya one too many nights,' she sings on the chorus. 'Don't care if it sound cold, it is what it is.' The single follows the release of 'Fraud' in June, which was her first new solo music since her debut studio album, Before Love Came to Kill Us in 2020.",
    comments: [],
    img: "https://static.netnaija.com/i/gVpagjZg7wO.jpg",
  },
  {
    id: 5306,
    type: "Foreign Music",
    song: "Tones and I - Charlie",
    time: "Aug 16",
    title: "Charlie",
    singer: "Tones and I",
    year: "2022",
    body: "Tones And I has released her new single 'Charlie' on streaming platforms. Charlie - an upbeat and catchy pop disco track - was debuted last week on the Jimmy Kimmel Live! show. 'I can't believe I'm debuting Charlie on Jimmy Kimmel. I'll take Triple J to play any day, but this is the new one for me,' the musician told Daily Telegraph of releasing 'Charlie' on the internationally renown talk show. Contrary to what some social media users have assumed - The 'Dance Monkey' singer has revealed that the new track is named after her chocolate labrador Charlie, who she misses desperately when she's on tour. 'Charlie doesn't care about the weekend/ Charlie parties every single night/ I swear that Charlie's doing all that he can/ I think that Charlie lives his own life,' the lyrics say.",
    comments: [],
    img: "https://static.netnaija.com/i/XV5Kv6WBK9m.jpg",
  },
  {
    id: 5307,
    type: "Foreign Music",
    song: "Rae Sremmurd - Community D**k (feat. Flo Milli)",
    time: "Aug 16",
    title: "Community D**k (feat. Flo Milli)",
    singer: "Rae Sremmurd",
    year: "2022",
    body: "Ahead of the release of their upcoming fourth studio album Sremm4Life, Swae Lee and Slim Jxmmi enlisted Flo Milli for their new single 'Community D**k.' The track, which arrives alongside an accompanying music video, follows 'Denial,' which dropped in June as the lead single from Sremm4Life. Due out later this year, the project will mark Rae Sremmurd's first full-length offering since 2018, when the duo dropped Sr3mm, the follow-up to 2016's SremmLife 2 and their 2015 debut SremmLife.",
    comments: [],
    img: "https://static.netnaija.com/i/WAPK4EZJ70B.jpg",
  },
  {
    id: 5308,
    type: "Foreign Music",
    song: "Quavo, Takeoff & Gucci Mane - Us vs. Them",
    time: "Jul 29",
    title: "Us vs. Them",
    singer: "Quavo, Takeoff & Gucci Mane",
    year: "2022",
    body: "Confidence can take people far in life, and it only gets boosted more when it is clear no one can compare. Quavo and Takeoff go the duo route once again, this time tapping fellow Atlanta native Gucci Mane for the confident anthem 'Us Vs Them.' Takeoff handles the hook before getting into his verse, followed by Quavo who raps with a fury, and Gucci Mane closes things off with a shoutout to the currently incarcerated Young Thug and Gunna.",
    comments: [],
    img: "https://static.netnaija.com/i/5VrNpweJa9O.jpg",
  },
  {
    id: 5309,
    type: "Foreign Music",
    song: "Beyoncé - RENAISSANCE",
    time: "Jul 29",
    title: "RENAISSANCE",
    singer: "Beyoncé ",
    year: "2022",
    body: "It's finally here! Beyoncé has returned with 'Renaissance,' her much-anticipated seventh studio album, which was released on Friday, July 29, by Columbia Records and Parkwood Entertainment. The pop star put out 'Act 1' of Renaissance, which has 16 tracks.  Nigerian superstar Tems, Ghanaian DJ/record producer GuiltyBeatz, Nigerian-British producer P2J, Jay-Z, Drake, Skrillex, The-Dream, Syd, Lucky Daye, Donna Summer, Giorgio Moroder, Nile Rodgers, Nija Charles, 070 Shake, and others, are included on the writing and production credits.",
    comments: [],
    img: "https://static.netnaija.com/i/1qdNVyM2a4g.jpg",
  },
  {
    id: 5310,
    type: "Foreign Music",
    song: "Chris Brown - Nobody Has To Know (feat. Davido)",
    time: "Jul 08",
    title: "Nobody Has To Know (feat. Davido)",
    singer: "Chris Brown",
    year: "2022",
    body: "American singer, songwriter and dancer, Chris Brown has released a deluxe edition of his latest album 'Breezy'. Off the project, the singer collaborates with Afrobeats superstar Davido on a beautiful piece dubbed 'Nobody Has To Know'.Co-produced by serm.style, Okan and Kevin Hissink, 'Nobody Has To Know' serves as the 30th track on the LP. It comes weeks after Chris Brown's collaboration with Wizkid on the buzzing joint 'Call Me Everday', making Wizkid and Davido the only Afrobeats artists on the 'Breezy' LP.",
    comments: [],
    img: "https://static.netnaija.com/i/90ZNPe1QK8e.jpg",
  },
  {
    id: 5311,
    type: "Foreign Music",
    song: "Cardi B - Hot Shit (feat. Kanye West & Lil Durk)",
    time: "Jul 01",
    title: "Hot Shit (feat. Kanye West & Lil Durk)",
    singer: "Cardi B",
    year: "2022",
    body: "Cardi B has today (June 1) released 'Hot Shit', a Kanye West and Lil Durk-assisted song lifted from the rapper's forthcoming album. The track, which was first confirmed during an advert at the 2022 BET Awards late last month, was produced by hip-hop juggernaut Tay Kieth. On it, Cardi brings her signature bravado before welcoming Durk and West for their own flow-switching verses.",
    comments: [],
    img: "https://static.netnaija.com/i/5wPKLvOQaVB.jpg",
  },
  {
    id: 5312,
    type: "Foreign Music",
    song: "City Girls - Good Love (feat. Usher)",
    time: "Jul 01",
    title: "Good Love (feat. Usher)",
    singer: "City Girls",
    year: "2022",
    body: "Just a week after announcing the summer anthem, City Girls join forces with Usher for their new single 'Good Love.' The track arrives alongside a music video, which features JT, Yung Miami, and Usher show off their skating skills at Atlanta's iconic Cascade roller rink. City Girls had previously teased the collaborative single during a red carpet interview at the Billboard Music Awards. Describing 'Good Love' as a 'party record, fun record, cookout record,' Yung Miami revealed she was a big fan of the R&B legend growing up. 'Growing up, big fan of Usher,' she said. 'Can't wait for everyone to hear the record.'",
    comments: [],
    img: "https://static.netnaija.com/i/mjyK6yL3NwD.jpg",
  },
];
