export const gospelData = [
  {
    id: 5101,
    type: "Gospel Music",
    song: "Mr. M & Revelation - Oga'di Loud",
    time: "Oct 21",
    title: "Oga'di Loud",
    singer: "Mr. M & Revelation",
    year: "2022",
    comments: [],
    body: "It's another praise and prophetic sound from the unrelenting & anointed music group Mr. M & Revelation. Oga'di Loud (It will be Loud) is a prophetic sound and declaration of the things you desire to see and they will happen and it will be very visible that men will know it is God. Oga'di loud is a blend good music and powerful declaration. 'Everything i need your hand supply, Oga'di LOUD' Listen to the new record below.",
    img: "https://static.netnaija.com/i/deYakp1ZNP3.jpg",
  },
  {
    id: 5102,
    type: "Gospel Music",
    song: "Chidinma - Blessings Follow Me (feat. KS Bloom)",
    time: "Oct 03",
    title: "Blessings Follow Me (feat. KS Bloom)",
    singer: "Chidinma",
    year: "2022",
    body: "The multi-talented Nigerian gospel female singer and songwriter widely known as Chidinma unfolds a brand new record captioned, Blessings Follow Me, which features a French talented music entertainer, KS Bloom, who also spiced up the song with cool and wonderful lyrics, that will surely blow your mind. The EeZee Conceptz Global Ministry recording artist, Chidinma comes through with this tune after her record named, 'Osuba', a Yoruba word that literally means 'Highest', as she exalts the God's name full of thanksgiving and worship. Blessings Follow Me is another tremendous entry coming from the revered turned gospel artist, Chidinma together with KS Bloom. Both music entertainers gave in their possible best to ensure that this awesomely-composed record is a remarkable one. Nevertheless, this latest gospel creative output will be part of Chidinma's forthcoming body of work tagged, Psalm 16, which is set to be released on the 14th of October, 2022.",
    comments: [],
    img: "https://static.netnaija.com/i/deYakz3n7P3.jpg",
  },
  {
    id: 5103,
    type: "Gospel Music",
    song: "Chinyere Udoma - Eze Mmuo (King of the Spirits)",
    time: "Oct 07",
    title: "Eze Mmuo (King of the Spirits)",
    singer: "Chinyere Udoma",
    year: "2022",
    producer: "Password",
    body: "Nigerian singer-songwriter and performer, Chinyere Udoma, comes through with a new song which is titled 'Eze Mmuo (KING OF THE SPIRITS)'. The newly released song 'Eze Mmuo (KING OF THE SPIRITS)' is an amazing record that should be on your playlist.Listen and download below.",
    comments: [],
    img: "https://static.netnaija.com/i/zOJabvx0aG2.jpg",
  },
  {
    id: 5104,
    type: "Gospel Music",
    song: "Mr. M & Revelation - PRAISE LOVE SONGS",
    time: "Sep 15",
    title: "PRAISE LOVE SONGS",
    singer: "Mr. M & Revelation",
    year: "2022",
    body: "Leading gospel music group Mr. M & Revelation returns with another powerful praise song 'Praise Love Songs'. This single comes just after their power ministration at the just concluded The African Praise Experience. The Group has consistently released songs that have massively blessed lives. This powerful song will empower you into another realm of praise.",
    comments: [],
    img: "https://static.netnaija.com/i/8yZaJdAYKJ0.jpg",
  },
  {
    id: 5105,
    type: "Gospel Music",
    song: "Mr. M & Revelation - Freedom Praise",
    time: "Jun 29",
    title: "Freedom Praise",
    singer: "Mr. M & Revelation",
    year: "2022",
    body: "Mr M & Revelation, an anointed musical group from Nigeria is out with a new praise number titled Freedom Praise. Thanksgiving and adoration fills our heart as we are overwhelmed with all the Lord is doing. Kicking off the year in grand style and ending the first half of the year is deserving of our praise. What a joy to lift up an exuberance praise to our God. No matter what situation it might be, stay focused with high praise in worship to God and see how you overcome it. The ultimate and greatest place where we can give praise and adoration to God is right in the depths of our hearts. 'Freedom Praise' is a mantle of worship and praise. Soak in deep worship and praise to God.",
    comments: [],
    img: "https://static.netnaija.com/i/WAPK46rka0B.jpg",
  },
  {
    id: 5106,
    type: "Gospel Music",
    song: "Chidinma - For You (feat. Fiokee)",
    time: "Feb 11",
    title: "For You (feat. Fiokee)",
    singer: "Chidinma",
    year: "2022",
    body: "Many a wedding celebration just got blessed as Gospel music minister Chidinma under  EeZee Conceptz Global, just released a pure, unadulterated love song titled 'For You' featuring Fiokee. Released in time before  Valentine's Day which is synonymous with the expression of love. She redefines the essence of love which is God, realigning her listeners to the original concept of the idea in its purest, unperverted form. 'Love is the greatest. 'The one who does not love has not become acquainted with God [does not and never did know Him], for God is love. [He is the originator of love, and it is an enduring attribute of His nature.] - 1 John 4:8' - Chidinma.",
    comments: [],
    img: "https://static.netnaija.com/i/zxG7Zn3L7q2.jpg",
  },
  {
    id: 5107,
    type: "Gospel Music",
    song: "Chissom Anthony - Shout for Joy",
    time: "Feb 01",
    title: "Shout for Joy",
    singer: "Chissom Anthony",
    year: "2022",
    body: "Nigerian Gospel singer, Chissom Anthony has released the official visuals to her latest soul stirring and exciting track titled 'Shout For Joy'. 'Shout For Joy' is a song that precipitates an atmosphere of joy mingled with hope whenever it is played. According to the artiste, this sound will echo everywhere in the weeks following the release of this new video. The Bible says 'In the presence of God there is fullness of joy' and Chissom Anthony has helped us with this track towards experiencing this biblical promise. Now she has taken this to a whole new level with an excellent video. Chissom Anthony is a well known Gospel singer who is becoming a household name in the Gospel music arena. She hails from Anambra state, Nigeria in Orumba North LGA. Since she began her ministry as a Gospel artiste, her story has been one of ever increasing glory and grace. She is a graduate of Accounting from the prestigious Nnamdi Azikiwe University, Awka and has worked in some Nigerian banks notably GTB and First Bank before the spiritual call into the Gospel music ministry. The ex- banker turned Gospel minister has written songs with great lyrical content and has blessed lives with lovely tunes that could have only come from Heaven. She is happily married and blessed with wonderful kids.",
    comments: [],
    img: "https://static.netnaija.com/i/gVpagW0XawO.jpg",
  },
  {
    id: 5108,
    type: "Gospel Music",
    song: "Nikki Laoye - Never Fail",
    time: "Nov 26, 2021",
    title: "Never Fail",
    singer: "Nikki Laoye",
    year: "2022",
    body: "Multiple Award Winning Urban Soul Singer, Nikki Laoye drops the highly anticipated Amapiano dance hit single, 'Never Fail', produced by SubHawkins & Dave Kizzle. The song features additional vocals by her brother/producer, Xblaze who also mixed and mastered the groovy dance tune. Renowned for her eclectic sound, Nikki delivers another catchy masterpiece - a Vibe of Victory, exclaiming God's unfailing power, especially in these uncertain times we live in. 'His Promises and His Word over our lives are guaranteed in His Name cos What God cannot do, does not exist. We certainly have a Loving Father who can NEVER FAIL' - says Nikki Laoye.",
    comments: [],
    img: "https://static.netnaija.com/i/3g8NB9DyaDR.png",
  },
  {
    id: 5109,
    type: "Gospel Music",
    song: "Judikay - Your Grace",
    time: "Oct 28, 2021",
    title: "Your Grace",
    singer: "Judikay",
    year: "2021",
    body: "Gospel music minister Judikay is out with a new single off the stables of EeZee Conceptz Global. She aptly titles this one 'Your Grace.' The single speaks of the love and grace of God that gives the enablement to live the abundant life through faith in Christ Jesus. She further acknowledges that we cannot accomplish anything without the grace, and finally breaks into worship celebrating the gift of grace. 'Your grace overwhelms me, your love overwhelms me, who am I without your grace?' Judikay sings. The new single is coming on the heels of the September release 'Nothing is too Hard for You' which features COZA's The Gratitude. In January, she released the Folk music laced 'Jesus is Coming.' and followed up with 'I Bow,' her second release for the year 2021.",
    comments: [],
    img: "https://static.netnaija.com/i/qvg701ndaze.jpg",
  },
  {
    id: 5110,
    type: "Gospel Music",
    song: "Chioma Jesus - Na God I Dey Praise (Craze)",
    time: "Oct 12, 2021",
    title: "Na God I Dey Praise (Craze)",
    singer: "Chioma Jesus",
    year: "2021",
    body: "From the stable of CJ Entertainment, ace Gospel music minister, Chioma Jesus is out with a brand new single labeled 'Na God I Dey Praise (Craze)'. This new sound is the latest of Chioma Jesus following the release of other captivating tracks from her recentalbum (Next Level) including 'Too Much', 'Change', 'I Go Make Am', 'Ekwueme', 'Onye Nmeri', and more. 'Na God I Dey Praise (Craze)' is a melodious dance all song that you will want to leave on repeat!",
    comments: [],
    img: "https://static.netnaija.com/i/BQJNjEq3arL.jpg",
  },
  {
    id: 5111,
    type: "Gospel Music",
    song: "Chike & Ada Ehi - Watching All Over Me",
    time: "Oct 01, 2021",
    title: "Watching All Over Me",
    singer: "Chike & Ada Ehi",
    year: "2021",
    producer: "DeeYasso",
    body: "Afro-pop/R&B singer, Chike gives a further treat from his critically acclaimed debut album 'Boo of the Booless,' by taping gospel diva Ada Ehi for 'Watching All Over Me,' ahead of his hotly anticipated sophomore album titled 'The Brother's Keeper.' Coming from the global success of his last single, the phenomenal hit 'Running (To You)' with Simi, Chike wraps up the year with a thankful number that exalts the ever-loving nature of the Almighty. Singing in Igbo and English, Chike and Ada Ehi both combine on this moving duet in glorious fashion, to birth a gem that is fated to be an uplifting anthem across the African continent and world at large. Speaking on duet:- 'Watching All over Me is an anthem of gratitude for all; regardless of tribe, religion, race, political views, gender, and whatnot. Looking back at the past 12 to 20 months, we survived a pandemic, we have survived tough times. The acceptance of my album is something I am thankful for, even having the gifted Ada Ehi join me on this song is a blessing, and I am thankful for that. This song preaches the gospel of gratitude, as the year comes to an end, we have to be thankful for life and people in it.'",
    comments: [],
    img: "https://static.netnaija.com/i/qvg70vWxNze.jpg",
  },
  {
    id: 5112,
    type: "Gospel Music",
    song: "Ada Ehi - Open Doors",
    time: "Sep 17, 2021",
    title: "Open Doors",
    singer: "Ada Ehi",
    year: "2022",
    producer: "JuzzyPro",
    body: "The year 2021 has been a great year for popular gospel artiste Ada Ehi who had had two lovely releases an audio and a video featuring some of the most popular artist in gospel music. In January, she dropped 'Congratulations' featuring Reggae Icon, Buchi and another hot one with her video release in June with Sinach for the single 'Fix My Eyes On You'. Ada Ehi also got featured in Nathaniel Bassey's hit single and video 'So Good' earlier in April.'Open Doors' comes forth as a brand new single not included in her late 2020 Album BORN OF GOD. It is a song of declaration with an african praise rhythm that will stir you up to dance. It was produced by Emmanuel Uzozie [@juzzypro].",
    comments: [],
    img: "https://static.netnaija.com/i/bvWaqX5W7rk.jpg",
  },
];
