export const highlifeMusicData = [
  {
    id: 5401,
    type: "Highlife/Old School",
    song: "Chief Onyenze Nwa-Amobi Na Ogidi - One One B",
    time: "Dec 15, 2019",
    title: "One One B",
    singer: "Chief Onyenze Nwa-Amobi Na Ogidi",
    year: "2017",
    comments: [],
    body: "Here is a requested highlife music performed by 'Chief Onyenze Nwa-Amobi Na Ogidi' - getting that name correct and authenticating it was a research project on its own. Well, the song is titled 'One One B' and should entice lovers of Igbo highlife music. Enjoy.",
    img: "https://img.netnaija.com/nX7HHK.jpg",
  },
  {
    id: 5402,
    type: "Highlife/Old School",
    song: "Umu Obiligbo - Onye Na Efu Efu",
    time: "Sep 21, 2019",
    title: "Onye Na Efu Efu",
    singer: "Umu Obiligbo",
    year: "2014",
    body: "Enjoy!",
    comments: [],
    img: "https://img.netnaija.com/CK2HHK.jpg",
  },
  {
    id: 5403,
    type: "Highlife/Old School",
    song: "Umu Obiligbo - Onyebuchi",
    time: "Sep 21, 2019",
    title: "Onyebuchi",
    singer: "Umu Obiligbo",
    year: "2014",
    body: "Enjoy.",
    comments: [],
    img: "https://img.netnaija.com/-K2HHK.jpg",
  },
  {
    id: 5404,
    type: "Highlife/Old School",
    song: "Umu Obiligbo - Nwalie (feat. Humblesmith)",
    time: "Aug 30, 2019",
    title: "Nwalie (feat. Humblesmith)",
    singer: "Umu Obiligbo",
    year: "2019",
    body: "Nigerian indigenous highlife duo - Umu Obiligbo, releases their new extended play (EP) titled 'Level Up'. Off the project, here is the third track titled 'Nwalie'.The record features Humblesmith who is popularly know for his smash hit single 'Osinachi'.",
    comments: [],
    img: "https://img.netnaija.com/R41HHK.jpg",
  },
  {
    id: 5405,
    type: "Highlife/Old School",
    song: "Umu Obiligbo - I Pray",
    time: "Aug 30, 2019",
    title: "I Pray",
    singer: "Umu Obiligbo",
    year: "2019",
    body: "Nigerian indigenous highlife duo - Umu Obiligbo, releases their debut extended play (EP) and it is titled 'Level Up'. Off the project comes the second single tagged 'I Pray'. I Pray' is a mid-tempo joint which sends prayer to God asking for the good things of life. It is also the second track off the project.",
    comments: [],
    img: "https://img.netnaija.com/K41HHK.jpg",
  },
  {
    id: 5406,
    type: "Highlife/Old School",
    song: "Femi Kuti - Na Their Way Be That",
    time: "Feb 15, 2018",
    title: "Na Their Way Be That",
    singer: "Femi Kuti",
    year: "2018",
    body: "Afrobeat legend Femi Kuti, releases a 'hopeful, horn-fueled song' Na Their Way Be That, from his forth coming 10th LP, One People One World. Femi explains the single as 'an easy explanation as to why some people act in a negative way ... It's just their nature, and it explains why they should be ignored.' This is the singer's second single from One People One World LP, out February 23rd. The whole project comes from a depth that Femi believes should inspire the younger generation in areas that will instigate social change positively.",
    comments: [],
    img: "https://img.netnaija.com/m64HHK.jpg",
  },
  {
    id: 5407,
    type: "Highlife/Old School",
    song: "Masterkraft & Mike Ejeagha - Ka Esi Le Onye Isi Oche",
    time: "Sep 28, 2017",
    title: "Ka Esi Le Onye Isi Oche",
    singer: "Masterkraft & Mike Ejeagha",
    year: "2017",
    producer: "Masterkraft",
    body: "Ace producer Masterkraft revamps one of the great Mike Ejeagha's songs. According to the producer the song is one of his Dad's favourite tune and he decided to work his magic on it, though short but sure worth a listen. One Of My Dads Favourite Tunes ..... God Bless The Great Mike Ejeagha And May The Spirit Of The Gone Legends Forever Rest Well.......Enjoy.",
    comments: [],
    img: "https://img.netnaija.com/8jxHHK.jpg",
  },
  {
    id: 5408,
    type: "Highlife/Old School",
    song: "Seun Kuti & Egypt 80 - Giant of Africa",
    time: "Dec 09, 2014",
    title: "Giant of Africa",
    singer: "Seun Kuti & Egypt 80",
    year: "2014",
    body: "Seun Kuti the son of the legendary Afrobeat pioneer Fela Anikulapo Kuti is out with a banging afrobeat single Giant of Africa which is off his recently released album 'From Africa With Fury'. If you looking for a good music rich in african instrumentation then this is the song for you.",
    comments: [],
    img: "https://img.netnaija.com/BSKHHK.jpg",
  },
  {
    id: 5409,
    type: "Highlife/Old School",
    song: "Onyinye Osadebe - Ndubuisi",
    time: "Aug 30, 2014",
    title: "Ndubuisi",
    singer: "Onyinye Osadebe",
    year: "2014",
    body: "The Son of late Chief Osita Osadebe has been crowned the Igbo highlife King. He was born in 1990 and graduated from Enugu State University of Science and Technology with a degree in MicroBiology and Brewing. Dr. Prince Emeka Morocco Maduka (Eze Egwu Ekpili) believes that Onyinye Osita Osadebe will replace his Late father as a King of Highlife. Dr Maduka who is also the Governor of PMAN says “Onyinye is a very good artiste that he will be greater than his late father Osita Osadebe that Nigerians”. Late Dr Ozoemena Nsugbe before his death also predicted that a new king of highlife will soon emerge and it would be Onyinye Osita Osadebe . Onyinye will drop a new album titled “Ndubuisi’ before 30th of August, 2014 under his new Record Label Morgan Entertainment. It would be a modern reincarnation of Osita Osadebe and here is the hit single from the forth coming album titled “Ndubuisi” for your listening pleasure. Enjoy!",
    comments: [],
    img: "https://img.netnaija.com/gLKHHK.thumb.jpg",
  },
  {
    id: 5410,
    type: "Highlife/Old School",
    song: "Sir Victor Uwaifo - Bobozi",
    time: "Jun 09, 2014",
    title: "Bobozi",
    singer: "Sir Victor Uwaifo",
    year: "2014",
    producer: "LeriQ",
    body: "Sir Victor Uwaifo has made a name as one of the greatest Nigerian musicians till date with an impressive musical career spanning over 50 years. The Music Legend demonstrates his musical pedigree in his new highlife meets pop electro track titled “BOBOZI” produced by Leriq. The timeless maestro is credited with hits such as Guitar Boy and Joromi, and this is his official debut single since signing to Hypertek Digital/960 Music Group. The song represents the idea of A Legend Reborn. “BOBOZI” is highlife meets pop electro. Sir Victor demonstrates a unique fusion of the contemporary electronic sound with nostalgic highlife melodies. The energetic track is a sure bet on party playlists this summer. He also addresses current societal ills such as the love for money, and the infatuation with social validation. Giving credence to the saying that “Music is Timeless” Sir Victor teams up with young Arstokrat Records producer Leriq to produce the head banging jam.",
    comments: [],
    img: "https://img.netnaija.com/TrHHHK.thumb.jpg",
  },
  {
    id: 5411,
    type: "Highlife/Old School",
    song: "Sir. Warrior - Elu Uwa",
    time: "Dec 17, 2013",
    title: "Hot Shit (feat. Kanye West & Lil Durk)",
    singer: "Cardi B",
    year: "2013",
    body: "Enjoy",
    comments: [],
    img: "https://img.netnaija.com/hsi/aHR0cDovLzMuYnAuYmxvZ3Nwb3QuY29tLy00VTZXZi1NdmNnVS9VVWlSeXJLdUlVSS9BQUFBQUFBQUQ4RS8tY2ZrbWNPYkNvdy9zMTYwMC9XYXJyaW9yKyYrT3JpZW50YWwrQnJvdGhlcnMsK2Zyb250LmpwZw==/images/Warrior+&+Oriental+Brothers,+front.jpg",
  },
  {
    id: 5412,
    type: "Highlife/Old School",
    song: "Bright Chimezie - Ube Nwanne",
    time: "Mar 31, 2013",
    title: "Ube Nwanne",
    singer: "Bright Chimezie",
    year: "2013",
    body: "Download and share!",
    comments: [],
    img: "https://img.netnaija.com/hsi/aHR0cDovLzEuYnAuYmxvZ3Nwb3QuY29tL19DdUdIcnpvbjhaNC9TX09oNGl0NVZlSS9BQUFBQUFBQUF3dy9uanl3QTlDbjk1dy9zNDAwL2JyaWdodC1jaGltZXppZS5qcGc=/images/bright-chimezie.jpg",
  },
];
