export const mixtapeData = [
  {
    id: 5501,
    type: "DJ Mixtape",
    song: "DJ Selex - Amapiano Vibes Mixtape",
    time: "1 hour ago",
    title: "Amapiano Vibes Mixtape",
    singer: "DJ Selex",
    year: "2022",
    comments: [],
    body: "DJ Selex is out with a new mixtape titled 'Amapiano Vibes Mixtape' which as the name suggests only songs with the Amapiano sound. According to Wikipedia, Amapiano is a style of house music that emerged in South Africa in 2012. It is a hybrid of deep house, jazz and lounge music characterized by synths and wide percussive basslines. The genre instantly became popular in the transition to the 2020s amongst Millennials and Gen Z in South Africa even in present day. Get the mixtape below and follow DJ Selex across social media @deejayselex.",
    img: "https://static.netnaija.com/i/90ZNPb5o78e.jpg",
  },
  {
    id: 5502,
    type: "DJ Mixtape",
    song: "DJ Lamp - Party Time (Vol. 3) (feat. Skye Tha Hypemachine & Prime Drums)",
    time: "Yesterday 10:38am",
    title: "Party Time (Vol. 3) (feat. Skye Tha Hypemachine & Prime Drums)",
    singer: "DJ Lamp",
    year: "2022",
    body: "DJ Lamp rolls out volume 3 of his Mixtape series 'Party Time' featuring Skye da HypeMachine and Prime Drums 🥁. This is one hell of a Mixtape, you all will surely love it for real 🔥🔥 Download it and jam it until your speaker explodes!",
    comments: [],
    img: "https://static.netnaija.com/i/AqgKGGb3Kr1.jpg",
  },
  {
    id: 5503,
    type: "DJ Mixtape",
    song: "DJ Selex - Xtra Cool Mixtape",
    time: "Oct 21",
    title: "Xtra Cool Mixtape",
    singer: "DJ Selex",
    year: "2022",
    body: "DJ Selex premieres a new mixtape titled 'Xtra Cool Mixtape'. The mixtape comprises of trending afrobeat songs and it is a sure to get you grooving for its entire 70-minut run. Get it below and follow Selex across social media @deejayselex. ",
    comments: [],
    img: "https://static.netnaija.com/i/WAPK4vbka0B.jpg",
  },
  {
    id: 5504,
    type: "DJ Mixtape",
    song: "DJ Baddo - Afrohit Mix (Vol. 4)",
    time: "Oct 10",
    title: "Afrohit Mix (Vol. 4)",
    singer: "DJ Baddo",
    year: "2022",
    body: "Multi-talented disc jockey, DJ Baddo has released this new music compilation tagged 'Afrohit Mix Vol 4'. The mixtape houses Afrobeats recently released hit songs from artists like Asake, Ayra Starr, Burna Boy, Wizkid, Mayorkun, Magixx, Donna Adja, Kizz Daniel, Fireboy, Rema, Hypeman Luckey, and others. You all will surely enjoy this dope mixtape. Follow @Djbaddo on Instagram",
    comments: [],
    img: "https://static.netnaija.com/i/5VrNpnO579O.jpg",
  },
  {
    id: 5505,
    type: "DJ Mixtape",
    song: "Quality DJ Jamsmyth - Transit Playlist (Vol. 4) [Long Ride Edition]",
    time: "Oct 08",
    title: "Transit Playlist (Vol. 4) [Long Ride Edition]",
    singer: "Quality DJ Jamsmyth",
    year: "2022",
    body: "Quality DJ Jamsmyth comes through with 'Transit Playlist Vol. 4', a compilation and blends of trending hits from across Africa. It features the best of Asake and other chart-topping hits of 2022.",
    comments: [],
    img: "https://static.netnaija.com/i/90ZNPPMQN8e.jpg",
  },
  {
    id: 5506,
    type: "DJ Mixtape",
    song: "DJ Selex - Best of Chike Mixtape",
    time: "Oct 07",
    title: "Best of Chike Mixtape",
    singer: "DJ Selex",
    year: "2022",
    body: "Singer, Chike Ezekpeazu Osebuka, better known as Chike is the focus artist for this edition of DJ Selex's 'Best of ...' series. As expected, the mixtape comprises solely of Chike's songs and features.",
    comments: [],
    img: "https://static.netnaija.com/i/1qdNVjYmN4g.jpg",
  },
  {
    id: 5507,
    type: "DJ Mixtape",
    song: "DJ Yinks - The Groove Party Mix (Vol. 2)",
    time: "Oct 04",
    title: "The Groove Party Mix (Vol. 2)",
    singer: "DJ Yinks",
    year: "2022",
    body: "DJ Yinks with the second edition of The Groove Party Mixtape. As the name implies, the mixtape is a that perfect mixtape to start off that groovy party.",
    comments: [],
    img: "https://static.netnaija.com/i/3g8NBvwRNDR.jpg",
  },
  {
    id: 5508,
    type: "DJ Mixtape",
    song: "DJ Selex - Best of Erigga Mixtape",
    time: "Sept 30",
    title: "Best of Erigga Mixtape",
    singer: "DJ Selex",
    year: "2022",
    body: "DJ Selex releases a new mixtape titled 'Best of Erigga'. As expected, the mixtape comprises of tracks and features of Erhiga Agarivbie, better known as Erigga.",
    comments: [],
    img: "https://static.netnaija.com/i/qEQN2xOz76W.jpg",
  },
  {
    id: 5509,
    type: "DJ Mixtape",
    song: "DJ Selex - With The Vibes Mixtape",
    time: "Sep 26",
    title: "With The Vibes Mixtape",
    singer: "DJ Selex",
    year: "2022",
    body: "DJ Selex releases a new party mixtape for the month of September containing trending and chart-topping afrobeats tracks. Titled 'With The Vibes Mixtape', the mixtape features songs from Asake, Ayra Starr, CKay, Fireboy DML, Victony, among others.",
    comments: [],
    img: "https://static.netnaija.com/i/3g8NBvdrNDR.jpg",
  },
  {
    id: 5510,
    type: "DJ Mixtape",
    song: "DJ Latitude - Amapiano Lifestyle Mixtape (Vol. 4)",
    time: "Sep 26",
    title: "Amapiano Lifestyle Mixtape (Vol. 4)",
    singer: "DJ Latitude",
    year: "2022",
    body: "Following up with the Vol 2 and Vol. 3, The New Amapiano Lifestyle Volume 4 mixtape is here, a playlist curated by DJ Latitude from a different range of Amapiano sound infused with a touch of soulful Amapiano wave to balance your mood & Groove. Enjoy",
    comments: [],
    img: "https://static.netnaija.com/i/Gem7QXm4KYx.jpg",
  },
  {
    id: 5511,
    type: "DJ Mixtape",
    song: "DJ Loyce - Afro Fusion Mix (Vol. 2)",
    time: "Sep 21",
    title: "Afro Fusion Mix (Vol. 2)",
    singer: "DJ Loyce",
    year: "2022",
    body: "Talented Disc Jockey, Dj Loyce comes through with a brand new Mixtape titled 'Afro Fusion Mix (Vol. 2)'. The new Mix 'Afro Fusion Mix (Vol. 2)' serves as a follow up to his previously heard single titled, 'Lover' which features Pizo.",
    comments: [],
    img: "https://static.netnaija.com/i/BQJNjzrYNrL.jpg",
  },
  {
    id: 5512,
    type: "DJ Mixtape",
    song: "DJ Tough - MOCLIST (Man On Cap List) Mixtape [Vol. 9]",
    time: "Sep 15",
    title: "MOCLIST (Man On Cap List) Mixtape [Vol. 9]",
    singer: "DJ Tough",
    year: "2022",
    body: "Black Diamond (Wande Coal) Official DJ, DJ Tough aka Man On Cap has released a new mixtape titled 'MOCList 9 (Man On Cap List)'. This mixtape contains trending Afrobeats and Amapiano jams you would love to hear.",
    comments: [],
    img: "https://static.netnaija.com/i/no4NXmg4K9M.jpg",
  },
];
