export const foreignMusicVideoData = [
  {
    id: 5701,
    title: "Chris Brown - Call Me Every Day (feat. WizKid)",
    type: "Foreign Music Video",
    time: "Aug 25",
    duration: "00:03:07",
    img: "https://static.netnaija.com/i/9bVNr5jDaWv.jpg",
    body: "Chris Brown has premiered the official music video for his buzzing track, 'Call Me Every Day' featuring Wizkid. 'Call Me Every Day' is on Chris' latest album, 'Breezy,' which came out in June and features collaborations with Lil Wayne, Lil Durk, Bryson Tiller, H.E.R., and Jack Harlow. A 33-track deluxe edition was released in July.",
    source: "https://www.youtube.com/watch?v=BLN2nsm1w6w",
    comments: [],
  },
  {
    id: 5702,
    title: "Tyga, Jhené Aiko & Pop Smoke - Sunshine",
    type: "Foreign Music Video",
    time: "Aug 16",
    duration: "00:04:11",
    img: "https://static.netnaija.com/i/PrO7OVLRKyp.jpg",
    body: "Tyga returns with a heavy dose of nostalgia. On Friday, the platinum-selling rapper came through with the summer-ready track 'Sunshine' featuring Jhené Aiko and the late Pop Smoke. Co-produced by Mike Crook and DJ Swish, the song pays homage to Lil Flip's 2004 hit of the same name. Flip appears in the 2000s-inspired video, which also includes a message from Pop Smoke's mother Audrey Jackson and brother Obasi Jackson. 'Pop Smoke was a legend in the making and I wish we could've collaborated together more,' said Tyga, who was featured on Pop Smoke's 'West Coast Shit' track. 'It's a been a great experience working with his mother and brother to pay homage with this song and contributing to keeping his legacy alive-the smoke will never clear.' Pop's brother said 'Sunshine' showcases a different side of the NYC rapper, and underscores the range he possessed as an artist.",
    source: "https://www.youtube.com/watch?v=FTpohtXaJcM",
    comments: [],
  },
  {
    id: 5703,
    title: "Jessie Reyez - MUTUAL FRIEND",
    type: "Foreign Music Video",
    time: "Aug 16",
    duration: "00:03:53",
    img: "https://static.netnaija.com/i/x5PKDOYlNnM.jpg",
    body: "Jessie Reyez has announced the arrival of her sophomore album, Yessie. The LP will be released on Sept. 16 via FMLY/Island Records. The singer announced the news during her appearance on Jimmy Kimmel Live on Thursday, where she shared a performance of her new single 'Mutual Friend.' In the Peter Huang-directed video for the song, Jessie Reyez confesses to a mutual friend that there is no love loss between her and her ex. In fact, she has resolutely moved into 'don't give AF' territory. And as the visuals display, it is a cause for dancing and celebration as flowers bloom around her, symbolizing the resiliency of moving on from a toxic relationship. 'If you die tomorrow/I don't think I'd cry, I gave ya one too many nights,' she sings on the chorus. 'Don't care if it sound cold, it is what it is.' The single follows the release of 'Fraud' in June, which was her first new solo music since her debut studio album, Before Love Came to Kill Us in 2020.",
    source: "https://www.youtube.com/watch?v=CG1m3b9j_qY",
    comments: [],
  },
  {
    id: 5704,
    title: "Rae Sremmurd - Community D**k (feat. Flo Milli)",
    type: "Foreign Music Video",
    time: "Aug 16",
    duration: "00:04:26",
    img: "https://static.netnaija.com/i/9bVNr5oMaWv.webp",
    body: "Ahead of the release of their upcoming fourth studio album Sremm4Life, Swae Lee and Slim Jxmmi enlisted Flo Milli for their new single 'Community D**k.' The track, which arrives alongside an accompanying music video, follows 'Denial,' which dropped in June as the lead single from Sremm4Life. Due out later this year, the project will mark Rae Sremmurd's first full-length offering since 2018, when the duo dropped Sr3mm, the follow-up to 2016's SremmLife 2 and their 2015 debut SremmLife.",
    source: "https://www.youtube.com/watch?v=1EaAQXtiUIY",
    comments: [],
  },
  {
    id: 5705,
    title: "Quavo & Takeoff - Us vs. Them (feat. Gucci Mane)",
    type: "Foreign Music Video",
    time: "Jul 29",
    duration: "00:03:38",
    img: "https://static.netnaija.com/i/DpraR5rk7Ao.jpg",
    body: "Confidence can take people far in life, and it only gets boosted more when it is clear no one can compare. Quavo and Takeoff go the duo route once again, this time tapping fellow Atlanta native Gucci Mane for the confident anthem 'Us Vs Them.' Takeoff handles the hook before getting into his verse, followed by Quavo who raps with a fury, and Gucci Mane closes things off with a shoutout to the currently incarcerated Young Thug and Gunna. The video shows the trio rapping while flanked by beautiful women. With some sports references in the track, it only makes sense for the ladies to be holding basketballs in addition to football players going at it and a boxer landing jabs into a punching bag.",
    source: "https://www.youtube.com/watch?v=A80MkpiMHVI",
    comments: [],
  },
  {
    id: 5706,
    title: "Cardi B - Hot Shit (feat. Kanye West & Lil Durk)",
    type: "Foreign Music Video",
    time: "Jul 13",
    duration: "00:03:38",
    img: "https://static.netnaija.com/i/zxG7ZOoEaq2.jpg",
    body: "Cardi B has released the music video for her latest single, 'Hot Shit,' featuring Kanye West and Lil Durk. The singer teased the music video's release in a tweet following her groundbreaking wireless performance last weekend. She tweeted, 'I know yall been waiting....HOT SHIT VIDEO THIS TUESDAY 7/12 8PM EST' 'Hot Shit' is Cardi B's first single of the year and her first drop since her March 2021 single 'Up,' which peaked at NO. 1 on the Billboard chart. The almost four-minute-long single was released on July 1st and is one of the singles off Cardi B's highly anticipated sophomore album. Recall that back in June, she teased the single's release, sharing a video teaser for the new Tay Keith (Drake, BlocBoy JB) produced single. The short clip featured Cardi on top of a skyscraper.",
    source: "https://www.youtube.com/watch?v=vjbBaai9ZA8",
    comments: [],
  },
  {
    id: 5707,
    title: "City Girls - Good Love (feat. Usher)",
    type: "Foreign Music Video",
    time: "Jul 01",
    duration: "00:03:50",
    img: "https://static.netnaija.com/i/xM6K5yLVKyE.jpg",
    body: "Just a week after announcing the summer anthem, City Girls join forces with Usher for their new single 'Good Love.' The track arrives alongside a music video, which features JT, Yung Miami, and Usher show off their skating skills at Atlanta's iconic Cascade roller rink. City Girls had previously teased the collaborative single during a red carpet interview at the Billboard Music Awards. Describing 'Good Love' as a 'party record, fun record, cookout record,' Yung Miami revealed she was a big fan of the R&B legend growing up. 'Growing up, big fan of Usher,' she said. 'Can't wait for everyone to hear the record.'",
    source: "https://www.youtube.com/watch?v=ruq-VkCAe-4",
    comments: [],
  },
  {
    id: 5708,
    title: "Future - WAIT FOR U (feat. Drake & Tems)",
    type: "Foreign Music Video",
    time: "May 07",
    duration: "00:03:59",
    img: "https://static.netnaija.com/i/3g8NBgkXKDR.jpg",
    body: "High-profile rapper, Future has released the official music video for the super-mellifluous record 'Wait For U' which features his colleague, Drake alongside Nigerian singer, Tems. Directed by Director X, it is the first music video from his recently released album 'I Never Liked You'. Speaking on the album, 'I Never Liked You' houses 16 impressive records featuring Kanye West, Drake, Young Thug, Gunna, Kodak Black, Est Gee and Nigeria's very own Tems. It'll serve as the rapper's 9th studio album after delivering projects like Pluto, EVOL, HNDRXX, and Draco, amongst others.",
    source: "https://www.youtube.com/watch?v=rP09GUQFDFk",
    comments: [],
  },
  {
    id: 5709,
    title: "Coi Leray & Nicki Minaj - Blick Blick",
    type: "Foreign Music Video",
    time: "Mar 19",
    duration: "00:02:59",
    img: "https://static.netnaija.com/i/LqXNEE55NlE.jpg",
    body: "Push it, push it, click, click. Fresh off the release of their collaboration 'Blick Blick,' Coi Leray and Nicki Minaj pop off in the music video. In the colorful clip, the 24-year-old rapper shows off her choreographed moves while rocking '90s-inspired fits. The Queen comes through in a heard-turning look to spit her 'verse of the year.' Later, Barbie and the Trendsetter bust their paintball guns while shooting at their opponents and don matching pink wigs.",
    source: "https://www.youtube.com/watch?v=1N1RwMOcjks",
    comments: [],
  },
  {
    id: 5710,
    title: "Ed Sheeran - The Joker And The Queen (feat. Taylor Swift)",
    type: "Foreign Music Video",
    time: "Feb 11",
    duration: "00:03:07",
    img: "https://static.netnaija.com/i/rOx7xLzQ70M.jpg",
    body: "Pop stars Ed Sheeran and Taylor Swift have released a duet remix of Equals track The Joker And The Queen. Dressed as the Joker and the Queen, the newest collaboration comes after Ed who in a recent interview gave a hint of the new hit set to drop. To announce its release, Ed tweeted: 'The joker and queen featuring @taylorswift13 is out right now. Me and Taylor first met and wrote + recorded our first song together in 2012, ten years ago now, I'm so so honoured to have her on this song.' He went on to add, ''Not only is she the best singer/songwriter in the world but she's also a very close friend. I'm very lucky to have her in my life.'' This is the fourth time the artistes will be collaborating. Ed, 30, and Taylor, 32, reunited with the same cast from a previous collaboration on 'Everything Has Changed'. The ballad describes the love story of two teenagers, Ava and Jack, who were  going to the university. With the release of The Joker And The Queen, Taylor wrote: 'This video makes me think of our friendship all these years... also can't believe Jack & Ava from the Everything Has Changed video came back and did this!! Nostalgic heaven! (sic)' In the chorus of the song, Ed sings: 'And I know you could fall for a thousand kings/And hearts that would give you a diamond ring. When I fold, you see the best in me/The joker and the queen.'",
    source: "https://www.youtube.com/watch?v=2qzcHLyv3N0",
    comments: [],
  },
  {
    id: 5711,
    title: "Future - Worst Day",
    type: "Foreign Music Video",
    time: "Feb 11",
    duration: "00:04:21",
    img: "https://static.netnaija.com/i/qEQN2MYxa6W.jpg",
    body: "Just in time for Black Future Month, Future returns with his first solo single in nearly two years. On 'Worst Day,' produced by Wheezy and Taurus, the Atlanta rapper pours out his heart. 'Valentine's Day, the worst day / Got too many to please / Spent over one hundred Gs and she still wasn't pleased,' he raps. Along with the song, Hndrxx has dropped a cinematic video shot by Daps, which finds him seeking help from dating coach Dr. Kevin Samuels.",
    source: "https://www.youtube.com/watch?v=o8Y9GMhIZLQ",
    comments: [],
  },
  {
    id: 5712,
    title: "Adele - Oh My God",
    type: "Foreign Music Video",
    time: "Jan 14",
    duration: "00:03:53",
    img: "https://static.netnaija.com/i/AqgKG43n7r1.jpg",
    body: "Adele has released a new video for 'Oh My God,' a track off her new album '30'. Her new video was created in collaboration with Greg Kurstin and directed by Sam Brown, who also helmed the singer's 2010 video for 'Rolling in the Deep.' Speaking about the music video on Instagram, she wrote, I got to work with Sam Brown again for 'Oh My God' who directed the 'Rolling In The Deep' video! So to collaborate together again a decade later was nostalgic to say the least. We filmed this one on the day Easy On Me dropped, there were a million things going on all at once. But the attention to detail from the crew was borderline hilarious - thank you so much for your patience and pulling it all together it was a lot of fun ?? Although right at the end a huge python was on set so I skidaddled my arse straight out of there! Big thank you to Harris Reed, Louis Vuitton and The Queens Haus - Vivienne Westwood for the most stunning clothes for me to sing my 'I'm a hot mess' song in!  ♥",
    source: "https://www.youtube.com/watch?v=niG3YMU6jFk",
    comments: [],
  },
];
