export const musicVideosData = [
  {
    id: 5601,
    title: "Fireboy DML - All Of Us (Ashawo)",
    type: "Music Video",
    time: "Oct 28",
    duration: "00:03:04",
    img: "https://static.netnaija.com/i/Wz27WbJ3K5R.jpg",
    body: "YBNL Nation presents the official music video for Fireboy DML's latest single, 'All Of Us (Ashawo).' 'All Of Us (Ashawo)' was one of the songs lifted from Fireboy DML's most recent third studio album, 'Playboy.' Produced by Telz. In the song, Fireboy DML refers to alcohol as the reason why he cheats, probably not his fault. The video was shot and directed by Clarence Peters. 'Playboy,' the album, was released a few months ago with a surpassing number of streams.",
    source: "https://www.youtube.com/watch?v=FfHSi48IY4g",
    comments: [],
  },
  {
    id: 5602,
    title: "Rema - Dirty",
    type: "Music Video",
    time: "Oct 26",
    duration: "00:03:45",
    img: "https://static.netnaija.com/i/wnRaMGXmKdq.jpg",
    body: "As the Rave & Roses tour - named after his debut album keeps raging in Europe, with stops in cities like Cologne, Brusells, Amsterdam, Berlin, Copenhagen, and Paris, Rema's album keeps penetrating the charts in different parts of the world and as you can see, he is not stopping anytime soon as he further propels the project, dishing out yet another music video from the album. Today, Mavin Records & Jonzing World superstar, Rema has released the official music video for 'Dirty.' Co-produced by his frequent collaborators, London and Andre Vibez, 'Dirty' serves as the 3rd track on the acclaimed Rave & Roses album. Directed by EARTHBOI.",
    source: "https://www.youtube.com/watch?v=kPUAUUZIvuk",
    comments: [],
  },
  {
    id: 5603,
    title: "Victony & Tempoe - Soweto",
    type: "Music Video",
    time: "Oct 22",
    duration: "00:02:38",
    img: "https://static.netnaija.com/i/yMX7y9JZ783.jpg",
    body: "Gifted singer cum rapper, Victony and record producer, Tempoe have unveiled the official music video of their trending record, Soweto. The video was directed by Jyde Ajala. Soweto serves as the 6th track on his 7-track extended play 'Outlaw.' Consisting of guest appearances by Kizito and Tempoe, the Outlaw EP stands as one of the best Nigerian projects of 2022. Quotable Lyrics - 'Call all your brokoto No go dey slogodo oh Body dey draw me like ogbono oh Body dey rise my tonono oh I say call all your brokoto no go dey slogodo oh Girlie dey burst my bololo oh Girl make I salute your commodore oh...'",
    source: "https://www.youtube.com/watch?v=DPBRGWUgQsA",
    comments: [],
  },
  {
    id: 5604,
    title: "Oxlade - KU LO SA",
    type: "Music Video",
    time: "Oct 21",
    duration: "00:02:29",
    img: "https://static.netnaija.com/i/PrO7OeprNyp.jpg",
    body: "Nigerian music sensation, Oxlade has released the video to his smash hit single titled, 'KU LO SA'. The song was performed by Oxlade at A COLORS SHOW few months ago and has been a chart topper since it released. However, Oxlade joins the likes of Doja Cat, H.E.R, Mahalia, Jorja Smith, Ayra Starr and others to deliver stunning performances at the A COLORS SHOW. The video was shot and directed by DK.",
    source: "https://www.youtube.com/watch?v=R4qud199tQk",
    comments: [],
  },
  {
    id: 5605,
    title: "Wizkid - Bad To Me",
    type: "Music Video",
    time: "Oct 19",
    duration: "00:03:20",
    img: "https://static.netnaija.com/i/90ZNPPDQN8e.jpg",
    body: "Hot off the back of the release of his gold-certified studio album 'Made in Lagos' and its deluxe edition comes 'Bad To Me' - his latest and first official single for 2022. The song was met with mixed reviews from fans and critics on its first day but has managed to amass good numbers on streaming platforms. Today, Starboy Entertainment's head honcho, Wizkid unveils the official music video for his latest single, Bad To Me. The song will be included as part of his forthcoming fifth studio album 'More Love Less Ego' out in the coming weeks.",
    source: "https://www.youtube.com/watch?v=2mkhevOXVNk",
    comments: [],
  },
  {
    id: 5606,
    title: "Simi - Loyal (feat. FAVE)",
    type: "Music Video",
    time: "Oct 19",
    duration: "00:06:26",
    img: "https://static.netnaija.com/i/1xYNeMm9NLJ.jpg",
    body: "Simi premieres a colourful visual for the single 'Loyal,' which features FAVE, off her fifth studio album 'To Be Honest.' Kemi Adetiba directed the video for the Blaise Beatz-produced song, which features cameos from Enioluwa Adeoluwa, Stephanie Coker Aderinokun, Samuel Perry (Broda Shaggi), Mariam Bakre (Mory Coco), and Frank Edoho.",
    source: "https://www.youtube.com/watch?v=L5qoTakVVAM",
    comments: [],
  },
  {
    id: 5607,
    title: "T.I Blaze - Lock Up",
    type: "Music Video",
    time: "Oct 19",
    duration: "00:02:16",
    img: "https://static.netnaija.com/i/gVpagP1gNwO.jpg",
    body: "Nigerian recording artist, T.I Blaze has released the video to his new single titled, 'Lock Up'. The song 'Lock Up' serves as follow-up to his recent song titled, 'My Life' released back in August.Shot by Perliks Definition for Nouvelle Films.",
    source: "https://www.youtube.com/watch?v=l1Onq3A02gY",
    comments: [],
  },
  {
    id: 5608,
    title: "Magixx - All Over",
    type: "Music Video",
    time: "Oct 19",
    duration: "00:03:08",
    img: "https://static.netnaija.com/i/XV5KvQ8BN9m.jpg",
    body: "Magixx has released the official music video for his song 'All Over' off his recently-released 'Atom EP'. Ademola Falomo directed the video for the Reward Beatz-produced song. The music video features the Big Brother Naija (Shine Ya Eye) Housemate, Tsakute Jonah (Saskay).",
    source: "https://www.youtube.com/watch?v=zwVQjisPfZY",
    comments: [],
  },
  {
    id: 5609,
    title: "Young Jonn - Xtra Cool",
    type: "Music Video",
    time: "Oct 18",
    duration: "00:02:37",
    img: "https://static.netnaija.com/i/Gem7Q8QqKYx.jpg",
    body: "Nigerian singer and record producer, Young Jonn, has released the official music video for his latest single, 'Xtra Cool.' This new Afrobeats single is a follow-up to his single, 'Dada.'",
    source: "https://www.youtube.com/watch?v=LWWCj-EbevI",
    comments: [],
  },
  {
    id: 5610,
    title: "BNXN fka Buju - In My Mind",
    type: "Music Video",
    time: "Oct 14",
    duration: "00:02:25",
    img: "https://static.netnaija.com/i/90ZNPPPwN8e.jpg",
    body: "Nigerian musician BNXN, formally known as Buju, comes through with the music video for 'In My Mind', a single off his recently released EP 'Bad Since '97.' The new EP 'Bad Since '97' features Nigerian Superstars such as Wizkid, Wande Coal, and Olamide. The EP is out now on all platforms.",
    source: "https://www.youtube.com/watch?v=DxV4Yt1vmg0",
    comments: [],
  },
  {
    id: 5611,
    title: "Iyanya - One Side",
    type: "Music Video",
    time: "Oct 14",
    duration: "00:03:03",
    img: "https://static.netnaija.com/i/wnRaMDDp7dq.jpg",
    body: "Iyanya comes through with the music video for his recent single, 'One Side', directed by OluTheWave. The Shugavybz-produced track serves as a follow-up to the popular single 'Like' which features Davido and Kizz Daniel.",
    source: "https://www.youtube.com/watch?v=c7Gofo8j3E0",
    comments: [],
  },
  {
    id: 5612,
    title: "Joeboy - Likkle Riddim",
    type: "Music Video",
    time: "Oct 14",
    duration: "00:02:48",
    img: "https://static.netnaija.com/i/PrO7OeeANyp.jpg",
    body: "Nigerian serial hit-maker, Joeboy has premiered the video to his latest single titled, 'Likkle Riddim'. The song follows the release of his previous song titled 'Contour'. Likkle Riddim was produced by P. Priime and music video shot and directed by TG Omori. As expected, the highly talented filmmaker delivers a colorful and befitting video to for the trending song.",
    source: "https://www.youtube.com/watch?v=RVJz7IF3bsY",
    comments: [],
  },
];
