export const examinationData = [
  {
    id: 4701,
    title: "WAEC releases 2022 WASSCE results",
    type: "Examinations",
    time: "Aug 08",
    author: "Moses O",
    img: "https://static.netnaija.com/i/1qdNVp3m74g.webp",
    body: "The West African Examinations Council, WAEC has released the results of the recently concluded 2022 West African Senior School Certificate Examinations, (WASSCE). WAEC's Head of National Office, Patrick Areghan made the disclosure on Monday while speaking at a media briefing. According to him, the results were released 45 days after the last paper. The examination held for six weeks from May 16 to June 23, 2022.",
    comments: [],
  },
  {
    id: 4702,
    title: "WAEC announces release of WASSCE result",
    type: "Examinations",
    time: "Feb 14",
    author: "Moses O",
    img: "https://static.netnaija.com/i/1qdNVp3m74g.webp",
    body: "The West African Examinations Council (WAEC), has announced when the West African Senior School Certificate Examination (WASSCE) results for Private Candidates 2021- Second Series will be released. WAEC disclosed that the result would be released later today, Monday, February 14, 2022. WASSCE for Private Candidates also known as General Certificate Examination, GCE, is written in November/December. It's a private examination that doesn't require uniforms, but biometric registration is compulsory. The examination is usually taken by secondary school leavers who want to correct deficiencies in their results. WAEC, in a tweet on its official Twitter handle on Sunday night, wrote: '@waecnigeria is set to announce the release of results of WASSCE for Private Candidates, 2021- Second Series tomorrow, Monday, February 14, 2022. Stay tuned for more details!'",
    comments: [],
  },
  {
    id: 4703,
    title: "BREAKING: WAEC releases 2021 SSCE results",
    type: "Examinations",
    time: "Nov 22, 2021",
    author: "Moses O",
    img: "https://static.netnaija.com/i/1qdNVp3m74g.webp",
    body: "The West Africa Examination Council (WAEC) has released the result of the 2021 West African Senior School Certificate Examination (WASSCE) Mr Patrick Areghan, Head of the Nigeria National Office of the Council who disclosed this on Monday, said a total of 80.56 per cent have been fully processed, and 19.44 per cent still being processed due to some issues being resolved. Areghan said One Million, Five Hundred and Seventy-Three Thousand, Eight Hundred and Forty-Nine (1,573,849) candidates registered for the examination and 1,560,261 candidates sat the examination. 'The examination, which was an international one, took place simultaneously throughout the five-member countries of the Council - The Gambia, Ghana, Liberia, Nigeria and Sierra Leone, using the same International Timetable. 'The examination spanned seven weeks, between August 16 and October 8, 2021. Throughout the period, we were faced with serious security challenges in the South East (IPOB and ESN sit-at-home order) and banditry, kidnapping, insurgency, etc, in the north and other parts of the country. All these, coupled with the continuous effect of the COVID-19 Pandemic, made the whole exercise a Herculean one.'",
    comments: [],
  },
  {
    id: 4704,
    title:
      "FG bans SS1, SS2 students from participating in WASSCE, NECO, NABTEB",
    type: "Examinations",
    time: "Sep 25, 2021",
    author: "Moses O",
    img: "https://static.netnaija.com/i/1qdNVp3m74g.webp",
    body: "The Federal Government has stopped students in Senior Secondary School one and two from participating in external West African Senior School Certificate Examination, WASSCE; the National Examination Council, NECO; and National Business and Technical Examinations Board, NABTEB. The development was contained in a circular issued to principals of federal unity schools by the Federal Ministry of Education. The circular was signed by the ministry's Director, Senior Secondary Education, Hajia Binta Abdulkadir, and confirmed by the Director of Press and Public Relations, Ben Bem Goong, on Friday. The circular read, 'The ministry's attention has been drawn to the flagrant disregard to its directive on (the) writing of external examinations such as NABTEB (NTC and NBC), WASSCE, NECO (SSCE) by SS1 and SS2 students. 'Students who are involved in the practice find it difficult to settle down on serious studies. They become unruly and distract other students from achieving their goals. 'Any student caught to have written any of the above examinations in SS1 or SS2 classes will be expelled from the college. All students must write these examinations after they have been duly registered for the examination by the college. 'All students of Federal Unity College should adhere strictly to the content of this circular. And Principals are advised to bring the content of this circular to the knowledge of all parents of the college.'",
    comments: [],
  },
  {
    id: 4705,
    title: "NECO releases 2020 SSCE results",
    type: "Examinations",
    time: "Jan 13, 2021",
    author: "Moses O",
    img: "https://img.netnaija.com/hsi/aHR0cHM6Ly9kYWlseXBvc3Qubmcvd3AtY29udGVudC91cGxvYWRzLzIwMjEvMDEvTkVDTy0xMDI0eDU3Ni5qcGc=/images/NECO-1024x576.jpg",
    body: "The National Examinations Council (NECO) has released the internal Senior Secondary School Examination (SSCE) results. This year, there has been a two per cent increase in candidates who made five credits and above in all subjects. NECO also derecognised 12 schools for their involvement in mass cheating and cases of malpractice. The Registrar, Professor Godswill Obioma, confirmed this at the NECO Headquarters in Minna. Obioma said the schools derecognised include four schools in Adamawa, two in Kaduna, two in Kastina, Two in Niger, one in Taraba and one in FCT. He said that 24 supervisors were blacklisted for various offences ranging from poor supervision, aiding and abetting, connivance with non candidates to write answers on chalkboards. The support lines to confirmed the news and the customer care assistant said: 'Yes, it is true. The results have been released. 'To check, visit result.neco.gov.ng and input your details'.",
    comments: [],
  },
  {
    id: 4706,
    title: "2021 WASSCE: WAEC confirms deadline for registration",
    type: "Examinations",
    time: "Jan 10, 2021",
    author: "Moses O",
    img: "https://img.netnaija.com/hsi/aHR0cHM6Ly9kYWlseXBvc3Qubmcvd3AtY29udGVudC91cGxvYWRzLzIwMTkvMDcvV0FFQy5qcGcud2VicA==/images/WAEC.jpg.webp",
    body: "The West African Examinations Council, (WAEC) Nigeria, has confirmed that Jan. 29, 2021, is the deadline for the registration of this year's West African Senior School Certificate Examination (WASSCE) for private candidates, 2021-First Series. WAEC's Head of Public Affairs, Mr Demianus Ojijeogu, made this known in Benin City on Saturday, Vanguard reports. Ojijeoge explained that the registration pins and information CDs could be obtained at the WAEC office. 'The West African Examinations Council invites potential candidates to register for the West African Senior School Certificate Examination for private candidates, 2021-First Series,' Ojijeoge said. 'Registration pins and information CDs can be obtained at WAEC office, Aduwawa Benin city, banks and accredited agents. 'Entry closes on Jan. 29, 2021, and the registration fee is N3, 950,00. 'The public announcement is from our WAEC zonal offices, Benin City, Edo State,' he added.",
    comments: [],
  },
  {
    id: 4707,
    title: "BREAKING: NECO announces new date for SSCE",
    type: "Examinations",
    time: "Nov 02, 2020",
    author: "Moses O",
    img: "https://img.netnaija.com/hsi/aHR0cHM6Ly9kYWlseXBvc3Qubmcvd3AtY29udGVudC91cGxvYWRzLzIwMTkvMDgvTkVDTy5qcGcud2VicA==/images/NECO.jpg.webp",
    body: "The National Examinations Council (NECO), on Monday, announced that 2020 Senior School Certificate Examination (SSCE) in all states and Abuja, will resume on November 9. NECO spokesperson, Azeez Sani, made the announcement on Monday. Recall that the exam was suspended due to the nationwide End SARS protest. Speaking on Monday Sani said, 'Following the return of normalcy in the states and FCT, the examinations will now continue with a new Time-Table from Monday 9th November, 2020 to Saturday 28th November, 2020.' He added that the exam body will make the new schedule available to the general public, schools and candidates from November 4.",
    comments: [],
  },
  {
    id: 4708,
    title: "WAEC withholds results of 215,149 candidates",
    type: "Examinations",
    time: "Nov 02, 2020",
    author: "Moses O",
    img: "https://img.netnaija.com/hsi/aHR0cHM6Ly93d3cuZ2lzdHJlZWwuY29tL3dwLWNvbnRlbnQvdXBsb2Fkcy8yMDIwLzExL2J1eS13YWVjLXJlc3VsdC1jaGVja2VyLXBpbi1vbmxpbmUtaW4tbmlnZXJpYS5wbmc=/images/buy-waec-result-checker-pin-online-in-nigeria.png",
    body: "The West African Examinations Council (WAEC) on Monday disclosed that it has withheld the results of 215,149 candidates who wrote the 2020 West African Senior School Certificate Examination (WASSCE) in Nigeria. WAEC said the results of the candidates representing 13.98% of the total number of candidates who wrote the examination are being withheld in connection with various reported cases of examination malpractice. Patrick Areghan, head of WAEC Nigeria, broke the news at a briefing in Lagos on Monday morning while announcing the official release of this year's WASSCE results. According him, 'The cases are being investigated and reports of the investigations will be presented to the appropriate Committee of the Council for determination in due course. The Committee's decisions will be communicated to the affected candidates through their various schools.' He added; '81,718 candidates, representing 5.31% have a few of their subjects still being processed due to some errors on the part of the candidates. Efforts are, however, being made to speedily complete the processing to enable all the affected candidates get their results fully processed and released, subsequently.'",
    comments: [],
  },
  {
    id: 4709,
    title: "2020 WASSCE results out Monday - WAEC",
    type: "Examinations",
    time: "Nov 01, 2020",
    author: "Moses O",
    img: "https://img.netnaija.com/hsi/aHR0cHM6Ly93d3cuZ2lzdHJlZWwuY29tL3dwLWNvbnRlbnQvdXBsb2Fkcy8yMDIwLzEwL3dhZWMtaW1hZ2VzLTEyMzAzNjAwMDYxOTM5MDY2OTkwLi5qcGc=/images/waec-images-12303600061939066990..jpg",
    body: "The results of the 2020 West African Senior Secondary School Certificate Examination (WASSCE) will be released on Monday, November 2. The West African Examinations Council (WAEC) gave the update Sunday night. The body announced that the results will be out from 10:30am. 'This is to inform candidates that sat West African Senior School Certificate Examination (WASSCE) for School Candidates, 2020 that the results of that exam will be released by @waecnigeria tomorrow, Monday, November 2, 2020 by 10:30am', it tweeted. WAEC had explained that the delay in release was due to incidents and curfew in some parts of Nigeria. ",
    comments: [],
  },
  {
    id: 4710,
    title:
      "WAEC postpones release of 2020 SSSCE results, reveals when results will be ready",
    type: "Examinations",
    time: "Oct 28, 2020",
    author: "Moses O",
    img: "https://img.netnaija.com/hsi/aHR0cHM6Ly93d3cuZ2lzdHJlZWwuY29tL3dwLWNvbnRlbnQvdXBsb2Fkcy8yMDIwLzEwL3dhZWMtaW1hZ2VzLTEyMzAzNjAwMDYxOTM5MDY2OTkwLi5qcGc=/images/waec-images-12303600061939066990..jpg",
    body: "The West African Examination Council, WAEC, has postponed the release of 2020 SSSCE results and has revealed when results will be released. WAEC told her candidates who sat for the 2020 Senior Secondary School Certificate Examination to expect the release of their results next week. This announcement was made by the West African Examinations Council on its official Nigerian Twitter page today, October 28. The results were supposed to be released today but the examination body said the postponement became unavoidable owing to the violence and arson in the country which affected some of its offices and operations across the country. The unrest experienced in the aftermath of the #EndSARS protests against police brutality and bad governance had compelled governments to impose curfew in various states. 'WASSCE SC 2020 Results Release Date: Dear candidates, the Council had planned to release the results today in fulfilment of our Project 45 but due to the curfew imposed last week, it had to be postponed till next week. The exact date will be made known soon,' @waecnigeria tweeted on Wednesday.",
    comments: [],
  },
  {
    id: 4711,
    title: "End SARS: NECO postpones examination",
    type: "Examinations",
    time: "Oct 18, 2020",
    author: "Moses O",
    img: "https://img.netnaija.com/hsi/aHR0cHM6Ly9kYWlseXBvc3Qubmcvd3AtY29udGVudC91cGxvYWRzLzIwMTkvMDgvTkVDTy5qcGcud2VicA==/images/NECO.jpg.webp",
    body: "The National Examination Council (NECO) has announced the reschedule of Paper I Computer Studies Practicals which was to take place on Monday 19 October 2020 to November 16 2020. This was made known in a statement by the Head, Information and Public Relations Division, NECO, Azeez Sani. Sani said the paper was rescheduled because of the End SARS protests that blocked the free movement of transport at the entrance gate into Benin City, the Edo state capital. He further stated that the NECO delivery truck left its take-off point two days earlier to deliver examination materials to some states but has been held up in the 'blockage. 'This is to inform the general public and especially candidates that the National Examinations Council (NECO) has been constrained to reschedule the Paper I Computer Studies Practical's earlier scheduled to take place on Monday 19 October 2020, 10 am to 1 pm. 'The examination of this paper will now hold on Monday 16 November 2020, 10 am-1 pm. 'This unforeseen incident has been caused by the End SARS protest that blocked the free movement of transport at the City entrance gate Benin. 'The Council wishes to assure all stakeholders and the general public that the affected examination materials have been retrieved intact and are in the custody of NECO's vault. 'While regretting any inconveniences this rescheduling may cause our esteemed stakeholders, the Council has however taken this decision in order to maintain the integrity and security of its examinations procedures for seamless conduct of the Council's examination.'",
    comments: [],
  },
  {
    id: 4712,
    title: "NECO releases dates for 2020 examination",
    type: "Examinations",
    time: "Aug 11, 2020",
    author: "Moses O",
    img: "https://img.netnaija.com/hsi/aHR0cHM6Ly9kYWlseXBvc3Qubmcvd3AtY29udGVudC91cGxvYWRzLzIwMTkvMDgvTkVDTy0xMDI0eDg2Ny5qcGcud2VicA==/images/NECO-1024x867.jpg.webp",
    body: "The National Examinations Council, NECO on Tuesday released the date for the conduct of its 2020 examinations for Senior Secondary three students. The board in a press statement signed by its Registrar/Chief Executive Officer, Professor Godswill Obioma, announced that the NECO SSCE will take place on Monday 5th October 2020 to Wednesday 18th November 2020. The exam body also announced that admission of JSS1 students into Federal Unity Colleges will take place on Saturday 17th October 2020. The Basic Education Certificate Examinations (re-sit) has also been scheduled to hold on Wednesday, 11th and Thursday 12th November 2020 for the prescribed relevant subjects. 'The BECE for JSS 3 students, also conducted by NECO, will start on August 24 and end on September 7. 'The National Business and Technical Examination Board examinations will start on September 21 and end on October 15. 'Other details of the schedule indicate that the Senior Secondary School Certificate Examinations for SS3, conducted by NECO will start on October 5 and end on November 18, 2020,' the statement read in part.",
    comments: [],
  },
];
