export const utmeData = [
  {
    id: 4801,
    title: "JAMB announces cut-off mark for 2022 admission",
    type: "UTME/Post-UTME",
    time: "Jul 21",
    author: "Moses O",
    img: "https://static.netnaija.com/i/W4lNmwLo7Ro.webp",
    body: "The Joint Admissions and Matriculation Board (JAMB) on Thursday approved 140 and above as the national minimum cut-off mark for admission into public universities in 2022. JAMB reached the decision at the ongoing Policy Meeting on Admissions to Tertiary Institutions in Nigeria.The board also approved 100 as the minimum cut-off mark for admission into polytechnics and Colleges of Education.Professor Ishaq Oloyede, JAMB's Registrar, who announced the cut-off said every institution has the right to fix its cut-off mark even up to 220 but no one would be allowed to go less than the agreed minimum marks of 100 for Colleges of Education, 100 for Polytechnics and 140 for Universities.He further revealed that a total of 378,639 of the 1,761,338 who wrote the 2022 Unified Tertiary Matriculation Examinations (UTME) scored 200 and above.",
    comments: [],
  },
  {
    id: 4802,
    title:
      "BREAKING: JAMB releases 2022 UTME results, reveals only way to check",
    type: "UTME/Post-UTME",
    time: "May 14",
    author: "Moses O",
    img: "https://static.netnaija.com/i/zxG7ZYyWKq2.webp",
    body: "The Joint Admissions and Matriculations Board (JAMB) has released the 2022 Unified Tertiary Matriculation Examination (UTME) results. A statement by the Head, Public Affairs and Protocol, Fabian Benjamin, said to check results, candidates need 'to simply send a text message, UTMERESULT to 55019 using the same phone number that he/she had used for registration and the result would be sent. According to the statement, the Board has not uploaded results on its website for obvious reasons, saying the above process is the only way to check results for now. The Board, however, warned candidates not to fall victim to fraudsters in accessing their results through the process outlined. 'Candidates are forewarned that they would, as usual, receive all kinds of messages from desperate fraudsters on how to check their results different from the aforementioned one. 'Hence, the Board urge all candidates to ignore all such messages on how to check their 2022 UTME results as they are all products of deceit aimed at misleading them. 'The Board, in line with its desire to adhere to the ease of doing business protocol of the government, has emplaced this user-friendly and simplified process of checking UTME results. 'This simplified process would also serve to preclude the unconscionable exploitation of candidates by shylock business centres and cybercafes which often take advantage of hapless candidates,' the statement stressed. Recall that the 2022 UTME began on Friday, 6th May 2022 and ended on Friday 13th May 2022. Over 1.7 milion candidates registered and sat for the examination nationwide.",
    comments: [],
  },
  {
    id: 4803,
    title: "JAMB announces date for 2022 UTME, DE registration",
    type: "UTME/Post-UTME",
    time: "Jan 24",
    author: "Moses O",
    img: "https://static.netnaija.com/i/zxG7ZYyWKq2.webp",
    body: "The Joint Admission and Matriculations Board have set aside April 20 to 30th, 2022, for the commencement of the Unified Tertiary Matriculation Examination (UTME). The mock examination is expected to hold on April 2nd, 2022, while registration for the examination would commence from 12th February and end on 19th March 2022, respectively. The information was contained in a weekly bulletin released by JAMB's director of media and public relations, Fabian Benjamin on Monday. We also gathered that the Board has resolved to refund N4,000 which many candidates paid but were unsuccessful in completing the registration process for the 2021 Unified Tertiary Matriculation Examination including the Direct Entry Examinations. 'This is to notify all 2021 candidates who had deposited a draft of four thousand naira (N4,000) for late registration for the 2021 Unified Tertiary Matriculation Examination and Direct Entry but were unable to complete the registration process owing to no fault of the Board, even after the Board had extended the registration period twice, to visit the Board's Website and complete a form for the refund of the value of the draft they submitted to the Board. 'The above candidates are to click on the link 2021 UTME/DE Unregistered Candidates Bank Draft Recapture and fill the spaces after which they would key in the token sent to the phone numbers they had submitted during the submission of their drafts. It is this token that would be used to access a form on which they will fill in their account details for the refund of the value of the draft. Candidates are to provide these details within the next two weeks from the date of this publication. 'A text message containing OTP has been sent to the affected candidates besides this notification, 'the bulletin added. The UTME, conducted by JAMB is a uniform entry-level examination for candidates seeking tertiary education. ",
    comments: [],
  },
  {
    id: 4804,
    title: "JAMB cancels national cut off marks, makes new decisions",
    type: "UTME/Post-UTME",
    time: "Aug 31, 2021",
    author: "Moses O",
    img: "https://static.netnaija.com/i/zxG7ZYyWKq2.webp",
    body: "The Joint Admissions and Matriculation Board (JAMB) has cancelled the national cut-off mark. The body said it would now be left for Nigeria's tertiary institutions to determine its admission benchmark. This decision was made on Tuesday at the 2021 policy meeting presided over by the Minister of Education, Malam Adamu Adamu. The Registrar of JAMB Prof. Is-haq Oloyede, who spoke during the forum said some universities such as the University of Maiduguri proposed 150, Usman Dan Fodio University Sokoto proposed 140, Pan Atlantic University proposed 210, University of Lagos 200, Lagos State University190, Covenant University 190, and Bayero University Kano, 180. According to the stakeholders, the 2021 admissions will be conducted only through JAMB CAPS and no institution is allowed to admit candidates without uploading their details onto the portal.",
    comments: [],
  },
  {
    id: 4805,
    title: "JAMB shifts 2021 UTME exam",
    type: "UTME/Post-UTME",
    time: "May 15, 2021",
    author: "Moses O",
    img: "https://static.netnaija.com/i/no4NXqjK9MY.webp",
    body: "The Joint Admissions and Matriculation Board has extended the deadline for the ongoing 2021 UTME/DE registration exercise by two weeks. The exam body took the decision after a meeting with stakeholders following reports of widespread delay in the registration process among candidates for the 2021 Unified Tertiary Matriculation Examination. JAMB Registrar, Ishaq Oloyede, who announced the extension said the exam will now start on the 19th of June 2021 and end on the 3rd of July. Prof Oloyede also announced that the registration exercise will now end on May 29. This comes after the JAMB Board earlier announced it's contemplating an extension to the registration period and change of date for the Unified Tertiary Matriculation Examination. ",
    comments: [],
  },
  {
    id: 4806,
    title: "UTME: JAMB gives update on printing of 2021 mock slip",
    type: "UTME/Post-UTME",
    time: "May 20, 2021",
    author: "Moses O",
    img: "https://static.netnaija.com/i/zxG7ZYyWKq2.webp",
    body: "The Joint Admissions and Matriculation Board, JAMB, has urged candidates to reprint their 2021 Unified Tertiary Matriculation Examination, UTME mock notification slip. JAMB's Director of Press, Dr. Fabian Benjamin said the new mock notification slip was ready for printing. Benjamin said the reprint was consequent to the change of date for the mock exercise earlier scheduled for Thursday, 20th May 2021 but would now hold on Thursday, 3rd June 2021. In a statement, Benjamin said the new slip would carry the new date of the examination. He said, 'Candidates who had registered for the 2021 Unified Tertiary Matriculation Examination and indicated interest to sit the optional mock examination are to REPRINT their mock notification slips. 'It is imperative to reprint as the new slip will have the new date. 'As disclosed earlier, the optional mock notification slips can be printed from anywhere that candidates find convenient provided they have internet access.' The JAMB spokesman said candidates should visit the JAMB website for directions. He added: 'To print the slip, candidates are to visit the website, click on e-facility and print their slips. The slip contains the candidates' details such as registration number and, most importantly, the centre at which they are to sit the examination within their chosen examination town and the expected time to be at the centre. 'Candidates need to print their slips and study the contents to know the location of their centres as some candidates do not read the instructions on their slips only for them to be looking for the name of their examination town instead of their examination centre on the day of the exercise.'",
    comments: [],
  },
  {
    id: 4807,
    title: "BREAKING: JAMB reschedules UTME Mock exams",
    type: "UTME/Post-UTME",
    time: "Apr 25, 2021",
    author: "Moses O",
    img: "https://static.netnaija.com/i/no4NXqjK9MY.webp",
    body: "The Joint Admissions and Matriculations Board (JAMB) has postponed the 2021 Mock Unified Tertiary Matriculation Examination (UTME). The exam, earlier scheduled to hold on Saturday, 30th April, has been rescheduled to hold on Thursday, 20th May. Fabian Benjamin, Head, Public Affairs in a statement said the change of date was due to ongoing adjustments in operational processes. He explained this would not affect the Mock Examination other schedules, including the date for the UTME fixed for 5th to 19th June, 2021. The spokesman informed all stakeholders that the 2021 UTME/DE Registration exercise is ongoing and will end on 15th May, 2021. The board, however, said it was concerned that some candidates, in trying to generate their profiles, were sending their details wrongly to 55019. 'The right process is to send the word 'NIN' allow one space in between, then insert the eleven digits NIN number to 55019 e.g. NIN 00000000000. 'Any other process is wrong and would not generate the profile code for the candidate. It is also necessary for the candidate to know that only the SIM that is linked to his/her NIN can be used to send the NIN to 55019', the statement added.",
    comments: [],
  },
  {
    id: 4808,
    title: "JAMB announces new feature in UTME registration",
    type: "UTME/Post-UTME",
    time: "Apr 22, 2021",
    author: "Moses O",
    img: "https://static.netnaija.com/i/no4NXqjK9MY.webp",
    body: "The Joint Admissions and Matriculation Board (JAMB) says it has announced a new feature in the ongoing registration for the 2021 Unified Tertiary Matriculation Examination (UTME). The exam body in a statement issued on Thursday by its Head of Media and Protocol, Fabian Benjamin, said the feature, 'Know Your Registration Officer,' aims to fortify the registration process. According to Benjamin, the new feature will also guard candidates against abuse and manipulation. Benjamin further noted that candidates who are applying for the 2021 UTME, which is due to close on 15th May 2021 are advised to immediately raise an alarm the moment they find out that the picture on the screen doesn't match the face of the person registering them. 'To further fortify the registration process and ensure that candidates know where and who is registering them for the 2021 Unified Tertiary Matriculation Examination Board( UTME) and Direct Entry (DE) exercise, the Joint Admissions and Matriculation Board(JAMB) has made provisions for the image of the Registration Officer to be displayed at the corner of the screen being used to register the candidate besides his biometric details that had been captured. 'Candidates registering for the 2021 UTME/DE exercise are urged to ensure that the picture shown on the corner of the screen is the same person registering them. If the picture does not match the face of the Registration Officer, candidates should immediately raise the alarm as such a person is not authorised to register them or they are in a completely unauthorised registration outlet. 'This measure is in addition to several others put in place to guide against manipulation, abuse and exploitation of candidates as well as forestalling examination malpractices. 'The Board's innovations, including this one which comes with some little changes and additions to its processes, are to make the system better and fortified against those who are working non-stop to take advantage of the system. 'It is, therefore, required of candidates who are the major stakeholders in the process, to monitor the process as they are being registered and adhere to extant instructions, rules and regulations,' the statement said. ",
    comments: [],
  },
  {
    id: 4809,
    title:
      "Reactions as JAMB uses “WhatsApp status” as a medium to make an official announcement to millions of Nigerians",
    type: "UTME/Post-UTME",
    time: "Mar 26, 2021",
    author: "Moses O",
    img: "https://static.netnaija.com/i/3g8NBzrNDR4.jpg",
    body: "Joint Admissions and Matriculation Board (JAMB) has passed on an official announcement to millions of students seeking admission into universities of their choice using “Whatsapp status” as a medium. Jamb on Thursday took to Twitter to announce that the official portal for the Unified Tertiary Matriculation Examination (UTME) and Direct Entry (DE) will be open for registration. This is, however, starting on Thursday, April 8, and ending on Saturday, May 15, 2021. Registration will be taking place in 700 centers across the country. In addition, Jamb has also said that all potential candidates must provide their NIN at the point of registration for the Unified Tertiary Matriculation Examination (UTME) and Direct Entry (DE) registration.",
    comments: [],
  },
  {
    id: 4810,
    title: "2021 UTME: JAMB begins registration, gives date for exam",
    type: "UTME/Post-UTME",
    time: "Mar 25, 2021",
    author: "Moses O",
    img: "https://static.netnaija.com/i/no4NXqjK9MY.webp",
    body: "Joint Admissions and Matriculation Board (JAMB) on Wednesday announced that it has started the 2021 Unified Tertiary Matriculation Examination (UTME) and Direct Entry (DE) registration. The exam body in a statement issued in Bwari, FCT, by its Head, Public Affairs and Protocols, Dr Fabian Benjamin, on Wednesday said all potential candidates must provide their National Identity Number (NIN) at the point of registration. According to the spokesperson, NIN is mandatory for participation in the 2021 registration exercise. Fabian also announced that UTME will hold from Saturday, June 5 to Saturday, June 19, 2021. “Registration will take place in 700 centres across the country; the list is available in all the state offices of JAMB and on its website at www.jamb.gov.ng. 'The approved schedule for registration and examination is that registration exercise will start on Thursday, April 8 and end on Saturday, May 15, 2021. 'Candidates are also to note that the registration for Direct Entry applicants will run concurrently with that of UTME candidates. 'There will be no extension of time for the sale of the UTME or DE application documents. 'Mock examination will be held on Friday, April 30 for those who indicate interest and are registered before April 24. The statement informed that venues of the examination would be at any of the centres in the candidate’s chosen examination town, adding that the registration fee for the 2021 application documents remained N3, 500 and N500 for recommended Reading Text. The exam body explained that information regarding the registration processes and requirements would be made available on the board’s official website and also advertised in the electronic and print media from April 5.",
    comments: [],
  },
  {
    id: 4811,
    title:
      "Here's How To Register For 2019 UTME | See All JAMB Accredited Centres",
    type: "UTME/Post-UTME",
    time: "Jan 11, 2019",
    author: "Moses O",
    img: "https://img.netnaija.com/hsi/aHR0cHM6Ly93d3cuMzYwbm9icy5jb20vd3AtY29udGVudC91cGxvYWRzLzIwMTUvMDgvSkFNQi1VVE1FLnBuZw==/images/JAMB-UTME.png",
    body: "The Joint Admissions and Matriculations Board (JAMB) has begun the sale of this year's Unified Tertiary Matriculation Examination (UTME) form to candidates.The board also took to its verified Twitter page (@JAMBHQ) to reveal how candidates should register for the exam. In a series of tweets, the exam body wrote: 1. No candidate should proceed to any CBT centre without first creating a profile. 2. Candidates are advised to create a profile by sending their name (Surname, First-name, and Middle-name) via SMS to 55019. 3. After which a 10 digit profile code would be sent to their telephone number. 4. This code will then be used to purchase the application document at the point of purchase (Banks, MMOs, MFBs, USSD Partners etc). 5. A form e-pin would then be sent to the candidate via SMS. 6. The candidate is to present the e-pin at any JAMB accredited CBT centre for registration. The link is arranged alphabetically. Meanwhile, the board also released a list of accredited computer-based test centres for registration. Click link: https://www.jamb.gov.ng/PDFs/listofapprovedcentres_2019.pdf It should be noted that on December 20, the board stated that the registration for the UTME would no longer be done at cybercafés but at accredited CBT centres.",
    comments: [],
  },
  {
    id: 4812,
    title: "BREAKING: 2020 admissions: JAMB announces start date for post UTME",
    type: "UTME/Post-UTME",
    time: "Aug 10, 2020",
    author: "Moses O",
    img: "https://img.netnaija.com/hsi/aHR0cHM6Ly9kYWlseXBvc3Qubmcvd3AtY29udGVudC91cGxvYWRzLzIwMTkvMDYvNzIxNjBmM2EtamFtYi1sb2dvLTEwMjR4NTc2LmpwZy53ZWJw/images/72160f3a-jamb-logo-1024x576.jpg.webp",
    body: "The Joint Admissions and Matriculation Board (JAMB), has announced the start date for the post-Unified Tertiary Matriculation Examination (Post-UTME). The screening for the 2020 admission processes will commence on September 7 in universities, polytechnics and colleges of education. JAMB explained that the shift from August 21 was to accommodate candidates taking part in this year's school-based Senior School Certificate Examination (SSCE). Ishaq Oloyede, the Registrar, made this known on Monday, after a virtual meeting with Vice Chancellors, Rectors, and Provosts of tertiary institutions. He said: 'Presently as you are aware, WAEC starts the Senior School Certificate Examination on Aug. 17, it will go on till Sept. 7. Similarly, on Sept. 2 or thereabout, NABTEB will commence its own examination that will go on till Oct. 15, and immediately after that, NECO starts from the 5th to Nov.18. 'Rather than making candidates run, particularly, when they will have to write their school certificate exam in different towns and rush to universities elsewhere for post-UTME, like somebody rushing from Sokoto to Ibadan for post-UTME, we believe as a custodian of the highest sector of the education system, we should avoid that.' Oloyede added that institutions whose post-UTME screening was mandatory for candidates would have to spread such exercise in two phases. 'For those institutions who want to take post-UTME, that cannot be earlier than the 7th of September and it will be held twice - from 7th September to 4th of October, and then it will be held for the second time on the 18th of November to mop up those who are taking their school certificate examination,' he said.",
    comments: [],
  },
];
