export const gamblingData = [
  {
    id: 3101,
    title: "ILOT: ONLINE BETTING IN NIGERIA",
    type: "Gambling",
    time: "May 18",
    author: "Same Emmanuel",
    img: "https://static.netnaija.com/i/zxG7ZvL27q2.jpg",
    body: "Everybody wants to win. Nobody wants to be a loser. However, in the business of sports betting, it isn't always the case to emerge a winner. But, if the right conditions are met, a user can record far more winnings than losses. This is where ILOT NG comes in. Online sports betting in Nigeria has just been made easier! ILOT NG is a relatively new sports betting company in Nigeria but they are proving to be a major contender with the other known big dogs in the industry.Sports betting in Nigeria is a vast business and the opportunities are endless. There have been cases of people that won multimillions with just meager sums of money as their initial stake. This is why the industry has amassed such popularity over the years and it continues to grow. ILOT NG is a bookie that offers incredibly large odds. This is no joke. In comparison with even some of the bigger names in the industry, ILOT NG has bigger odds, and if you ask me, this is a major selling point for them and this explains why more people are joining the latest Big Dog in the sports betting community in Nigeria. Log on to http://www.ilot.ng and witness the sweetness of the BEST ODDS IN NIGERIA for yourself. ILOT NG is a sports betting and lottery bookmaking company that offers online services in Nigeria. Among the company's services offerings are Sports betting, not restricted to football, hockey, tennis, basketball, and Lottery games including Football 14, Quick 3, 5/90 and so much more. ILOT NG also offers Virtual Games (Virtual Cup & Virtual League) which is sure to keep customers glued to their screens for maximum entertainment. The virtual games run for a short duration as 60 seconds and users can win up to TWO MILLION NAIRA just in the space of one minute!!",
    comments: [],
  },
  {
    id: 3102,
    title: "Win Exciting Bonuses with the Vitamin Promo at 1xBet",
    type: "Gambling",
    time: "Apr 16, 2020",
    author: "Same Emmanuel",
    img: "https://img.netnaija.com/02MHHK.jpg",
    body: "1xBet launched a new promotion focused on their pack of over 100 unique 1xGames. Besides the exclusive opportunity to enjoy games that are not available anywhere else online, you get the opportunity to win four different types of rewards. The promotion is called Vitamin Bonus and it's the perfect way to boost your gameplay and improve your winning chances. To take part in this promotion you need to be a registered 1xBet user. In case you don't have an account already, creating one takes just a couple of seconds and on top of becoming eligible for the Vitamin Bonus promo, you will get to enjoy plenty of bonuses and rewards.",
    comments: [],
  },
  {
    id: 3103,
    title: "Win a PlayStation 5 in Mozzart Bet Play 'n' Win",
    type: "Gambling",
    time: "Mar 08",
    author: "Same Emmanuel",
    img: "https://static.netnaija.com/i/1qGK1A22KrV.jpg",
    body: "Stand a chance to win a PS 5 in the Mozzart Bet Play 'n' Win contest. Instructions:- Stake your bets on Mozzart Bet Nigeria with a minimum of NGN 2,000 every day for three weeks and the game console could be yours! The more you play, the more your chances of winning. This contest is not for persons under the age of 18.",
    comments: [],
  },
  {
    id: 3104,
    title: "Join The Joker on a path to riches!",
    type: "Gambling",
    time: "Oct 15, 2019",
    author: "Same Emmanuel",
    img: "https://img.netnaija.com/tN2HHK.jpg",
    body: "Join the Joker as he traverses Gotham City gaining riches at every turn. The clown prince of crime is alive and unwell, conjuring up some evil plans to take over the city while making it big. Todd Phillips and Scott Silver delved into the dark side of life to produce the 2019 film The Joker that is hot on everyone's lips.Oscar talk is abuzz, but not only in Hollywood. 1xBet provides bettors with a load of betting opportunities on The Joker which could potentially bring rich rewards. While the Joker is a delusional man who taps in and out of reality, there is nothing delusional about the winning potential at 1xBet. The Joker brings a world of winning chances! And the Oscar goes to....'  - in a few months, the Oscars will reveal the big winners in Hollywood but in the meantime, the bets are rolling in as to who is going to take the top prize. At 1xBet players can bet on the 2020 Academy Awards 2020 with markets which include categories such as who will win Best Actor, Best Picture and Best Director. Plenty of pundits are predicting a multitude of awards The Joker!. Besides being able to bet on who is going to win at the Oscars, the 1xBet team offers another way to be caught up in the crazy crook's antics with a game dedicated entirely to 'Beating the Joker.' The  game revolves around beating the villian with higher cards trigger, which triggers a great win! Now that is something to laugh about - so smile and profit with The Joker! 'Is it just me or is the city getting crazier?'  - nope it's 1xBet doing what they do best, creating a multitude of betting opportunities for its most treasured audience. For once the audience doesn't have to sit back and merely enjoy the show though as 1xBet believes in everyone being involved in big wins and betting on The Joker is no exception. Jaoquin Phoenix is not walking the line on this one, he is laughing all the way to the bank and he is taking you with him! Get to 1xBet right away to make your movie prediction for the Oscars and while you are there, try out 'Beat The Joker'.",
    comments: [],
  },
  {
    id: 3105,
    title: "One Solid Strategy for Each Online Casino Game",
    type: "Gambling",
    time: "Jun 21",
    author: "Same Emmanuel",
    img: "https://static.netnaija.com/i/8yZaJYPA7J0.jpg",
    body: "With so many online casino game strategies, you may not know the best ones for each game. Sure, all games are designed to give the house (site) an edge. But what if we told you there are solid strategies to enhance your chances of winning. In this article, you'll learn the best strategies to make you a better gambler and ultimately increase your chances of winning. -Differentiate Games of Skill from Games of Luck- There are so many game offerings in an online casino. It is common to get immersed in a game you don't comprehend due to its fanciful gameplay and graphics. Although casinos are meant to provide you with relaxation, every gambler intends to win money as much as they enjoy. You can limit yourself to playing games of skill if you want a fruitful outcome. Games of skill are card and table games. Avoid games like slots, 3-card poker, and keno at all costs. Poker: - Poker is by far the most skillful online casino game. There are multiple poker options at Betway Casino Zambia, which increases the offerings you can wager on. Caribbean Hold'em, Texas Hold'em, and Caribbean Stud Poker are the best poker games that emphasize strategy. Master the suits in every poker game you play. If you draw an ace, you know that after 13 rounds, any player can draw the next ace. So, in a 52-card deck, you know there are four cards of equal rank in each suit. Use this card counting technique to win at online poker.",
    comments: [],
  },
  {
    id: 3106,
    title:
      "1xBet's Prize Hunt Promotion Final Draw Prizes Awarded - a Samsung TV, two smartphones, and tons of bonus points",
    type: "Gambling",
    time: "Jul 16, 2021",
    author: "Same Emmanuel",
    img: "https://static.netnaija.com/i/1qdNVPLA74g.jpg",
    body: "The Prize Hunt promotion started on 1xBet in March and had its second and final draw on the 13th of June. During the months it was active, this promo awarded many rewards to players that took part in it. That was the case for three lucky Nigerian 1xBet customers that won in the final Prize Hunt draw. One player walked away with a brand-new Samsung TV, while two other participants won a Samsung A71 smartphone each. The list of rewards continues with no less than six 1xBet customers that received bonus points. With nine winners in total, there were plenty of reasons to celebrate, take pictures, and enjoy the event. Ubong Effiong Okon, the Full HD Samsung 5 Series TV winner, lives in Itu and was a 1xBet member for a short while before taking part in the Prize Hunt promo. He placed several bets for the promotion, winning some of them. Even though he didn't win in the first draw of the promotion, he kept trying and ended up winning the Samsung TV. When 1xBet called to announce the prize he won, Ubong couldn't believe it. However, the shock quickly turned into pure happiness as he realized everything is real, and he's going to pick up his prize. He said he'll put the new TV to good use, watching sport matches and his favourite TV shows. Ubong's message to other Nigerians is not to hesitate and take part in 1xBet promotions, as one can never know when luck strikes. Adeniran Adetunwase Adeyemo also won the Prize Hunt promotion on 1xBet. After placing numerous bets and winning most of them, he also added the Samsung A71 to the list of rewards received from the bookmaker. Not aware of the promotion until after the first draw took place, he decided to participate in the second one and was among lucky players. When asked about his prize, Adeniran said he will use the smartphone to have a better experience on 1xBet and to access other mobile websites of interest. Furthermore, mister Adeyemo shared some of his wisdom with other players by saying that betting is a game of luck, and if anyone is afraid to take part, it only means that person is afraid to let his luck shine. Okoye Anthony from Aba Abia state is the winner of the second Samsung A71 in the Prize Hunt promotion. He's a long-time 1xBet user, with over five hundred bets placed across time. A determined individual, Okoye, kept on placing bets after discovering the 1xBet promotion and won the smartphone without taking part in the first stage. He plans on keeping the phone for himself and use it for everyday tasks that will be easier and more enjoyable. Okoye is an example of how you need to keep trying to win since life itself is a risk, in his own words. So even if sometimes you win, and sometimes you don't, you need to keep trying to achieve your goals.",
    comments: [],
  },
  {
    id: 3107,
    title:
      "Win Lamborghini, Bentley and Jaguar supercars in the new 1xBet promotion with a prize pool of $1,000,000!",
    type: "Gambling",
    time: "Jun 16, 2021",
    author: "Same Emmanuel",
    img: "https://static.netnaija.com/i/W4lNm6XwKRo.jpg",
    body: "The European Football Championship is one of the most popular sporting events, always eagerly awaited by fans worldwide. 1xBet couldn't ignore such an important event and, especially for this top tournament, has launched an incredible 1xEuro promotion. As part of the promo, fans can win one of three supercars - a Lamborghini, Bentley or Jaguar - as well as cutting-edge gadgets, free bets and much more. The prize fund of the promo is an astounding $1,000,000! How to participate Simply follow a few easy steps: Register or log in to 1xBet. Go to the 1xEuro promotion page and click the 'Take Part' button. Place single bets of $7 or more, with odds of 1.6 or greater, on the outcome or exact score of EURO matches Collect points (1 point for a losing bet and 3 for a winning bet) and open EURO stadium cards on the promotion page. How will the winners be determined? During the 1xEuro promotion, players have several opportunities to win. Firstly, every player who reveals all 11 European Championship stadium cards will receive a guaranteed prize - a $5 Free Bet! It's simple: to open one card, you just need to place a bet, according to the promotional parameters, on the match that will take place at the corresponding stadium. Secondly, the 12 players who have accumulated the most points during the promotion (from June 2nd to July 11th) will receive guaranteed top prizes, the main of which is the Lamborghini Urus Giallo Inti! Other lucky winners will receive gifts such as the Apple MacBook Pro 13' 256Gb, Samsung Galaxy S21 Ultra 5G 256Gb smartphone and other cool gadgets. Thirdly, on July 13th, the final draw will take place, in which the winners of luxurious prizes will be randomly selected among all the participants who have scored 10 points or more! Among them: a Bentley Bentayga V8, Jaguar F-Pace PRESTIGE, five Apple MacBook Pro 16' 512Gb laptops, ten Apple iPhone 12 Pro Max 256 GB, as well as other smartphones, tablets, drones, headphones, game consoles and smartwatches.",
    comments: [],
  },
  {
    id: 3108,
    title: "1xBet player wins over $2 million on a 44-event accumulator",
    type: "Gambling",
    time: "Apr 22, 2021",
    author: "Same Emmanuel",
    img: "https://static.netnaija.com/i/qEQN2jwRN6W.jpg",
    body: "We all know the story of Ali Baba from childhood, the man who found untold riches and managed to take advantage of his good fortune. Who hasn't dreamed of emulating him and becoming rich in an instant? After all, we all love fairy tales with a wonderful ending, where the people's hero is revered. It turns out that in 2021, to get rich overnight, you don't have to go to mysterious caves or seek spells - just place bets on the 1xBet website! At least, this was the path to success for a 44-year-old Almaty resident named Mukhazhan, who recently started playing at 1xBet in 2019. The inspired punter succeeded in a really impressive forecast, almost incredible in its accuracy - well worth telling about in more detail. This player placed bets on the website of 1xBet, one of the world's leading bookmakers, and risked a large sum of 100 thousand tenge (approximately $ 238) on an accumulator comprising of 44 events. Astoundingly, he won, scooping up an incredible 876,682,300 tenge, which is more than 2 million dollars! A fantastic amount that will surely motivate plenty of people to bet at 1xBet. 'I bet exclusively on football. I myself am a football player - I am well versed in this sport. You have seen the result. I chose 1xBet due to the fact that they have freedom of choice in betting: For example, unlimited accumulator bets, high odds, plus the ability to bet on the same team in different tournaments. I like the freedom of choice; I think it's right, that's why I am with 1xBet. I like big accumulator bets; if you win, then it's big. To be honest, I was nervous before the last matches. When there are 3-4 matches left, and you understand that such an outcome is possible, then willy-nilly, you start to get nervous. The last match was at night; I did not believe it right away. It seemed that this was not happening to me. I immediately woke up my wife, showed her what was occuring. The money was immediately credited to the gaming account - there was zero, and then the amount that you already know about was immediately received,' said Mukhazhan.",
    comments: [],
  },
  {
    id: 3109,
    title: "FG directs filmmakers to avoid money ritual contents",
    type: "Gambling",
    time: "Feb 21",
    author: "LuvlyGist",
    img: "https://static.netnaija.com/i/1xYNeDj2aLJ.jpg",
    body: "Minister of Information and Culture, Lai Mohammed has disclosed that filmmakers in the country have been asked to avoid making money ritual contents. Speaking during a media visit to Daily Trust office in Abuja on Monday February 21, the Minister said the Federal Government's decision to sanitise social media is hinged on confessions of some money ritual suspects. Lai Mohammed said:- 'Many have also blamed Nollywood for featuring money rituals in some of its movies, saying this has negatively influenced the vulnerable youth. To mitigate this, I have directed the National Film and Video Censors Board, the body set up to regulate the film and video industry in Nigeria, to take this issue into consideration while performing its role of censoring and classifying films and videos. 'I have also directed NFVCB to engage with stakeholders in the film industry in order to express the concerns of the government and Nigerians on the need to eschew money ritual content in their movies.'",
    comments: [],
  },
  {
    id: 3110,
    title:
      "Kaduna govt shuts down Bet9ja, Access Bet, King bet, others' offices",
    type: "Gambling",
    time: "Sep 13, 2020",
    author: "Moses O",
    img: "https://img.netnaija.com/hsi/aHR0cHM6Ly9kYWlseXBvc3Qubmcvd3AtY29udGVudC91cGxvYWRzLzIwMjAvMDkva2FkdW5hLTE1MzZ4MTE1Mi5qcGc=/images/kaduna-1536x1152.jpg",
    body: "The Kaduna State Internal Revenue Service (KADIRS) has shut down 13 gaming offices in the state. Mr Liye Anthony, Head of Gaming in the agency, disclosed this in an interview with the News Agency of Nigeria (NAN) in Kaduna on Sunday. Anthony said that the operation, which began on Thursday, had so far shut down five offices of bet9ja and King Bet respectively, two Access Bet offices and one office of Derby Lotto. He said that there were about 1,500 gaming offices across the state operating illegally without due registration and license. According to him, the exercise will continue until all the illegal gaming offices are shut down. 'We will continue to go after them until all the operators of the gaming companies regularized their operations and obtain the needed license to operate in the state,' he said. The Executive Chairman of the agency, Dr Zaid Abubakar, had told newsmen that apart from operating illegally, the gaming companies were mopping about N2.0 billion monthly from the state and were not paying a kobo to the state government as tax. He also said that the operators of the gaming companies were equally required by law to integrate their operations into the KADIRS Service Software, stressing that the companies failed to do so.",
    comments: [],
  },
  {
    id: 3111,
    title: "Win More at 1xBet with the Hot Win Promotion",
    type: "Gambling",
    time: "Sep 01, 2020",
    author: "Same Emmanuel",
    img: "https://img.netnaija.com/RDvHHK.jpg",
    body: "Who doesn't love a good promotion that boosts winning chances? Especially one that doesn't require you to do anything extra or special. 1xBet has put together an amazing promo called Hot Win that presents you with the chance of winning Samsung smartphones, thousands of bonus points, or a Bajaj Motorcycle 150. Already curious about how you can put your hands on such prizes at 1xBet? Keep reading to find out how the promotion works and how you can maximize your winning chances. How to Take Part? To be able to enjoy the benefits of the Hot Win promotion you need to be a 1xBet member. So, create an account if you don't have one already. Then, you need to access your account - no matter if you do so on a mobile device or desktop - and place a minimum stake of 2 USD on any sport. That's it! Every bet of 2 USD or more brings you tickets for the three draws that can see you walking away with a Samsung Galaxy A51 (September, 9), Samsung Galaxy A71 (September, 23), or a Bajaj Boxer 150 Motorcycle (October, 7). And all these amazing prizes aren't destined just for one winner. There are 7 winners for each first prize draw. On top of that, another 35 winners will receive amounts between 50 and 1,000 bonus points with each draw.",
    comments: [],
  },
  {
    id: 3112,
    title: "Sports Betting Guide - Simple Tips and The Basics",
    type: "Gambling",
    time: "Aug 13, 2020",
    author: "Same Emmanuel",
    img: "https://img.netnaija.com/hsi/aHR0cHM6Ly93d3cudGVjaGljeS5jb20vd3AtY29udGVudC91cGxvYWRzLzIwMjAvMDMvR2V0dGluZy1Uby1Lbm93LVRoZS1TcG9ydHMtQmV0dGluZy1HYW1lLUJlZ2lubmVycy1HdWlkZS5wbmc=/images/Getting-To-Know-The-Sports-Betting-Game-Beginners-Guide.png",
    body: "Sports betting is a simple, fun way of making some money. However, if you are a beginner, you shouldn't rush into placing bets just yet. Even though sports betting on an online betting platform like Betway is simple, it is not easy to get things right when you're beginning. In this guide, you'll learn simple tips and basics of sports betting to make it more interesting. Set Achievable Goals- You can make a few correct predictions from time to time. But, it is usually an uphill task to win frequently enough to make a profit. The truth is there is a higher chance you'll lose money than win when starting. The biggest mistake many beginners make is thinking that they can use their sports knowledge to outsmart the bookmakers. The truth is that it takes more than sports knowledge to profit from sports betting. To be a successful bettor takes a lot of preparation and learning. The first thing to do is set achievable goals. Your target should be to learn more and improve gradually. Once you become more knowledgeable, you can start setting more complex goals. You can begin by enjoying yourself in the short term then start getting serious slowly as you continue. Learn All the Basics. Before you start placing your bets on Betway, ensure you learn all the basics. Remember, the basics alone are not sufficient to help you make a profit but are critical in helping you start right. The basics you must learn are:",
    comments: [],
  },
  {
    id: 3113,
    title:
      "Journalist rents a billboard to appreciate her husband on Valentine",
    type: "Gambling",
    time: "Feb 14",
    author: "LuvlyGist",
    img: "https://static.netnaija.com/i/9bVNrA22aWv.png",
    body: "Tanzanian media personality, Zamaradi Mketema started off an online conversation after putting up a huge billboard with her husband's face, as one of her Valentine's Day gift.Mketema who appreciated her husband for being an amazing lover and father to their kids, also said she will make sure her husband is the happiest man alive. She wrote on Instagram:- If words will let me, it's hard to express your value in words. THANK YOU FOR EVERYTHING !!!I will make sure you are the HAPPIEST MAN alive, I LOVE you man, I love you so much. Happy Valentines Baby!",
    comments: [],
  },
  {
    id: 3114,
    title: "Turn Your Music Knowledge into Profit at 1xBet!",
    type: "Gambling",
    time: "Jul 24, 2020",
    author: "Same Emmanuel",
    img: "https://img.netnaija.com/RNbHHK.jpg",
    body: "1xBet provides variety and many betting markets besides sports betting. Of course, you still get fantastic odds and around 60 sports betting options; however, there is much more than sports betting at 1xBet! Customers like to bet on something different apart from sports. 1xBet has a fantastic choice of unusual and alternative betting markets. There are lots of exciting, fun events that provide even winning opportunities. You can benefit from your knowledge of your favourite singers and pop stars. If you aren't a music fan, there are lots of other original betting markets like movies, politics, TV and world events. Let's look closer at the music-related betting markets for now. Profit by Betting on the Grammys The Grammy Awards are an opportunity to earn a profit if your favourite artist wins. Why not do more than cheer along and take the chance of making an income? If you visit the 1xBet site and place a bet on the Grammys, you may have all the more reasons to celebrate when the award is presented. There is the cream of music artists to choose from, and only one of them will take the crown and win Album of the Year. Who will it be? Fans of Billie Eilish can dig into particular bet types for her results at the Grammy Awards. 1xBet serves up a special and unique betting market where you need to anticipate if she will win more or less than two Grammys at the 2021 award ceremony.",
    comments: [],
  },
  {
    id: 3115,
    title:
      "Best time for NetNaijaRians - Get N100,000 Bonus on 1xBet with our Exclusive Promo Code",
    type: "Gambling",
    time: "Sep 20, 2019",
    author: "Same Emmanuel",
    img: "https://img.netnaija.com/vv1HHK.jpg",
    body: "Sports betting can be profitable and a whole lot of fun. Finding the best odds and special offers is a key part in making that experience even richer. But exactly how do we go about doing that? Fortunately, the answer is right here with an exclusive promo code from 1xBet! Renowned as the world leader in sport betting, 1xBet not only has incredible odds but also the widest array of markets. That all adds up to your best chance of winning big! Now the 1xBet journey is even more exciting for players in Nigeria! By registering with the 'NN1' promo code, the standard welcome deposit of 200% up to $270 will be boosted to 200% up to $350! A great win before you even begin to bet! At 1xBet you'll find all your favourite sporting action with thousands of betting markets daily. Use the promo code on this page to begin your journey today at 1xBet with a boosted betting bankroll! Don't miss out - register now!",
    comments: [],
  },
  {
    id: 3116,
    title: "How to win a motorcycle with 1xBet - success stories",
    type: "Gambling",
    time: "Jun 04, 2020",
    author: "Same Emmanuel",
    img: "https://img.netnaija.com/-p_HHK.jpg",
    body: "Big prizes and vivid emotions - this is how the Africa Cup of Nations was remembered for many Nigerians. During this tournament, leading bookmaker 1xBet launched a promotion that saw dozens of players become proud owners of modern motorcycles. How did this become possible? The winners of the promo talk about how they managed to win motorcycles without much effort: 'My name is Moses Alexander. I am a YouTube blogger, but in my free time I like to bet on 1xBet. During the Africa Cup, I made only one bet on the match of the Nigeria national team, and this was enough to win. A representative of 1xBet contacted me and said that I won a prize. At first I thought that they were kidding me. It turned out to be true! It's just fantastic, I have never won such a big prize before, 'said one of the winners. Taiwo Yahaya. another participant of the promo, has a similar story -. He made only one bet, but that was also all that was needed for him to become the owner of a motorcycle. 'I live in Lagos, I work as a business administrator. I love football and sometimes bet. I remember that during the Africa Cup I put on the winner of the tournament. When I found out that I won a motorcycle, I was very happy. I had to learn to ride a motorcycle, because before I did not have this type of transport. Such a prize is very useful in everyday life, it helps to get to work faster. After winning the promotion from 1xBet, I can say for sure that I will continue to bet on football, ' declared Taiwo. If you believe in luck, then the victory will be yours. So says one of the winners, who wished to remain anonymous. He says: 'I made one bet on the Africa Cup, I just don't remember which one. But I was sure of my victory, because I've always been lucky. So I was waiting for the announcement of the winners, then a guy from 1xBet called me and said that I won the motorcycle. 'These amazing stories once again confirm that sometimes luck is somewhere nearby, and you can also become the owner of a motorcycle without any effort. One bet on a match made these guys ecstatic. Perhaps next time good luck and prizes are waiting for you?",
    comments: [],
  },
];
