export const jobsData = [
  {
    id: 3401,
    title: "10 Things To Never Do In An Interview",
    type: "Jobs/Vacancies",
    time: "Aug 30, 2021",
    author: "Same Emmanuel",
    img: "https://static.netnaija.com/i/BQJNjljV7rL.jpg",
    body: "Looking forward to selling yourself? Job interviews are one of the best places to do that. Now, if your résumé and cover letter have been impressive enough to get you an interview, the job could be yours-provided you perform well at the interview. They have trained your interviewer to identify key signals to help them determine if you have the skillset and appropriate temperament to fit into the organisation and execute your job. The company will most likely have several other applicants interviewing for the role, and limited time to fill the position, so it's essential for them to take all things into consideration during the interview process. It is okay to be uncomfortable at first, remember that even the most seasoned professional can get flustered and spoil their chances, so with a little preparation, you can avoid these common interview blunders. There are some things you must not do in a job interview, and below are some of these: -Not Researching- A major mistake you can make is not doing enough research about the company you are going to for an interview. You need to know the core of the business, what they do, their mission statement. When you check these, you will know how to key into what they do. Find out who the competition and major players in the market are. -Dressing Inappropriately- Understandably, times are changing. However, for your interviews, dress appropriately and look responsible. The way you dress says a lot about who you are and you do not want your interviewer to have the wrong impression. Don't forget, first impressions matter. -Not Being Punctual- NEVER go to your interview late, it says all the wrong things about you. However, if things beyond your control come up, send a mail or reach out to your interviewer. Not informing your interviewer and being careless shows you do not respect the time of your interviewer. -Poor Body Language- Being fidgety will not get you the desired language, but when you smile, maintain eye contact, and keep a cheerful demeanour, you will get what you want. Also, it feels like you know what you are doing and confidence works in getting what you want. -Speaking Negatively About Your Previous Employers- No matter what you must have gone through in your previous place of work, do not speak ill about your previous employers. Avoid words that are negative, it shows professionalism, and that is what you want the interviewer to see. -Cursing- As said earlier, times are changing, however, don't get too familiar and start using unaccepted language. Keep everything professional. Do not get too familiar with your interviewer and lose yourself. -Lying On Your Resumé- There is always a need to impress your interviewer and at least bag an interview, however, you cannot keep up with the lies. When you send in your resumé, send in your exact education status, what you have done and what you can do. -Rambling- Before you answer the questions, take your time. You might be flustered and just want to get done with the interview, hence, you might be in a rush. No matter how tense you are, remember, you can do the job, you are capable and they would be lucky to have you on board. So do not ramble, be calm, and think before answering the questions. -Interrupting Your Interviewer- Interviews can be nerve-wracking and could make you appear and become overly enthusiastic. Regardless of how excited you are to list off your accomplishments and ideas for the company, which you would be allowed to do at some point, it is important to listen intently and pay close attention to what your interviewer is saying. Do not interrupt your interviewer or make them feel inadequate. When it's your turn, share all your ideas, or revisit any of the points the interviewer brought up that will help position you as the perfect candidate. -Using Your Phone- Putting your phone or smartwatch on vibrate will not suffice because a buzzing device can be distracting. You will have to excuse yourself while you dig in your bag to silence your phone, or constantly look down at your watch as the notifications roll in. Any type of unnecessary interruption is distracting and can make you come across as unprofessional and unprepared. When choosing between two nearly perfect candidates, this type of incident could be the reason you don't make the cut. So put your phone on silent till you are done with the interview, the short period off your phone will not harm you. All the best as you navigate through life.",
    comments: [],
  },
  {
    id: 3402,
    title: "4 Unconventional Jobs To Try In Nigeria",
    type: "Jobs/Vacancies",
    time: "May 18, 2021",
    author: "Same Emmanuel",
    img: "https://static.netnaija.com/i/pJdN9bD5K4P.jpg",
    body: "However, the world is evolving, and people are becoming more enlightened about the endless possibilities and financial stability several other careers offer. High-income earnings are an important factor for many people when choosing a career. As the Yoruba saying goes, 'Owo ni Koko' meaning money is the principal thing. These days people are taking career paths that lead to making money. It is no wonder digital marketing and social media influencing has become popular amongst many around the world. These online jobs pay well, for those maximising the use of their platform. Nevertheless, there are more jobs outside of the box that can fetch good returns. Here are 4 infamous jobs with high rate earnings: Thrift business Engaging in the thrift business can be lucrative. Thrift business involves the buying and selling of fairly used items from countries abroad specifically, the UK, China, and Korea. These items include; fashion wears morale and female, various home appliances, children toys among many others. The thrift industry is a booming sector, with thrift-style businesses having an earning rate of $17 billion a year in just the US. In Nigeria, an average thrift business owner earns between 200,000 Naira and above in a month. The business is a straightforward and open business for all. You don't have to tender a certificate or have prior knowledge of how to operate in the sector. The business gives room for wholesalers and retailers to make good profits. It is also cheap and easy to set up. You can start a thrift business with a capital as low as 10,000 Naira and make almost double of the capital. Also, you don't need a shop to start your thrift business. Thanks to social media, you can connect to a potential customer without having to do so much. Just find your niche, a social media account, take a wonderful picture of what you are selling and you are on the go. Cattle rearing This business can be dangerous, but that doesn't stop it from being one of the infamous high earning rate businesses in Nigeria. In this part of the world, the notion of cattle rearing is boxed. Many believe it to be a business for only Hausa and the Fulani men. This notion is false, anyone can be a cattle rearer just as anyone can decide to become a doctor. Although a bit costly to start up, the cattle farming business is very profitable. A small-sized cow can sell for 200,000 naira.",
    comments: [],
  },
  {
    id: 3403,
    title: "'We are recruiting'- NNPC confirms",
    type: "Jobs/Vacancies",
    time: "Mar 13, 2019",
    author: "Tayo",
    img: "https://img.netnaija.com/hsi/aHR0cHM6Ly93d3cuZ2lzdHJlZWwuY29tL3dwLWNvbnRlbnQvdXBsb2Fkcy8yMDE5LzAzL0dNRC1OTlBDLU1haWthbnRpLUJhcnUuanBn/images/GMD-NNPC-Maikanti-Baru.jpg",
    body: "The Nigerian National Petroleum Corporation ( NNPC) says it has opened its portal for recruitment of fresh graduates and experienced professionals into the system. Mr Ndu Ughamadu, its Group General Manager, (Public Affairs Division), confirmed this to the News Agency of Nigeria (NAN) in Abuja on Wednesday.He said that the portal for the recruitment was opened on Wednesday. The recruitment portal address is https://careers.nnpcgroup.com 'The portal was opened today and I have received hundreds of inquiries weather it is correct or not.' We are going to recruit people from different engineering fields , especially fresh graduates and equally in the administrative areas,' he said Ughamadu said that recruitment would be in three categories of fresh graduates, senior officers/ supervisory cadre and managerial cadre. (NAN)",
    comments: [],
  },
  {
    id: 3404,
    title: "RECRUITMENT: Nigerian Air Force Airmen & Airwomen 2017",
    type: "Jobs/Vacancies",
    time: "Jan 07, 2017",
    author: "Tayo",
    img: "https://img.netnaija.com/hsi/aHR0cDovL25haWphbG9hZGVkLTE0ZmNreXpmdHdoeHJkNWN0YmF1LnN0YWNrcGF0aGRucy5jb20vd3AtY29udGVudC91cGxvYWRzLzIwMTcvMDEvTkdSLU1JTElUQVJZLTEuanBn/images/NGR-MILITARY-1.jpg",
    body: "Application for Nigerian Air Force Airmen and Airwomen Recruitment Exercise 2017 is all set: GUIDELINE 1. Interested applicants are to apply free of charge online 2. Applicants are to apply once, multiple online application will be disqualified 3. Applicants are to print out the underlisted documents after completion of application online a. Local Government Indigeneship Form b. Attestation form to be signed by Military officer or Local Government Chairman c. Parent/Guardian Consent Form d. Acknowledgment Form.",
    comments: [],
  },
  {
    id: 3405,
    title: "NYSC Launches Job Portal For Corps Members (Read Details)",
    type: "Jobs/Vacancies",
    time: "Dec 09, 2017",
    author: "Tayo",
    img: "https://img.netnaija.com/hsi/aHR0cHM6Ly8zLmJwLmJsb2dzcG90LmNvbS8tTUVkVE9SOEtweG8vV2lzTTIzZ18tb0kvQUFBQUFBQUFQZFEvRUhVVGduaFc5LUlsc25TWEZpek1vMFJMWXJtWkx3Mmh3Q0xjQkdBcy9zMTYwMC9OWVNDLmpwZw==/images/NYSC.jpg",
    body: "The National Youth Service Corps has launched a job portal that would enhance job seeking opportunities for Corps Members and also make them available for prospective employers. NYSC Director-General, Brigadier General Sulaiman Kazaure, while speaking at the launch today in Lagos, urged Corps Members to make themselves available for job opportunities with the aid of the portal. He added that the portal would serve as a pool for employers searching for suitable candidates and also provide a means of verification of credentials. He, however added that the Management of National Youth Service Corps have established Zonal lntegrated Skill Centres in six different locations across the country aimed at entrenching entrepreneurship among Corps Members. In her keynote address, the Managing Director, Gr8jobs Limited, Mrs Omomene Odike, emphasized the need for every job seeker to acquire relevant information in order to survive in the competitive job market. She said there was the need to reduce unemployment in Nigeria while she urged Corps Members to upload their data on relevant portals. NYSC Lagos Statec Coordinator, Prince Mohammed Momoh, said the NYSC Lagos initiative would reduce the stress of job search among Corps Members.",
    comments: [],
  },
  {
    id: 3406,
    title:
      "LOL !! See this funny application letter written by a graduate in Abuja (photo)",
    type: "Jobs/Vacancies",
    time: "Jul 04, 2017",
    author: "Tayo",
    img: "https://img.netnaija.com/hsi/aHR0cDovL3d3dy55YWJhbGVmdG9ubGluZS5jb20vd3AtY29udGVudC91cGxvYWRzLzIwMTcvMDcvQXBwbGljYXRpb24tTGV0dGVyLmpwZw==/images/Application-Letter.jpg",
    body: "Here's a funny application letter received by an office in Abuja today, from a female graduate. According to the twitter user (@BryteDude) who shared it on Twitter, they are still recovering from the shock. He Tweeted ; See an application letter received by an office in Abuja today, from a graduate... Scratch that. A compatriot. God help us Walahi, you can't imagine the shock those of us who received the letter, are going through. Letter that came with CV and copies of credentials? This is real life. Had to crop out the address at the top, and her name below.",
    comments: [],
  },
  {
    id: 3407,
    title: "Online registration of unemployed Nigerians begins April 5th",
    type: "Jobs/Vacancies",
    time: "Apr 04, 2017",
    author: "Olaniran Sodiq Adeniyi",
    img: "https://img.netnaija.com/hsi/aHR0cDovL2NkbjEuZGFpbHlwb3N0Lm5nL3dwLWNvbnRlbnQvdXBsb2Fkcy8yMDEzLzAxL25ld3MxOS0zMDB4MzMwLmpwZw==/images/news19-300x330.jpg",
    body: "The Federal Government has said all is set for the commencement of online registration of unemployed persons in the country on Wednesday April 5th 2017. This was disclosed in a statement signed by the Deputy Director, Information & Public Relations, National Directorate of Employment (NDE), Edmund Onwuliri on Monday.According to him, the development was part of the federal government's plan to develop and maintain a robust database of unemployed persons and for job provision. He explained that the registration was in compliance with the third mandate of the NDE which required it 'to obtain and maintain a data bank on employment and vacancies in the country with a view to acting as a clearing house to link job seekers with vacancies in collaboration with other government agencies.' He said: 'The online portal which goes live on Wednesday April 5, 2017, is designed to capture the relevant details of any unemployed person. It will equally serve as a job exchange portal that will link job seekers and employers. 'There will be a practical demonstration of the workings of the portal at the NDE stand at the on-going 28th edition of the Enugu International Trade on Thursday April 6, 2017. However, the portal can be accessed by logging on to www.jobsforall.ng. 'The Directorate sees this initiative as a bold step towards deepening the effectiveness of its employment creation strategies and a critical input into the process of designing, implementation, monitoring and evaluation of programmes and schemes. 'The online portal will also serve as a meeting point for job seekers and employers thereby reducing the cumbersome process of recruitment among employers of skilled labour in the private and public sectors.'",
    comments: [],
  },
  {
    id: 3408,
    title:
      "International Youth Day: Fulfil Your Promise On Job Creation, NLC Tells FG",
    type: "Jobs/Vacancies",
    time: "Aug 12, 2016",
    author: "Tayo",
    img: "https://img.netnaija.com/hsi/aHR0cHM6Ly8zLmJwLmJsb2dzcG90LmNvbS8tYk4zVGREdXNtYm8vVjY0QTV4c3pqUUkvQUFBQUFBQUNxVWMvTm5EbGhZRXlhVmdNRHpOZXladWUtUzVwcjlfaWlneC1BQ0xjQi9zMjgwL05MQy5qcGc=/images/NLC.jpg",
    body: "The Nigeria Labour Congress, NLC today urged the Federal Government to fulfil its promise on job creation and youth employment in the country. The NLC General Secretary, Peter Ozo-Eson, made the call in a statement he issued in commemoration of the 2016 International Youth Day. Mr. Ozo-Eson said as the NLC felicitates with Nigerian youths and the world on the commemoration of the 2016 International Youth Day, it was imperative for the Federal Government to fulfil its promise to them. 'The congress is committed to the issues of youth empowerment because only then can we guarantee the future of our nation and the sustainability of the labour movement.'This is also in line with the United Nations 2016 theme which is 'The Road to 2030: Eradicating Poverty and Achieving Sustainable Consumption and Production'. 'It is in realisation of the role of the youths in the trade unions and indeed the society at large that the congress has adopted a Youth Policy as part of the activities to mark this year's International Youth Day,' he said.",
    comments: [],
  },
  {
    id: 3409,
    title: "FG extends online job application by one month",
    type: "Jobs/Vacancies",
    time: "Aug 02, 2016",
    author: "Tayo",
    img: "https://img.netnaija.com/hsi/aHR0cDovL3MzLWV1LXdlc3QtMS5hbWF6b25hd3MuY29tL3B1bmNobmcvd3AtY29udGVudC91cGxvYWRzLzIwMTYvMDcvMDgyMzIxNDcvTGFvbHUtQWthbmRlLmpwZw==/images/Laolu-Akande.jpg",
    body: "The Federal Government on Monday extended the timeline for the N-Power online jobs and training applications till the end of August. The Senior Special Assistant to the Vice-President on Media and Publicity, Mr. Laolu Akande, disclosed this in a statement made available to journalists. Akande said the decision to extend the timeline was taken in order to pull in more potentially qualified candidates and expand the opportunity base around and across the country. He said the application process which commenced on June 12 was initially billed to close on July 25. The statement read, 'However, being very keen on keeping its promise of empowering and uplifting young Nigerians by improving their livelihood and creating opportunities such as this (in an as inclusive and diverse manner), the Federal Government is providing an additional grace period for more young Nigerians to access the N-Power opportunity. 'The new deadline for the receipt of applications is now Wednesday, August 31, 2016. 'N-Power is one of the initiatives of the N500bn President Muhammadu Buhari's Social Investment Programme designed to empower young Nigerians with life-long skills to find or create work.",
    comments: [],
  },
  {
    id: 3410,
    title: "Job at Forte Oil Plc",
    type: "Jobs/Vacancies",
    time: "Jun 12, 2015",
    author: "Tayo",
    img: "https://img.netnaija.com/hsi/aHR0cDovLzIuYnAuYmxvZ3Nwb3QuY29tLy1QcEFTUVZSdTdYby9WWG9VN1hXSkFSSS9BQUFBQUFBRmh6RS9PNDdqWUc4ODdETS9zMTYwMC9hLmpwZw==/images/a.jpg",
    body: "Forte Oil PLC currently has over 300 vacancies available within its petrol stations in Lagos. These jobs include station managers, supervisors, cashiers and attendants. To apply, register at www.joblinknigeria.com/applynow or visit the Job-Link head office at 8 Kingsway Road, Ikoyi, Lagos. Applicants must write Forte on the application form when asked which vacancy they wish to apply for. Interviews and aptitude tests commence from 1st July 2015. Apply now",
    comments: [],
  },
];
