export const religionData = [
  {
    id: 3201,
    title:
      "Sacked Living Faith pastor drags Bishop Oyedepo, others to court, alleges frustration, maltreatment by church cabal",
    type: "Religion",
    time: "Oct 07",
    author: "Moses O",
    img: "https://static.netnaija.com/i/BQJNjoEBKrL.jpg",
    body: "A pastor of the Living Faith Church also known as Winners Chapel, Calabar, Dominic Essang Winner, has alleged that the 'cabal in the church' has been persecuting, maltreating and frustrating him, although he has spent two decades in the church and now has six branches under him. He spoke in an interview in Calabar after he sued the church and its founder, David Oyedepo, for not following the Mandate/operational manual used by the ministry to fire erring staff. He went further to claim that the gang up and lies against him led to termination of his appointment as resident pastor of Palm Street Extension parish Calabar. He has, therefore, dragged the church before the National Industrial Court of Nigeria, Calabar Judicial Division for alleged unlawful termination of his appointment. In suit No: NICN/CA/25/2022 suing Founder of Living Faith Church Worldwide Incorporated, Bishop David Oyedepo, Adebisi Aboluwade, and other two defendants for N350 Million compensation, the dismissed pastor, a Maths Statistics graduate of the University of Calabar, said he was bitter, not because he has been sacked, but because, it did not follow due process of the church. Essang was sad that the effort to let the General Overseer of the ministry, Dr David Oyedepo wade into the matter was highly frustrated by the cabals. Essang said, 'I was a member of that church for over a decade before training to become a pastor. At least, I have spent more than two decades in the ministry, that alone makes me a son to our General Overseer, Bishop David Oyedepo.' According to him, the church cabal consists one Pastor Tamunotoye Chukunda and the state pastor LFCWW Cross River State, Pastor Adeolu Adewumi.",
    comments: [],
  },
  {
    id: 3202,
    title: "Mbaka will return after solitude - Catholic Church",
    type: "Religion",
    time: "Oct 03",
    author: "Moses O",
    img: "https://static.netnaija.com/i/qvg70x5z7ze.png",
    body: "The spiritual Director of the Adoration Ministry, Enugu Nigeria, AMEN, will return after observing moments of solitude, the Catholic Church has revealed. This was confirmed by Padre Mike Nsikak Umoh, National Director of Social Communications, Catholic Secretariat of Nigeria (CSN). The clarification followed protests that had greeted Mbaka's announcement of his replacement during a mass on Sunday. He had told his followers that Rev. Fr. Anthony Amadi has been appointed his replacement as he proceeds to the monastery. The development sparked protest from the adorers. In a statement issued on Monday by Umoh, he said Amadi would oversee the ministry in the interim. While quoting Director of Communications, Enugu Diocese, Rev. Fr. Benjamin Achi, the CSN Spokesman said 'it was recommended that Fr. Mbaka takes time away in solitude, in order to listen to what the Spirit of God has to tell him, he was allowed to propose a priest to administer, in the interim, to the faithful at the Adoration Ministry.' He added that what every true Christian, and especially every true Catholic, should do at this moment 'is to commit our dear brother and priest, Fr. Mbaka, to God in prayer so that he may, through this moment, encounter God specially, come out stronger and better in recognizing His will for him and gain more graces to channel those rare gifts for His glory and for the sanctification of the people of God and society at large.' We learnt that he would be away till early next year. Before he announced his replacement on Sunday, he had told the congregation that he knew solutions to Nigeria's problem with regards to the 2023 general election but that he was restrained by God not to reveal it. He went further to say that some unnamed persons were wasting their time.",
    comments: [],
  },
  {
    id: 3203,
    title: "Fr. Mbaka removed from Adoration Ministry, sent to Monastery",
    type: "Religion",
    time: "Oct 03",
    author: "Moses O",
    img: "https://static.netnaija.com/i/gVpagbMj7wO.jpg",
    body: "Charismatic Enugu Priest, Rev. Fr. Ejike Mbaka has been transferred out from the Adoration Ministry. We report that the Church's latest decision is already generating protest from Mbaka's followers. The Adoration Ministry, which was shut down three months ago, was re-opened yesterday, Sunday. However, in the place of Fr. Mbaka, another clergy of the Catholic Diocese of Enugu, Rev. Fr. Anthony Amadi has been posted to take charge of the Adoration Ministry. Mbaka has been sent to Monastery. The transfer is with immediate effect. A top member of the ministry, who confirmed the posting, said the development was unfortunate. According to him:, 'all along, the Bishop has been trying to take over the Adoration Ministry. But I can assure you that no priest will succeed there. So long as Fr. Mbaka is not there, nobody will come there to worship. 'This will lead to anarchy. It's unthinkable that this kind of harsh decision could be made. We the adorers will never accept any other priest. 'Fr. Mbaka suffered and built that place will sole effort. Now they have tactically hijacked the place through the backyard. Let's see how they will succeed.' Mbaka's trouble started three months ago after he preached against Labour Party's presidential candidate, Mr. Peter Obi.",
    comments: [],
  },
  {
    id: 3204,
    title: "Catholic Diocese of Enugu lifts ban on Mbaka's adoration ministry",
    type: "Religion",
    time: "Sep 29",
    author: "Moses O",
    img: "https://static.netnaija.com/i/XV5KvzBBK9m.webp",
    body: "The Catholic Diocese of Enugu has lifted the ban on Rev Fr Ejike Mbaka's adoration ministry. This was disclosed in a terse statement by Rev Fr, Ejike Mbaka via a Facebook post on Thursday. The statement read, 'Dear Adorers, to the glory of God, Adoration Ministry Enugu Nigeria Amen, starts on Sunday 2nd October 2022 with 10am Mass at the Adoration ground Umuchigbo Iji Nike Emene Enugu State. God bless you miraculously as you come to worship God with us, Rev Fr, Ejike Mbaka",
    comments: [],
  },
  {
    id: 3205,
    title: "Stop expensive burials, help those alive - Fr. Gopep to Christians",
    type: "Religion",
    time: "Sep 25",
    author: "Moses O",
    img: "https://static.netnaija.com/i/deYakzb27P3.jpg",
    body: "Rev. Fr. Godfrey Gopep, Parish Priest of St. Finbarrs' Catholic Church in Rayfield, Jos, has advised Christians to stop expensive burials. The religious leader gave the advice in his homily on Sunday, NAN reports. Gopep noted that funerals should be solemn instead of the recurring 'show' during such ceremonies. The cleric said organizing expensive burials for loved ones would not take the deceased to heaven. 'I have observed that most Christian burials are expensive; we sink huge amounts of money to bury our loved ones. 'Sometimes, those who donated huge sums for the burial didn't support the deceased when he or she was alive. 'It has become like a show and competition among families; I heard that some churches now demand a fee before they conduct funerals. 'I advise Christians to cut down how they spend huge amounts to bury the dead and learn to support people when they are alive,' he advised. In January, Plateau Governor Simon Lalong appointed Gopep as Chaplain of the Government House Chapel. The 40-year-old was ordained a priest for the Catholic Archdiocese of Jos in October 2011.",
    comments: [],
  },
  {
    id: 3206,
    title:
      "Meet RCCG Pastor who participated in Queen Elizabeth II's funeral ceremony",
    type: "Religion",
    time: "Sep 21",
    author: "Moses O",
    img: "https://static.netnaija.com/i/1xYNeYAjNLJ.webp",
    body: "A Redeemed Christian Church of God Pastor (RCCG), Agu Irukwu, participated in the funeral ceremony of Britain's longest-serving monarch, Queen Elizabeth II, held on Monday, September 19. Irukwu is a former Chairman of the Redeemed Christian Church of God in the United Kingdom. The RCCG Pastor was one of the eight Pastors who represented the churches of England at the event. This was captured on page 4 of the Order of Service for Queen Elizabeth II's State Funeral. The Nigerian-born cleric is the current Senior Pastor of RCCG's Jesus House Parish, United Kingdom. He stepped down as the chairman of UK RCCG in April 2021. Pastor Irukwu was ordained a pastor in August 1993, according to RCCG UK website. He took over as Senior Pastor of Jesus House in April 1994, two months after it was birthed. He is a law graduate from the University of Warwick, a Barrister, and a former investment banker. Irukwu also serves as Chairman of the Board of Trustees and Head of the Executive Council of RCCG UK which acts in a supervisory capacity over the 600 parishes located in the United Kingdom. In addition, he is Chairman of the Festival of Life organizing committee.",
    comments: [],
  },
  {
    id: 3207,
    title:
      "Persistent covering of hair causes odour, stop imposing it on women - Kumuyi tells his church's ushers",
    type: "Religion",
    time: "Sep 18",
    author: "Moses O",
    img: "https://static.netnaija.com/i/gVpagbqR7wO.webp",
    body: "General Superintendent of Deeper Life Bible Church, Williams Kumuyi has preached against the persistent covering of hair by women. In a recent sermon, Kumuyi told ushers in his church to stop imposing hair covering rules on ladies as persistent coverings cause heat in the hair, which leads to odour. He lamented that Christians who don't know how to interpret God's word are driving people away from the church. The Deeper General Superintendent backed his directive by citing 1Cor 11v5 in the Bible. Kumuyi who wondered why some sisters in the church would cover their hair for almost 20 hours a day, stated that women should only have their heads covered while praying or prophesying. The cleric also said that such a manner of dressing has made some women unattractive. Kumuyi said;- 'Somebody is coming to our church for the first time. And she happens to be a lady not covering her head. 'We ask the person to cover her head before coming in and don't know whether the person does not even know God. 'Ushers confront her out there before she even enters the church and doesn't know if she does not know how to pray or prophesy. But we impose rules on her.'",
    comments: [],
  },
  {
    id: 3208,
    title:
      "Catholic Church resumes handshake during Mass, after COVID-19 pandemic",
    type: "Religion",
    time: "Sep 18",
    author: "Same Emmanuel",
    img: "https://static.netnaija.com/i/8yZaJonBNJ0.webp",
    body: "The Catholic Church has announced the resumption of the traditional handshakes in churches, which were suspended during the COVID-19 pandemic. His Grace, Most Rev. Lucius IIwejur-Ugorji, the Archbishop of Owerri diocese said in a statement that worshippers were to resume the 'Kiss of Peace' during Eucharistic and other events in the liturgical celebrations of the Church. The statement was signed by Rev. Fr. Cosmas Uzoigwe Personal Assistant to the Archbishop, and released through the National Director of Social Communications of the Church, Fr Mike Umoh, on Sunday in Abuja. The News Agency of Nigeria (NAN) reports that the statement was addressed to all Priests and Lay faithful in Owerri Archdiocese. 'It would be recalled that the COVID-19 pandemic forced us to pronounce stringent guidelines which affected our liturgical worship, and one of such was that which restrained all from shaking hands during Mass. 'The resolution to commence the liturgical gesture of shaking of hands came following the proceedings of the recently concluded Second Plenary of the Catholic Bishops' Conference of Nigeria held at Orlu. 'We thank God who led us through the challenging times of the COVID-19 pandemic, we pray Him to bless us always with His presence,' the Archbishop said.",
    comments: [],
  },
  {
    id: 3209,
    title:
      "'Carry your bl*od money and go' - Pastor Ibiyeomie tackles yahoo boys; stops them from remitting tithes, offerings (Video)",
    type: "Religion",
    time: "Jul 31",
    author: "Moses O",
    img: "https://static.netnaija.com/i/eDxawdeRNPZ.webp",
    body: "Pastor David Ibiyeomie of Salvation Ministry has stopped internet fraudsters popularly called 'Yahoo boys' from remitting tithes and offerings to the church. Speaking while delivering a sermon on Sunday, the cleric condemned the menace of cybercrime in Nigeria which is reportedly accompanied with 'blood ritual'. 'Carry your blood money and get out, it is not good, If it's that kind of money you have, carry and go to another church. This church will be rich. You think God cannot supply? Or you think it's your wicked blood money, carry and go, we don't want it here..Money that you kill people you want to pay tithe here..; Pastor Ibiyeomi passed the message in a video. His order is coming a few months after he cursed Yahoo boys in the country, noting that they would get into an accident because their activities have led to the death of some persons who they have scammed off all their retirement benefits. He had also laid curses on police officers who released arrested Yahoo boys after collecting bribes from them.",
    comments: [],
  },
  {
    id: 3210,
    title: "Pope Francis hints on stepping down",
    type: "Religion",
    time: "Jul 30",
    author: "Moses O",
    img: "https://static.netnaija.com/i/wnRaM26WNdq.jpg",
    body: "Catholic pontiff, Pope Francis, on Saturday, hinted on stepping down from his position. Pope Francis said he needed to slow down because he could no longer withstand the hectic schedule of international travels. He disclosed this to journalists after a six-day Canada trip. Pope Francis, who is suffering from knee pain, said he is considering stepping down due to his health issues. 'I don't think I can go at the same pace as I used to travel. 'I think that at my age and with this knee limitation, I have to save myself a little bit to be able to serve the Church. Or, alternatively, to think about the possibility of stepping aside,' he said.",
    comments: [],
  },
  {
    id: 3211,
    title:
      "Pope Francis names three women to Vatican department as calls grow for women priests in Catholic Church",
    type: "Religion",
    time: " Jul 13",
    author: "LuvlyGist",
    img: "https://static.netnaija.com/i/zOJabe6V7G2.jpg",
    body: "Pope Francis has named two nuns and a laywoman to the Vatican department that helps choose new bishops, the first time women have been allowed to serve on the body. The Holy See Press Office published the Pope's latest appointments to the Dicastery in a statement on Wednesday, July 13. The female members are Sister Raffaella Petrini, F.S.E., Secretary General of the Governorate of the Vatican City State; Sister Yvonne Reungoat, F.M.A, former Superior General of the Daughters of Mary Help of Christians; and, Dr. Maria Lia Zervino, President of the World Union of Catholic Women's Organizations. The three women were among 14 people appointed to the Dicastery for Bishops, which vets candidates and advises the pope on which priests should become bishops. The other 11 appointed on Wednesday were cardinals, bishops and priests. The appointment of the three women to the Dicastery for Bishops, nuns Raffaella Petrini and Yvonne Reungoat and lay woman María Lia Zervino comes as Francis seeks to usher in more gender equality within the Church's positions of government and responsibility. The 85-year-old pope has repeatedly said that women should play greater roles within the Vatican's hierarchy and has broken centuries of precedent to place women in some key spots previously held by men. Last year, the Argentine pontiff issued a decree to allow women to serve as readers at liturgies, altar servers and distributors of communion  but stopped short of saying the change could one day open the door to female priests.",
    comments: [],
  },
  {
    id: 3212,
    title: "'My church was not demolished' - Prophet Odumeje (Video)",
    type: "Religion",
    time: "Jul 08",
    author: "Same Emmanuel",
    img: "https://static.netnaija.com/i/9bVNrYzMaWv.webp",
    body: "Controversial Anambra-based clergyman, Prophet Odumeje, has dismissed reports that his church, Mountain of Holy Ghost Intervention and Deliverance Ministry, was demolished. It was earlier reported that the church located in Bida Road, Fegge, Onitsha, Anambra State, was demolished by the Anambra State Government (ANSG) task force on Thursday, July 7, and a video capturing the moment the building was taken down was shared online. Anambra State Governor, Soludo, also confirmed the demolition in a statement signed on his behalf by his Chief Press Secretary, Christian Aburime. It was stated that the church and other buildings were demolished because they were built on Fegge waterways. The statement read, 'Following the expiration of the more than two weeks notice beginning from April 2022 served on developers and building owners who built several illegal structures along the waterway in Fegge and environs within Onitsha, Anambra state government has begun demolition of such structures. The exercise which is being carried out by a joint government task force, commenced the exercise from Bida Road by Modebe Avenue, Fegge Onitsha. The affected buildings include Mountain of Holy Ghost Intervention Deliverance Ministries, shops and other perimeter fences. The structures were marked since April, 2022 and all developers and building owners were served notice to remove such illegal structures.' However, the clergyman has now come out to dismiss reports that his church was demolished, tagging it as fake news. According to him, it was the security house close to the church that had been destroyed and not his church building. A post on the church's official Facebook page reads, 'Lion Family No Fear: Prophet Odumeje's Church was never Demolished. Only the Securty/Store bulding beside the Drainage System. What shall it Profit you to be spreading Fake Rumours.'",
    comments: [],
  },
  {
    id: 3213,
    title:
      "Catholic Priest shares photos of 'Virgin Mary' who appeared to parishioners in Calabar",
    type: "Religion",
    time: "Jul 01",
    author: "Same Emmanuel",
    img: "https://static.netnaija.com/i/zxG7ZOGWaq2.jpg",
    body: "A Catholic Priest, Fr. Evaristus Bassey, has shared photos of 'Virgin Mary' that appeared at the St. Charles Lwanga in Calabar, Cross Rivers state. Fr Evaristus shared photos of the 'Virgin Mary' and said many people including non-Catholics 'saw her image.' He wrote; 'On Wednesday 22-6-2022 the Blessed Virgin Mary appeared in one of our parishes in Calabar, St. Charles Lwanga. It was something more than 100 people witnessed,even a Protestant pastor who came to visit his cousin, the assistant priest. He took these pictures. The rays around her were too bright for a clear picture. She moved up to the Shrine dedicated to her and then was taken up. It was amazing, the entire aura around the parish, that evening. She didn't say anything to anyone. But I think she came to assure of God's presence with us. Even the rays of light on the premises showed there was something happening. May the prayers of our Blessed Mother help our country Nigeria. Amen.'",
    comments: [],
  },
  {
    id: 3214,
    title:
      "'Anybody who blasphemes Jesus will taste the fire of God' - Pastor Adeboye to Daddy Freeze",
    type: "Religion",
    time: "Jul 03",
    author: "Moses O",
    img: "https://static.netnaija.com/i/xM6K5yWVKyE.webp",
    body: "General Overseer of the Redeemed Christian Church of God, Pastor Enoch Adeboye, condemns Daddy Freeze over a statement made during Owo Massacre. It would be recalled that following the Owo Massacre, residents of the township consulted the gods against the attacker that took tens of innocent lives. Reacting to the event, Daddy Freeze mocked the religious people for doing so little while the traditional worshippers took charge. Freeze had written last month, 'When dem call bros J and he nor answer dem nko? We abandoned African paganism to adopt European pagan ideologies. Until we start telling ourselves the truth and take our security issues more seriously this won't end. Christ's message is love and that's the first thing so glaringly missing in Nigeria.' While addressing his congregation at the RCCG monthly event, Holy Ghost Service for July, Pastor Adeboye said, 'I understand that one funny fellow said that some people were calling on Ogun because Jesus didn't answer them. 'Well, the one who said that there's a Yoruba proverb, it said, the mouth that the snail uses to blasphemy God, that mouth would kiss the ground. From now on, anybody who dares blaspheme Jesus Christ, they will taste the fire of the Almighty God.'",
    comments: [],
  },
  {
    id: 3215,
    title:
      "Pastor Adeboye clarifies reports alleging he asked Christians to buy guns",
    type: "Religion",
    time: "Jul 03",
    author: "Moses O",
    img: "https://static.netnaija.com/i/LqXNEOqD7lE.jpg",
    body: "The General Overseer of the Redeemed Christian Church of God (RCCG) Pastor Enoch Adeboye, has denied reports making the rounds that he asked Christians to buy guns for self-protection. The renowned cleric made this known during the church's monthly thanksgiving. The clarification came against reports that he said it was now 'fire-for-fire' for any attack on Christians. 'I never asked Christians to go and buy guns. Samson in the Bible did not fight with guns,' 'Don't buy guns. You don't want to kill anybody. We just must make sure that unwanted visitors don't come to our churches, so don't go and buy guns,'' he said. Adeboye also urged members of the church not to be afraid to attend church programmes because of the terrorist attack on a church in Owo, Ondo State. Recall that over 40 worshippers were killed and many injured when terrorists attacked Saint Francis Catholic Church, Owo, on June 5 2022. The 80-year- old cleric urged Christians to rise to the occasion and call the bluff of the devil.",
    comments: [],
  },
  {
    id: 3216,
    title:
      "Elon Musk expresses excitement as he visits Pope Francis with his children",
    type: "Religion",
    time: "Jul 02",
    author: "Moses O",
    img: "https://static.netnaija.com/i/BQJNjYbVarL.webp",
    body: "SpaceX founder and Tesla chief executive, Elon Musk has expressed his excitement at meeting the head of the Catholic Church, Pope Francis. The world's richest man on Thursday met the Pope at the Vatican, and posted a photo of the encounter on Twitter. 'Honored to meet @Pontifex yesterday,' the billionaire tweeted, and when one person remarked about his ill-fitting suit Musk admitted it was 'tragic'. Musk, 50, was accompanied by four of his five teenage children - all born to his first wife Justine Wilson, a Canadian author The Tesla boss' visit to the Pope comes a week after his son Xavier legally changed gender from male to female and dropped last name to distance herself from father.",
    comments: [],
  },
];
